### ISSUE TITLE
Messages while simulating Modelica.Fluid.Examples.HeatExchanger.HeatExchangerSimulation

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OpenModelica#7566] opened 2021-06-16 12:37 UTC
### Description

MSL 3.2.3
While simulating Modelica.Fluid.Examples.HeatExchanger.HeatExchangerSimulation you get:
![image](https://user-images.githubusercontent.com/4192979/122219303-fb933e00-ceb7-11eb-95d1-14f8819164f6.png)

### Steps to Reproduce

Simulate Modelica.Fluid.Examples.HeatExchanger.HeatExchangerSimulation

### Expected Behavior

Simulate the example without failing or giving error messages.

### Version and OS

 - OpenModelica Version: 1.18 nightly-build
    Connected to OpenModelica v1.18.0-dev-332-g155bdf9c86 (64-bit)
    Connected to OMSimulator v2.1.1.post80-g1bf17f4-mingw
-  OS: Windows 10, 64 bit
 - Versions of used Modelica: MSL 3.2.3

**Comment by casella** [comment] 2021-06-16 13:49
Duplicate of [#5768](https://trac.openmodelica.org/OpenModelica/ticket/5768)

**Closed by casella** 2021-06-16 13:49 UTC
Labels: COMP/Runtime
