### ISSUE TITLE
Modelica-Buildings Library (master-fmi-fmpy): Solving non linear system failed

### ISSUE THREAD

**Issue by deepak19015** [OpenModelica/OpenModelica#11859] opened 2024-01-23 11:42 UTC
### Description

The simulation of fmu generated through omedit are failed while simulating in jupyter-notebook using fmpy library and throws error that is Invalid root and  Solving non-linear system failed.
The following below listed models have same issues: 

```
Buildings.Fluid.HeatPumps.Examples.ScrollWaterToWater_OneRoomRadiator
Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases6xx.Case640
Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases6xx.Case695
Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases9xx.Case940
Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases9xx.Case985
Buildings.Examples.ScalableBenchmarks.BuildingVAV.Examples.OneFloor_OneZone
Buildings.Experimental.DHC.EnergyTransferStations.Combined.Subsystems.Validation.HeatPump
```
On simulating the model in jupyter-notebook using fmpy library leads to following errors/warnings:

```
1. Invalid root: (1.97046)^(3.12556e+19)
2. Solving non-linear system 1474 failed at time=811.290794362111.
3. RuntimeError: CVode error (code -8) in module CVODE, function CVode: At t = 811.291, the right-hand side routine failed in an unrecoverable manner.
4. FMICallException: fmi2GetDerivatives failed with status 3 (error).
```

### Steps to Reproduce

Load the Modelica-Buildings master fmi fmpy library (Source: https://libraries.openmodelica.org/branches/master-fmi-fmpy/Buildings_latest/Buildings_latest.html)
Right click on the model and export fmu. import the fmu in python platform and the run python code.
Simulate the model "Buildings.Fluid.HeatPumps.Examples.ScrollWaterToWater_OneRoomRadiator"

### Expected Behavior

The simulation should run without any error and plot the graph according to variables present in model.

### Screenshots
![Screenshot from 2024-01-23 17-18-14](https://github.com/OpenModelica/OpenModelica/assets/139556265/640bc863-47ea-4d9b-b4a7-6f39a7ffbde9)
![Screenshot from 2024-01-23 17-07-31](https://github.com/OpenModelica/OpenModelica/assets/139556265/b1a3a80e-564a-429b-835d-1f6faf39a7c6)

### Version and OS

-    OpenModelica Version: OpenModelica 1.23.0~dev-151-g8fef40a
-    OS: Ubuntu 22.04 focal
-    FMPy 0.3.19 
-    Python version: Python 3.10.12

       Versions of used Modelica libraries:
        Modelica 4.0.0
        Buildings master (11.0.0)

**Comment by casella** [comment] 2024-03-05 10:35
Keeping @AndreaBartolini in the loop

**Comment by casella** [comment] 2024-03-14 14:23
We've had some issues with the CI, now [job #7607](https://test.openmodelica.org/jenkins/job/LibraryTesting/job/LibraryTest/7607/console) is running and should finally provide some positive regression results [here](https://libraries.openmodelica.org/branches/history/master-fmi-fmpy/) in one-two days.

**Comment by casella** [comment] 2024-03-15 17:56
OK, [job #7607](https://test.openmodelica.org/jenkins/job/LibraryTesting/job/LibraryTest/7607/console) finished successfully, unfortunately the previous one ran with OMSimulator only, not with FMPy, so the regression report is probably missing something.

Anyway, the [master-fmi-fmpy/Buildings_latest](https://libraries.openmodelica.org/branches/master-fmi-fmpy/Buildings_latest/Buildings_latest.html) report should now be up to date with the latest commits. Unfortunately, the models cited in #11859 still fail in the same way, so there is probably still something wrong somewhere.

**Comment by casella** [comment] 2024-03-15 18:23
@deepak19015, I checked the generated FMU after @arun3688's commit ddce110, and it seems good now, as it contains the following line:
```xml
 <DefaultExperiment startTime="0.0" stopTime="172800.0" tolerance="1e-8" stepSize="345.6"/>
```
which corresponds to 500 reporting intervals. However, the simulation of those models fails in the same way. If I remember correctly, when we manually set the step size to something like that, it worked in Jupyter. Please check.

**Comment by arun3688** [comment] 2024-03-16 00:20
@casella I tested the following fmu in OMSimulator and it works fine see the results below
```

# OMSimulator C:/OPENMODELICAGIT/buildingstest/ScrollWaterToWater_OneRoomRadiator.fmu
LOG_ASSERT        | warning | [C:/Users/arupa54/AppData/Roaming/.openmodelica/libraries/Buildings 10.0.0/Fluid/Movers/BaseClasses/PartialFlowMachine.mo:417:3-427:39:writable]
|                 | |       | The following assertion has been violated during initialization at time 0.000000
|                 | |       | ((not (pumHeaPum.per.etaHydMet == Buildings.Fluid.Movers.BaseClasses.Types.HydraulicEfficiencyMethod.Power_VolumeFlowRate or pumHeaPum.per.etaHydMet == Buildings.Fluid.Movers.BaseClasses.Types.HydraulicEfficiencyMethod.EulerNumber))) --> "*** Warning in ScrollWaterToWater_OneRoomRadiator.pumHeaPum: Mover has per.etaHydMet=.Power_VolumeFlowRate or per.etaHydMet=.EulerNumber.
|                 | |       | This requires per.pressure to be provided.
|                 | |       | Because it is not, the model overrides this setting by using per.etaHydMet=.NotProvided.
|                 | |       | Also consider using models under Movers.Preconfigured which autopopulate a pressure curve."
LOG_ASSERT        | warning | [C:/Users/arupa54/AppData/Roaming/.openmodelica/libraries/Buildings 10.0.0/Fluid/Movers/BaseClasses/PartialFlowMachine.mo:429:3-439:39:writable]
|                 | |       | The following assertion has been violated during initialization at time 0.000000
|                 | |       | ((pumHeaPum.per.haveWMot_nominal or not (pumHeaPum.per.etaMotMet == Buildings.Fluid.Movers.BaseClasses.Types.MotorEfficiencyMethod.Efficiency_MotorPartLoadRatio or pumHeaPum.per.etaMotMet == Buildings.Fluid.Movers.BaseClasses.Types.MotorEfficiencyMethod.GenericCurve))) --> "*** Warning in ScrollWaterToWater_OneRoomRadiator.pumHeaPum: Mover has per.etaMotMet=.Efficiency_MotorPartLoadRatio or per.etaMotMet=.GenericCurve.
|                 | |       | This requires per.WMot_nominal or per.pressure to be provided. Because neither is provided,
|                 | |       | the model overrides this setting and by using per.etaMotMet=.NotProvided.
|                 | |       | Also consider using models under Movers.Preconfigured which autopopulate a pressure curve."
LOG_ASSERT        | warning | [C:/Users/arupa54/AppData/Roaming/.openmodelica/libraries/Buildings 10.0.0/Fluid/Movers/BaseClasses/PartialFlowMachine.mo:417:3-427:39:writable]
|                 | |       | The following assertion has been violated during initialization at time 0.000000
|                 | |       | ((not (pumHeaPumSou.per.etaHydMet == Buildings.Fluid.Movers.BaseClasses.Types.HydraulicEfficiencyMethod.Power_VolumeFlowRate or pumHeaPumSou.per.etaHydMet == Buildings.Fluid.Movers.BaseClasses.Types.HydraulicEfficiencyMethod.EulerNumber))) --> "*** Warning in ScrollWaterToWater_OneRoomRadiator.pumHeaPumSou: Mover has per.etaHydMet=.Power_VolumeFlowRate or per.etaHydMet=.EulerNumber.
|                 | |       | This requires per.pressure to be provided.
|                 | |       | Because it is not, the model overrides this setting by using per.etaHydMet=.NotProvided.
|                 | |       | Also consider using models under Movers.Preconfigured which autopopulate a pressure curve."
LOG_ASSERT        | warning | [C:/Users/arupa54/AppData/Roaming/.openmodelica/libraries/Buildings 10.0.0/Fluid/Movers/BaseClasses/PartialFlowMachine.mo:429:3-439:39:writable]
|                 | |       | The following assertion has been violated during initialization at time 0.000000
|                 | |       | ((pumHeaPumSou.per.haveWMot_nominal or not (pumHeaPumSou.per.etaMotMet == Buildings.Fluid.Movers.BaseClasses.Types.MotorEfficiencyMethod.Efficiency_MotorPartLoadRatio or pumHeaPumSou.per.etaMotMet == Buildings.Fluid.Movers.BaseClasses.Types.MotorEfficiencyMethod.GenericCurve))) --> "*** Warning in ScrollWaterToWater_OneRoomRadiator.pumHeaPumSou: Mover has per.etaMotMet=.Efficiency_MotorPartLoadRatio or per.etaMotMet=.GenericCurve.
|                 | |       | This requires per.WMot_nominal or per.pressure to be provided. Because neither is provided,
|                 | |       | the model overrides this setting and by using per.etaMotMet=.NotProvided.
|                 | |       | Also consider using models under Movers.Preconfigured which autopopulate a pressure curve."
info:    maximum step size for 'model.root': 345.600000
info:    Result file: model_res.mat (bufferSize=10)
info:    Parameter model.root.ScrollWaterToWater_OneRoomRadiator.timTab.fileName will not be stored in the result file, because the signal type is not supported
info:    Parameter model.root.ScrollWaterToWater_OneRoomRadiator.timTab.tableName will not be stored in the result file, because the signal type is not supported
info:    Final Statistics for 'model.root':
         NumSteps = 58 NumRhsEvals  = 73 NumLinSolvSetups = 16
         NumNonlinSolvIters = 72 NumNonlinSolvConvFails = 0 NumErrTestFails = 2
warning: temp directory "C:\OPENMODELICAGIT\buildingstest\model-qfunezo5" couldn't be removed
         filesystem error: cannot remove all: The process cannot access the file because it is being used by another process [C:\OPENMODELICAGIT\buildingstest\model-qfunezo5] [C:\OPENMODELICAGIT\buildingstest\model-qfunezo5\temp\0001_ScrollWaterToWater_OneRoomRadiator\resources\C\Users\arupa54\AppData\Roaming\.openmodelica\libraries\Buildings 10.0.0\Resources\weatherdata\USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.mos]
info:    1 warnings
info:    0 errors
```

**Comment by casella** [comment] 2024-03-18 11:25
@arun3688, that's good, unfortunately we can't use OMSimulator for verification because it is too crude when handling events. Can you try with FMPy (or PyFMI)?

**Comment by casella** [comment] 2024-03-19 18:29
We eventually figured out that we were running FMPy with default parameters that led to a co-simulation run, rather than a model-exchange one driven by a solid stiff solver in FMPy. We need to add `--output-interval xxx --interface-type ModelExchange --solver CVode` to get FMPy to do that.

OpenModelica/OpenModelicaLibraryTesting#79 updates the test scripts accordingly. Test job #7627 has been scheduled to run with the new setup. Hopefully the next [regression report](https://libraries.openmodelica.org/branches/history/master-fmi-fmpy/) will contain good news.

Additionally, when testing Buildings.Fluid.HeatPumps.Examples.ScrollWaterToWater_OneRoomRadiator manually from the command line, we realized that the simulation is successful with integer output intervals, but fails if the interval has digits after the decimal points. CATIA-Systems/FMPy#655 was opened on that topic. We may need it to be resolved before getting all those simulations running correctly.

**Comment by casella** [comment] 2024-03-19 18:33
For the record, the CI fetches the simulation parameters from the Modelica model (see [here](https://github.com/OpenModelica/OpenModelicaLibraryTesting/blob/c36be386fb67d1a8b2a316c911915cd597de4fc5/testmodel.py#L325)), not from the modelDescription.xml, which is still OK. 

FMPy selects the type of interface (ME or CS) based on what is available, but if both are, it selects CS by default (see [here](https://github.com/CATIA-Systems/FMPy/blob/04aa5fd1aa86af25caa37b7f9a710d240890ca4e/fmpy/simulation.py#L673)), so we must set that explicitly.

**Comment by casella** [comment] 2024-03-20 19:05
We got some improvements after https://github.com/OpenModelica/OpenModelicaLibraryTesting/pull/79, see [report](https://libraries.openmodelica.org/branches/master-fmi/Buildings_latest/Buildings_latest.html):
- Buildings.Fluid.HeatPumps.Examples.ScrollWaterToWater_OneRoomRadiator now simulates and verifies
- Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases6xx.Case640 fails with CVode error (code -1) in module CVODE, function CVode: At t = 2.42885e+07, mxstep steps taken before reaching tout.
- Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases6xx.Case695 simulates successfully, two signals don't pass verification, we need to investigate why
- Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases9xx.Case940 fails with CVode error (code -8) in module CVODE, function CVode: At t = 39.7862, the right-hand side routine failed in an unrecoverable manner.
- Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases9xx.Case985 fails with RuntimeError: CVode error (code -8) in module CVODE, function CVode: At t = 0.253688, the right-hand side routine failed in an unrecoverable manner.
- Buildings.Examples.ScalableBenchmarks.BuildingVAV.Examples.OneFloor_OneZone simulates, it fails verification on the "time"signal, which is weird, I'll open a ticket on Buildings about that.
- Buildings.Experimental.DHC.EnergyTransferStations.Combined.Subsystems.Validation.HeatPump now simulates, apparently the reference files are missing

@deepak19015, please open new tickets for 
- Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases6xx.Case640
- Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases6xx.Case695
- Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases9xx.Case940
- Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases9xx.Case985
and then close this ticket. 

Thanks!

**Comment by deepak19015** [comment] 2024-03-21 07:21
@casella , I have opened a new ticket for above mentioned model. This is the link for new ticket. [](https://github.com/OpenModelica/OpenModelica/issues/12126)

**Closed** 2024-03-21 07:24 UTC
Labels: COMP/FMI
