### ISSUE TITLE
Large memory leak in kinsol nonlinear solver

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#5485] opened 2020-06-27 11:06 UTC

**Comment by githubfrond** [comment] 2021-05-03 01:29
progress on this?

**Comment by casella** [comment] 2021-05-06 13:09
Not yet. Do you have any specific test case to report?

**Comment by githubfrond** [comment] 2021-05-06 23:59
Unfortunately we can't share our test cases outside of Defence in Australia.  However, I did attempt to run the 6dof robot example in the Modelica Standard Library with the Kinsol nls and -noScaling options, and it displays the very large memory usage and significantly slow solution times that we are experiencing with our other models.

Case a)
Running with Default Simulation Settings (dassl selected only, Tend=2seconds,steps=500) takes <10 seconds using <0.5G of RAM.

Case b)
Running same Default Sim Settings but additionally select **nls=kinsol, option=-noScaling** takes > 10 mins uses all available 31G of RAM and all 2G of swap memory.  I believe running without the -noScaling option results in the same performance.
Noting that it does seem to finish the simulation successfully, despite repeated reports that kinsol line search did not converge.  I think it may be exiting the use of kinsol, trying another method successfully, then returning to attempt kinsol for the next solution step, but I don't know for sure. However the memory use continually grows until everything is exhausted.

Information:
Model=Modelica.Mechanics.Multibody.Examples.Systems.RobotR3.fullRobot
Compiler=OpenModelica 1.13.2
Machine=Dell Precision 7820, 32 processors, 31G RAM, 2G swap
OS=Linux Ubuntu 18.04.1

**Comment by casella** [comment] 2021-05-07 06:40
@kabdelhak, @AnHeuermann, @phannebohm, we'll have to look again into this.

**Comment by AnHeuermann** [comment] 2021-05-07 06:50
Do I see it correctly that OpenModelica Compiler version 1.13.2 is used?

@githubfrond Have you already tried with the nightly build? We fixed at least some memory issues (but not all).

**Comment by casella** [comment] 2021-05-07 08:16
> Do I see it correctly that OpenModelica Compiler version 1.13.2 is used?

Ops, I completely overlooked that. Version 1.13.2 is out of the Jurassic period, there is no reason whatsoever to use it as of today. Please try with 1.17.0, or with the latest 1.18.0-dev nightly build.

**Comment by sjoelund** [comment] 2021-05-07 08:26
(Also, we changed Sundials version, so maybe the bug can be fixed by changing some things now; like free'ing every (configurable) 1000 or so iterations)

**Comment by githubfrond** [comment] 2021-05-14 04:09
Finally had a chance to re-execute the simulation with the later OMC, apologies for the delay.
The same model using the kinsol nonlinear solver exhibits the same errors as before with regard to not converging, including the growth in memory usage over time, eventually reaching 60% of all memory before the simulation fails with no further messages.
It solves fine if the nonlinear solver is not kinsol.
Thanks for your responses above, all the best!  Let me know if you need anything further from me.  It appears easy enough to reproduce.

Information:
Simulation=default simulation setup for the model fullRobot in MSL 3.2.2
Model=Modelica.Mechanics.Multibody.Examples.Systems.RobotR3.fullRobot
Compiler=OpenModelica 1.17.0-1
Machine=Dell Precision Inspiron 7573, Intel i5-8250U,  8G RAM Physical 13G Virtual
OS=Linux Ubuntu 18.04.3 running as a VM under Windows 10 Pro 10.0.19041

**Comment by AnHeuermann** [comment] 2021-05-14 11:29
Okay, I can confirm that running Kinsol on the full robot example with `OMCompiler v1.18.0-dev.269+g83ff1a1bb1` will consume all of my precious memory.
```
loadModel(Modelica, {"3.2.3"}); getErrorString();
simulate(Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.fullRobot, simflags="-nls=kinsol"); getErrorString();
```

I'll investigate more.

**Comment by AnHeuermann** [comment] 2021-05-14 13:03
It is like @githubfrond guessed. 

Kinsol fails with the default strategy, we change it to something else and before solving again call `nlsKinsolConfigSetup` which will change it back to the default strategy, which will fail, so we change it to something else and so on...

This over and over call of `nlsKinsolConfigSetup` is the reason for the endless loop and the memory leak. I fixed this and now get event chattering and an endless-loop again. But this is a different bug. When your example doesn't have event chattering as well I guess this will work for you.

Btw. the newton solver experiences the same event chattering for the fullRobot example.

**Closed** 2021-05-14 15:20 UTC

**Comment by AnHeuermann** [comment] 2021-05-14 15:21
@githubfrond The next nightly build (tomorrow) will have the fix. Can you check if this solves the issue with your model running with Kinsol or at least gives some error message?
