### ISSUE TITLE
Buildings library related modules are not available in Openmodelica

### ISSUE THREAD

**Issue by shiyishiba** [OpenModelica/OpenModelica#12480] opened 2024-05-30 01:16 UTC
### Description

Buildings of the library module error, an error message for [C: / OM122 OM64bit/OMCompiler/Compiler/NFFrontEnd/NFCeval Buildings library module error, An error information for [C: / OM122 / OM64bit/OMCompiler/Compiler/NFFrontEnd/NFCeval. Mo: 1062:9-1062:67] : Internal error NFCeval.evalBinarySub failed to evaluate ‘3 - sla1.iLayPip‘mo: 1062:9-1062:67]: Internal error NFCeval.evalBinarySub failed to evaluate ‘3 - sla1.iLayPip‘

### Steps to Reproduce

【 Buildings. Fluid. HeatExchangers. RadiantSlabs 】 all of the module and case under this module cannot be used

### Expected Behavior

The RadiantSlabs module can be used smoothly and you can enter the editing interface

### Screenshots

See the attachment for screenshot
![problem](https://github.com/OpenModelica/OpenModelica/assets/125559199/6b9da060-354f-4c87-bcca-50a9004659e5)

### Version and OS

 - OpenModelica Version: Connected to OpenModelica v1.22.3 (64-bit)
 - OS: [e.g. Windows 10, 64 bit]
 - Buildings V11.0.0

### Additional Context

No

**Comment by casella** [comment] 2024-05-30 10:34
@shiyishiba I cannot reproduce the issue with the latest nightly build. I guess the problem has been fixed in the meantime. Please try with 1.23.0.dev.beta.1 and/or with the latest nightly build.

**Comment by shiyishiba** [comment] 2024-05-31 12:54
Thanks for you very much, and this version don't have the bug.

**Closed** 2024-05-31 13:20 UTC
Labels: COMP/GUI/OMEdit, COMP/GUI/InstBased Interface
