### ISSUE TITLE
Status of OpenModelica Library Testing

### ISSUE THREAD

**Issue by christiankral** [OpenModelica/OpenModelica#7702] opened 2021-07-18 20:12 UTC
### Description

The actual status of OpenModelica Library Testing is reported on https://libraries.openmodelica.org/branches/overview.html

Today's report shows:

- master refers to OMCompiler v1.19.0-dev.47+gd4b39c950e
  ![image](https://user-images.githubusercontent.com/4184218/126080593-f36f3c23-6cd8-4a23-be56-ca53201992b8.png)
- Library `PhotoVoltaics_TGM` shows for master the following statistics:
  ![image](https://user-images.githubusercontent.com/4184218/126080574-5f4632c7-546a-4193-a6f5-9bbfc9bc1833.png)

I am using the same nightly version of OpenModelica
![image](https://user-images.githubusercontent.com/4184218/126080618-acac7ae7-76ba-411f-9179-13d2eb35e0e9.png)
and the PhotoVoltaics_TGM library (v1.6.0), but come to a different result:

Out of the 18 examples there are 10 examples which simulate. I found that the following 18 - 10 = 8 examples are not simulating:

- PhotoVoltaics_TGM.TGM_Comax_Analytical_20160629
- PhotoVoltaics_TGM.TGM_Comax_Analytical_20160704
- PhotoVoltaics_TGM.TGM_Comax_Analytical_20160808
- PhotoVoltaics_TGM.TGM_Comax_Analytical_2016
- PhotoVoltaics_TGM.TGM_Trina_Analytical_20160629
- PhotoVoltaics_TGM.TGM_Trina_Analytical_20160704
- PhotoVoltaics_TGM.TGM_Trina_Analytical_20160808
- PhotoVoltaics_TGM.TGM_Trina_Analytical_2016

This leads to a discrepancy:

- The OpenModelica Library Testing report indicates 18 - 12 = 6 models are not simulating
- I found with the same version that 18 - 10 = 8 models are not simulating

Where does this difference come from?

**Comment by rfranke** [comment] 2021-07-25 12:47
It appears that
- PhotoVoltaics_TGM.TGM_Comax_Analytical_2016
- PhotoVoltaics_TGM.TGM_Trina_Analytical_2016

work in the daily library tests but not for you. These two examples take quite some time to simulate. It looks like OMEdit crashes when retrieving results after the simulation. The daily library tests run without the graphical UI OMEdit.

Btw. the other 6 failing examples all generate the same strange error:
```
LOG_INIT          | error   | The initialization problem is inconsistent due to the following equation: 0 != 1 = PhotoVoltaics.Functions.dayOfTheYear(irradiance.startDay, irradiance.startMonth, irradiance.startYear) - $PRE.irradiance.dayOfYear
```
They work for me with the Cpp runtime (Tools->Options->Simulation: Target Language: Cpp) or
```
setCommandLIneOptions("--simCodeTarget=Cpp")
```

**Comment by casella** [comment] 2021-07-25 17:01
@christiankral, @rfranke, the difference in reporting is due to some issue in the formation of the command line execution string. If you check the simulation results of [PhotoVoltaics_TGM.TGM_Trina_Analytical_2016](https://libraries.openmodelica.org/branches/master/PhotoVoltaics_TGM/files/PhotoVoltaics_TGM_PhotoVoltaics_TGM.TGM_Trina_Analytical_2016.sim), what you see is:
```
startTime=0
stopTime=3.1536e+07
tolerance=1e-06
numberOfIntervals=35040
stepSize=900
Regular simulation: ./PhotoVoltaics_TGM_PhotoVoltaics_TGM.TGM_Trina_Analytical_2016 -abortSlowSimulation -alarm=480   -jacobian=coloredNumerical
-s=dassl -lv=LOG_STATS -lv LOG_STATS
stdout            | warning | each command line option can only be used once: -lv
stdout            | info    | usage: ./PhotoVoltaics_TGM_PhotoVoltaics_TGM.TGM_Trina_Analytical_2016
|                 | |       | | <-abortSlowSimulation>
|                 | |       | |   aborts if the simulation chatters
|                 | |       | | <-alarm=value> or <-alarm value>
|                 | |       | |   aborts after the given number of seconds (0 disables)
|                 | |       | | <-clock=value> or <-clock value>
|                 | |       | |   selects the type of clock to use -clock=RT, -clock=CYC or -clock=CPU
|                 | |       | | <-cpu>
|                 | |       | |   dumps the cpu-time into the result file
|                 | |       | | <-csvOstep=value> or <-csvOstep value>

etc. etc.
```
In other words, the simulation is not run at all (in fact, getting this output only takes 0.09 s), but is still reported as running successfully, apparently because in this case the simulation executable does not exit with an error code. BTW, there are other two such cases in the library testing, [TGM_Comax_Analytical_2016](https://libraries.openmodelica.org/branches/master/PhotoVoltaics_TGM/files/PhotoVoltaics_TGM_PhotoVoltaics_TGM.TGM_Comax_Analytical_2016.sim) and [TGM_Trina_Measurement_20160626_to_20161004](https://libraries.openmodelica.org/branches/master/PhotoVoltaics_TGM/files/PhotoVoltaics_TGM_PhotoVoltaics_TGM.TGM_Trina_Measurement_20160626_to_20161004.sim).

On my PC, the [TGM_Trina_Analytical_2016](https://libraries.openmodelica.org/branches/master/PhotoVoltaics_TGM/files/PhotoVoltaics_TGM_PhotoVoltaics_TGM.TGM_Trina_Analytical_2016.err) model gives these two warnings:
```
[1] 18:32:01 Translation Warning
It was not possible to determine if the initialization problem is consistent, because of not evaluable parameters/start values during compile time: $PRE.irradiance.dayOfYear = PhotoVoltaics.Functions.dayOfTheYear(irradiance.startDay, irradiance.startMonth, irradiance.startYear) (/*Real*/(PhotoVoltaics.Functions.dayOfTheYear(irradiance.startDay, irradiance.startMonth, irradiance.startYear)) = PhotoVoltaics.Functions.dayOfTheYear(irradiance.startDay, irradiance.startMonth, irradiance.startYear))

[2] 18:32:01 Translation Warning
The initial conditions are over specified. The following 1 initial equations are redundant, so they are removed from the initialization sytem:
         $PRE.irradiance.dayOfYear = PhotoVoltaics.Functions.dayOfTheYear(irradiance.startDay, irradiance.startMonth, irradiance.startYear).
```
and then fails at runtime with 
```
Simulation process failed. Exited with code 0xffffffffffffffff.
The initialization problem is inconsistent due to the following equation: 0 != 1 = PhotoVoltaics.Functions.dayOfTheYear(irradiance.startDay, irradiance.startMonth, irradiance.startYear) - $PRE.irradiance.dayOfYear
Error in initialization. Storing results and exiting.
Use -lv=LOG_INIT -w for more information.
```
which looks very much related to the former issue.

Same story for [TGM_Comax_Analytical_2016](https://libraries.openmodelica.org/branches/master/PhotoVoltaics_TGM/files/PhotoVoltaics_TGM_PhotoVoltaics_TGM.TGM_Comax_Analytical_2016.err).

So, it seems there are at least three separate issues here.

1. In some occasions, the testing framework tries to run the simulation executable with multiple -lv statements instead of merging them
2. In such cases, a success code is returned so the simulation is reported as successful in the test report
3. The two models with the year only in their name have some issues with irradiance data.

@christiankral I opened #7718 and #7719 on the first two issues. I'm not sure about the third, because I don't know about the implementation details of your library. Maybe you can investigate a bit more to see if the problem is with the code of the library, with OMC, or with the testing infrastructure, and open a more detailed ticket.

I'm closing this one because it is too generic.

**Closed by casella** 2021-07-25 17:01 UTC
