### ISSUE TITLE
Export Modelica utility functions symbols on Windows from executables generated by omc, and in OMEdit as well

### ISSUE THREAD

**Issue by fedetftpolimi** [OpenModelica/OpenModelica#9029] opened 2022-05-27 18:15 UTC
Hello,
in an attempt to fix error handling in ExternalMedia built as a shared library, I encountered the long standing issue of calling ModelicaError from a DLL (https://github.com/modelica/ModelicaSpecification/issues/2191), and I think I found a general solution, which relies on shared libraries calling symbols exported by the executable.

I tested my solution with OpenModelica (and Dymola by the way) on Linux and it works.
On Windows with OpenModelica however it doesn't, apparently because the symbols for Modelica utility functions (such as ModelicaError) are not exported in this platform.

To be clear, even though symbol exporting on Windows is usually associated with DLLs, executables can export symbols too, that loaded DLLs can call back, exactly what is needed to let an external function in a DLL call ModelicaError. If this bug is resolved, we may have found a solution to this long standing issue (the ModelicaSpecification issue is from 2017).

Attached is a small example to demonstrate the issue.
It contains two models,
- TestFoo that causes a call to the shared object during simulation, to test that the generated simulation executable exports symbols
- TestFooAsStructuralParameter that causes a call to the shared object right when the model is checked, to test that OMEdit itself exports symbols

When I test these examples on Linux, I can correctly see in the OMEdit user interface the strings "ModelicaError can be successfully called", while testing on Windows (with the help of @casella , as I don't have a Windows machine) symbols for the function ModelicaError cannot be retrieved.

[mwe_symbols.zip](https://github.com/OpenModelica/OpenModelica/files/8788923/mwe_symbols.zip)

**Comment by mahge** [comment] 2022-06-03 19:55
I am not sure if I completely understood what the expectations are when you compile your shared library. If it needs to be compiled by itself with no expectations that omc is available at compile time then your approach might be something to consider (we had actually thought about that a while back).

However, for the linux case in your tests, I see that you are including OpenModelica's `ModelicaUtilities.h`. I assume this means your library is being compiled with the assumption that it is going to work with `omc` and `omc `should be available at the time of compilation. In that case you can just link to our runtime library (libOpenModelicaRuntimeC) which provides the definitions of the functions. 

If your general target is to compile your DLL with no regard to availability if OpenModelica then we can see what we can do. My guess is that this is not working because the executable ****omc.exe** does not actually contain the symbols** you are looking for. They are in an another DLL (from which we do export all symbols). I do not know how to make that setup work.

_In my opinion this should have been a task for a package manager. In an ideal world all you need to provide would be source files and the package manager should compile them when making your Modelica library available._ 

For now however we can layout and list all the use cases we can think of and see if we can find a solution that can work for you.

**Comment by casella** [comment] 2022-06-03 23:42
> this is not working because the executable omc.exe does not actually contain the symbols you are looking for

Absolutely. On the other hand, it is working on Linux, so apparently the omc executable in Linux actually exports them.

@mahge, our high-level requirement stems from the use-case of ExternalMedia, and can be stated in very simple terms: Modelica libraries that use pre-compiled external functions should work out of the box with all Modelica tools and all operating systems. This has been the Holy Grail for ExternalMedia since 2006, and a completely satisfactory solution has not been found yet.

Linking against libOpenModelicaRuntimeC would work fine for a library which is used exclusively with OMC. But that won't be a Modelica library, just an OMC library. It won't work in Dymola, for example.

@fedetftpolimi's idea is very simple: if all Modelica tool vendors agreed to link all the ModelicaUtilities functions with their tools, and export their symbols, then whomever writes a library with external functions can import those symbols from within their external C code by relying on that, and call those functions when appropriate. Then, the library would be compiled once and run with all Modelica tools out of the box.

There is only one case that won't be supported, which is when the compiled simulation executable (or FMU) is run standalone, outside a Modelica tool session, so there is no running Modelica tool from which to import those symbols. In this case, I guess the solution would be that such symbols are linked and exported into the simulation executable (or the FMU), which knows by definition what to do of such calls. However, we'd still need the Modelica tool itself to export ModelicaError if we want to be able to deal with calls to such a function at compile time, e.g. for evaluating package constants.

I'm not sure if it is possible that you have the same symbol exported multiple times without generating a mess.

**Comment by adrpo** [comment] 2022-06-04 07:10
We had a long discussion about this a while back and the only way to do this in a portable way is to have "dummy" implementations of these functions in a new library that you can link against.

**Comment by mahge** [comment] 2022-06-05 11:47
> My guess is that this is not working because the executable omc.exe does not actually contain the symbols you are looking for. They are in an another DLL (libOpenModelicaRuntimeC, from which we do export all symbols)

I made some changes to your original code so that it can go through all the loaded DLLs using [EnumProcessModules](https://docs.microsoft.com/en-us/windows/win32/psapi/enumerating-all-modules-for-a-process?redirectedfrom=MSDN) and look for the function we are interested in. It seems to work. You can test it out and see if it fits your general usage.


```c++
template<typename FunctionType>
FunctionType findFunctionInLoadedModules(const char *funcName)
{
    FunctionType pfn = nullptr;
    HMODULE loaded_modules[1024];
    HANDLE h_process;
    DWORD cbNeeded;

    // Get a handle to the process.
    h_process = GetCurrentProcess();

    if(!h_process) {
        fprintf(stderr, "Failed to get a handle to the current Process (error %d)\n", GetLastError());
        exit(1);
    }

   // Get a list of all modules loaded in this process.
    if(!EnumProcessModules(h_process, loaded_modules, sizeof(loaded_modules), &cbNeeded)) {
        CloseHandle(h_process);
        fprintf(stderr, "Failed to enumerate loaded modules (error %d)\n", GetLastError());
        exit(1);
    }

    // The actual number of loaded modules.
    int num_modules = cbNeeded / sizeof(HMODULE);

    for (int i = 0; i < num_modules; ++i) {
        // See if the function can be found in this module.
        pfn = reinterpret_cast<FunctionType>(GetProcAddress(loaded_modules[i], funcName));

        // Function found in this module.
        if (pfn) {
            // // Print the dll path for debugging
            // TCHAR szModName[MAX_PATH];
            // GetModuleFileNameEx(h_process, loaded_modules[i], szModName, sizeof(szModName) / sizeof(TCHAR));
            // fprintf(stderr, "Found function %s in module %s\n", funcName, szModName);
            break;
        }

    }

    CloseHandle(h_process);

    if(!pfn) {
        fprintf(stderr, "Failed to get handle to function %s (error %d) in all loaded modules.\n", funcName, GetLastError());
        exit(1);
    }

    return pfn;
}
```

**Comment by casella** [comment] 2022-06-09 18:04
@mahge, thanks for you input!

@fedetftpolimi ported your code into ExternalMedia, we ran it under Windows 10 with v1.20.0-dev-119-g4241954151 (64-bit), it managed to enumerate the processes, but it couldn't get a handle, so it eventually failed, at least on my computer when tested with OMEdit 1.20.0-dev119-g4241954151. 
```
Simulation process failed. Exited with code 0x00000001.
Can't get handle to ModelicaError in all loaded modules. 
```
Apparently, we are still unable to get the symbols that should be made available by the runtime dll, for some reason.

You can reproduce the issue by
- checking out the [mwe_modelicautilities](https://github.com/modelica-3rdparty/ExternalMedia/tree/mwe_modelicautilities) branch of ExternalMedia
- following the instructions on [README_compilation.md](https://github.com/modelica-3rdparty/ExternalMedia/blob/master/README_compilation.md) to compile it locally on a Windows machine
- copying the `ExternalMedial.dll` file produced by CMAKE one directory up (from Resources/Libraries/win64/vsXXXX to Resources/Libraries/win64), so that omc actually finds it (we'll take care of fixing this asap)
- running the following MWE model, that should produce an error handled by ModelicaError because of the negative pressure value
```modelica
model MWE
  "Test case to generate an error at runtime"
  extends Modelica.Icons.Example;
  extends ExternalMedia.Test.GenericModels.TestStates(
    redeclare  package  Medium = ExternalMedia.Examples.CO2CoolProp);
equation
  p1 = -8e6;
  h1 = 1.0e5 + 6e5*time;
  p2 = 8e6;
  T2 = 280 + 50*time;
end MWE;
```
We also tested this MWE with Dymola, which also failed at runtime, except that for some reason Dymola could not even catch the printf output and simply reported dymosim.exe stopped working.

**Comment by mahge** [comment] 2022-06-10 09:45
Alright as far as I can gather, this is happening because the new test case does not actually try (does not need to) to evaluate the external function at **compile** time.  Instead it is doing it in the generated simulation executable. This is where you get the error saying it can't get handle to ModelicaError in all loaded modules.  

**For the simulation executable the symbol `ModelicaError` is actually inside the executable itself and not in another DLL** since we build the simulation library (libSimulationRuntimeC) as as static library AND the simulation executable does not export its symbols (there was no need so far).

There are two ways to fix this:

1. Build `libSimulationRuntimeC` as a DLL. It is built as an `.so` on linux and the CMake build also builds it as DLL. So it should really be a DLL as well. This is a good and proper fix but I am not sure how easy/annoying it will be to change it. I suspect it should not be. I am trying it out now.

2. Export symbols from the simulation executables (link them with `-Wl,-export-all-symbols`) and adjust the importing code to look in the executable itself first and then all loaded DLLs (basically add back what you had originally). 
```diff
template<typename T>
T importFromLoadedModules(const char *funcName)
{
+    T pfn = reinterpret_cast<T>(GetProcAddress(GetModuleHandleA(nullptr), funcName));
+    if(pfn) {
+        return pfn;
+    }
+
    //TODO: we should do caching
    HANDLE process = GetCurrentProcess();
    if(process == NULL)
    {
        fprintf(stderr, "Can't get a handle to current process (error %d)\n", GetLastError());
        exit(1);
    }


If option (1) works out without complications then we will go with that. Otherwise we can fall back to (2). However, the addition to the importing code should actually be done anyway to cover all cases and possibly other tools and setups. It was just an oversight by me.

**Comment by fedetftpolimi** [comment] 2022-06-10 10:01
I still find it more elegant to to just export symbols from the executable, as what the external function really needs to do is to call back into the executable. It's likely more performant too as there's no need to enumerate all loaded DLLs till we find the one with the symbol, but if you prefer to have them in a DLL it's fine for us as well.

I added the code to look for symbols in the executable first to ExternalMedia, so as to be as compatible as possible to what OpenModelica (and other tools such as Dymola) will decide to do in the future.

**Comment by mahge** [comment] 2022-06-10 10:28
> I still find it more elegant to to just export symbols from the executable, as what the external function really needs to do is to call back into the executable. It's likely more performant too as there's no need to enumerate all loaded DLLs till we find the one with the symbol, but if you prefer to have them in a DLL it's fine for us as well.

Elegant in one case but not in others 🙂. 

You have two use cases here. Evaluating at compile time and evaluating at simulation time. 

For the compile time evaluation we have to enumerate the DLLs loaded. It is just too big a change to pull out the `ModelicaError` functions from our runtime libraries and move them to the executable. Even if that was not a lot of work then what do we do about other libraries/code that wants to use those functions? link back to the exe... And then as you mentioned there is also the fact that even if we change things in OpenModelica you will still need to do the enumeration if you want to be more resilient to variations in other tools.

For the simulation time evaluation we can keep them in the executable and avoid the enumeration for now. However it will not stay that way. The library has to be a DLL at some point (it is already a DLL in the new CMake build system). Unless there are other reasons, I do not think it is reasonable to keep it static just for avoiding enumerating in this use case.

> I added the code to look for symbols in the executable first to ExternalMedia, so as to be as compatible as possible to what OpenModelica (and other tools such as Dymola) will decide to do in the future.

Just heads up, the test will not work with OpenModelica yet (at least for simulation time evaluations) until we add the flag to export all symbols to the generated executables.

**Comment by mahge** [comment] 2022-06-10 13:20
#9077 has changed the build type of the simulation library (`libSimulationRuntimeC`) to DLL on Windows, I know this appears an overkill for this specific issue but it is something that was overdue for a while. 

We will keep an eye on the Windows tests when they run and hopefully nothing has been broken. For this specific case it now means both test cases should work the same way on Linux as well as Windows. 

You can check again and if everything works as expected we can close this ticket.

**Comment by fedetftpolimi** [comment] 2022-06-10 13:42
I guess we will have to wait for a nightly build for Windows to become available?

**Comment by mahge** [comment] 2022-06-10 13:48
Yes if you are not building from source. Unfortunately though the Windows nightly job seems to be broken for the past two days. Hopefully it gets fixed today.

**Comment by mahge** [comment] 2022-06-27 12:12
@fedetftpolimi How is it going? Does it work as expected now? If so I think we should port the changes to our maintenance branch so that we can have it on the next release. And then we can close this.

**Comment by casella** [comment] 2022-06-27 15:12
@mahge I have to arrange a meeting with @fedetftpolimi, because I have the Windows machine, but he know exactly what I should test. We'll do that ASAP.

**Comment by casella** [comment] 2022-06-27 18:05
@mahge, we checked that symbols are correctly exported. Unfortunately we can't yet use this solution because it doesn't work in Dymola, but at least we have a demo implementation for our proposal to the MAP_LANG group.

Please cherry pick to maintenance/v1.19 and close the ticket. 

Thanks!

**Comment by mahge** [comment] 2022-06-27 18:26
> Unfortunately we can't yet use this solution because it doesn't work in Dymola

I was afraid that might not work. The Dymola people are probably not so keen on exposing the internals of their system. Unless, of course, you support it with some official proposal. Good luck. 

I will port this and close it.

**Comment by casella** [comment] 2022-06-27 18:57
> I was afraid that might not work. The Dymola people are probably not so keen on exposing the internals of their system. 

It's not internals, it's the functions defined in Modelica.Utilities. That's standard stuff.

> Unless, of course, you support it with some official proposal. Good luck.

Will do, thanks! 😄

**Comment by mahge** [comment] 2022-06-30 12:31
> Please cherry pick to maintenance/v1.19 and close the ticket.

This is going to bring a lot of other commits with it and that is going to be problematic to do smoothly.  How bad do you want this in the maintenance/v1.19? Maybe we can leave it for the next one.

**Closed** 2022-06-30 19:05 UTC
