### ISSUE TITLE
OMEncrypted removes connections from  diagrams of BRSL

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#7578] opened 2021-06-18 11:50 UTC
For encrypted version of BRSL the connections are removed if it is loaded in OMEncrypted

### Steps to Reproduce
E.g. load the encrypted libary Rexroth_Generic.mol and open the example: Rexroth_Generic.Hydraulics.Examples.FlowDirections
There you will see that the connections are removed
The error messages are:
```
[2] 13:24:59 Skripting Error
Unable to find component flowSource.port_A while parsing connection {flowSource.port_A,orifice.port_A,}.

[3] 13:24:59 Skripting Error
Unable to find component orifice.port_B while parsing connection {tank.port_A,orifice.port_B,}.

[4] 13:24:59 Skripting Error
Unable to find component flowSink.port_A while parsing connection {flowSink.port_A,orifice1.port_A,}.

[5] 13:24:59 Skripting Error
Unable to find component orifice1.port_B while parsing connection {tank1.port_A,orifice1.port_B,}.

[6] 13:24:59 Skripting Error
Unable to find component flowSink.port_A while parsing connection {flowSink.port_A,initialization.port_A,}.

[7] 13:24:59 Skripting Error
Unable to find component flowSource.port_A while parsing connection {flowSource.port_A,initialization1.port_A,}.
```
### Expected Behavior
The connection should not be removed

### Screenshots
Unfortuantly I cannot upload pictures due to an error

### Version and OS

 - OpenModelica Version: v1.16.0-dev-331-g8c4285669 (64-bit)
 - OS: Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable

**Comment by adeas31** [comment] 2021-06-23 14:14
This is because the components have access annotation of level `Access.documentation`. @niklwors I sent you an email with more information.

**Comment by niklwors** [comment] 2021-06-30 09:45
@adeas31  I have changed the access annotation to ```Access.diagram``` but the problem still exist. All connections are removed. Also the connections with MSL components.
I uploaded a new version of the encrpyted library.

**Comment by adeas31** [comment] 2021-06-30 10:35
Can you please also upload the unencrypted version as well? With the encrypted version I can't access `Rexroth_Generic.Hydraulics.Sources` modelica text which means it still have `Access.documentation` annotation.

**Comment by casella** [comment] 2021-07-05 12:45
@niklwors points out that the problem is due to inheritance of Access annotations. The [Modelica Specification 18.9.1](https://specification.modelica.org/maint/3.5/annotations.html#protection-of-classes) is silent about that, we should open a ticket there and discuss it.

**Comment by adeas31** [comment] 2021-07-05 16:50
I made a small test package [AccessPack.zip](https://github.com/OpenModelica/OpenModelica/files/6765515/AccessPack.zip). The package contents are,

AccessPack (No protection annotation defined so default is `Access.documentation`)
|--Internal (`Access.hide`)
|--InternalExtends (`Access.nonPackageText`)
|--View (`Access.nonPackageText`)

The Modelica model `AccessPack.View` diagram is,

![image](https://user-images.githubusercontent.com/4007231/124501137-4e7a5a00-ddc1-11eb-8d14-740dd40788c1.png)

OpenModelica encrypted version,

![image](https://user-images.githubusercontent.com/4007231/124501070-31458b80-ddc1-11eb-9004-cad2deb40648.png)

Dymola 2021 encrypted version,

![image](https://user-images.githubusercontent.com/4007231/124501091-3b678a00-ddc1-11eb-8eb1-a1fa6c17c204.png)

OpenModelica hides everything about `AccessPack.Internal` except for its name. Dymola shows the component icon both when the model is used directly or as extended. I think its a bug in Dymola. Dymola is only hiding the model from its `Package Browser`.

**Comment by niklwors** [comment] 2021-07-06 09:18
I have imported the encrypted library into Dymola and created a new model View2 that is extended from View. The diagram of View2 looks like the diagram of View.

**Comment by adeas31** [comment] 2021-09-02 09:43
It is clear from the above example that our implementation of `Access.hide` is correct. @niklwors shall we close this issue then?

**Comment by niklwors** [comment] 2021-10-01 08:14
@adeas31 we also have the problem that for some components the diagram is not completely shown,  although the package has the access annotation Access.nonPackageText and all used components in the diagram have the access annotation Access.icon. I will provide you the encrypted version of our BRSL

**Comment by niklwors** [comment] 2021-10-01 13:38
@adeas31 you can use the model BRSL.Rexroth_Generic.Hydraul….Cylinders.SingleRodCylinder. The annoations are as in the picture I sent you

**Closed** 2021-10-12 12:37 UTC
Labels: COMP/OMEdit

**Comment by niklwors** [comment] 2021-10-12 13:41
@adeas31 do you know why the text of the SingleRodCylinder is visible but not the diagram?

**Comment by adeas31** [comment] 2021-10-13 09:23
`SingleRodCylinder` uses the access annotation from parent package i.e., `access.nonPackagetext` so you can't see the text but you should be able to see the diagram if there is any. The reason you don't see the diagram is because `SingleRodCylinder` doesn't have any diagram, the diagram is extended from `BaseCylinder` which uses `access.icon` so you can't see the diagram.

Consider the actual case, if you go to `BaseCylinder` you can't see the diagram since its protected by `access.icon`. If I allow this diagram to be shown on `SingleRodCylinder` that means you are overriding the access annotation through extends which is not allowed.
