### ISSUE TITLE
Division by zero with 1.22 (and higher) but not with 1.21 in a simple model.

### ISSUE THREAD

**Issue by Ulfsen** [OpenModelica/OpenModelica#12730] opened 2024-07-19 08:46 UTC
### Description

Simulation of a simple model (fluid system) crashes in openmodelica 1.22 and higher with division by zero and "divisor b expression is: 0.0" - so it's hard to analyse what is going wrong. In 1.21 it's running fine.

### Steps to Reproduce

See attached minimal example "divzero.mo" in attached zip file. I have also included .log files for 1.21, 1.22 and 1.24.
[divzero.zip](https://github.com/user-attachments/files/16309630/divzero.zip)

### Expected Behavior

Simulation should run.

### Version and OS

 - OpenModelica Version: 1.22, 1.23, 1.24-dev ...
 - OS: Windows & Linux

**Comment by phannebohm** [comment] 2024-07-19 13:44
For some reason we generate the equation
```
m_dot_sensor.port_a.h_outflow = 0.0 / 0.0
```
which in the flat model looks like this
```modelica
m_dot_sensor.port_a.h_outflow = ($OMC$PositiveMax(-CV50a_16_A.port_a.m_flow, 1e-7) * CV50a_16_A.port_a.h_outflow + $OMC$PositiveMax(-CV50b_16_A.port_a.m_flow, 1e-7) * CV50b_16_A.port_a.h_outflow) / ($OMC$PositiveMax(-CV50a_16_A.port_a.m_flow, 1e-7) + $OMC$PositiveMax(-CV50b_16_A.port_a.m_flow, 1e-7));
```
There is clearly still something wrong with how we handle stream connections...

**Comment by casella** [comment] 2024-07-20 17:14
Absolutely. By definition, it should never happen that positiveMax's are all zero. At least one of them should be positive.

In fact, since `allowFlowReveral = false`, `m_dot_sensor.port_a.h_outflow` is totally irrelevant, so it should not be computed and instead given some default value. But that's another story. See modelica/ModelicaStandardLibrary#4436

I guess the problem is that we over-optimized PositiveMax. In this specific case, both flow are equal to constant zero, because the two valves CV1_03 and CV3_03 have both a hardwired zero opening. So, I guess the backend is smart enough to figure out that those flows are both zero.

If I remember correctly, we said that we would not take into account flows which are constant zero when determining these mixing quantities. Unfortunately, if they are all zero, we can end up with a singularity. 

@phannebohm can you please check if we have that rule? I guess we should remove it. We should only ignore those terms for which the flow rate has min >= 0.

**Comment by phannebohm** [comment] 2024-07-22 09:33
With #12739 merged the model `divzero` now fails during codegen instead of at runtime. It doesn't solve this issue but at least we can see more directly where the problem is.

**Comment by phannebohm** [comment] 2024-07-22 13:29
Since the min attribute is `0.0` for both `CV50a_16_A.port_a.m_flow` and `CV50b_16_A.port_a.m_flow`, the backend applies the following rule:
```
positiveMax(-cref, eps) = 0 if variable(cref).min >= 0
```

I can change that to a strict inequality check
```
positiveMax(-cref, eps) = 0 if variable(cref).min > 0
```
With that change, the model simulates.

What's weird is that in the flat model it looks like the min attribute is set to `-1e60` for both `*.m_flow` variables. In that case the above mentioned rule would not apply and the model should also simulate fine.

**Comment by phannebohm** [comment] 2024-07-22 15:28
> What's weird is that in the flat model it looks like the min attribute is set to `-1e60` for both `*.m_flow` variables. In that case the above mentioned rule would not apply and the model should also simulate fine.

I guess that is just a consequence of merging attributes of aliases.

**Comment by casella** [comment] 2024-07-22 16:15
> I can change that to a strict inequality check

Please don't do that, this will be very inefficient in a lot of cases.

I'm getting more and more convinced that the posted test cases has issues, see https://github.com/modelica/ModelicaStandardLibrary/issues/4436. Flow reversal is disabled, so that stream variable should not be computed based on properties of what comes in from the other side in the first place.

**Comment by phannebohm** [comment] 2024-07-23 12:21
> > I can change that to a strict inequality check
> 
> Please don't do that, this will be very inefficient in a lot of cases.

Agreed, and I suppose my "fix" doesn't even solve the problem in general. If you set `var.min = 1` the rule applies again and we still get `0.0 / 0.0`...

> I'm getting more and more convinced that the posted test cases has issues, see [modelica/ModelicaStandardLibrary#4436](https://github.com/modelica/ModelicaStandardLibrary/issues/4436). Flow reversal is disabled, so that stream variable should not be computed based on properties of what comes in from the other side in the first place.

I tried to read the MLS and understand stream connectors. I think this case is what's described in [Appendix C.3.4 of the MLS](https://specification.modelica.org/master/derivation-of-stream-equations.html#connection-of-3-stream-connectors-where-two-mass-flow-rates-are-positive-ideal-splitting-junction-for-uni-directional-flow). Is that correct? I'm not sure if we handle it as described.

**Comment by casella** [comment] 2024-07-23 13:53
> I tried to read the MLS and understand stream connectors. 

They are indeed tricky. The problem is, handling flow reversal in a way that is at the same time efficient, fast, and robust is a tough problem. I think stream connectors are a good solution for that, but they are definitely not trivial.

> I think this case is what's described in [Appendix C.3.4 of the MLS](https://specification.modelica.org/master/derivation-of-stream-equations.html#connection-of-3-stream-connectors-where-two-mass-flow-rates-are-positive-ideal-splitting-junction-for-uni-directional-flow). Is that correct?

Absolutely. In fact, I had forgotten about that case. We should add a rule, that if all the flows involved in the inStream connector have min >= 0, then `inStream(c.streamVar)` should just return `c.streamVar`. It could actually return any value, since the actual quantity is undetermined, but if we put, say, zero, that could be outside the validity range for some medium models and trigger some asserts.

Please proceed with that. Thanks!

**Comment by casella** [comment] 2024-07-23 13:54
Hopefully this will fix some more issues in the library testsuite 😅

**Closed** 2024-07-24 15:12 UTC
Labels: COMP/OMC/Backend

**Comment by Ulfsen** [comment] 2024-07-25 07:46
A big thank you for the quick solution. 👍

**Comment by phannebohm** [comment] 2024-07-25 07:58
> Hopefully this will fix some more issues in the library testsuite 😅

According to [this report](https://libraries.openmodelica.org/branches/history/master/2024-07-23%2022:55:14..2024-07-25%2000:41:10.html) the results are sadly not so strong... a few models work now, but a few others have numerical issues.

**Comment by casella** [comment] 2024-07-25 09:25
> A big thank you for the quick solution. 👍

Thank you for reporting 😃

**Comment by casella** [comment] 2024-07-25 09:27
> According to [this report](https://libraries.openmodelica.org/branches/history/master/2024-07-23%2022:55:14..2024-07-25%2000:41:10.html) the results are sadly not so strong... a few models work now, but a few others have numerical issues.

@phannebohm, we are reviewing all the simulation and verification failures in Buildings, it turns out there are many models which are numerically fragile, so those regressions are not necessarily significant. In any case, we should implement what the specification says, unless we find out it's not good, in which case we should change it. So far, I don't see any reason to do that in this specific case.
