### ISSUE TITLE
Cannot load library in OMEdit from a directory with accented letters

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8777] opened 2022-03-28 22:16 UTC
Unpack the attached zip file, that contains two libararies in an accented letter directory.

When trying to open TestPackage/package.mo, I get:
```
[1] 00:13:40 Translation Error
[C:/dev/OM64bit/OMCompiler/Compiler/FrontEnd/ClassLoader.mo: 313:9-313:128]: Internal error loadCompletePackageFromMp failed for unknown reason: mp=D:/Temp/Lib èèè pack=TestPackage

[2] 00:13:40 Scripting Error
Failed to load package TestPackage () using MODELICAPATH D:/Temp/Lib èèè/.
```
When I try to open ExternalMedia 3.3.0/package.mo instead, I get
```
[1] 00:15:02 Grammar Warning
[D:/Temp/Lib èèè/ExternalMedia 3.3.0/package.mo: 2:1-23:18]: Media was referenced in the package.order file, but was not found in package.mo, Media/package.mo or Media.mo.
```
and an empty ExternalMedia package is shown in the Libraries Browser.

**Comment by casella** [comment] 2022-04-11 21:26
@adrpo has already implemented this feature using short directory names in #8573, for use by the package manager and linker/compiler. This also needs to be done when loading libraries in OMEdit.

**Comment by casella** [comment] 2022-05-02 23:17
Short directory names seem to be used now, since the error I get with 1.19.0-beta.1 uses them. However, the issue is not yet fixed. Please unzip the [TestAccentedLetterDir.zip](https://github.com/OpenModelica/OpenModelica/files/8606514/TestAccentedLetterDir.zip).

If you attempt to load TestLibrary/package.mo from OMEdit under Windows, you get
```
[1] 01:14:23 Translation Errore
[C:/OM119/OM64bit/OMCompiler/Compiler/FrontEnd/ClassLoader.mo: 334:9-334:128]: 
Internal error loadCompletePackageFromMp failed for unknown reason: mp=D:/Temp/TestAccentedLetterDir/Lib èèè pack=TestPackage

[2] 01:14:23 Scripting Errore
Failed to load package TestPackage () using MODELICAPATH D:/Temp/TestAccentedLetterDir/Lib èèè/.
```
while if you run omc test.mos, you get
```
false
"[C:/OM119/OM64bit/OMCompiler/Compiler/FrontEnd/ClassLoader.mo:334:9-334:128:writable]
Error: Internal error loadCompletePackageFromMp failed for unknown reason: mp=D:/Temp/TestAccentedLetterDir/Lib ├¿├¿├¿ pack=TestPackage
Error: Failed to load package TestPackage () using MODELICAPATH D:/Temp/TestAccentedLetterDir/Lib ├¿├¿├¿/.
"
```
@adrpo, as I understand the class loader for Windows must also be fixed, otherwise it would be impossible to load libraries from accented directories at all.

**Comment by AnHeuermann** [comment] 2022-05-17 13:08
I changed `omc_fopen`. Do we need to use it in OMEdit as well? I did not change it there, because it uses different stuff around `fopen`.

@adeas31 Should we check wat OMEdit is using and if `omc_fopen` is usable there?

**Comment by adeas31** [comment] 2022-05-18 20:31
The library loading error is from compiler so if you have changed the compiler to use `omc_fopen` then it should be good enough. OMEdit only uses `fopen` for its own log files.

**Comment by casella** [comment] 2022-05-19 08:24
@AnHeuermann, @adeas31 please agree on who can take care of this and please make sure it is also cherry-picked to maintenance/v1.19, so it will go into 1.19.0 as well. Thanks!

**Comment by AnHeuermann** [comment] 2022-05-19 09:04
I'll give it a go today.

**Comment by AnHeuermann** [comment] 2022-05-19 10:00
First issue is, that function `getProgramFromStrategy` is able to fail silently when getting a file name from a hash table. I re-actiavted the error message in that function:

```
"[D:/workspace/OpenModelica/OMCompiler/Compiler/FrontEnd/ClassLoader.mo:827:9-827:184:writable] Error: Internal error HashTable missing file D:/workspace/Testitestetst/issue-8777/TestAccentedLetterDir/Lib ├¿├¿├¿/TestPackage/Media.mo - all entries include:
D:/workspace/Testitestetst/issue-8777/TestAccentedLetterDir/Lib ├¿├¿├¿/TestPackage/package.mo
```

But the root problem is, that the string for the directory path  changes from `Lib èèè` to  `Lib ├¿├¿├¿`. Could be an encoding issue.

---------------------

On Ubuntu `unzip` did extract the directory to `.../Lib KKK/...`. I had to change it manually  but then there is still no issue on Ubuntu.

By the way, is the typo in Media.mo relevant?
```modelica
with TestPackage; <---- within?
package Media
end Media;
```

**Comment by AnHeuermann** [comment] 2022-05-19 11:12
Okay, the issue goes way deeper than what I could change quickly.

When creating a mos script test.mos
```
print("Test: Lib èèè\n\n");
```
in Windows I get
```
# omc test.mos 
Test: Lib ├¿├¿├¿
```

I can add the error message https://github.com/OpenModelica/OpenModelica/pull/8985 to the master.
@casella Do you want the error message in maintenance/v.19 as well?

But I don't think we can solve this issue fast.
I opened a new ticket for this: https://github.com/OpenModelica/OpenModelica/issues/8986

**Comment by casella** [comment] 2022-05-19 18:23
> Okay, the issue goes way deeper than what I could change quickly.
> 
> When creating a mos script test.mos
> 
> ```
> print("Test: Lib èèè\n\n");
> ```
> 
> in Windows I get
> 
> ```
> # omc test.mos 
> Test: Lib ├¿├¿├¿
> ```

Is this just a problem of graphical rendering of the output on the Windows terminal? In that case, I wouldn't bother.
 
> I can add the error message #8985 to the master. 

OK. Can be helpful for debugging.

> @casella Do you want the error message in maintenance/v.19 as well?

I don't think getting an Internal Error on getProgramFromStrategy (BTW, what the hell does that function name mean?) helps end-user much.
 
> But I don't think we can solve this issue fast. I opened a new ticket for this: #8986

I'm still not convinced that this is the issue. Getting a bad rendering of pathnames with accented letters in error messages on a Windows cmd console is slightly annoying, but no big deal. Not being able to load libraries from directories with accented letters can completely break the package manager, if the username contains accented letters (or Russian characters, as it happened once with one of my students). That is a much bigger deal, particularly in corporate environments, where you cannot install stuff where you want in the file system, but you must stick to your home directory.

**Comment by casella** [comment] 2022-05-19 18:24
I mean, the package manager and the linker work fine in that case. We just need to use the same mechanism for the package loader.

**Comment by perost** [comment] 2022-05-19 18:32
> I don't think getting an Internal Error on getProgramFromStrategy (BTW, what the hell does that function name mean?) helps end-user much.

It loads a file (as an `Absyn.Program`) using a given strategy: on-demand (loads directly from filesystem) or hashtable (loads from a hash table of pre-loaded files). It actually makes sense in context.

**Comment by sjoelund** [comment] 2022-05-19 18:35
I wonder if ANTLR internally loads things fine. Does loadFile work with accents in paths? https://github.com/OpenModelica/OpenModelica/blob/934e1493a0f39f6dbc26c92ebb2df981e65612ea/OMCompiler/Parser/parse.c#L457

It might also exist other functions that do not support this as Windows is a mess.

**Comment by AnHeuermann** [comment] 2022-05-20 07:46
`loadFile` is working correctly in the case below:

```
loadFile("Lib èäöüß/model.mo"); getErrorString();
```

What is the difference in running the original problem? We do stuff differently for files named `package.mo`.

But I can't debug this without #8986 being fixed because my prints won't show the right stuff and I don't have Eclipse with MDT set up on my Windows system.

**Comment by AnHeuermann** [comment] 2022-05-20 11:27
@mahge and myself tracked it down to `void* System_moFiles(const char *directory)`. Using [FindFirstFileW](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirstfilew) on unicode string `pattern`. will solve the issue. I'll create a PR for it.

**Comment by AnHeuermann** [comment] 2022-05-20 19:08
I'll create the cherry pick for maintenance/v1. 19 on Monday.

**Comment by casella** [comment] 2022-05-20 20:31
I'd keep this open until we've actually tested it on 1.19.0-dev.beta5 😅

**Comment by casella** [comment] 2022-05-29 21:36
@mahge, @AnHeuermann, we are almost there, but not yet. Try the attached [TestAccentedLetterDir.zip](https://github.com/OpenModelica/OpenModelica/files/8794349/TestAccentedLetterDir.zip) with v1.19.0-dev.beta5 (64-bit). TestPackage is loaded fine, but when I try to load ExernalMedia, I get:
```
[1] 23:35:16 Grammar Warning
[D:/Temp/TestAccentedLetterDir/Lib èèè/ExternalMedia 3.3.0/package.mo: 2:1-23:18]: Media was referenced in the package.order file, but was not found in package.mo, Media/package.mo or Media.mo.
```
and the Media package is actually not loaded at all.

**Comment by mahge** [comment] 2022-05-30 09:28
@AnHeuermann this mos script reports the error for me

```mo
loadFile("Lib èèè/ExternalMedia 3.3.0/package.mo");
getErrorString();
```

**Comment by AnHeuermann** [comment] 2022-05-30 09:35
Works for me.
```
Username@PC MINGW64 /d/workspace/Testitesttest/issue-8777/TestAccentedLetterDir
# omc test.mos 
true
""
```

Are we on the same omc version?
I'm on maintenance/v1.19 (1b635573bf0f9557562cb50d94b26573b4b3f3c3) and have build with CMake and am running the test in the MINGW64 shell from OMDev.

**Comment by mahge** [comment] 2022-05-30 09:42
I am on d51b93f84b (tip of master) and also with CMake and OMDev/MINGW64. Something is not right here. 

Unfortunately, eclipse is refusing to recognize any breakpoints. It just woke up today and decided not to. I am trying to figure out what is behind that.

**Comment by perost** [comment] 2022-05-30 09:44
> Unfortunately, eclipse is refusing to recognize any breakpoints. It just woke up today and decided not to. I am trying to figure out what is behind that.

Did you build omc as Release instead of Debug perhaps?

**Comment by mahge** [comment] 2022-05-30 09:46
It is a debug build. The odd thing is that me and @AnHeuermann used it just a few days ago and since then it has not even been opened 🙂. Maybe something got updated.

**Comment by mahge** [comment] 2022-05-30 10:18
@AnHeuermann I think `SystemImpl__directoryExists` needs the wide character treatment just like `SystemImpl__regularFileExists`

https://github.com/OpenModelica/OpenModelica/blob/d51b93f84bc922c557d88d2bb925f31ec6627788/OMCompiler/Compiler/runtime/systemimpl.c#L913-L939

**Comment by AnHeuermann** [comment] 2022-05-30 10:23
Could be, but I can't test if it works since for me it is still working. Even with the installed OpenModelica v1.19.0-dev.beta5.

I guess in the end we need to modify nearly all functions in systemimpl.c.

**Comment by casella** [comment] 2022-05-30 11:09
@AnHeuermann here is a step-by-step guide to reproduce the issue that does not involve the zip file
- create a directory with spaces and accented letters
- download [ExternalMedia 3.3.1.zip](https://github.com/modelica-3rdparty/ExternalMedia/releases/download/v3.3.1/ExternalMedia_v3.3.1.zip) from github and unpack it in there
- open the ExternalMedia library with OMEdit 1.19.0-dev.beta5 and check if the Media package shows up in the Libraries Browser tree

Note that ExternalMedia won't work if you try to simulate some of the examples - we're currently working on that. The goal for the time being is that it should be loaded correctly from accented letter directories.

**Comment by AnHeuermann** [comment] 2022-05-30 11:54
I created `D:\workspace\Testitesttest\issue-8777\dir w äöüéè\` and unziped `ExternalMedia 3.3.1` into it.

Then I'm starting OMEdit 1.19.0-dev.beta5, unloading all standard libraries (I have MSL 4.0.0 loaded on startup) and then open the `package.mo` with `File->Open Model/Library Files`.

![image](https://user-images.githubusercontent.com/38031952/170986684-cda3b60b-0ec0-489e-9a02-4c9a1d44417b.png)

**Comment by mahge** [comment] 2022-05-31 18:54
[This](https://github.com/OpenModelica/OpenModelica/issues/8777#issuecomment-1140528948) should be now fixed with #9044. We probably need to do more of these adjustments in more places. For now we can take them as they occure.

Please reopen if the issue is still there.

**Comment by casella** [comment] 2022-05-31 19:30
I'll test it tomorrow with the nightly build and re-close if it is fine. If it works for me, then it would be nice to backport the fix to maintenance/v1.19, so we get it in 1.19.1. Thanks!

**Comment by casella** [comment] 2022-06-05 15:52
@mahge, I tested #9044 with the latest nightly and now everything works for me 😃 

Could you please port it to maintenance/v1.19? Thanks!

**Comment by mahge** [comment] 2022-06-06 19:36
Fixed in #9044 and ported to maintenance/v1.19 in #9063.

**Comment by casella** [comment] 2022-06-07 09:12
I prefer to keep this open until I've actually checked in on the built version, just in case. I'll take care of that.

**Closed** 2022-06-23 21:38 UTC
Labels: bug, COMP/GUI/OMEdit

**Comment by casella** [comment] 2022-07-05 23:19
Works fine in 1.19.2-dev.beta2.
