### ISSUE TITLE
OMEdit GUI: Allow to edit parameters and replaceable classes for the top level model

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OpenModelica#11089] opened 2023-08-26 10:38 UTC
### Description

Currently when you right click on a model diagram you don't get any way to edit the parameters and replaceable classes.
You can only edit the parameters and replaceable classes of the components of the top level model.

### Steps to Reproduce

See:
https://stackoverflow.com/questions/76982441/how-to-change-medium-in-msl-fluid-examples-tanks-threetanks

### Expected Behavior

Add a "Parameters" context menu item for right click on the diagram (or double click on the diagram) that should get you a dialog where you can edit the top level parameters and replaceable classes.

**Comment by casella** [comment] 2023-09-06 10:11
Duplicate of #8066.

**Closed by casella** 2023-09-06 10:11 UTC
Labels: duplicate
