### ISSUE TITLE
The NB generates invalid C code for IEEE14busStaticNetwork because of unhandled Complex operator records

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12629] opened 2024-06-22 13:37 UTC
Please check [PowerGrids.Examples.IEEE14bus.IEEE14busStaticNetwork](https://libraries.openmodelica.org/branches/newInst-newBackend/PowerGrids/files/PowerGrids_PowerGrids.Examples.IEEE14bus.IEEE14busStaticNetwork.err). The C code compilation fails with
```

PowerGrids_PowerGrids.Examples.IEEE14bus.IEEE14busStaticNetwork_02nls_part0.c:2566:18: error: invalid operands to binary expression ('Complex' and 'PowerGrids_Types_ComplexAdmittance' (aka 'Complex'))
    tmp13 = tmp0 - tmp1 - (data->simulationInfo->daeModeData->residualVars[1210]) /* $RES_SIM_771 DAE_RESIDUAL_VAR */ - (data->simulationInfo->daeModeData->residualVars[1210]) /* $RES_SIM_771 DAE_RESIDUAL_VAR */;
            ~~~~ ^ ~~~~
```
probably due to some issue related to code generation involving Complex operator records. As far as I understood, Complex operator records should be completely eliminated by the backend, probably something's missing somewhere.

**Comment by phannebohm** [comment] 2024-09-13 15:16
#12880 is a duplicate of this issue. I'm closing this because the discussion is in the other issue.

**Closed by phannebohm** 2024-09-13 15:16 UTC
Labels: COMP/OMC/New Backend
