### ISSUE TITLE
Modelica-Buildings Library (master): Simulation fails while Compiling.

### ISSUE THREAD

**Issue by NehaSPatwardhan** [OpenModelica/OpenModelica#13222] opened 2024-11-15 06:32 UTC
### Description

Solver fails to check /compile the model. It throws translation error while checking.

The given model is having this issue:
```
Buildings.Templates.Plants.HeatPumps.Components.Validation.HeatRecoveryChiller
```
On simulating the model in OpenModelica leads to following errors/warnings:
```
1.Translation error	
2.Cannot connect expandable connector busPumHeaWatHrc with non-expandable connector bus.pumHeaWatHrc.	

```
The error report of the model is given below:
https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Templates.Plants.HeatPumps.Components.Validation.HeatRecoveryChiller.err
```
[/home/hudson/saved_omc/libraries/.openmodelica/libraries/Buildings 12.0.0-master/Templates/Plants/HeatPumps/Components/Validation/HeatRecoveryChiller.mo:154:3-155:89:writable] Error: Cannot connect expandable connector busPumHeaWatHrc with non-expandable connector bus.pumHeaWatHrc.

```
### Steps to Reproduce

Load the Modelica-Buildings master library (Source: https://github.com/lbl-srg/modelica-buildings/)
Simulate the examples model present in  
Buildings.Templates.Plants.HeatPumps.Components.Validation.HeatRecoveryChiller

### Expected Behavior
The model should simulate successfully.

### Version and OS

 - OpenModelica Version: OpenModelica 1.25.0~dev-152-g78d9a41
- OS: 11.1.0ubuntu4
 - Versions of used Modelica libraries:
Modelica 4.0.0
Buildings 12.0.0

**Comment by casella** [comment] 2024-11-15 07:07
See #13067.

**Comment by casella** [comment] 2024-12-05 10:12
Duplicate of #13354

**Closed by casella** 2024-12-05 10:12 UTC
Labels: COMP/OMC/Frontend
