### ISSUE TITLE
Equivalent systems give very different results (high priority!)

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#8373] opened 2021-12-29 12:11 UTC
### Description
Consider the following tiny package:
[BugGround.mo.txt](https://github.com/OpenModelica/OpenModelica/files/7788763/BugGround.mo.txt)
It contains two simulation models: GroundAC and GroundDC.
They represent identical circuits: only the position of ground is different. In circuits in which only the position of the one ground is different, all voltages (i.e. differences of potentials) must be the same.
In OpenModelica the quantity of the two simulations is largely different. Dymola gives the same result in the two cases.

See "Description" 
### Expected Behavior
The values of Rload.v[1] created using GroundAC and GroundDC must be the same.

### Screenshots
OM results:
![image](https://user-images.githubusercontent.com/37046832/147660520-e954f9ad-473f-43f9-a84f-e082ea60d241.png)
Dymola results:
![image](https://user-images.githubusercontent.com/37046832/147660552-7805da1e-77b7-4727-84bd-4867486818de.png)

### Version and OS

 - OpenModelica Version: OM 1.19.0-dev336
 - OS: Win 10 64 bit
 - Modelica Standard Library: 3.2.3

**Comment by casella** [comment] 2022-01-04 16:18
I checked the results of the simulation of the GroundAC model, where the there is a very large current (tens of mega-Ampere) flowing into the ground, which is of course a bogus result, because that current should turn out to be zero if there only one ground component, hence no ground loop(s).

I guess there is something wrong with the ASCC algorithm, that does not produce equivalent equations.

I'll try to come up with a simpler model that replicates this issue and post it here.

**Comment by casella** [comment] 2022-01-04 22:17
@kabdelhak, please check the attached package, which contains two simplified models that reproduce the issue of non-zero ground current.

The first one, `GroundAC1`, still contains the time-varying driving signals for the switches, and reproduces the very large current found in the original `GroundAC` model.

The second one, `GroundAC2`, replaces the switch inputs with constants equal to their initial values; this allows for further symbolic simplification, so the computed ground current is different and much lower, but it is still non-zero, so I think this should be used for debugging first.

The corresponding (equivalent) circuits with the ground placed on the DC side are also included.

The backend correctly identifies the constraint among the three inductor currents, and selects the following state variables:
```
Lf.inductor[2].i, Lf.inductor[3].i, dcC.v
```
I looked into the symbolic debugger and tried finding out how `ground.p.i` is computed in `GroundAC2`. I found the following equations:
```
(torn) downSW.i[1] := downSW.v[1] * downSW.idealClosingSwitch[1].Goff
(torn) upSW.v[1] := dcC.v - downSW.v[1]
(torn) upSW.i[1] := upSW.v[1] / upSW.idealClosingSwitch[1].Ron
(residual) upSW.i[1] - Lf.inductor[2].i + Lf.inductor[3].i + downSW.i[1] = 0
(assign) Lf.inductor[1].i := upSW.i[1] - downSW.i[1]
(assign) ground.p.i := Lf.inductor[1].i + Lf.inductor[2].i + Lf.inductor[3].i
```
The 1st, 2nd, 3rd, 5th, and 6th equations look good to me. The fourth not so much. Unfortunately the debugger does not contain information about where it comes from - I guess it was somehow reshuffled, and something went wrong there, but unfortunately there is no debugging information about that.

My guess is that the 4th equation should rather look like this:
```
upSW.i[1] + Lf.inductor[2].i + Lf.inductor[3].i - downSW.i[1] = 0
```
so that, combined with the 5th and 6th it would yield
```
ground.p.i = 0
```
Maybe something went wrong with the signs during the recombiation of equations. @kabdelhak, can you please check what happens there?

It would also be good if the reshuffleLoop and ASCC operations were recorded in the debugging information, maybe @sjoelund could help with that.

**Comment by casella** [comment] 2022-01-10 20:36
Following advice by @AnHeuermann, I switched off ASSC, but then index reduction did not take place and the system was singular.

So, I turned on `-d=dumpASSC` and got this:
```
###################################################### 
 LinearJacobian sparsity pattern: Solved (initial: false) 
###################################################### 
(scal_idx|arr_idx|changed) [var_index, value] || RHS_EXPRESSION 
(32|32|false):    [23|1.0] [21|-1.0] [11|1.0] [9|-1.0]     || RHS: dcC.v + (-downSW.idealClosingSwitch[1].v) - upSW.idealClosingSwitch[1].v 
(4|4|false):    [14|1.0] [26|-1.0]     || RHS: -Lf.inductor[3].i 
(3|3|false):    [27|1.0] [15|-1.0]     || RHS: -Lf.inductor[2].i 
(11|11|true):    [32|1.0] [15|-1.0] [26|-1.0]     || RHS: (-upSW.i[1]) - Lf.inductor[3].i 
(5|5|true):    [34|1.0] [15|1.0] [26|1.0]     || RHS: (-upSW.i[1]) - Lf.inductor[3].i 
(10|10|true):    EMPTY ROW         || RHS: downSW.i[1] + Lf.inductor[3].i + upSW.i[1] - Lf.inductor[2].i 
 
[ASSC] The equation: downSW.i[1] + downSW.i[2] + downSW.i[3] + star1.pin_n.i = 0.0 
[ASSC] Gets replaced by equation: 0.0 = downSW.i[1] + Lf.inductor[3].i + upSW.i[1] - Lf.inductor[2].i 
```
I'm not sure I can follow how the result was obtained, but I am positive that the original equation is correct, while I'm fairly sure the replaced one isn't.

@kabdelhak, please double-check what the ASSC algorithm does in this specific case.

**Comment by kabdelhak** [comment] 2022-01-18 23:09
fixed with #8436 , thanks @phannebohm for the help!

**Closed** 2022-01-18 23:59 UTC

**Comment by casella** [comment] 2022-01-19 10:00
Very good! Let's see if this has a positive impact on the library testsuite, besides this specific issue.

Thanks to @max-privato for reporting and @kabdelhak + @phannebohm for the quick fix!

**Comment by kabdelhak** [comment] 2022-01-19 11:21
> Very good! Let's see if this has a positive impact on the library testsuite, besides this specific issue.
> 
> Thanks to @max-privato for reporting and @kabdelhak + @phannebohm for the quick fix!

It was actually i quite bad error from my part which in many cases just happened to cancel out with another error i made. Could have some impact on all models where ASSC is involved

**Comment by casella** [comment] 2022-01-19 11:49
> Could have some impact on all models where ASSC is involved

I guess so, let's see.

**Comment by casella** [comment] 2022-01-19 22:59
Here is the [report](https://libraries.openmodelica.org/branches/history/master/2022-01-18%2022:23:33..2022-01-19%2011:23:30.html). It's not a dramatic improvement, just 4 models. I guess the DeviceDrivers model is one of those that flip back and forth between different runs for some reason, while the other three are probably genuine improvements.

Anyway, nice outcome.

**Comment by max-privato** [comment] 2022-01-20 06:56
Thank you!

This solves 99% of the issue.
For the record, I just want to mention that now in the GroundDC model we have ground currents around 0.1 A peak, and in the groundAC 0.005A.
They are a bit too large (theoretically they should be zero), especially those in GroundDC, if compared with the load current which has less than 200A peak.

For comparison: in Dymola in both cases we have ground currents around 10^(-13)A.

**Comment by casella** [comment] 2022-01-21 10:12
@max-privato, I tried BugGround.GroundDC from your original package with the latest nightly, this is the result:

![immagine](https://user-images.githubusercontent.com/4233148/150495924-e6e19254-b63b-4b93-8781-22b8ea47c75f.png)

Looks pretty much like Dymola. I guess you are using a version of OMC that still does not include that update.

**Comment by phannebohm** [comment] 2022-01-21 14:42
Note the unit (pA) perhaps :slightly_smiling_face:

**Comment by max-privato** [comment] 2022-01-21 15:33
Bleah, my fault!

Now the outcome of this ticket is very, VERY good.

Thanks again, everybody.

**Comment by casella** [comment] 2022-01-21 16:17
> Note the unit (pA) perhaps 🙂

@max-privato, you [asked for this feature](https://trac.openmodelica.org/OpenModelica/ticket/5447) yourself 😄
