### ISSUE TITLE
NF fails to evaluate division between a scalar and an array (and viceversa)

### ISSUE THREAD

**Issue by mscuttari** [OpenModelica/OpenModelica#9251] opened 2022-07-20 13:18 UTC
### Description

Considering the [Type1_N_1_M_1 model](https://github.com/PowerGrids/ScalableTestGrids/blob/master/ScalableTestGrids/Models/Type1_N_1_M_1.mo) within the ScalableTestGrids library, the frontend fails when encountering a division between a scalar and an array (and viceversa).

### Steps to Reproduce

The array / scalar issue can be reproduced with the following command:

```omc Type1_N_1_M_1.mo Modelica +i=ScalableTestGrids.Models.Type1_N_1_M_1 -f -d=nonfScalarize,mergeComponents```

```
Notification: Automatically loaded package Complex 3.2.3 due to uses annotation.
Notification: Automatically loaded package ModelicaServices 3.2.3 due to uses annotation.

Error processing file: Type1_N_1_M_1.mo
Notification: Automatically loaded package PowerGrids 1.0.2 due to uses annotation.
Notification: Automatically loaded package ScalableTestGrids default due to uses annotation.
[/var/lib/jenkins2/ws/LINUX_BUILDS/tmp.build/openmodelica-1.20.0~dev-218-g2dd6f78/OMCompiler/Compiler/NFFrontEnd/NFCeval.mo:1125:9-1125:67:writable] Error: Internal error NFCeval.evalBinaryDiv failed to evaluate ‘{400000.0, 400000.0, 400000.0, 400000.0, 400000.0, 400000.0, 63000.0, 63000.0} / 1.732050807568877‘

# Error encountered! Exiting...
# Please check the error message and the flags.
```

The scalar / array issue can be reproduced with the additional `evaluateAllParameters` flag:

```omc Type1_N_1_M_1.mo Modelica +i=ScalableTestGrids.Models.Type1_N_1_M_1 -f -d=nonfScalarize,mergeComponents,evaluateAllParameters```

```
Notification: Automatically loaded package Complex 3.2.3 due to uses annotation.
Notification: Automatically loaded package ModelicaServices 3.2.3 due to uses annotation.

Error processing file: Type1_N_1_M_1.mo
Notification: Automatically loaded package PowerGrids 1.0.2 due to uses annotation.
Notification: Automatically loaded package ScalableTestGrids default due to uses annotation.
[/var/lib/jenkins2/ws/LINUX_BUILDS/tmp.build/openmodelica-1.20.0~dev-218-g2dd6f78/OMCompiler/Compiler/NFFrontEnd/NFCeval.mo:1125:9-1125:67:writable] Error: Internal error NFCeval.evalBinaryDiv failed to evaluate ‘0.0 / {1000000000.0, 1000000000.0, 1000000000.0, 1000000000.0, 1000000000.0, 1000000000.0, 1000000000.0, 1000000000.0}‘

# Error encountered! Exiting...
# Please check the error message and the flags.
```

### Expected Behavior

Model is instantiated correctly in both cases.

### Version and OS

 - OpenModelica 1.20.0~dev-218-g2dd6f78
 - Ubuntu 18.04
 - Modelica 3.2.3, PowerGrids 1.0.2

**Comment by casella** [comment] 2022-07-20 17:00
@perost the models in that library often have binding equations where some variables or parameters are divided by normalization factors (such as SNom) or by numerical factors, such as sqrt(3). I guess this is not handled correctly when collecting multiple scalar instances in a single array.

**Comment by perost** [comment] 2022-08-17 11:32
The issue can be reduced to (using only `-d=nonfScalarize`):
```Modelica
model PortAC
  parameter Real UNom annotation(Evaluate=true);
  final parameter Real VBase = UNom / 3;
end PortAC;

model Type1_N_1_M_1
  PortAC[2] ports(UNom = {400e3, 400e3});
end Type1_N_1_M_1;
```
The problem is that when scalarization is turned off the `VBase` variable is turned into an array `Real[2] ports.VBase = UNom / 3`, where the binding after evaluating `UNom` becomes `{400e3, 400e3} / 3`. This is technically valid Modelica but doesn't work because the compiler still thinks it's supposed to be a scalar operation, and if there are e.g. bindings from multiple levels you can easily get something that's not valid Modelica regardless.

I'm not sure how to solve this in general, we probably need to vectorize the bindings somehow but it's not immediately obvious to me how. I think there's already a ticket open for the issue but I can't find it right now.

**Comment by casella** [comment] 2022-08-18 22:50
@perost, couldn't we use iterators to vectorize binding equation, e.g.
```
Real[2] ports.VBase = {Unom[i]/3 for i in 1:end}
```

**Comment by perost** [comment] 2022-08-19 08:04
> @perost, couldn't we use iterators to vectorize binding equation, e.g.
> 
> ```
> Real[2] ports.VBase = {Unom[i]/3 for i in 1:end}
> ```

Yes, but it's far from trivial to implement correctly in general when you have variables and bindings from different scopes. I've spent a lot of time on it for the scalarized path to get the constant evaluation working correctly, but it's not obvious how to use that to vectorize bindings.

**Comment by casella** [comment] 2022-08-19 21:55
I understand it's not optimal, but could we start with a solution that handle simple cases as the ones in question (i.e. expressions involving one parameter and some literal constants)? This would get us going with power grid models, which are a key application for large-scale systems.

**Comment by casella** [comment] 2022-10-17 18:10
> The problem is that when scalarization is turned off the `VBase` variable is turned into an array `Real[2] ports.VBase = UNom / 3`, where the binding after evaluating `UNom` becomes `{400e3, 400e3} / 3`. This is technically valid Modelica but doesn't work 
because the compiler still thinks it's supposed to be a scalar operation.

As an alternative to the iterator-based solution, we could fix the issue with the ScalableTestGrids library by making this binding ok. As you wrote, multiplications and divisions of arrays by scalars are well-defined in Modelica, I'm not sure why the compiler "thinks it's supposed to be a scalar operation", since the binding equation now has an array on the LHS. Could you find a fix for that instead?

**Comment by casella** [comment] 2022-10-17 18:13
Adding @danielecattaneo and @kabdelhak to the loop.

**Comment by perost** [comment] 2022-10-18 13:34
@casella: #9541 implements the proposed iterator solution, which fixes my MWE but unfortunately not the `Type1_N_1_M_1` model when using the `mergeComponents` flag.

I had to add a flag that enables this functionality, `-d=vectorizeBindings`, because it breaks one of the existing vectorized test cases [(testVectorizedBlocks)](https://github.com/OpenModelica/OpenModelica/blob/master/testsuite/openmodelica/cppruntime/testVectorizedBlocks.mos). For some reason it gets the wrong simulation result with this enabled, but I'm not sure why. The flat model looks correct, but the vectorized models seem to be very sensitive to changes.

One issue is that we now generate fill/array constructor calls during the flattening process, instead of towards the end of the instantiation like before. This means that the expressions are expanded during constant evaluation or simplification, so we can get large array expressions in the final flat model which is kind of counter-productive to our goal. I'm not yet sure how to avoid that without breaking other things.

So you can try out the new flag if you want, but it needs more work.

**Comment by perost** [comment] 2022-10-18 16:10
#9541 is still not merged due to server issues. I'm trying it for the third time now, if it still doesn't work I'll try again tomorrow instead.

**Comment by casella** [comment] 2022-10-19 20:44
> @casella: #9541 implements the proposed iterator solution, which fixes my MWE but unfortunately not the `Type1_N_1_M_1` model when using the `mergeComponents` flag.
 
Too bad, our goal remains elusive 😅 

Is it a bad interaction with `mergeComponents`?

> I had to add a flag that enables this functionality, `-d=vectorizeBindings`, because it breaks one of the existing vectorized test cases [(testVectorizedBlocks)](https://github.com/OpenModelica/OpenModelica/blob/master/testsuite/openmodelica/cppruntime/testVectorizedBlocks.mos). For some reason it gets the wrong simulation result with this enabled, but I'm not sure why. The flat model looks correct, but the vectorized models seem to be very sensitive to changes.

Weird. I'll have a look at that.
> 
> One issue is that we now generate fill/array constructor calls during the flattening process, instead of towards the end of the instantiation like before. This means that the expressions are expanded during constant evaluation or simplification, so we can get large array expressions in the final flat model which is kind of counter-productive to our goal. I'm not yet sure how to avoid that without breaking other things.

Me neither. Maybe we could briefly discuss this during the next devmeeting.
 
> So you can try out the new flag if you want, but it needs more work.

Will do.

**Comment by perost** [comment] 2022-10-20 07:39
> > @casella: #9541 implements the proposed iterator solution, which fixes my MWE but unfortunately not the `Type1_N_1_M_1` model when using the `mergeComponents` flag.
> 
> Too bad, our goal remains elusive sweat_smile
> 
> Is it a bad interaction with `mergeComponents`?

I'm not sure, but it's probably not an issue with `mergeComponents` as such but that it produces some form of array bindings that we can't yet handle without scalarization.

**Comment by casella** [comment] 2022-11-08 00:43
On the other hand, if I try to flatten the original Type1_N_1_M_1 model from ScalableTestGrids with
```
-f -d=nonfScalarize,vectorizeBindings,mergeComponents,combineSubscripts,printRecordTypes,evaluateAllParameters --newBackend --showStructuralAnnotations
```
I get
```
[3] 01:34:28 Translation Error
[C:/dev/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFCeval.mo: 1422:9-1422:67]: 
Internal error NFCeval.evalUnaryMinus failed to evaluate 
‘-{1000000000.0, 1000000000.0, 1000000000.0, 1000000000.0, 1000000000.0, 1000000000.0, 1000000000.0, 1000000000.0}[$$LineConstantImpedance11]‘
```
while if I don't use the -d=vectorizeBindings flag:
```
-f -d=nonfScalarize,mergeComponents,combineSubscripts,printRecordTypes,evaluateAllParameters --newBackend --showStructuralAnnotations

```
I get
```
[3] 01:33:27 Translation Error
[C:/dev/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFCeval.mo: 1125:9-1125:67]: Internal error NFCeval.evalBinaryDiv failed to evaluate ‘0.0 / {1000000000.0, 1000000000.0, 1000000000.0, 1000000000.0, 1000000000.0, 1000000000.0, 1000000000.0, 1000000000.0}‘
```
So, it seems that your fix works fine in the real case when the division is involved, but then fails when a unary minus is involved. I guess the trick here would be to use iterators also in the case of expressions only involving a unary minus?

**Comment by perost** [comment] 2022-11-08 08:45
> I'm a bit confused, do I miss something?

The issue is that you use the `evaluateAllParameters` flag which triggers additional evaluation, which in this case doesn't work for some reason.

> So, it seems that your fix works fine in the real case when the division is involved, but then fails when a unary minus is involved. I guess the trick here would be to use iterators also in the case of expressions only involving a unary minus?

We already use iterators for expressions involving unary minus, it's not based on what kind of expression it is but on the information we use to scalarize them. So the issue in this case is not that it's a unary minus expression but that it's subscripted with a "proxy node" that's used internally and shouldn't show up there.

**Comment by casella** [comment] 2022-11-08 09:10
> > I'm a bit confused, do I miss something?
> 
> The issue is that you use the `evaluateAllParameters` flag which triggers additional evaluation, which in this case doesn't work for some reason.

Aha, so that is the culprit. For efficient code generation this is really important, we need to carry out as much work as possible at compile time, so evaluating parameters is essential. Later on, it may be useful to leave some un-evaluated, see #4960, but this is not top priority now.

> We already use iterators for expressions involving unary minus, it's not based on what kind of expression it is but on the information we use to scalarize them. So the issue in this case is not that it's a unary minus expression but that it's subscripted with a "proxy node" that's used internally and shouldn't show up there.

I afratid can't follow you down the technical rabbit hole. What I can say is that being able to flatten ScalableTestGrids models while keeping arrays intact is a top priority milestone in our quest for large-scale system support (including the LargeDyn project, ending this year), and also very important for our key OSMC partner RTE.

Please see what you can do here, getting this thing done may pay huge dividends. Thanks!

**Comment by perost** [comment] 2022-11-10 15:18
With the changes in #9685 the `Type1_N_1_M_1` model now flattens with all of the flags.

However, it doesn't work with `-d=arrayConnect` which is necessary for the new backend, it seems to choke on some for-loop iterators for some reason.

It also doesn't work with the old backend, because the non-scalarized flattening doesn't unroll for-loops with connects in them. That's fine when using the array connection handling, but doesn't work with the normal connection handling. This leads to a lot of empty for-loops in the flat model, because they still contain connects after the connection handling which the frontend doesn't know what to do with.

So we probably need to decide on which backend to target if we want to take it further.

**Comment by perost** [comment] 2022-11-10 15:23
And also, the `-d=vectorizeBindings` flag is still necessary. The `testVectorizedBlocks` test case that didn't work before now actually works, but one of the other tests broke instead. So seems like there's still some issues left to fix before we can make this the default.

**Comment by casella** [comment] 2022-11-10 15:53
> With the changes in #9685 the `Type1_N_1_M_1` model now flattens with all of the flags.

Great, thanks! At least we can now give it a try with our MARCO compiler, starting from the non-scalarized flat Modelica output.

> However, it doesn't work with `-d=arrayConnect` which is necessary for the new backend, it seems to choke on some for-loop iterators for some reason.

Ouch. This is weird, parameter modifiers and array connections seem pretty disconnected things to me. Any clue what could be the reason?

Anyway, power grid models do not contain array connection statements. In fact, those models are scalar in the beginning, they are array-fied by -d=mergeComponents, so that the code generation can avoid generating the code of components multiple times. But the code corresponding to each scalar connect must be preserved. So, I hope this is good enough for MARCO, for the time being.

> It also doesn't work with the old backend, because the non-scalarized flattening doesn't unroll for-loops with connects in them. That's fine when using the array connection handling, but doesn't work with the normal connection handling. This leads to a lot of empty for-loops in the flat model, because they still contain connects after the connection handling which the frontend doesn't know what to do with.

I don't think this is relevant. Why would you want to use -nonfScalarize with the old backend? Many other things won't be supported. Do I miss something?

> So we probably need to decide on which backend to target if we want to take it further.

Why, of course the new one. The old one is scalarized, and it [already works fine like that](https://libraries.openmodelica.org/branches/master/ScalableTestGrids_noopt/ScalableTestGrids_noopt.html).

**Comment by casella** [comment] 2022-11-10 15:54
> And also, the `-d=vectorizeBindings` flag is still necessary. The `testVectorizedBlocks` test case that didn't work before now actually works, but one of the other tests broke instead. So seems like there's still some issues left to fix before we can make this the default.

OK. For the time being we'll try this out in MARCO. Regarding OMC with the new backend, it seems there are also other problems to be fixed first...

**Comment by casella** [comment] 2022-11-15 23:17
@perost, I still have several issues, sorry.

I can flatten successfully Type1_N_1_M_1 with these flags:
```
-f -d=nonfScalarize,mergeComponents,evaluateAllParameters,printRecordTypes,vectorizeBindings --showStructuralAnnotations
```
However, I need to add
- `combineSubscripts` to shift all subscripts at the end of composite names. If I do that I get "Internal error NFType.subscript got unsubscriptable type $LineConstantImpedance1.portB.InputComplexCurrent"
- --newBackend to avoid flattening records in variable definitions. If I do that I get "Internal error NFCeval.evalBinaryDiv failed to evaluate ‘1.0 / {1443.375672974064, 1443.375672974064, 1443.375672974064, 1443.375672974064, 1443.375672974064, 1443.375672974064, 9164.289987136917, 9164.289987136917}‘"

I'd like to try if `--frontendInline` can bypass some problems, but the nightly with it hasn't been compiled yet.

**Comment by casella** [comment] 2022-11-21 16:40
@perost, I tried to compile `ScalableTestGrids.Models.Type1_N_1_M_1` with flags `-f -d=nonfScalarize,mergeComponents,evaluateAllParameters,vectorizeBindings --frontendInline` but I got
```
[3] 17:30:46 Translation Error
[C:/dev/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFSubscript.mo: 706:11-707:53]:
Internal error NFSubscript.toDAEExp failed on unknown subscript '<$Bus6, 1>'
```
I'm afraid I need all these flags: I need non-scalarized stuff, I need to collect multiple instances of the same model into arrays, I need to evaluate all parameters for maximally efficient code, and of course I need to vectorize bindings, which was and still is the main point of this ticket.

@perost would you mind checking that flag combination and see if that is a quick fix?

Thanks!

**Comment by perost** [comment] 2022-11-24 16:45
@casella: #9755 should fix the issue.

**Comment by casella** [comment] 2022-11-24 17:40
Great, thanks!

@mscuttari with this fix we should be able to proceed with the model, by also replacing saturations with smooth expressions in the Modelica source code.

**Comment by perost** [comment] 2022-12-12 12:17
Considering that the model now works for me at least I'll consider no feedback to be good feedback and close this issue.

**Closed by perost** 2022-12-12 12:17 UTC

**Comment by casella** [comment] 2022-12-12 22:31
I can confirm that we can now flatten `ScalableTestGrids.Models.Type1_N_1_M_1` with flags `-f -d=nonfScalarize,mergeComponents,evaluateAllParameters,vectorizeBindings --frontendInline`.

Thanks @perost!

**Comment by casella** [comment] 2022-12-12 22:34
There are other issues with the flattened model, but I'll open other tickets for that 😃
