### ISSUE TITLE
OMEdit 1.22.1 - Error by Instance Placement in presence of SI parameter in protected section

### ISSUE THREAD

**Issue by ialkov** [OpenModelica/OpenModelica#11952] opened 2024-02-05 12:37 UTC
### 1. Consider simple model

![image](https://github.com/OpenModelica/OpenModelica/assets/151835130/27a0167b-8553-4f0f-aa7b-9451ab819ce2)
![image](https://github.com/OpenModelica/OpenModelica/assets/151835130/5eca77cd-7ad3-481c-8f61-d6084a93eead)

### 2. Pay attention for protected section (for simple Real parameters the issue does not occur)
![image](https://github.com/OpenModelica/OpenModelica/assets/151835130/7b406418-78ce-4cd3-8b19-c92bae6df30e)

### a) E.g. adding a "fixed1" instance indicates a graphical issue but this do not initially occurs in source code 
![image](https://github.com/OpenModelica/OpenModelica/assets/151835130/c17ad5db-93b3-4393-ad03-610d7691495e)
![image](https://github.com/OpenModelica/OpenModelica/assets/151835130/a6b39d06-c926-4edd-ac80-b6d4fbaea96f)

### b) Moving the corrupted instance "fixed1" on graphical modeling space reveals a reaction in source code which seems to be not related but...
![image](https://github.com/OpenModelica/OpenModelica/assets/151835130/68d93c5d-21d2-4c25-bbbc-bf6906a21ad0)
![image](https://github.com/OpenModelica/OpenModelica/assets/151835130/ae70c488-5167-43df-948e-c91d721da941)

### c) ...but removing the annotation added by GUI interaction from the protected parameter leads to proper behaviour of both GUI and source code except for initial positioning of the instance "fixed1"
![image](https://github.com/OpenModelica/OpenModelica/assets/151835130/00e1c8fb-9ae4-45f8-800a-76b44ce2aab9)
![image](https://github.com/OpenModelica/OpenModelica/assets/151835130/39cdcedf-95e9-4824-978c-c381d5403ed6)

### Version and OS
 - OpenModelica Version: 1.22.1
 - OS: Windows 10, 64 bit
 - Libraries: Modelica(version = "4.0.0") and any other user libraries

![image](https://github.com/OpenModelica/OpenModelica/assets/151835130/9a74fb60-c046-428f-bce6-c7d349c5774a)

### Additional Context
What annoying magic

**Comment by abuntrock** [comment] 2024-02-08 07:56
Maybe this is related to #11055, which is fixed in the current nightly version, but was present in 1.22.1 as well

**Comment by casella** [comment] 2024-02-08 18:37
@ialkov can you try with the latest nightly build?

**Comment by ialkov** [comment] 2024-02-09 07:19
@casella 
No. Unfortunately, I cannot install the newest version. The cyber security polices require a substantial effort for the software whitelisting and secure distribution in companies. That's because, I always reliant on the stability of official release. :-(

**Comment by adeas31** [comment] 2024-02-09 08:24
This is a duplicate of #11055 as pointed out by @abuntrock.

**Closed by adeas31** 2024-02-09 08:24 UTC

**Comment by ialkov** [comment] 2024-02-09 12:40
OK. Thanks to all for the analyses. Looking forward to the improvements in 1.23.0.

**Comment by casella** [comment] 2024-02-09 12:59
You shoud be able to use 1.22.2 for that. Will be released soon.
