### ISSUE TITLE
Changing Stop Time in Re-Simulation Setup options makes OMEdit crash

### ISSUE THREAD

**Issue by matteodepascali** [OpenModelica/OpenModelica#8371] opened 2021-12-28 22:05 UTC
Trying to re-simulate a model in OMEdit changing the simulation Stop Time from the Re-Simulate Setup options causes OMEdit to crash. This behavior is present from OpenModelica version **v1.19.0-dev-460-gaeb8a6d1a3**.

-Simulate in OMEdit the model:

```
model test
Real x;
equation
x = 1;
end test;
```

-Click Re-Simulate Setup in the Plotting tab
-Change simulation Stop Time
-Simulate the model

In the previous nightly build the simulation works fine.

@casella

**Comment by adrpo** [comment] 2021-12-29 00:59
Duplicate of #8369.

**Closed by adrpo** 2021-12-29 00:59 UTC
