### ISSUE TITLE
Structurally singular system

### ISSUE THREAD

**Issue by Rajanrudani96** [OpenModelica/OpenModelica#10285] opened 2023-03-01 10:07 UTC
### Description

Internal error IndexReduction.pantelidesIndexReduction failed! System is structurally singular and cannot be handled because the number of unassigned equations is larger than the number of states. Use -d=bltdump to get more information

### Version and OS

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment] 2023-03-01 14:33
@Rajanrudani96 your model is obviously not balanced because of high-index issues, but if you do not include an example to reproduce the problem in this ticket, we can't help you much.

**Comment by AnHeuermann** [comment] 2023-03-06 10:46
Closing this issue because no information about the issue is provided / it is most likely a modelling issue and not an issue with OpenModelica. @Rajanrudani96 If this is wrong please add more information and re-open this issue.

@Rajanrudani96 You can open a [new discussion](https://github.com/OpenModelica/OpenModelica/discussions/new/choose) and add more information to get some help regarding your higher index problem.

**Closed by AnHeuermann** 2023-03-06 10:46 UTC
Labels: invalid
