### ISSUE TITLE
Exported FMU with linux subsystem for Win has link issues

### ISSUE THREAD

**Issue by BjorHart** [OpenModelica/OpenModelica#7895] opened 2021-09-15 07:41 UTC
### Description

I have exported an FMU from a linux subsystem for windows. Trying to run the FMU in a clean virtual environment using fmpy  the fmu throws error

```python
'Failed to load shared library /tmp/tmpgm0f5nd7/binaries/linux64/Runner_test.so. liblapack.so.3: cannot open shared object file: No such file or directory'
```

I am able to remove the error by ni installing libatlas-base-dev with sudo:
```
sudo apt-get install libatlas-base-dev

```
Why does the fmu have a dependency on an external library? How can I get around this?

### Steps to Reproduce
change extension of below zipped fmu to .fmu, and run with fmpy function fmpy.simulate_fmu():
[Runner_test.zip](https://github.com/OpenModelica/OpenModelica/files/7167807/Runner_test.zip)

### Version and OS

 - OpenModelica Version: 1.18.0
 - OS: Ubuntu 18.04 subsystem on Windows 10

**Comment by sjoelund** [comment] 2021-09-15 08:06
This seems to be due to configure not checking for static linking of lapack (configure.ac RT_LDFLAGS_GENERATED_CODE_SOURCE_FMU).

The work-around is simple: compile for the platform directly instead of using the default, faster method:
```mo
loadString("model M
end M;");
buildModelFMU(M, platforms={"x86_64-linux-gnu"}); // Much slower, but will do what you want
// buildModelFMU(M); // Links with cached variables, doesn't recompile everything
getErrorString();
```

I'll assign this to myself (I'm too busy to fix it now) and Mahder (who hates autoconf and FMI, but perhaps is interested in the bug).

**Comment by mahge** [comment] 2021-09-15 08:13
> I'll assign this to myself (I'm too busy to fix it now) and Mahder (who hates autoconf and FMI, but perhaps is interested in the bug).

I do not hate autoconf 😊 Let alone FMI. 

@BjorHart Can you please check and tell us what version of `gfortran` and `gcc` you have on WSL.

**Comment by sjoelund** [comment] 2021-09-15 08:19
> @BjorHart Can you please check and tell us what version of `gfortran` and `gcc` you have on WSL. They might not match.

This shouldn't matter. But the Linux installation package needs to depend on the static version of lapack/blas so it is installed and can be linked. The autoconf needs to look for static lapack/blas at compile-time of the deb-package and change that RT_LDFLAGS_GENERATED_CODE_SOURCE_FMU to link it. Otherwise we could end up with someone installing omc but not able to link FMUs... It's more involved than just linking lapack/blas dynamically.

**Comment by mahge** [comment] 2021-09-15 10:03
It was just a blind guess to eliminate possibilities. I have seen FMUs linking to two different `liblapack` versions on Ubuntu 18.04 on WSL1. Old `gfortran` versions depend on `liblapack.so.3` or something like that. While Ipopt/suitesparse and others (?) pull in `liblapack.so.5`. I am not sure if I am remembering this correctly but it is along these lines. We might be linking one statically as intended but the other is linked dynamically. Another thing is that the autoconf detected lapack is not passed to the CMake compiled 3rdParty libs. Which can possibly end up picking the other one. 

It might not be what is happening here but it needs to be fixed anyway to make sure we always link to only one. I will check properly. The good news is that I was working on FMU support for CMake so it is a good time. I am finishing up setting up a new  PC. As soon as it is ready I will install WSL Ubuntu 18.04 and see if I can duplicate this.

**Comment by BjorHart** [comment] 2021-09-15 10:13
Hi! Thank you for getting back to me!

> This seems to be due to configure not checking for static linking of lapack (configure.ac RT_LDFLAGS_GENERATED_CODE_SOURCE_FMU).
> 
> The work-around is simple: compile for the platform directly instead of using the default, faster method:
> 
> ```modelica
> loadString("model M
> end M;");
> buildModelFMU(M, platforms={"x86_64-linux-gnu"}); // Much slower, but will do what you want
> // buildModelFMU(M); // Links with cached variables, doesn't recompile everything
> getErrorString();
> ```
> 
> I'll assign this to myself (I'm too busy to fix it now) and Mahder (who hates autoconf and FMI, but perhaps is interested in the bug).

I was running the GUI using XLaunch. Where do you run these API commands?



> > I'll assign this to myself (I'm too busy to fix it now) and Mahder (who hates autoconf and FMI, but perhaps is interested in the bug).
> 
> I do not hate autoconf 😊 Let alone FMI.
> 
> @BjorHart Can you please check and tell us what version of `gfortran` and `gcc` you have on WSL. They might not match.

GNU Fortran==7.5.0
gcc==7.5.0

**Comment by sjoelund** [comment] 2021-09-15 10:33
> I was running the GUI using XLaunch. Where do you run these API commands?

If you are using OMEdit, you can make the changes under Tools->Options->FMI->Platforms.
Use none in the drop-down and check x86_64-linux-gnu.

I was using a mos-script (can input the commands in OMShell / OMNotebook / OMPython as well).

**Comment by AnHeuermann** [comment] 2022-11-02 08:58
It should now be possible to copy all dynamic dependencies into an FMU using the CMake FMUs.
There is a section on it in the User's Guide: https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/fmitlm.html#cmake-fmu-export

```
setCommandLineOptions(" --fmuCMakeBuild=true --fmuRuntimeDepends=modelica"); getErrorString();
```
or
```
setCommandLineOptions(" --fmuCMakeBuild=true --fmuRuntimeDepends=all"); getErrorString();
```

should do the trick.

If this doesn't resolve the issue please reopen it.

**Closed by AnHeuermann** 2022-11-02 08:58 UTC
Labels: COMP/FMI
