### ISSUE TITLE
Unreported results in the testsuite regression report

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#7849] opened 2021-09-02 09:50 UTC
### Description

The [latest regression report](https://libraries.openmodelica.org/branches/history/master/2021-08-31%2023:16:46..2021-09-01%2022:54:52.html) on the master branch lacks a result for 23 test cases in different versions of the Buildings library.

All those cases fail for the same reason
```
Error: Too few equations, under-determined system. The model has 3145 equation(s) and 3225 variable(s).
[Buildings 8.0.0/BoundaryConditions/SolarIrradiation/DiffusePerez.mo:73:3-79:31:writable]
Warning: Variable roo.bouConExtWin.sha[4].weaBus.HDifHor does not have any remaining
equation to be solved in.
```
I guess there are at least two, possibly three problems here

- @perost's commit probably broke something related to arrays with records
- it may be possible that @phannebohm's commit is involved, though it doesn't seem likely to me
- in any case, the compilation fails in a way that breaks the testing script, so that a regression result is not reported

Please check and report

**Comment by phannebohm** [comment] 2021-09-02 17:05
I guess there is a small chance that my cleaning up of `calculateSimulationSettings` did that. I would be very surprised if that's the case, since that code looked as if it served no purpose. But I will revert that and see.

**Comment by perost** [comment] 2021-09-02 17:59
The regressions where due to my changes. They should already be fixed, but I will wait for the regression report before I close this.

I have no clue why the models even show up in the regression report though, they failed in the backend both before and after so it shouldn't technically be counted as a regression (it's good that it was caught though).

**Closed** 2021-09-03 09:13 UTC
Labels: COMP/New Instantiation, COMP/Backend, CI/Library Testing
