### ISSUE TITLE
Issue with NFTyping.typeBindings in Buildings 7.0.1

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#7838] opened 2021-08-31 17:33 UTC
Please check [Buildings.ThermalZones.Detailed.Examples.ElectroChromicWindow](https://libraries.openmodelica.org/branches/master/Buildings_7.0.0/files/Buildings_7.0.0_Buildings.ThermalZones.Detailed.Examples.ElectroChromicWindow.err). NFTyping.typeBindings fails with
```
[Buildings 7.0.1/HeatTransfer/Conduction/SingleLayer.mo:149:5-149:33:writable]
Error: Array types mismatch. Argument 5 ({3, 3}) has type Integer[2] whereas previous arguments have type Integer[4].
```

**Comment by perost** [comment] 2021-11-01 16:26
Duplicate of #7835.

**Closed by perost** 2021-11-01 16:26 UTC
Labels: bug, COMP/New Instantiation
