### ISSUE TITLE
Checking for functions fails systematically 

### ISSUE THREAD

**Issue by arouhan** [OpenModelica/OpenModelica#7737] opened 2021-08-04 05:07 UTC
using OpenModelica v1.18.0-dev.beta1, checking of any function fails.
the error message being: (example: splitPathName  from the MSL 4.0.0):

`Error: Cannot instantiate Modelica.Utilities.Files.splitPathName due to class specialization FUNCTION.`

**Comment by casella** [comment] 2021-08-22 14:54
Duplicate of [#5045](https://trac.openmodelica.org/OpenModelica/ticket/5045).

@arouhan, we'll try to address it in one of the next releases.

**Closed by casella** 2021-08-22 14:54 UTC
