### ISSUE TITLE
Missing dll when running Buildings.Applications.DataCenters.DXCooled.Examples.DXCooledAirsideEconomizer in Windows

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8184] opened 2021-11-21 19:34 UTC
I tried to reproduce [this error](https://libraries.openmodelica.org/branches/master/Buildings_maint.7.0.x/files/Buildings_maint.7.0.x_Buildings.Applications.DataCenters.DXCooled.Examples.DXCooledAirsideEconomizer.sim) with the latest nightly build on Windows. During compilation, I get these errors:
```
[6] 20:24:55 Translation Error
[Modelica.Utilities.Strings: 84:3-113:14]: External function ‘ModelicaStrings_compare‘ could not be found in any of the given shared libraries:
  C:/Program Files/OpenModelica1.19.0-dev-64bit/lib//omc/ModelicaExternalC.dll
  C:/Program Files/OpenModelica1.19.0-dev-64bit/lib/omlibrary/Modelica 3.2.3/Resources/Library/win64/ModelicaExternalC.dll
  C:/Program Files/OpenModelica1.19.0-dev-64bit/lib/omlibrary/Modelica 3.2.3/Resources/Library/ModelicaExternalC.dll

[7] 20:24:55 Translation Error
[Modelica.Utilities.Strings: 123:5-123:80]: Failed to evaluate function: Modelica.Utilities.Strings.compare.

```
Apparently the model works on Linux, since we get some output from the simulation in the [test report](https://libraries.openmodelica.org/branches/master/Buildings_maint.7.0.x/files/Buildings_maint.7.0.x_Buildings.Applications.DataCenters.DXCooled.Examples.DXCooledAirsideEconomizer.sim). I guess #8149 may be involved. @mahge, can you please check?

In any case, this should be fixed before the 1.19.0 release.

**Comment by sjoelund** [comment] 2021-11-22 08:52
Does the following file work? I don't have an OM Windows installation, but could cross-compile this from mingw (extract it to the correct location and rename it):

[libModelicaExternalC.zip](https://github.com/OpenModelica/OpenModelica/files/7579430/libModelicaExternalC.zip)

**Comment by mahge** [comment] 2021-11-22 09:53
#8149 just moved around source directories. It did not change how `ModelicaExternalC` libraries were built.

This is due to #8153. More context https://github.com/OpenModelica/OpenModelica/pull/8149#issuecomment-972741055

**Comment by casella** [comment] 2021-11-22 11:58
Folks, sorry, we have a serious problem with the Windows version, and we need to get it fixed properly before the 1.19.0 release. That is my main concern. Please let's avoid flame wars on a public forum and let's try to keep cool.

I am seeing a basic problem here, for which I guess we will also need @adrpo's help. I just installed the latest Win64 nightly build, which is what the majority of our user do use, like it or not. 

If I browse the `C:\Program Files\OpenModelica1.19.0-dev-64bit\lib\omlibrary\Modelica 3.2.3\Resources` directory, the `Libraries` directory is missing entirely. According to my understanding, it should be there, and it should contain all the libraries that we see on the [GitHub repo](https://github.com/modelica/ModelicaStandardLibrary/tree/maint/3.2.3/Modelica/Resources/Library/win64), plus ModelicaExternalC, which should be built according to the instruction of this [readme.txt](https://github.com/modelica/ModelicaStandardLibrary/blob/maint/3.2.3/Modelica/Resources/C-Sources/readme.txt).

As I understand, those libraries are specific to the MSL, so they belong to that place, not to `C:\Program Files\OpenModelica1.19.0-dev-64bit\lib\omc`

So the question is, why are all those libraries missing? This is going to cause a lot more problem than the specific issue of this ticket. @adrpo, can you please comment about that?

BTW, we have exactly the same problem with MSL 4.0.0.

For the record, I put the library attached by Martin in the system library directory `C:\Program Files\OpenModelica1.19.0-dev-64bit\lib\omc`, where it could be found, and after renaming it to ModelicaExternalC.dll (Windows does not start library names with the lib- prefix) the example did indeed run.

**Comment by mahge** [comment] 2021-11-22 11:58
Okay. Then I guess I will see what I can do.

**Comment by sjoelund** [comment] 2021-11-22 12:11
> As I understand, those libraries are specific to the MSL, so they belong to that place, not to C:\Program Files\OpenModelica1.19.0-dev-64bit\lib\omc

But MA does not build the DLLs/shared objects (that we need) and we build libraries as part of OMC 3rdParty, especially since we use MINGW and not regular Win32/Win64. The library is (thus far) backwards compatible, so it's been somewhat OK to keep it in there.

@casella did the DLL work?

> Okay. Then I guess I will see what I can do.

I would just work on fixing the problem at the source, making sure https://github.com/modelica/ModelicaStandardLibrary can build the DLLs easily, and then copying them into OMC to see if things work. And I think maybe marking the ModelicaUtilitites.o functions as dllexport (not sure if it's needed or not).

**Comment by mahge** [comment] 2021-11-22 12:22
> And I think maybe marking the ModelicaUtilitites.o functions as dllexport (not sure if it's needed or not).

If you build them with MinGW you can probably use `export-all-symbols` instead (Depending on your preference). They also have a CMake build support now, so you can maybe use that to build with MSVC with CMake's `WINDOWS_EXPORT_ALL_SYMBOLS`.

_Just a heads up though, if you do `export-all-symbols`, note that MinGW `ld` will ignore the `export-all-symbols` it if you have even one explicit `dllexport` in the code._

**Comment by mahge** [comment] 2021-11-22 12:25
On second thought, the CMake build support is tied to OpenModelica (as in to assumes it is part of OpenModelica) so if you are building them standalone, I can adjust the CMake file for that and pass it to you.

**Comment by casella** [comment] 2021-11-22 12:27
> > As I understand, those libraries are specific to the MSL, so they belong to that place, not to C:\Program Files\OpenModelica1.19.0-dev-64bit\lib\omc
> 
> But MA does not build the DLLs/shared objects (that we need) and we build libraries as part of OMC 3rdParty, especially since we use MINGW and not regular Win32/Win64. The library is (thus far) backwards compatible, so it's been somewhat OK to keep it in there.

Yeah, now I remember about that. It's a bit borderline, but OK.

**Comment by casella** [comment] 2021-11-22 12:28
>@casella did the DLL work

Yes, after renaming, as I wrote in a previous comment:

> For the record, I put the library attached by Martin in the system library directory `C:\Program Files\OpenModelica1.19.0-dev-64bit\lib\omc`, where it could be found, and after renaming it to ModelicaExternalC.dll (Windows does not start library names with the lib- prefix) the example did indeed run.

**Comment by sjoelund** [comment] 2021-11-22 12:28
> On second thought, the CMake build support is tied to OpenModelica (as in to assumes it is part of OpenModelica) so if you are building them standalone, I can adjust the CMake file for that and pass it to you.

I would prefer if ModelicaStandardLibrary.git can build the DLLs. Otherwise, how would we remove ModelicaExternalC from OMC sources in the future?

**Comment by mahge** [comment] 2021-11-22 12:34
> I would prefer if ModelicaStandardLibrary.git can build the DLLs. Otherwise, how would we remove ModelicaExternalC from OMC sources in the future?

That is what I meant. If you instead need a standalone build with the corresponding compiler, I can adjust our CMake file and you can add that to ModelicaStandardLibrary.git and use it to generate and build Visual Studio dlls if needed. I thought the ModelicaStandardLibrary.git only provided autoconf targets. However, I can see now that it actually includes Visual Studio projects as well.

**Comment by sjoelund** [comment] 2021-11-22 12:37
Well, I used the automake build project to build [the attached](https://github.com/OpenModelica/OpenModelica/files/7579430/libModelicaExternalC.zip) and I expect it to work.

**Comment by sjoelund** [comment] 2021-11-22 12:40
[ModelicaUtilitiesImport.zip](https://github.com/OpenModelica/OpenModelica/files/7581025/ModelicaUtilitiesImport.zip) and just adding to Makefile.am (should be limited to when using mingw):

```
+AM_LDFLAGS = -no-undefined -Wl,--export-all-symbols
+libModelicaExternalC_la_LDFLAGS      = -module -shared -avoid-version -export-dynamic -no-undefined -enable-runtime-pseudo-reloc --export--all-symbols -Wl,-lModelicaUtilititesImport
```

**Comment by mahge** [comment] 2021-11-22 12:41
> Well, I used the automake build project to build the attached and it did work...

Then it is all good. I thought there was problems with building and dllexport.

**Comment by sjoelund** [comment] 2021-11-22 12:44
The ModelicaUtilititesImport.c is just a small program that you can use with `x86_64-w64-mingw32-gcc -o libImportModelicaUtilities.o -Wl,--out-implib,libImportModelicaUtilities.a ModelicaUtilitiesImport.c` to create the import library. But I guess it could cause problems with build static and shared libs at the same time.

**Comment by mahge** [comment] 2021-11-22 12:46
My recommendation is to avoid having any explicit `dllexport` at all. That way the header can work for both versions without changes. 

It is a small library and almost all functions are exported anyway. So `export-all-symbols` should be fine. But it can not be mixed with explicit `dllexport` on MinGW.

**Comment by sjoelund** [comment] 2021-11-22 12:49
The header doesn't need it. That's just a separate C-file to create the import library (could be part of ModelicaStandardLibrary.git - nothing OMC-specific). But when you link OMC, are we sure there is **nothing** in there using dllexport? It's a big library...

**Comment by mahge** [comment] 2021-11-22 12:52
> But when you link OMC, are we sure there is nothing in there using dllexport? It's a big library...

I am not sure but maybe you can just remove the macro definition (#define DLLExport _declspec ...) if there is one. I am not sure. I will check.

**Comment by mahge** [comment] 2021-11-22 12:56
The problem is `importlibs` and `def` files are annoying (unfamiliar for most linux people) to produce, use and keep maintained. And for something that is distributed with ModelicaStandardLibrary maybe a little too advanced(?). It is all personal preference I guess. 

It is alright for now. Whatever works to get started and then can be adjusted if there are issues.

**Comment by sjoelund** [comment] 2021-11-22 12:59
The thing is they are necessary for anything that resembles plugins. And the Modelica specification does use ModelicaUtilitites.c, so there is not really any way around it if you want DLLs on Windows. And we do want to recommend DLLs in order to easily load any external libraries necessary for structural parameters/etc. If it's part of MSL that's a nice place to show how to do it in a good way.

**Comment by mahge** [comment] 2021-11-22 13:10
Ahh. Okay I see now. We are, of course, talking about building them without `libOpenModelicaCompilerC`. For some reason I was thinking about using them. Then yes `importlibs` are a must. I was stuck on the old process somehow.

**Comment by adrpo** [comment] 2021-11-23 22:18
Geez, I should have read all the comments before trying to build a dll for ModelicaExternalC, it would have saved me some hours of googling :)

**Comment by adrpo** [comment] 2021-11-23 22:21
I managed to force the autotools to build also the shared libs but then I got unresolved symbols from the functions in ModelicaUtilities.h and I was planning to write a small dll containing those but it seems @sjoelund already did that, thanks. I'll try to integrate my stuff with your stuff.

**Comment by adrpo** [comment] 2021-11-24 08:55
Yeah, building both static and dynamic at the same time is problematic, I fear we need to make two different projects as we need to conditionally build and link the libImportModelicaUtilities and I don't seem to find a proper way to do this with autotools.

**Comment by sjoelund** [comment] 2021-11-24 09:37
Well, you could --enable-shared --disable-static, etc to be able to compile one of them at least. But then I suppose we would need some copies or symbolic links to have 2 build directories. This is the one thing cmake does better, with separate build directories per configuration.

**Comment by mahge** [comment] 2021-11-24 10:23
> This is the one thing cmake does better, with separate build directories per configuration.

I can adjust the CMake config I wrote for use with OMC to be more general and strictly "correct" if you need it (_ModelicaExternalC also does not have a config header, it needs one_). It is a very small one so you can even write one. But the advantage of providing a CMake build is probably more of the fact that it is cross platform, e.g., you can remove the Visual Studio projects from MSL ExternalC.

btw does
```
mkdir build && cd build
../.configure --...
```
not work? In theory that should be just fine.

--------------------------------------------------------------------
However, my recommendation (if we don't find any hidden problems with it) is this.

As it stands now I think we always have `libOpenModelicaRuntimeC` compiled by the time we clone/download/install/prepare MSL to be used by omc. So perhaps we can just link to it and avoid the import libs and the complications that come with it. 

We can patch the downloaded `ModelicaExternalC` build system to link to our `libOpenModelicaRuntimeC`. 

_Ideally the upstream can also provide a linking command (for shared builds) to some non existing "implementation" library and then we can just provide that by copying our implementation or symlinking it. But I doubt that this will be considered good by everyone. Whichever is easier._

**Comment by adrpo** [comment] 2021-11-26 10:51
I don't know how to fix this using autotools and building both static/dynamic libraries without having two projects, one for Linux (the current one) and one for Windows with all the weirdo dll attributes. I don't think is possible without manually writing the Makefile or using cmake.

**Comment by sjoelund** [comment] 2021-11-26 10:53
You can write some things in configure.ac and pass it along to the Makefile.am, no? Just look for MINGW compiler and fill in some variables

**Comment by adrpo** [comment] 2021-11-26 10:53
The "easiest" hack to fix this until we properly solve it it to put the binary that @sjoelund attached, libModelicaExternalC.dll in OMDev and copy it from there. So we only build the static ones on Windows.

**Comment by sjoelund** [comment] 2021-11-26 10:54
You need the other DLLs too, though :)

**Comment by adrpo** [comment] 2021-11-26 10:55
> You can write some things in configure.ac and pass it along to the Makefile.am, no? Just look for MINGW compiler and fill in some variables

I have that, it doesn't help. On Linux i need to not link it with the import, on Windows i need to link it for the shared but not for the static and also provide different idefs on the command line so dllexport/import/extern attributes are set correctly.

**Comment by adrpo** [comment] 2021-11-26 10:56
So the only way I can see of doing this is either have two different targets for the shared/static library or two different projects.

**Comment by sjoelund** [comment] 2021-11-26 10:57
Do you have a copy of ModelicaStandardLibrary.git with your changes? I could have a look how to conditionally link that

**Comment by adrpo** [comment] 2021-11-26 10:57
I didn't do it there, i did it in SimulationRuntime/ModelicaExternalC.

**Comment by sjoelund** [comment] 2021-11-26 10:58
Fix it upstream. That's where it belongs. It shouldn't touch OpenModelica.git

**Comment by adrpo** [comment] 2021-11-26 10:59
then we remove the ModelicaExternalC from SImulationRuntime?

**Comment by sjoelund** [comment] 2021-11-26 11:01
Maybe, yes. It shouldn't have been moved there regardless

**Comment by adrpo** [comment] 2021-11-26 11:01
https://github.com/adrpo/OpenModelica/commit/1964b108ee87cd6ea907dcd0f1f066410737cb38

**Comment by adrpo** [comment] 2021-11-26 11:03
That is what I ended up with and that is missing the static linking ifdef on Windows from ModelicaUtilities.h.
Also you need to put "-no-undefined" for libtool flags as otherwise will not build the shared libs and that might not work in Linux.

**Comment by adrpo** [comment] 2021-11-26 11:07
Is a freaking mess and I understand why @mahge wants to avoid this all dll attributes crap.

So all these external libraries would need to support this:
1. static define if you want to use the static libraries
2. dll export defines if you build shared dll
3. dll import defines if you want to use the dll (if you don't load it via code)

None of the code or the autotools project is prepared for this.

**Comment by sjoelund** [comment] 2021-11-26 11:07
You make it something like `@LD_NO_UNDEFINED@` and I think you can do the same for the library dependency. `ModelicaExternalC/C-Sources/ModelicaUtilities.h` will be removed in the next version of it, right? You need to pass it as CPPFLAGS manually in the latest MSL master I think. So for our version that we pass, I think we put dllimport or also add the define to make it dllimport (as the upstream project cannot assume things about how ModelicaUtilities.h was modified).

**Comment by sjoelund** [comment] 2021-11-26 11:08
We anyway need to have some way of showing people how to build their DLLs to work in OMC... We can't statically link libraries from all different libraries out there.

**Comment by adrpo** [comment] 2021-11-26 11:46
Yes, but this is not one library, is a chain of libraries that use each other so one would need for each of them make a dll/static interface. Anyhow, we can do it but it will take a while and in the meantime everything that uses these libraries in Windows is broken.

**Comment by adrpo** [comment] 2021-11-26 11:49
Also, this looks like a job for MA but they haven't done it because is not that easy :)

**Comment by sjoelund** [comment] 2021-11-26 11:56
We are the MA. It's mostly the tool developers maintaining the C sources

**Comment by adrpo** [comment] 2021-11-26 14:24
The only problem is that i don't have enough time now to invest into this and the Windows builds are sort of broken without this fixed. I don't want to revert your commit as I think this is a good change so I guess the Windows builds will stay broken for a while.

**Comment by sjoelund** [comment] 2021-11-26 14:44
Either way, the only problem is with some models, right? The Windows builds should still be able to build and work for most things.

**Comment by adrpo** [comment] 2021-11-26 14:48
Actually all the models I had to try recently did not compile due to this bug so I had to use the 1.18 
release.

**Comment by casella** [comment] 2021-11-26 16:04
@adrpo, sorry, this thread is way too long and I'm a bit lost. 

Are you saying that all models that use ModelicaExternalC in Windows are broken and we have to live with it? This would seem to me a bit far-fetched.

**Comment by adrpo** [comment] 2021-11-26 16:59
No, what I'm saying is models that need to evaluate functions in ModelicaExternalC or ModelicaStandardTables or ModelicaIO *during* compilation will have issues. We can link fine with the static versions of these libraries for the simulation executable.

**Comment by casella** [comment] 2021-11-26 17:51
OK, I guess they not that many then.

**Comment by casella** [comment] 2021-12-06 12:59
@mahge has a possible solution using cmake.

**Comment by casella** [comment] 2021-12-06 13:05
We can re-test it with the zipped file, but trying to compile something that causes an error function to be called.

@sjoelund can make the test on Linux and then I can test it myself

**Comment by sjoelund** [comment] 2021-12-06 13:10
```mo
model M
  constant String s[:] = Modelica.Utilities.Streams.readFile("xxxxxxxxx");
end M;
```

**Comment by sjoelund** [comment] 2021-12-06 13:12
And if you want a test to see if ModelicaAllocateString works, use the same but give it a valid file.

**Comment by casella** [comment] 2021-12-06 13:16
This looks quite a thorny issue where fixes may have potentially many side effects, so we'll move it to 1.12.0

**Comment by casella** [comment] 2021-12-12 00:37
Using OpenModelica v1.19.0-dev-460-gaeb8a6d1a3 (64-bit), freshly installed under Windows 10.

First run of model `M`, I get:
```
[4] 01:28:26 Translation Error
[C:/Program Files/OpenModelica1.19.0-dev-64bit/lib/omlibrary/Modelica 4.0.0/Utilities/Streams.mo: 98:3-118:17]: External function ‘ModelicaInternal_countLines‘ could not be found in any of the given shared libraries:
  C:/Program Files/OpenModelica1.19.0-dev-64bit/lib//omc/ModelicaExternalC.dll
  C:/Program Files/OpenModelica1.19.0-dev-64bit/lib/omlibrary/Modelica 4.0.0/Resources/Library/win64/ModelicaExternalC.dll
  C:/Program Files/OpenModelica1.19.0-dev-64bit/lib/omlibrary/Modelica 4.0.0/Resources/Library/ModelicaExternalC.dll

[5] 01:28:26 Translation Error
[M: 2:3-2:74]: Failed to evaluate function: Modelica.Utilities.Streams.countLines.
```
If I rename libModelicaExternalC.dll shipped in the [zipped file](https://github.com/OpenModelica/OpenModelica/files/7579430/libModelicaExternalC.zip) by @sjoelund to ModelicaExternalC.dll and put it in the lib/omc/ directory, when I run `M` OMEdit crashes. Just sent the crash report, you can have a look at that.

**Comment by casella** [comment] 2022-02-07 14:59
@niklwors reports that this is a regression for them, they had models that worked in 1.18.0 and now fail because of this. We should solve the issue in 1.19.0, or at least provide them with some workaround.

**Comment by adrpo** [comment] 2022-02-07 15:41
Should be fixed with #8506.

**Comment by mahge** [comment] 2022-02-11 20:11
This should finally be fixed by #8506 (assisted by #8531 and #8533). The model in the ticket is translates and simulates successfully on Windows.  

The libffi tests pass on Windows now. The Jenkins Windows build is also functional again. So I am going to close this for now. Please reopen if the issue is still there.

**Closed by mahge** 2022-02-11 20:11 UTC
Labels: COMP/Runtime

**Comment by casella** [comment] 2022-02-12 00:21
Great, thanks @mahge!

We had similar problems with ExternalMedia, that needs to evaluate external functions with statically linked binary code at compile time to get package constants values. Are they also resolved now thanks to libffi?

**Comment by mahge** [comment] 2022-02-12 10:11
If the issue was with finding the libraries and loading for the purpose of constant evaluation by libffi, then it might be fixed now. 96be606e5f425a1924ac05ccc0907cbb69ce4fd8 has updated how the FFI implementation looks for libraries to cover more directories and name variations. 

> external functions with statically linked

I think you mean dynamically linked (DLLs) the ffi approach would not if your libraries are not dynamic ones. If they are indeed static then you will have to build shared versions of them. Same as what we achieved here for ModelicaExternalC libs but it should be a lot simpler since, I assume, the ExternalModica libraries are self contained, i.e., straightforward to have them as DLLs. If not we can take a look and see what we can do about them as well.

**Comment by casella** [comment] 2022-02-12 18:53
At the moment we compile the ExternalMedia binaries as statically linked libraries, but this creates a number of issues (including this one, I understand), so we'll soon switch to dynamically linked libraries.
