### ISSUE TITLE
Opening a library subfolder in the library browser takes a very long time with new instantiation-based OMEdit GUI

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#9856] opened 2022-12-05 15:41 UTC
### Description

Opening a library subfolder of the BRSL library in the library browser takes a very long time

### Steps to Reproduce

Load the BRSL package: Rexroth_Valves/package.mo.
Expand the folder Rexroth_Valves.ProportionalValves  package, see picture 1.
It takes about 30s on my computer. Without using the new API it works immediately.

### Screenshots
<img width="367" alt="OM-Ticket" src="https://user-images.githubusercontent.com/12269776/205679106-dd567f3d-eb73-4864-b7ee-3626cc406c9a.png">

### Version and OS

 - OpenModelica Version: v1.21.0-dev-106-g14b2673de1
 - OS:  Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable
MSL 4.0.0
BRSL 2.2 RC

**Comment by niklwors** [comment] 2022-12-05 15:43
@sbaetzing @abuntrock FYI

**Comment by casella** [comment] 2022-12-05 17:27
@perost have you already implemented the functions to only instantiate the icon layer, instead of the whole class? I guess this would help here.

**Comment by perost** [comment] 2022-12-05 21:24
> @perost have you already implemented the functions to only instantiate the icon layer, instead of the whole class? I guess this would help here.

No, we have `getModelInstanceIcon` which returns the icon annotation if it doesn't need to be instantiated. But we have nothing in the NF to only instantiate what's needed.

**Comment by casella** [comment] 2022-12-08 18:56
How long will it take to get that feature?

**Comment by perost** [comment] 2022-12-08 19:40
> How long will it take to get that feature?

No idea.

**Comment by casella** [comment] 2023-01-16 23:01
Decision after today's devmeeting: @perost will investigate how much work is needed to implement this and if it is possible to do it in a simpler way for starters.

**Comment by perost** [comment] 2023-01-20 15:13
#10078 should greatly improve the experience. We now instantiate the scope of the annotation if the annotation contains component references, same as the old API does.

This is not correct since we don't take the modifiers on the extends into account, but I can't see any way of doing that without significant work.

The issue is that the models extends from an Icon class and modify the parameters used in the inherited Icon annotation , such as (simplified): `extends Icon_22(Icon0 = valve.Icon0);`. So in that case we'd have to instantiate the entire model in order to get the value of `valve.Icon0`.

To solve this properly we'll need some way of only instantiating the parts of the model that's actually used by the annotation, but that's far from trivial. So for now we do it the same way as in the old API, which isn't entirely correct but at least usable.

**Comment by casella** [comment] 2023-01-20 22:28
LGTM.

@niklwors, @sbaetzing, please test and report.

**Comment by niklwors** [comment] 2023-01-23 09:55
Unfortunately, it did not improve so  I could not notice a big improvement in time.  For the example described in this ticket, the opening takes about 35s. With the old API the folder is opened immediately.

**Comment by perost** [comment] 2023-01-23 10:28
> Unfortunately, it did not improve so I could not notice a big improvement in time. For the example described in this ticket, the opening takes about 35s. With the old API the folder is opened immediately.

Did you try the latest nightly build? It looks like at least for the Windows build it wasn't included until the nightly build from today.

But if it still doesn't work for you it might be possible that you've changed something in the libraries that causes other issues with this. The version I have seem to be from october, so it's a bit old I guess.

**Comment by niklwors** [comment] 2023-01-23 10:57
I used the nightly build form today with the version: v1.21.0-dev-204-g84c3c16bf9. The change log says that you changes are include. We haven't really changed anything since October that would affect a longer loading.

**Comment by adeas31** [comment] 2023-01-23 16:19
I tested this and now expanding `Rexroth_Valves.ProportionalValves` takes 4-5 secs.

**Comment by casella** [comment] 2023-01-24 00:44
@niklwors are you maybe testing this with an old PC?

One thing you can do is to open the library that takes a long time, then close OMEdit and attach to this ticket the `omeditcommunication.log` file that you see with the Tools | Open Temporary Directory menu. This can help us pinpoint what is going slow in the operation.

**Comment by niklwors** [comment] 2023-01-24 09:19
I actually have a new and fast laptop. I tried it with the version from today and it still takes about 35s. Maybe @adeas31  accidentally did not start OMEdit with the new API.The log file is 500MB after opening the folder so I unfortunately can't upload it. Before opening the folder it is only 10MB large. This indicates to me that a lot of API calls are made when opening a folder.

**Comment by perost** [comment] 2023-01-24 09:42
> The log file is 500MB after opening the folder so I unfortunately can't upload it. Before opening the folder it is only 10MB large. This indicates to me that a lot of API calls are made when opening a folder.

For me it's 15 MB after opening the folder with the new API, 10 MB with the old API. However, I get about 500 MB if I open the folder and then open every model in the folder, which is basically how the new API worked before my fix.

Considering that the version you're using definitely should have the fix I can only really think of two options for why it's not working for you: either the library is different or you have some flag activated that somehow interfers with the new API. Would it be possible for you to try it out in a clean environment, i.e. some other computer or maybe a VM?

The large log file is a bit of a problem in itself though, besides quickly using up the users disk space it can also be slow to dump that much data to file. The issue seems to be that the whole JSON structure from `getModelInstance` is dumped when opening a model, maybe we should try to avoid that.

**Comment by niklwors** [comment] 2023-01-24 09:52
A colleague has also just tested it with today's version and it also takes so long for him to open the folder. We both use Windows. Can this be the reason?

**Comment by perost** [comment] 2023-01-24 09:55
> A colleague has also just tested it with today's version and it also takes so long for him to open the folder. We both use Windows. Can this be the reason?

@adeas31 also uses Windows, so that shouldn't be the issue. But then maybe there's some difference in the library anyway?

**Comment by niklwors** [comment] 2023-01-24 09:57
I have tested it with the Version from October, but there is also the problem.

**Comment by perost** [comment] 2023-01-24 10:14
@niklwors: If you look in the `omeditcommunication.log` and search for e.g. `getModelInstanceIcon(Rexroth_Valves.ProportionalValves.Rexroth_2WRCE_4X,true)`, does it give some JSON as output or does it fail?

**Comment by adeas31** [comment] 2023-01-24 10:24
> > The log file is 500MB after opening the folder so I unfortunately can't upload it. Before opening the folder it is only 10MB large. This indicates to me that a lot of API calls are made when opening a folder.
> 
> For me it's 15 MB after opening the folder with the new API, 10 MB with the old API. However, I get about 500 MB if I open the folder and then open every model in the folder, which is basically how the new API worked before my fix.
> 
> Considering that the version you're using definitely should have the fix I can only really think of two options for why it's not working for you: either the library is different or you have some flag activated that somehow interfers with the new API. Would it be possible for you to try it out in a clean environment, i.e. some other computer or maybe a VM?
> 
> The large log file is a bit of a problem in itself though, besides quickly using up the users disk space it can also be slow to dump that much data to file. The issue seems to be that the whole JSON structure from `getModelInstance` is dumped when opening a model, maybe we should try to avoid that.

We should think about how to handle log of new API. The new API dumps alot of data and makes the log very large and is not useful.

**Comment by niklwors** [comment] 2023-01-24 13:50
@perost I searched for it and I got:
```
getModelInstanceIcon(Rexroth_Valves.ProportionalValves.Rexroth_2WRCE_4X,true) 14:13:22:046
"" 14:13:22:057
#s#; 0.011000; 10.543000; 'getModelInstanceIcon(Rexroth_Valves.ProportionalValves.Rexroth_2WRCE_4X,true)'

getErrorString(false) 14:13:22:057
"[C:/Projekte/BRSL/BDP_BRSL_ModelicaLibraries/Rexroth_Valves/Internal/Templates/Interfaces/Interface_22.mo:71:28-112:79:writable] Error: Variable showName not found in scope Interface_22.
" 14:13:22:057
```

**Comment by bilderbuchi** [comment] 2023-01-25 07:22
> We should think about how to handle log of new API. The new API dumps alot of data and makes the log very large and is not useful.

Store it compressed (e.g. 7z/zip)? Ideally, stream the log into the file? Libraries for this seem to be available, so you don't have to code that yourself.

**Comment by niklwors** [comment] 2023-01-25 07:57
@perost  With the version from today I get this error message:
```
getModelInstanceIcon(Rexroth_Valves.ProportionalValves.Rexroth_2WRCE_4X,true) 08:46:58:203
"" 08:46:58:213
#s#; 0.010000; 10.609000; 'getModelInstanceIcon(Rexroth_Valves.ProportionalValves.Rexroth_2WRCE_4X,true)'

getErrorString(false) 08:46:58:213
"[C:/Projekte/BRSL/BDP_BRSL_ModelicaLibraries/Rexroth_Generic/Hydraulics/Interfaces/ComponentNeedsFluidProperties.mo:16:3-16:46:writable] Warning: The model can't be instantiated due to top-level outer element ‘bRSL_World‘, it may only be used as part of a simulation model.
[C:/Projekte/BRSL/BDP_BRSL_ModelicaLibraries/Rexroth_Generic/Hydraulics/Interfaces/ComponentNeedsFluidProperties.mo:16:3-16:46:writable] Warning: An inner declaration for outer component bRSL_World could not be found and was automatically generated.
[C:/Projekte/BRSL/BDP_BRSL_ModelicaLibraries/Rexroth_Generic/Hydraulics/Interfaces/ComponentNeedsFluidProperties.mo:16:3-16:46:writable] Notification: The diagnostics message for the missing inner is: No BRSL_World has been added to the model. A default world with default settings will be used! To avoid this warning drag and drop BRSL_World to your model.
[C:/Projekte/BRSL/BDP_BRSL_ModelicaLibraries/Rexroth_Valves/Internal/Templates/Interfaces/Interface_22.mo:12:65-12:73:writable] Error: Variable Icon1 not found in scope Interfaces.
[C:/Projekte/BRSL/BDP_BRSL_ModelicaLibraries/Rexroth_Valves/Internal/Templates/Interfaces/Interface_22.mo:71:28-112:79:writable] Error: Variable showName not found in scope Interface_22.
" 08:46:58:213
```

**Comment by perost** [comment] 2023-01-25 13:26
@niklwors: I've fixed the `Variable Icon1 not found in scope Interfaces` error in #10101.

I still don't know why it works for me but not for you though, since I also got that error and it still worked fine for me. But this was definitely wrong, so maybe it also fixes the issue you're experiencing.

**Comment by casella** [comment] 2023-01-25 18:10
> > We should think about how to handle log of new API. The new API dumps alot of data and makes the log very large and is not useful.
> 
> Store it compressed (e.g. 7z/zip)? Ideally, stream the log into the file? Libraries for this seem to be available, so you probably don't have to code that yourself.

That's one option, but I wonder if we should actually log all that stuff by default. Maybe that is also slowing down the GUI, isn't it?

**Comment by casella** [comment] 2023-01-25 18:18
@niklwors please check with tomorrow's nightly build.

**Comment by niklwors** [comment] 2023-01-26 10:37
Thank you very much, now it works fine for us.

**Comment by perost** [comment] 2023-01-26 10:40
> Thank you very much, now it works fine for us.

Great! I think there are still some improvements that could be made, but I think it works well enough that we can close this then.

**Closed by perost** 2023-01-26 10:40 UTC
Labels: COMP/GUI/InstBased Interface

**Comment by casella** [comment] 2023-01-27 00:49
#adeas31, what do you mean by "logging the output of `getModelInstance` _in the GUI_"? I thought the only logging took place in omeditcommunication.log

**Comment by adeas31** [comment] 2023-01-27 18:06
> @adeas31, what do you mean by "logging the output of getModelInstance in the GUI"? I thought the only logging took place in omeditcommunication.log

Sorry my bad. We don't do GUI logging. It is only done in debug mode and since I use the debug mode all the time so I got a bit confused.
