### ISSUE TITLE
Set a proper default value of stepSize in modelDescription.xml 

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12070] opened 2024-03-05 10:33 UTC
Consider the following MWE:
```modelica
model M
  Real x(start = 0, fixed = true);
  constant Real pi = 3.1415927;
equation
  der(x) = sin(time*2*pi/86400*10);
  annotation(experiment(StartTime=15552000, Tolerance=1e-6, StopTime=15638400)); 
end M;
```
The experiment annotation lacks the Interval field. When generating an FMU, the `DefaultExperiment` tag in `modelDescription.xml` looks like this:
```xml
<DefaultExperiment startTime="1.5552e7" stopTime="1.56384e7" tolerance="1e-6" stepSize="0.002"/>
```
The default `stepSize` of 0.002 is really bad and not appropriate, potentially causing issues with simulation, see, e.g., #11859.

If the Interval annotation is not set, we should set `stepSize = (StopTime-StartTime)/500`, rather than `stepSize = 0.002`. @arun3688 can you please take care of that?

This should fix #11859, and potentially also other issues with FMI testing, not only with the Buildings library.

**Comment by arun3688** [comment] 2024-03-06 16:05
@casella the issue is fixed with this commit https://github.com/OpenModelica/OpenModelica/commit/ddce110937430282f507ddecd7387a59f666ea71

**Comment by casella** [comment] 2024-03-06 21:58
Thanks @arun3688!

@deepak19015, can you please check #11859 with tomorrow's nightly build and report here and in that ticket? Thanks!

**Comment by casella** [comment] 2024-03-14 14:24
We've had some issues with the CI, now [job #7607](https://test.openmodelica.org/jenkins/job/LibraryTesting/job/LibraryTest/7607/console) is running and should finally provide some positive regression results [here](https://libraries.openmodelica.org/branches/history/master-fmi-fmpy/) in one-two days.

@deepak19015 in the meantime you can always check with the nightly build and Jupyter test.

**Comment by casella** [comment] 2024-03-15 17:56
OK, [job #7607](https://test.openmodelica.org/jenkins/job/LibraryTesting/job/LibraryTest/7607/console) finished successfully, unfortunately the previous one ran with OMSimulator only, not with FMPy, so the regression report is probably missing something.

Anyway, the [master-fmi-fmpy/Buildings_latest](https://libraries.openmodelica.org/branches/master-fmi-fmpy/Buildings_latest/Buildings_latest.html) report should now be up to date with the latest commits. Unfortunately, the models cited in #11859 still fail in the same way, so there is probably still something wrong somewhere.

**Closed** 2024-03-19 18:22 UTC
