### ISSUE TITLE
Support of conversion scripts

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#5297] opened 2020-06-27 10:50 UTC

**Comment by thorade** [comment] 2020-11-02 12:07
https://trac.openmodelica.org/OpenModelica/ticket/5297

**Comment by casella** [comment] 2022-03-10 23:55
This is the workflow that I envision for the handling of conversion scripts in OMEdit.

If I am a user developing a package `MyPackage` that uses `LibraryXYZ` from some other vendor or developer, which in turn uses libraries `PackageA` and `PackageB`. These are the requirements for the GUI
- I must have the option of upgrading `MyPackage` to use a new version of `LibraryXYZ`, which is not backwards compatible, when it becomes available.
- The decision as to when to do this conversion should be entirely up to me. Doing library conversions is an irreversible process, which can be a big deal if those libraries are used by multiple persons and/or organizations; in that case, all stakeholders must agree on when to do the conversion, in order to avoid chaos and lost work
- In this scenario, I am responsible for the conversion of `MyPackage`, to use a new version of `LibraryXYZ`. I am not responsible for the conversion of `LibraryXYZ`, nor of its dependencies, that's none of my business. This is upon the developers of `LibraryXYZ`, which should release an upgraded version, that I can download with the package manager.
- One potential problem is multiple shared dependencies. For example, if `MyPackage` uses `LibraryXYZ` and the `MSL`, and the new version of `LibraryXYZ` uses a new version of the `MSL`, which is also not backward compatible, then if I want to upgrade MyPackage, I need to run _two_ conversion scripts on it, the one for `LibraryXYZ` and the one for `MSL`. This can be determined automatically by checking if there are common dependencies between MyPackage and the dependencies of its dependencies, though this could be a bit involved.

**Comment by casella** [comment] 2022-04-11 21:16
The GUI to conversion scripts is now implemented, see #8061.

The idea is that the upgrade of libraries to newer versions of used libraries is triggered by the context menu "Convert to newer version of used libraries". This pops up a window to select the new versions, then the conversion script are run, the converted library is saved, and finally reloaded together with the new used libraries.

**Comment by casella** [comment] 2022-04-11 21:19
@adeas31, I just tried the GUI with the attached example.
[TestPackage 1.0.0.zip](https://github.com/OpenModelica/OpenModelica/files/8467665/TestPackage.1.0.0.zip)
When I select "Convert to newer version of used libraries" I get this window

![immagine](https://user-images.githubusercontent.com/4233148/162830893-76e46e39-72b7-4f70-b4d5-b3dd38b47b8f.png)

I would have expected to see "4.0.0", instead I get "trunk", "4.0.0-master" and "4.0.0+maint.om". As in #8797, I think this could be quite confusing for the average users.  

@adeas31, how is this drop-down menu generated and why don't I just get "4.0.0", as I now do when I click on the Welcome | System Libraries menu?

**Comment by casella** [comment] 2022-04-11 23:09
@bilderbuchi, would you be interesting at testing the conversion scripts with the latest nightly and/or with 1.19.0-beta.1 as soon as it is released?

**Comment by casella** [comment] 2022-04-12 09:29
@bilderbuchi what if you select 4.0.0-main.om instead?

**Comment by adeas31** [comment] 2022-04-12 10:41
> I would have expected to see "4.0.0", instead I get "trunk", "4.0.0-master" and "4.0.0+maint.om". As in https://github.com/OpenModelica/OpenModelica/issues/8797, I think this could be quite confusing for the average users.

> @adeas31, how is this drop-down menu generated and why don't I just get "4.0.0", as I now do when I click on the Welcome | System Libraries menu?

The drop down is populated based on [getAvailablePackageConversionsFrom(Modelica, 3.2.3)](https://build.openmodelica.org/Documentation/OpenModelica.Scripting.getAvailablePackageConversionsFrom.html) which lists all the versions that you can possibly convert to according to the package manager regardless if they are already installed or not. OMEdit checks if the requested package is not installed then install it first using [installPackage(Modelica, "4.0.0+maint.om", true)](https://build.openmodelica.org/Documentation/OpenModelica.Scripting.installPackage.html), note that OMEdit uses true for `exactMatch`, and then converts it using [convertPackageToLibrary(TestPackage, Modelica, "4.0.0+maint.om")](https://build.openmodelica.org/Documentation/OpenModelica.Scripting.convertPackageToLibrary.html)

**Comment by perost** [comment] 2022-04-12 10:50
> > I would have expected to see "4.0.0", instead I get "trunk", "4.0.0-master" and "4.0.0+maint.om". As in #8797, I think this could be quite confusing for the average users.
> 
> > @adeas31, how is this drop-down menu generated and why don't I just get "4.0.0", as I now do when I click on the Welcome | System Libraries menu?
> 
> The drop down is populated based on [getAvailablePackageConversionsFrom(Modelica, 3.2.3)](https://build.openmodelica.org/Documentation/OpenModelica.Scripting.getAvailablePackageConversionsFrom.html) which lists all the versions that you can possibly convert to according to the package manager regardless if they are already installed or not.

It might be a good idea to sort the list so that already installed versions are listed first, since the first version in the list is selected as the default in the drop-down list.

**Comment by adeas31** [comment] 2022-04-12 11:49
Sometime back I removed the text that shows if the version is installed or not. Maybe that was not a good idea. Perhaps the drop down can be listed like this,

- (installed) 4.0.0+maint.om
- (not installed) 4.0.0-master
- (not installed) trunk

What do you think @perost ? Will this be good info for the user?

**Comment by bilderbuchi** [comment] 2022-04-12 13:44
> @bilderbuchi what if you select 4.0.0-main.om instead?

When, exactly? After start, I already did (and this works):

> Restarting OMEdit and then directly doing a conversion to 4.0.0+maint.om works correctly afaict.

**Comment by bilderbuchi** [comment] 2022-04-12 13:56
I also have to admit, as (apparently) a non-expert, I am confused by these version identifiers: "trunk", "4.0.0-master" and "4.0.0+maint.om". 
* I'm guessing "trunk" is the current master HEAD of https://github.com/modelica/ModelicaStandardLibrary.`
* I'm guessing "4.0.0+maint.om" is release 4.0.0 with OM-specific maintenance fixes? Or is it https://github.com/modelica/ModelicaStandardLibrary/tree/maint/4.0.x with OM-specific fixes?
* What, then is "4.0.0-master"? 4.0.0 is a release tag, what does the "master" modification mean in this context? How is a "master" version different from "trunk" (in my mental model SVN-speak for "master"). Also, why is there a "+", not a "-", and what is the difference between the two?
* Importantly, which one is the _release version_ of 4.0.0?
Is that documented somewhere? I checked the [MSL](https://specification.modelica.org/master/annotations.html#S8.SS4.p1) but that did not help, and I did not find anything in the OM user guide.

**Comment by casella** [comment] 2022-04-12 15:53
So, what we need to have is a uniform mechanism for selecting libraries
- for the package manager GUI
- for the library conversion GUI
- for the Welcome | System Libraries button

that is consistent, intuitive and easy to use. Currently, what we have is not consistent and not particularly intuitive.

**Comment by bilderbuchi** [comment] 2022-04-12 15:56
Ah thanks, didn't have the right search terms to find _that_ page, apparently. I'll read through it again tomorrow. Thank you for the detailed explanation!

Clearly defined precedence rules can be very helpful as you illustrate, I suspected something like this. 
From the linked page (and the semver rules) I conclude 
* "4.0.0+maint.om" is actually 4.0.0 release, with the patching hidden as additional "builds" (which in my practice seems a bit unusual, but you do you)
* "4.0.0-master" is a pre-release version of 4.0.0 with a pre-release ID of "master", which I can't make sense of...
* * "trunk" kinda goes against the grain, as it's not a valid version. I guess it's actually MSL master :D

**Comment by casella** [comment] 2022-04-12 16:02
The Welcome | System libraries shows the installed libraries (including the ones installed by default in the installation directory outside the package manager, this will go away in 1.20.0)
![immagine](https://user-images.githubusercontent.com/4233148/163005205-02512784-d51d-4bc9-a466-07d19fd6927b.png)

**Comment by casella** [comment] 2022-04-12 16:05
The conversion script GUI shows me all the possible libraries I can convert to, including the ones that currently have no level of support, like trunk and 4.0.0-master
![immagine](https://user-images.githubusercontent.com/4233148/163005685-a1757778-7a70-4c61-9806-321cd83932c5.png)

**Comment by bilderbuchi** [comment] 2022-04-13 07:11
Sure, this sounds like a good improvement (although I guess this is not the most pressing issue :-P) 
If the re-parsing of the version string into something user-friendly is too difficult, maybe a prominent link to the definition for the strings will already help a lot?

**Comment by casella** [comment] 2022-04-13 09:31
> Sure, this sounds like a good improvement (although I guess this is not the most pressing issue :-P)

For me, it is. If people do not understand how to deal with the MSL, we're in trouble. @bilderbuchi, what else do you have in mind?

> If the re-parsing of the version string into something user-friendly is too difficult, maybe a prominent link to the definition for the strings will already help a lot?

I don't think so. According to semver metadata semantics, "+" translates into "post-release build" and "-" translates into "pre-release build". Piece of cake.

The problem is, no everybody knows what semver metadata sematics is, nor they need to, in order to use OMEdit proficiently. KISS (keep it simple and stupid)!

**Comment by bilderbuchi** [comment] 2022-04-13 11:03
> @bilderbuchi, what else do you have in mind?

Nothing specific at this point, I meant that generally I try to prioritize bugs & regressions (but I'm not the release planner, here).
Getting unit checking fully functional (#8179) would be nice (it [saves lives](https://github.com/OpenModelica/OpenModelica/issues/8179#issuecomment-985511115), after all 😁 ) although I'm comfortable with running a nightly, so I can also easily grab that later if it does not make it into 1.19.

**Comment by casella** [comment] 2022-04-13 13:39
> @casella only the fix of repos.json is remaining.

I'm starting to work on it now.

**Comment by casella** [comment] 2022-04-13 16:57
I've started a nightly build, I'll check this myself and then close this.

**Comment by sjoelund** [comment] 2022-04-14 06:48
> (this is a mistake in our database, of course trunk should be "Experimental", we just forgot to add the level of support for that)

It really should be "none". It's an MSL version where the version annotation has been replaced with "trunk" instead of containing a version number.

**Comment by casella** [comment] 2022-04-14 15:30
> > (this is a mistake in our database, of course trunk should be "Experimental", we just forgot to add the level of support for that)
> 
> It really should be "none". It's an MSL version where the version annotation has been replaced with "trunk" instead of containing a version number.

do you mean "noSupport"?

**Comment by casella** [comment] 2022-05-17 14:55
@adeas31 I went through repos.json once and updated it. I guess there is some ambiguity between "support" and "noSupport", please let me know what tags are you using for the library support selection, I'm not sure where to look at in the source code. Thanks!

**Comment by casella** [comment] 2022-05-21 00:29
repos.json update finalized, removed `partialSupport` in favour of `support`, which is recognized by OMEdit

**Closed by casella** 2022-05-21 00:29 UTC
