### ISSUE TITLE
Modifier of redeclared classes should be available through parameter dialog

### ISSUE THREAD

**Issue by sbaetzing** [OpenModelica/OpenModelica#7826] opened 2021-08-31 06:41 UTC
### Description
Having a replaceable class inside a model should produce an possibility to change modifiers through the parameter dialog of the redeclared one. Same behavior expected having record parameters. Without its not possible to modify selected instance

Since i cant upload any file i will send some screenshots to adeel.

### Steps to Reproduce

Open parameter dialog of class "classwithReplaceable" in package:

```
within ;
package TestOMEdit
  model ClasswithReplaceable

    replaceable TestOMEdit.Internal.ClassA testClass annotation(choices(
      choice(redeclare TestOMEdit.Internal.ClassA testClass "A"),
      choice(redeclare TestOMEdit.Internal.ClassB testClass "B")));
    replaceable parameter TestOMEdit.Internal.recordA testrecrod;

    annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(
          coordinateSystem(preserveAspectRatio=false)));
  end ClasswithReplaceable;

  package Internal
    model ClassA
      parameter Real A = 1;
      annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(
            coordinateSystem(preserveAspectRatio=false)));
    end ClassA;

    model ClassB
      parameter Real B = 2;
      annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(
            coordinateSystem(preserveAspectRatio=false)));
    end ClassB;

    record recordA
      parameter Real a = 1;
      annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(
            coordinateSystem(preserveAspectRatio=false)));
    end recordA;

    record recordB
      parameter Real B = 1;
      annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(
            coordinateSystem(preserveAspectRatio=false)));
    end recordB;
  end Internal;
end TestOMEdit;
```

OpenModelica Version: OpenModelica v1.19.0-dev-14-g63df406c47 (64-bit)
OS: Windows 10, 64 bit

**Comment by casella** [comment] 2021-08-31 11:10
@sbaetzing, this feature is planned to be introduced ASAP. It's not trivial, so we can't promise anything regarding the delivery date. I set it tentatively for 1.19.0

**Comment by casella** [comment] 2021-11-10 22:35
@adrpo has been working on this feature for a while, and I understand it is nearly finished. It should be definitely available in 1.19.0

**Comment by casella** [comment] 2021-11-11 10:27
@perost, can you please take care of this? @adrpo has ideas how to do it, please discuss them with him.

The question is if we should do it as we do it now for parameter modifiers (which has limitations) or redo the whole thing right, so that we also solve other problems like #2081.

**Comment by annikakuhlmann** [comment] 2022-11-30 13:01
Can anyone tell me what the status is on this issue? I have seen that it is not yet included in the latest build.

**Comment by adeas31** [comment] 2022-11-30 13:04
Yes, this is not yet supported. We are working on it but I can't tell exactly when this will be fixed.

**Comment by casella** [comment] 2022-12-01 19:22
Please follow #8066 and #8425. In fact, this ticket is mostly a duplicate of #8066.

**Comment by casella** [comment] 2023-01-17 00:46
The front-end functionality should now be in place. @adeas31 needs to implement the GUI side.

**Comment by adeas31** [comment] 2023-01-19 12:14
@sbaetzing did you send me any screenshots? Maybe I lost track of them. Please send them again.

**Comment by casella** [comment] 2023-01-19 15:51
I'm not sure there is much to see right now. I think we should put a button to the left of the drop-down menu of replaceable classes that activates the parameter editing window for the current redeclared class, then fill it up with the same logic we use for the main parameter window. 

Note that this may include other replaceable classes or components recursively.

**Comment by casella** [comment] 2023-03-07 09:21
Status update: @perost and @adeas31 have been working on this in recent weeks, unfortunately issues continued to pop up as they progressed with the implementation.

According to @adeas31, we could finally have something working by the end of this week.

**Comment by adeas31** [comment] 2023-03-07 09:32
Actually I already have a partial solution which allows setting the modifiers of redeclared classes in a hierarchal way. I will push in this solution soon. The difficult part is retaining the applied modifiers.

**Comment by casella** [comment] 2023-03-07 18:11
BTW, at some point we should also have a GUI for hierarchically applied modifiers. But that is another story.

**Comment by adeas31** [comment] 2023-03-08 14:13
#10350 partially fixes this issue. We need some more work on the instance api to handle this completely. See #10348 and #10349.

For now OMEdit will show edit button for replaceable components and opens a parameter dialog for component class and not the actual redeclare class.

**Comment by adeas31** [comment] 2023-03-10 11:45
With #10375 the correct redeclare class is used. However, there are still some issues that we need to fix e.g., #10349

**Comment by niklwors** [comment] 2023-04-04 08:12
The ticket is still open. For many models, the entered values are not applied to the model. @adeas31  knows the problem, we had talked about it in the dev meeting.

**Closed** 2023-05-04 08:19 UTC
Labels: COMP/GUI/OMEdit, COMP/OMC/Interactive Environment, COMP/GUI/InstBased Interface
