### ISSUE TITLE
Modelica-Buildings Library (master): Simulation fails while Compiling. 

### ISSUE THREAD

**Issue by NehaSPatwardhan** [OpenModelica/OpenModelica#13206] opened 2024-11-13 06:15 UTC
### Description

Solver fails to check /compile the model. It throws translation error while checking.

The following below listed models have same issues:
```
Buildings.Fluid.Geothermal.ZonedBorefields.Validation.FEFLOW.MassFlowRatePulse50
```
On simulating the model in OpenModelica leads to following errors/warnings:
```
1.translation error
2.Internal error NFCeval.evalLogicBinaryAnd  
3.failed to evaluate ‘true and borFie.borHol.borFieDat.conDat.borCon == Buildings.Fluid.Geothermal.Borefields.Types.BoreholeConfiguration.DoubleUTubeParallel‘

```
The error report of the model is given below:
https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Fluid.Geothermal.ZonedBorefields.Validation.FEFLOW.MassFlowRatePulse50.err

### Steps to Reproduce

Load the Modelica-Buildings master library (Source: https://github.com/lbl-srg/modelica-buildings/)
Simulate the examples model present in Buildings.Fluid.Geothermal.ZonedBorefields.Validation.FEFLOW.MassFlowRatePulse50

### Expected Behavior
The model should simulate successfully.

### Version and OS

 - OpenModelica Version: OpenModelica 1.25.0~dev-152-g78d9a41
- OS: 11.1.0ubuntu4
 - Versions of used Modelica libraries:
Modelica 4.0.0
Buildings 12.0.0

**Comment by casella** [comment] 2024-11-13 19:00
@perost is this another expandable connector issue?

**Comment by perost** [comment] 2024-11-13 19:04
> @perost is this another expandable connector issue?

Probably not, it doesn't look like one at least.

**Comment by casella** [comment] 2024-11-13 22:30
Can you please have a closer look at it? Thanks!

**Comment by casella** [comment] 2024-12-05 09:23
Duplicate of #12675.

**Closed by casella** 2024-12-05 09:23 UTC
Labels: COMP/OMC/Frontend
