### ISSUE TITLE
Enhancement: Editing similar parameters of different instances at once

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#11180] opened 2023-09-14 10:02 UTC
### Description

We know that this is a pure comfort feature and probably difficult to implement. However, since the UI of OMEdit has improved that much we are adding this here because this feature is really helpful in other tools like Dymola in our opinion.

When selecting multiple instances on a diagram layer (e.g. by dragging a rectangle over it) and then double clicking any of them a parameter dialogue should open with the shared parameters. 
A shared parameter is a parameter with the same name and the same type, which is present in all selected instances.

Consider the following modelica package:
```modelica
package MultieditTest
  model Model1
    parameter Modelica.Units.SI.Length a = 5;
    parameter Modelica.Units.SI.Length b = 5;
    parameter Modelica.Units.SI.Length c = 5;
  end Model1;

  model Model2
    parameter Modelica.Units.SI.Length a = 5;
    parameter Modelica.Units.SI.Length b = 5;
    parameter Modelica.Units.SI.Length c = 5;
  end Model2;

  model Model3
    parameter Modelica.Units.SI.Length a = 5;
    parameter Modelica.Units.SI.Angle b = 5;
  end Model3;
end MultieditTest;

```
1. Instantiate `Model1`, `Model2` and `Model3` inside a new class.
2. Select all three instances from step 1 and double click any of it.
3. A parameter dialogue appears which only displays parameter `a` since the type of parameter `b` is different between the models and parameter `c` is not present in `Model3`.
4. Enter a value of e.g. 10 in this dialogue for parameter `a`. the resulting modelica would look as follows:
```modelica
model Unnamed2
  MultieditTest.Model1 model1_1(a=10) annotation (Placement(transformation(extent={{-56,6},{-36,26}})));
  MultieditTest.Model2 model2_1(a=10) annotation (Placement(transformation(extent={{-8,8},{12,28}})));
  MultieditTest.Model3 model3_1(a=10) annotation (Placement(transformation(extent={{36,4},{56,24}})));
end Unnamed2;
```

### Enhanced Behavior

The same parameter can be edited for different class instances at the same time via the parameter dialogue.

### Version and OS

 - OpenModelica Version: v1.22.0-dev-317-g5a1f654c74 (64-bit) with Instance API
 - OS: Windows 10, 64 bit
 - MSL 4.0.0

Thanks for reading and maybe considering this at some time in the future
Aaron Buntrock - Bosch Rexroth

**Comment by casella** [comment] 2023-09-15 23:02
I agree. This is actually a duplicate of a very old ticket #3287. I'll add a reference there to the test case reported here.

**Closed by casella** 2023-09-15 23:02 UTC
Labels: duplicate
