### ISSUE TITLE
MSL model not working probably due to #6100

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#10598] opened 2023-04-23 07:55 UTC
### Description
#6100 describes a misinterpretation of a MSL model by OM.
Model Batteries.Examples.CCCV_StackRC tries to use that model and fails in OM. Maybe the failure is due to #6100?

### Steps to Reproduce
see #6100

### Expected Behavior
see #6100; model Model Batteries.Examples.CCCV_StackRC should compile and run

### Version and OS
OM 1.20.0

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment] 2023-04-26 08:06
@ceraolo thanks for reporting!

@perost mind having a look, please?

**Comment by perost** [comment] 2023-04-26 09:40
#6100 seems to be an OMEdit issue with the old API that doesn't apply modifiers, it would probably be fixed with the new API but unfortunately there seems to be some issue with that model.

The models are balanced but gives an error message from the backend about something not being supported and then it fails in `solveEquation` with an internal error. So it doesn't seem to be a frontend issue.

Closing as duplicate of #9052.

**Closed by perost** 2023-04-26 09:40 UTC
