### ISSUE TITLE
Modelica-Buildings Library (master): Buildings.Experimental.DHC.Plants.* Models fails during simulation

### ISSUE THREAD

**Issue by Pavanrajhr** [OpenModelica/OpenModelica#11236] opened 2023-09-22 06:42 UTC
### Description
Models fail at simulation.

The below listed models have these issues:
```
Buildings.Experimental.DHC.Plants.Combined.Controls.BaseClasses.Validation.StagingPlant
Buildings.Experimental.DHC.Plants.Combined.Examples.AllElectricCWStorage
Buildings.Experimental.DHC.Plants.Combined.Validation.AllElectricCWStorage
Buildings.Experimental.DHC.Plants.Cooling.Examples.StoragePlantDualSource
```

On simulating the model in OpenModelica leads to the following errors/warnings:
```
[1] 12:08:45 Translation Error
[/var/lib/jenkins/ws/LINUX_BUILDS/tmp.build/openmodelica-1.23.0~dev-2-ga714efa/OMCompiler/Compiler/BackEnd/BackendDAETransform.mo: 332:7-332:48]: Internal error BackendDAETransform.analyseStrongComponentBlock failed (Purely discrete algebraic loops cannot be solved by iterative processes. Try to break them open using the delay() operator.)
staChi.hol.u[3]
staChi.hol.u[2]
0.0 = staChi.nChiHeaAndCooUnb.y + staChi.hol.u[3] + staChi.hol.u[2] + staChi.numOpeCooChiHea.y + staChi.staHea.idxSta + (-staChi.numOpeCooChiHea.y) - staChi.hol.u[3] - staChi.nChiHeaAndCooUnb.y - staChi.hol.u[4]
staChi.hol.u[2] = staChi.numOpeCooChiHea.y - staChi.hol.u[3]

[2] 12:08:45 Translation Error
[/var/lib/jenkins/ws/LINUX_BUILDS/tmp.build/openmodelica-1.23.0~dev-2-ga714efa/OMCompiler/Compiler/BackEnd/BackendDAETransform.mo: 342:7-342:48]: Internal error BackendDAETransform.analyseStrongComponentBlock failed
variables:
  staChi.hol.u[3]
  staChi.hol.u[2]
equations:
  0.0 = staChi.nChiHeaAndCooUnb.y + staChi.hol.u[3] + staChi.hol.u[2] + staChi.numOpeCooChiHea.y + staChi.staHea.idxSta + (-staChi.numOpeCooChiHea.y) - staChi.hol.u[3] - staChi.nChiHeaAndCooUnb.y - staChi.hol.u[4]
  staChi.hol.u[2] = staChi.numOpeCooChiHea.y - staChi.hol.u[3]

[3] 12:08:45 Translation Error
[/var/lib/jenkins/ws/LINUX_BUILDS/tmp.build/openmodelica-1.23.0~dev-2-ga714efa/OMCompiler/Compiler/BackEnd/BackendDAETransform.mo: 346:7-346:90]: Internal error function analyseStrongComponentBlock failed

[4] 12:08:45 Translation Error
[/var/lib/jenkins/ws/LINUX_BUILDS/tmp.build/openmodelica-1.23.0~dev-2-ga714efa/OMCompiler/Compiler/BackEnd/BackendDAETransform.mo: 196:5-196:89]: Internal error function analyseStrongComponentScalar failed

[5] 12:08:45 Translation Error
[/var/lib/jenkins/ws/LINUX_BUILDS/tmp.build/openmodelica-1.23.0~dev-2-ga714efa/OMCompiler/Compiler/BackEnd/BackendDAETransform.mo: 107:7-107:113]: Internal error function strongComponentsScalar failed (sorting strong components)

[6] 12:08:45 Translation Error
[/var/lib/jenkins/ws/LINUX_BUILDS/tmp.build/openmodelica-1.23.0~dev-2-ga714efa/OMCompiler/Compiler/BackEnd/BackendDAEUtil.mo: 7953:5-7953:89]: Internal error Transformation module sort components failed
```

The list of warnings reported in the simulation test are given below: (Source: https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Experimental.DHC.Plants.Combined.Controls.BaseClasses.Validation.StagingPlant.err)
```
1) Warning: The model contains alias variables with redundant start and/or conflicting nominal values. It is recommended to resolve the conflicts, because otherwise the system could be hard to solve. To print the conflicting alias sets and the chosen candidates please use -d=aliasConflicts.
2) Error: Internal error function analyseStrongComponentBlock failed
3) Error: Internal error function analyseStrongComponentScalar failed
4) Error: Internal error function strongComponentsScalar failed (sorting strong components)
5) Error: Internal error Transformation module sort components failed
6) Error: Illegal to instantiate partial class PartialMultiplePumps.
```

### Steps to Reproduce
Load the Modelica-Buildings master library (Source: https://github.com/lbl-srg/modelica-buildings/). Simulate the following below models:
1) Buildings.Experimental.DHC.Plants.*

### Expected Behavior
Simulation should succeed.

### Version and OS
 - OpenModelica Version: OpenModelica 1.23.0~dev-2-ga714efa
 -  - OS: Ubuntu 20.04 focal
Versions of used Modelica libraries:
	Modelica 4.0.0
	Buildings 11.0.0

**Comment by AndreaBartolini** [comment] 2024-03-18 12:15
The omc compiler reports that there is an algebraic loop generated by the equation
```
  0.0 = staChi.nChiHeaAndCooUnb.y + staChi.hol.u[3] + staChi.hol.u[2] + staChi.numOpeCooChiHea.y + staChi.staHea.idxSta + (-staChi.numOpeCooChiHea.y) - staChi.hol.u[3] - staChi.nChiHeaAndCooUnb.y - staChi.hol.u[4]
  staChi.hol.u[2] = staChi.numOpeCooChiHea.y - staChi.hol.u[3]
```
This equation is generated in the instance `staChi`, that is an instance of the model `Buildings.Experimental.DHC.Plants.Combined.Controls.BaseClasses.StagingPlant` that has the diagram reported below:

![immagine](https://github.com/OpenModelica/OpenModelica/assets/25974985/8d50f939-1c1c-4bce-819c-bf606c8cdc91)

The parts of the diagram involved in the  equation seem to be the following:

![Buildings Experimental DHC Plants Combined Controls BaseClasses StagingPlant](https://github.com/OpenModelica/OpenModelica/assets/25974985/ddec6d4e-e718-4d68-a4aa-e6a1f59ab3c6)

on the right side of the equation `= staChi.numOpeCooChiHea.y - staChi.hol.u[3]` there is the output of the block `numChiCasCoo `(green circle in the upper), the left side of the equation contains the term `staChi.nChiHeaAndCooUnb.y - staChi.hol.u[4]` that seems to be the output of the block `numChiHeaCoo` (the green circle in the middle), the outputs of the blocks with the red circles, the output of the block `staHea` (green circle in the bottom) and the signals hol.u[2], hol.u[3] and hol.u[4] from the connection sets also indicated in the figure above.

All this elements are connected without loops, the `hol ` block that collect the `hol.u[.]` signals simply hold teirs values and the blocks connected to the output of the `hol` block don't generate loop. The outputs of this model are left unconnected in the model `Buildings.Experimental.DHC.Plants.Combined.Controls.BaseClasses.Validation.StagingPlant`, so it seems that there is no way to generate the left side of the equation (i.e., it  seems that there is no way to generate an algebraic loop).

So at the end it necessary to understand how the left side of the equation has been generated by the compiler.

**Comment by AndreaBartolini** [comment] 2024-03-18 14:00
I cannot investigate how omc build the left side of the equation... i need help from osmc

**Comment by casella** [comment] 2024-03-18 19:52
From OMEdit, Tools | Options | Debugger | Transformational Debugger | Generate Operations. This should give you all the steps from the original flattened code to the solved equations in the bottom-right corner of the Declarative Debugger when you select the equation in question.

**Comment by AndreaBartolini** [comment] 2024-03-26 16:49
The following (attached) MWE reproduces the issue:

```modelica
model TestAlgebraicLoop
  Buildings.Controls.OBC.CDL.Integers.Add sum annotation(
    Placement(transformation(origin = {18, -20}, extent = {{-10, -10}, {10, 10}})));
  Buildings.Controls.OBC.CDL.Integers.Subtract sub2 annotation(
    Placement(transformation(origin = {0, -16}, extent = {{40, 10}, {60, 30}})));
  Buildings.Controls.OBC.CDL.Integers.Subtract sub1 annotation(
    Placement(transformation(origin = {90, -10}, extent = {{-120, 10}, {-100, 30}})));
  Modelica.Blocks.Sources.IntegerExpression in1(y = integer(time)) annotation(
    Placement(transformation(origin = {-48, 16}, extent = {{-10, -10}, {10, 10}})));
  Modelica.Blocks.Sources.IntegerExpression zero(y = 0) annotation(
    Placement(transformation(origin = {-48, 4}, extent = {{-10, -10}, {10, 10}})));
  Modelica.Blocks.Sources.IntegerExpression in2(y = integer(time))  annotation(
    Placement(transformation(origin = {-10, -26}, extent = {{-10, -10}, {10, 10}})));
equation
  connect(in1.y, sub1.u1) annotation(
    Line(points = {{-37, 16}, {-32, 16}}, color = {255, 127, 0}));
  connect(zero.y, sub1.u2) annotation(
    Line(points = {{-37, 4}, {-32, 4}}, color = {255, 127, 0}));
  connect(sub1.y, sub2.u1) annotation(
    Line(points = {{-8, 10}, {38, 10}}, color = {255, 127, 0}));
  connect(sum.y, sub2.u2) annotation(
    Line(points = {{30, -20}, {34, -20}, {34, -2}, {38, -2}}, color = {255, 127, 0}));
  connect(in2.y, sum.u2) annotation(
    Line(points = {{1, -26}, {6, -26}}, color = {255, 127, 0}));
  connect(sub1.y, sum.u1) annotation(
    Line(points = {{-8, 10}, {0, 10}, {0, -14}, {6, -14}}, color = {255, 127, 0}));
  annotation(
    uses(Modelica(version = "4.0.0")));
end TestAlgebraicLoop;
```

![immagine](https://github.com/OpenModelica/OpenModelica/assets/25974985/52499f8c-0f1d-43a9-9068-486c32a5f806)

this MWE has been extracted by the diagram shown in https://github.com/OpenModelica/OpenModelica/issues/11236#issuecomment-2003757355

The output of `sub2` is equal to  `-in2`, that is `-integer(time)`, but if you run the model the following error is thrown:

```
[1] 17:45:27 Translation Error
[C:/dev/OM64bit/OMCompiler/Compiler/BackEnd/BackendDAETransform.mo: 332:7-332:48]: Internal error BackendDAETransform.analyseStrongComponentBlock failed (Purely discrete algebraic loops cannot be solved by iterative processes. Try to break them open using the delay() operator.)
sum.y
sub2.y
0.0 = sub1.y + in2.y + sum.y + sub2.y + (-sum.y) - sub1.y
sub2.y = sub1.y - sum.y

[2] 17:45:27 Translation Error
[C:/dev/OM64bit/OMCompiler/Compiler/BackEnd/BackendDAETransform.mo: 342:7-342:48]: Internal error BackendDAETransform.analyseStrongComponentBlock failed
variables:
  sum.y
  sub2.y
equations:
  0.0 = sub1.y + in2.y + sum.y + sub2.y + (-sum.y) - sub1.y
  sub2.y = sub1.y - sum.y
```
herebelow the output of the same MWE simulated by using Dymola:
![immagine](https://github.com/OpenModelica/OpenModelica/assets/25974985/27aff7b9-b327-4851-b4a0-5ee5d536078e)

OpenModelica v1.23.0-dev-396-g9ae201ce92 (64-bit)
Win11 pro - 64 bit

[TestAlgebraicLoop.zip](https://github.com/OpenModelica/OpenModelica/files/14761874/TestAlgebraicLoop.zip)

**Comment by AndreaBartolini** [comment] 2024-03-27 14:49
@casella who can take a look to this MWE?

**Comment by casella** [comment] 2024-03-27 17:46
I tried this with `--newBackend` and it works fine, so it is only a problem with the old backend. I guess this should be investigated anyway. I also noticed that integer(time) is _not_ generating events, as it should according to the MLS, but this is another story.

@kabelhak, @phannebohm, can you please have a look?

**Comment by casella** [comment] 2024-03-27 18:05
I checked with `-d=optdaedump`. After alias elimination there are four equations:
```
1/1 (1): sum.y = sub1.y + in2.y   [dynamic |0|0|0|0|] 
2/2 (1): sub2.y = sub1.y - sum.y   [dynamic |0|0|0|0|] 
3/3 (1): sub1.y = integer(time)   [binding |0|0|0|0|] 
4/4 (1): in2.y = integer(time)   [binding |0|0|0|0|] 
```
then the `resolveLoops` module turns them into
```
Equations (4, 4) 
======================================== 
1/1 (1): 0.0 = sub1.y + in2.y + sum.y + sub2.y + (-sum.y) - sub1.y   [unknown |0|0|0|0|] 
2/2 (1): sub2.y = sub1.y - sum.y   [dynamic |0|0|0|0|] 
3/3 (1): sub1.y = integer(time)   [binding |0|0|0|0|] 
4/4 (1): in2.y = integer(time)   [binding |0|0|0|0|] 
```
This is kind of weird, it is trivial to see that those four equations can be solved sequentially:
```
sub1.y := integer(time)   [binding |0|0|0|0|] 
in2.y := integer(time)   [binding |0|0|0|0|] 
sum.y := sub1.y + in2.y
sub2.y := sub1.y - sum.y 
```
Why should `resolveLoops` actually create a loop where there is none?

**Comment by casella** [comment] 2024-03-29 17:15
Thanks @phannebohm!

**Comment by casella** [comment] 2024-03-30 09:56
I checked with the [latest report](https://libraries.openmodelica.org/branches/master/Buildings_latest/Buildings_latest.html) including commit 6c2fe7, of the four reported broken models three now run, but [Buildings.Experimental.DHC.Plants.Combined.Examples.AllElectricCWStorage](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Experimental.DHC.Plants.Combined.Examples.AllElectricCWStorage.sim) still fails with
```
LOG_ASSERT        | debug   | Buildings_latest_Buildings.Experimental.DHC.Plants.Combined.Examples.AllElectricCWStorage_functions.c:26107: Invalid root: (0)^(-1.5)
```
This needs to be investigated further.

**Comment by AndreaBartolini** [comment] 2024-04-02 09:35
The error is risen by the function `sublimationPressureIce` that in the model that fails is inlined in the following call:

`pSat := Buildings.Utilities.Math.Functions.regStep(TSat - 273.16, Buildings.Utilities.Psychrometrics.Functions.saturationPressureLiquid(TSat), Buildings.Utilities.Psychrometrics.Functions.sublimationPressureIce(TSat), 1.0);`

So this failure seem to be of the same type of the one in https://github.com/OpenModelica/OpenModelica/issues/10981

**Comment by casella** [comment] 2024-04-03 07:59
@phannebohm thanks for the thorough analysis. Unfortunately, it seems from the [last test report](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/) that [Buildings.Experimental.DHC.Plants.Combined.Examples.AllElectricCWStorage](Buildings_latest_Buildings.Experimental.DHC.Plants.Combined.Examples.AllElectricCWStorage.sim) still fails with the same error. Are you sure that 6c2fe7e had any effect on that model?

Regarding resolvedLoops being superseded by assc/cse, do you think ASSC is mature enough that we could do it now?

**Comment by AndreaBartolini** [comment] 2024-04-03 13:51
> @phannebohm thanks for the thorough analysis. Unfortunately, it seems from the [last test report](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/) that [Buildings.Experimental.DHC.Plants.Combined.Examples.AllElectricCWStorage](Buildings_latest_Buildings.Experimental.DHC.Plants.Combined.Examples.AllElectricCWStorage.sim) still fails with the same error. Are you sure that [6c2fe7e](https://github.com/OpenModelica/OpenModelica/commit/6c2fe7e393121bb8313397603a1f2caaee763256) had any effect on that model?
> 
> Regarding resolvedLoops being superseded by assc/cse, do you think ASSC is mature enough that we could do it now?

The model fails with a different error (not algebraic loop), I put the analysis in the new dedicated ticket https://github.com/OpenModelica/OpenModelica/issues/12176

**Comment by casella** [comment] 2024-04-03 20:53
OK, then we can close this ticket.

**Closed by casella** 2024-04-03 20:53 UTC
Labels: COMP/OMC/Backend
