### ISSUE TITLE
OMEdit crashes when duplicating a class without specifying a path

### ISSUE THREAD

**Issue by perost** [OpenModelica/OpenModelica#12218] opened 2024-04-10 09:51 UTC
### Description

OMEdit crashes if you try to duplicate a class without specifying a path for the new class.

### Steps to Reproduce

1. Choose to duplicate any class.
2. Remove the Path in the dialog that opens and press ok.
3. OMEdit crashes when calling `GraphicsView::addUsesAnnotation`.

### Expected Behavior

OMEdit shouldn't crash, and I guess the expected behaviour is for the class to be added as a top-level class?

### Version and OS

 - OpenModelica Version: master

**Comment by abuntrock** [comment] 2024-04-10 11:07
From our perspective the expected behavior is that the new class is added as a top level class just as you described

**Comment by perost** [comment] 2024-04-10 20:09
> Is this an API or an OMEdit problem?

OMEdit

**Comment by adeas31** [comment] 2024-04-11 13:26
This is regression from https://github.com/OpenModelica/OpenModelica/pull/12213. I only tested the case when duplicating inside a package.

**Comment by casella** [comment] 2024-04-11 13:29
Good that we have committed alpha testers and this was caught immediately. Thanks @abuntrock!

**Comment by abuntrock** [comment] 2024-04-11 13:37
Always happy to help. I was just lucky, that duplicating something as a top level class is the most common use case when looking at our example classes.

**Comment by perost** [comment] 2024-04-11 13:50
> Always happy to help. I was just lucky, that duplicating something as a top level class is the most common use case when looking at our example classes.

Maybe leaving the path empty should actually be the default? Currently the default is the same package as the class being duplicated is declared in, but I assume the feature is most often used to duplicate example models from system libraries in which case the current default will actually be invalid.

**Comment by perost** [comment] 2024-04-11 13:56
> I duplicate inside the same package all the time, particularly when making MWEs. Removing this path is much easier than adding it. It would leave it as it is.

Ok, better keep the path then. Or maybe leave the path empty if the package isn't writable? I find it a bit odd that OMEdit currently proposes a path that's not valid when duplicating from system libraries, but it's not really a big issue I guess.

**Comment by casella** [comment] 2024-04-11 14:50
> Ok, better keep the path then. Or maybe leave the path empty if the package isn't writable? I find it a bit odd that OMEdit currently proposes a path that's not valid when duplicating from system libraries

Good point.

We could have two menu items, one for duplicating in the same scope, and another one to duplicate elsewhere, but it seems a bit of an overkill.

What about the following solution:
- if the class being duplicated belongs to a read-only installed library, set the default path to empty
- otherwise, set the default path to the scope that contains the class

**Comment by perost** [comment] 2024-04-11 15:16
#12227 makes the trivial change of omitting the path if the class if from a system library. If you want anything more complicated, please open an issue for it.

**Comment by casella** [comment] 2024-04-11 16:05
@abuntrock please try tomorrow's nightly and report. If this works well, we can back-port #12226 and #12227 to 1.23.0.

**Comment by abuntrock** [comment] 2024-04-12 11:24
@casella I tested this with today's nightly (v1.24.0-dev-6-gdadd01e539 (64-bit)) and the different defaults depending on the library type (system library or not) work as expected and I can simulate the duplicated classes.

However, there is no uses annotation written to the model file. I thought this was done in #12213.
For example when duplicating `Modelica.Blocks.Examples.PID_Controller` as a top level class `uses(Modelica(version="4.0.0"))` is not added to the duplicated class.

**Comment by casella** [comment] 2024-04-12 11:59
@abuntrock I understand there are two use cases:
1. the duplicated model is a standalone model in the global scope
2. the duplicated model is put in a package

I guess #12213 handled case 2., whereby a uses annotation must be put _at the end of the package declaration_. In case 1., it must be put at the end of the duplicated class.

I'll open a follow-up ticket.

**Closed by casella** 2024-04-12 11:59 UTC
Labels: COMP/GUI/OMEdit, regression

**Comment by abuntrock** [comment] 2024-04-12 13:49
That sounds reasonable. Thanks for opening up the follow up ticket. I totally forget that when duplicating inside a package the uses annotation is only present at the package itself.

**Comment by casella** [comment] 2024-04-12 17:22
In fact, older versions of Dymola sometimes apparently messed up with this, so there is existing Modelica code which is perfectly valid except for some extra uses annotation placed in the wrong place, including the odd case of package P with annotation(uses(SomeLib(version = "x"))) which contains sub-packages with annotation(uses(SomeLib(version = "y"))). 

This of course makes no sense, because you cannot have multiple dependencies on different versions of the same library in the same Modelica mode. 

I think OMC just ignores them, but technically speaking they should not be there in the first place.
