### ISSUE TITLE
Exported FMU  with "protected" option contains sensitive data.

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#8411] opened 2022-01-13 13:09 UTC
*Note: The original issue regarding the blackbox problem is already reported in #8158. Hence I edited this ticket to be about the "protected" option only.*

### Description
When exporting an FMU with a protected component and exporting 
it with the "proteced" filter activated then the FMU should not contain any details about the protected component. But unfortunately it does.

### Steps to Reproduce

Export an FMU with "protected" filter. 

[FMUtests.SinSource_protected.zip](https://github.com/OpenModelica/OpenModelica/files/7862962/FMUtests.SinSource_protected.zip)

and open it. 

### Expected Behavior

The FMU should not contain any details about the structure but actually (see file above) the FMU contains `resources/FMUtests_SinSource_info.json` with **all** the details of the protected model (down to installation  and model paths).  

I've created the also an FMU with the same "protected" filter option using Dymola and here you can see that it does not contain any `resources` that could give away any details about the nature and origins of the model:

[FMUtests_SinSource_protected_dymola.zip](https://github.com/OpenModelica/OpenModelica/files/7863052/FMUtests_SinSource_protected_dymola.zip)

### Version and OS

 - OpenModelica Version: OpenModelica 1.19.0~dev-514-gaed8f07
 - OS: Linux Ubuntu 20.04
 - MSL 4.0.0

**Comment by dietmarw** [comment] 2022-01-14 12:38
@arun3688 but if the simulation is dependent on the open visible `.json` file then this has to be a bug since it kind of defeats the whole point of filtering information and also offering a blackbox variant which this is not runnable.

**Comment by lochel** [comment] 2022-01-14 14:54
@dietmarw, you are of course right. We are investigating the issue right now.

**Comment by arun3688** [comment] 2022-01-18 14:18
@dietmarw The issue is fixed with this commit https://github.com/OpenModelica/OpenModelica/commit/808cd71bd1357ceba4d54cfc12ea78754eae1565, You can test the fixes from the nightly builds tomorrow

**Closed** 2022-01-18 20:51 UTC
Labels: COMP/FMI

**Comment by dietmarw** [comment] 2022-01-19 09:35
@arun3688 Thanks and I can confirm it is working now for both protected and blackbox FMUs
