### ISSUE TITLE
Default name in Dialog "OMEdit - Enter Component Name" can easily cause Errors

### ISSUE THREAD

**Issue by BenjaminRueth** [OpenModelica/OpenModelica#6995] opened 2020-11-30 13:10 UTC
### Description

When importing a Model Exchange FMU whose identifier starts with a lowercase character e.g. `lowerFirstChar.fmu`, OMEdit will create a class `lowerFirstChar_me_FMU` 

When instantiating an object of this class, OMEdit suggests the default name as the class name with the first letter turned to lower case. But this leads to a conflict because class and instance carry the same name `lowerFirstChar_me_FMU`.

### Steps to reproduce

1. Open Example `Modelica.Mechanics.Translational.Examples.SignConvention`.
2. Export FMU via `File > Export > FMU`. Returns: 
```
[4] 13:57:13 Scripting Notification
The FMU is generated at /tmp/OpenModelica_benjamin/OMEdit/Modelica.Mechanics.Translational.Examples.SignConvention/Modelica.Mechanics.Translational.Examples.SignConvention.fmu.
```
3. Create a new Modelica Class via `File > New Modelica Class`. Named `myClass`.
4. Import FMU via `File > Import > FMU` from `/tmp/OpenModelica_benjamin/OMEdit/Modelica.Mechanics.Translational.Examples.SignConvention/Modelica.Mechanics.Translational.Examples.SignConvention.fmu`. `Modelica_Mechanics_Translational_Examples_SignConvention_me_FMU` will now show up under `Libraries`.
5. Drag & Drop `Modelica_Mechanics_Translational_Examples_SignConvention_me_FMU` into the "Diagram View" of `myClass`. In the Dialog "OMEdit - Enter Component Name" modify the suggested name to "**M**odelica_Mechanics_Translational_Examples_SignConvention_me_FMU". Results in
```
model myClass
  Modelica_Mechanics_Translational_Examples_SignConvention_me_FMU Modelica_Mechanics_Translational_Examples_SignConvention_me_FMU annotation(
    Placement(visible = true, transformation(origin = {-32, 4}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation

end myClass;
```
6. Click on "Simulate". This gives the error:
```
[1] 14:05:19 Translation Error
[myClass: 2:3-3:113]: Found a component with same name when looking for type Modelica_Mechanics_Translational_Examples_SignConvention_me_FMU.

[2] 14:05:19 Translation Error
Error occurred while flattening model myClass
```

### Expected behavior

The suggested name under 5. above should not lead to an error. Note that the suggested name for an FMU starting with a capital letter is fine. However, for an FMU starting with a lower case letter (e.g. `myModel.fmu`) the suggested name (`myModel_me_FMU`) will directly lead to an error without any modifications in the dialog.

OMEdit should not suggest a name that leads to an error.

### Version and OS
 - OpenModelica Version 1.16.0
 - OS: Ubuntu 20.04

**Comment by AnHeuermann** [comment] 2020-11-30 15:19
Thanks for reporting this issue. With `v1.17.0-dev-116-g4486fa0ea1` I can't reproduce your error. The generated names are looking fine:
```modelica
model myClass
  Modelica_Mechanics_Translational_Examples_SignConvention_me_FMU modelica_Mechanics_Translational_Examples_SignConvention_me_FMU annotation(
    Placement(visible = true, transformation(origin = {-32, 4}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
end myClass;
```

But the point is we should really remove the FMI import using OMC completely and move on to OMSimulator for all FMI import.

We have a lot of issues with the FMI import. It doesn't work for various reasons, some are:

- It's not maintained and never really worked.
- It's not creating legal Modelica code and the new frontend will reject the generated Modelica model.
  ```bash
  [1] 15:20:50 Translation Error
  [Modelica_Mechanics_Translational_Examples_SignConvention_me_FMU: 128:7-128:37]: Operator reinit may only be used in the body of a when equation.
  ```

We plan to get rid of the omc FMI import in the future, but no decent replacement is there at the moment.

Problem with using only OMSimulator to import and simulate FMUS is, that the OMSimulator/SSP support in OMEdit is very limited at the moment.
Also it is not possible to connect Modelica models with FMUs directly. You have to export everything to FMus and connect them via SSP or with a lua script and simulate with OMSimulator.

Related Trac issue: https://trac.openmodelica.org/OpenModelica/ticket/5345.

**Comment by BenjaminRueth** [comment] 2020-11-30 15:50
With

> ```modelica
> model myClass
>   Modelica_Mechanics_Translational_Examples_SignConvention_me_FMU modelica_Mechanics_Translational_Examples_SignConvention_me_FMU annotation(
>     Placement(visible = true, transformation(origin = {-32, 4}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
> equation
> end myClass;
> ```

(from https://github.com/OpenModelica/OpenModelica/issues/6995#issuecomment-735850575) everything should be fine. However

```modelica
model myClass
  Modelica_Mechanics_Translational_Examples_SignConvention_me_FMU Modelica_Mechanics_Translational_Examples_SignConvention_me_FMU annotation(
    Placement(visible = true, transformation(origin = {-32, 4}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
end myClass;
```

and 

```modelica
model myClass
  lowerFirstChar_me_FMU lowerFirstChar_me_FMU annotation(
    Placement(visible = true, transformation(origin = {-32, 4}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
end myClass;
```

are causing trouble on my end.

As far as I understand the problem the name of the class and component cannot be the same. If the class name is `lowerFirstChar_me_FMU` the proposed default name for the component is `lowerFirstChar_me_FMU` which leads to a problem.

**Comment by AnHeuermann** [comment] 2020-11-30 15:59
Yeah, I can see the problem. But we probably won't fix this issue because we can't invest time into the FMI import with omc, since we want to replace it completely.

**Closed** 2020-12-07 16:30 UTC
Labels: wontfix
