### ISSUE TITLE
Implement EnumTypeName(i)

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10685] opened 2023-05-11 18:13 UTC
The EnumTypeName() function described in Sectio 3.7.1 of the MLS should be implemented in the NF. Apparently, it is badly needed by some users, see #10679.

**Comment by perost** [comment] 2023-05-11 18:23
Duplicate of #10681

**Closed by perost** 2023-05-11 18:23 UTC

**Comment by casella** [comment] 2023-05-11 19:02
Ops... 😅
