### ISSUE TITLE
Implement partial derivative operator in the old backend

### ISSUE THREAD

**Issue by angmarion** [OpenModelica/OpenModelica#12285] opened 2024-04-19 13:36 UTC
### Description

There seems to be a regression on the syntax of the `der` operator.

### Steps to Reproduce

Step 1 : declare dummy function

```
function Func
input Real x1;
input Real x2;
output Real y;
algorithm
y := x1*3 + x2;
end Func;
```

Step 2 : declare partial derivative

```
function DerFunc = der(Func, x1);
```

Step 3 : check model
The following error mùessage appears:

[/var/lib/jenkins/ws/LINUX_BUILDS/tmp.build/openmodelica-1.24.0~dev-1-g57ab835/OMCompiler/Compiler/NFFrontEnd/NFInst.mo: 648:9-648:125]: Internal error NFInst.expandClass2 got unknown class:
function DerFunc = der(Func, x1)

### Expected Behavior

In OMEdit 1.18.1, the model works as expected. The Modelica 3.6 specifications, section 12.7.2, indicate such a syntax. Is this an expected behaviour that this syntax should fail?

### Version and OS

 - OpenModelica Version: 1.24.0~dev-1-g57ab835
 - OS: Linux 64bit

### Additional Context

The model works on Dymola 2023x.

**Comment by angmarion** [comment] 2024-04-19 13:37
@YomGarcia @jschueller

**Comment by perost** [comment] 2024-04-19 13:48
We only started adding support for it about a year ago, so I'm not sure how 1.18.1 could work. Did you try to actually use it, or is it a case of the compiler just ignoring it?

But regardless, you need to use the new backend we're developing by using the `--newBackend` flag. I improved the error message in #12252 a few days ago to mention that.

**Comment by casella** [comment] 2024-04-21 18:58
@angmarion please note the new backend is still very far from being mature, this will probably take a couple more years.

**Comment by casella** [comment] 2024-04-21 19:00
@angmarion are you sure 1.18.1 gave you DerFunc returning 3?

**Comment by angmarion** [comment] 2024-04-23 07:39
@casella @perost  My mistake, it only worked on Dymola. This is not a critical bug, we just noticed it and thought it deserved a ticket.

**Comment by casella** [comment] 2024-04-23 11:26
No problem, in fact, thanks for bringing this up. It turned out, 10 years ago we almost got this done with the old frontend and backend (see the story [here](https://trac.openmodelica.org/OpenModelica/ticket/2538)), then for some reason we left it unfinished.

Now the feature is implemented with the new frontend and new backend (which is still not mature enough for production use), but we should be able to also get it working with the old backend. See #2538 for updates.

**Comment by casella** [comment] 2024-04-29 08:06
@angmarion at the end of the day this turns out to be a duplicate of #2538. Please follow that.

**Closed by casella** 2024-04-29 08:06 UTC
Labels: duplicate, COMP/OMC/Backend

**Comment by angmarion** [comment] 2024-04-29 10:20
Thank you @casella, I'll follow #2538.
