### ISSUE TITLE
Wrong clock interval

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#3771] opened 2020-06-27 03:28 UTC

**Comment by AnHeuermann** [comment] 2021-11-29 13:29
Duplicate of #7854. (Actually the other way around but who cares)

**Closed by AnHeuermann** 2021-11-29 13:29 UTC
Labels: duplicate

**Comment by casella** [comment] 2021-11-29 19:00
Nice to get rid of old tickets like this, it seems we are making progress. But in fact we are, since these issues are now being actually addressed, so it's fine 😄
