### ISSUE TITLE
Compilation error with German umlauts in path

### ISSUE THREAD

**Issue by Messias94** [OpenModelica/OpenModelica#10010] opened 2023-01-05 13:18 UTC
### Steps to reproduce
To reproduce the error you have to create a data path with umlauts.
After that you must open a openmodelica model in this data path and simulate it. 
The simulation shouldn't be possible.

**Comment by AnHeuermann** [comment] 2023-01-05 15:18
Can reproduce on Windows 11:

Save
```modelica
model M
  Real x(start=1.0, fixed=true);
equation
  der(x) = -x;
end M;
```

in `D:/Das ist ein Pfad mit Ä und so/M.mo`.

When compiling with OMEdit the C compilation failes with following error message:

```
/usr/bin/sh: clang -I. -o M.exe M.o M_functions.o M_records.o M_01exo.o M_02nls.o M_03lsy.o M_04set.o M_05evt.o M_06inz.o M_07dly.o M_08bnd.o M_09alg.o M_10asr.o M_11mix.o M_12jac.o M_13opt.o M_14lnz.o M_15syn.o M_16dae.o M_17inl.o M_18spd.o -I"C:/Program Files/OpenModelica1.21.0-dev-64bit/include/omc/c" -I"C:/Program Files/OpenModelica1.21.0-dev-64bit/include/omc" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=M -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=0 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0 -L"D:/Das ist ein Pfad mit Ã„ und so"    -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse     -I"C:/Program Files/OpenModelica1.21.0-dev-64bit/include/omc/c" -I"C:/Program Files/OpenModelica1.21.0-dev-64bit/include/omc" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=M -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=0 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0 -L"C:/Program Files/OpenModelica1.21.0-dev-64bit/lib//omc" -L"C:/Program Files/OpenModelica1.21.0-dev-64bit/lib" -Wl,--stack,16777216,-rpath,"C:/Program Files/OpenModelica1.21.0-dev-64bit/lib//omc" -L"C:/Program Files/OpenModelica1.21.0-dev-64bit/bin" -Wl,-rpath,"C:/Program Files/OpenModelica1.21.0-dev-64bit/lib"  -fopenmp -Wl,-Bstatic -lregex -ltre -lintl -liconv -lexpat -lpthread -loleaut32 -limagehlp -lhdf5 -lz -lszip -Wl,-Bdynamic -lSimulationRuntimeC -Wl,-Bdynamic -lomcgc -lopenblas -Wl,-Bdynamic  -lstdc++ -Wl,-Bdynamic  : No such file or directory
mingw32-make: *** [M.makefile:37: omc_main_target] Error 127
```

The linker flag `-L"D:/Das ist ein Pfad mit Ã„ und so" ` is wrong, so this seems to be a duplicate of #9402.
I guess we need to use UFT8 encoding for everything that could be a path.

**Closed by AnHeuermann** 2023-01-05 15:18 UTC
Labels: duplicate
