### ISSUE TITLE
Issue with Modelica.ComplexMath.sum in CodeGen

### ISSUE THREAD

**Issue by AHaumer** [OpenModelica/OpenModelica#8306] opened 2021-12-13 09:32 UTC
Please have a look at the BLDC library release v1.3.3 [https://github.com/AHaumer/BLDC/releases/tag/v1.3.3](url) 
and try one of the examples {DemoElectronicCommutator, DemoBLDC Voltages, DemoBLDC, DemoBLDCwithPWM}. 
These examples fail to compile with the new frontend but simulate with the old frontend.

OM1.1.8.0 on Woíndows 10 64bit

**Comment by perost** [comment] 2021-12-13 11:13
This seems to be a duplicate of [#5885](https://trac.openmodelica.org/OpenModelica/ticket/5885), which is that the code generation can't handle the way the new frontend flattens `Modelica.ComplexMath.sum`. The old frontend flattens the function incorrectly so that it always return `Complex(0.0, 0.0)`, which compiles but is completely wrong.

@mahge: Any progress on that ticket?

**Comment by perost** [comment] 2021-12-13 11:18
Also, if you'd like we can add that library to our automatic library testing.

**Comment by mahge** [comment] 2021-12-13 11:28
I am afraid there is no specific progress. I guess that ticket got forgotten in the pile. The problem was that doing the "correct" thing to fix the ticket was causing failures in the test suite and that meant it was going to take lot of time to hunt down more issues and fix them.

Handling record member crefs has gotten a little better since then. Perhaps we have already fixed some of the issues that were preventing this from being correctly implemented. I will take a look again.

**Comment by AHaumer** [comment] 2021-12-13 11:30
I had a PR to add BLDC to the OM system libraries.

**Comment by casella** [comment] 2021-12-13 14:07
> I had a PR to add BLDC to the OM system libraries.

@sjoelund, can you get that through?

**Comment by sjoelund** [comment] 2021-12-13 14:08
https://github.com/OpenModelica/OpenModelicaLibraryTesting/commit/48fc28e34b72b70a7be446c07cc612ddde2792b9

**Comment by casella** [comment] 2021-12-13 14:46
> I am afraid there is no specific progress. I guess that ticket got forgotten in the pile.

I refreshed the ticket with the list of pending issues with Complex numbers, see #4835.

**Comment by mahge** [comment] 2021-12-22 11:36
This has been fixed with #8339. All BLDC models are simulating now on our testing https://libraries.openmodelica.org/branches/master/BLDC/BLDC.html

I am going to close the ticket. Please open another if there are more issues.

**Closed by mahge** 2021-12-22 11:36 UTC
Labels: COMP/Codegen

**Comment by casella** [comment] 2021-12-22 17:35
@AHaumer, all 6 runnable models of BLDC now pass the simulation phase, see [report](https://libraries.openmodelica.org/branches/master/BLDC/BLDC.html).
