### ISSUE TITLE
GUI constantly crashing

### ISSUE THREAD

**Issue by Nico-Hard** [OpenModelica/OpenModelica#11946] opened 2024-02-03 20:21 UTC
### Description
GUI crash randomly when editing model.

### Steps to reproduce
This is random... but more there are blocks on the model, more there is chance to crash when a modification is performed.
Some clue can show that the app will crash : When a modification is done, some lines connecting blocks become out of order... then if a block is added/deleted/connected... then the app crash.

### Expected behavior
No crash...

### Version and OS
 - OpenModelica Version 1.23 dev
 - Versions of used Modelica libraries : v4
 - OS: windows 10, 64bits

**Comment by perost** [comment] 2024-02-03 20:44
Most likely a duplicate of #11919.

**Comment by casella** [comment] 2024-02-03 20:54
@Nico-Hard, thanks for reporting!

The fix of #11919 is already available in the 1.23.0-dev nightly build, please try that out. It will be included in the 1.22.2 patch release, due in a couple of weeks (hopefully).

If you get the same problem with the nightly builds or with the forthcoming 1.22.2, please open another ticket.

**Closed by casella** 2024-02-03 20:54 UTC
