### ISSUE TITLE
replaceable instance of a record ends up in a bad parameter dropdown menue

### ISSUE THREAD

**Issue by sbaetzing** [OpenModelica/OpenModelica#7488] opened 2021-05-26 07:51 UTC
### Description
A definition like 
` replaceable EnchancementDropDown.Database.A  params annotation (choices(
      choice(redeclare
          EnchancementDropDown.Database.A
          params "Dataset A"),
      choice(redeclare
          EnchancementDropDown.Database.B
          params "Dataset B"),
      choice(redeclare
          EnchancementDropDown.Database.C
          params "Dataset C")));`

should end in a parameter dialog with a drop down menue with the entries 
"Dataset A"
"Dataset B"
"Dataset C"

but only shows 
![grafik](https://user-images.githubusercontent.com/84787397/119622487-7d3b0300-be07-11eb-863e-e319b066bdc3.png)

### Steps to Reproduce

Open the parameter dialog from Model1 in attached minimal example
```
package EnchancementDropDownOMEdit
  
  model Model1
   
   replaceable EnchancementDropDown.Database.A  params annotation (choices(
        choice(redeclare
            EnchancementDropDown.Database.A
            params "Dataset A"),
        choice(redeclare
            EnchancementDropDown.Database.B
            params "Dataset B"),
        choice(redeclare
            EnchancementDropDown.Database.C
            params "Dataset C")));
   
  
  equation
  
  end Model1;
  
  
  model testModel1
    Model1 model11(test1 = false)  annotation(
      Placement(visible = true, transformation(origin = {2, 4}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  equation
  
  end testModel1;
  
  
  package Database
    record A "Dataset A"
    parameter Real a = 1;
    end A;
    
    record B "Dataset B"
    extends A;
    end B;
    
    record C "Dataset C"
    extends A;
    end C;
  end Database;
  
end EnchancementDropDownOMEdit;
```

### Version and OS

OpenModelica v1.18.0-dev-280-g0b76908279 (64-bit)
OMSimulator v2.1.1.post70-gdf73447-mingw
OS: Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable: MSL 3.2.3, Bosch Rexroth Simulation Libraries (1.4)

Best wishes

Sven Bätzing

**Comment by casella** [comment] 2021-11-11 10:23
This is hopefully addressed by PR #7652

**Comment by adrpo** [comment] 2022-01-04 19:02
After fixes with #7652 you will get this dropdown:
![Issue7488](https://user-images.githubusercontent.com/4192979/148110062-bcf17da6-04f5-43b7-a426-6caff8e9f9e7.png)

I guess we can discuss if only the comment should be in the dropdown or the entire element.

**Comment by casella** [comment] 2022-01-05 00:52
If there are comments maybe it would be better to only show them, this is quite ugly.

**Comment by casella** [comment] 2022-01-05 21:27
@adrpo, if there is a comment in the choice declaration, I would just display that in the drop-down menu item, without the quotation marks. I understand this feature is meant to make the library easily usable from a GUI by persons who may not be familiar with the intricacies of replaceable/redeclare constructs, so displaying parts of it would just be confusing. 

If there is no comment in the choice item, then you could drop the "redeclare" keword, display the actual choice, followed by a `-` sign and by the comment of the declaration of the class being redeclared. This will be consistent with the current behaviour of the choicesAllMatching annotation, which looks good to me.

**Comment by adrpo** [comment] 2022-01-06 22:36
I now implemented this:
![image](https://user-images.githubusercontent.com/4192979/148461941-8f1b1ced-8d64-41eb-b8ca-1362a1d136d6.png)

The last two are because after I add the choices I also search for choicesAllMatching and add those. Maybe we should not.

**Comment by adrpo** [comment] 2022-01-06 22:38
As the last choice does not have a comment there is none, you however suggest to put the comment of the class C in there but that is wrong.

**Comment by casella** [comment] 2022-01-06 22:53
> The last two are added because after I add the choices I also search for `choicesAllMatching` and add those. Maybe we should not (or at least have a setting in OMEdit for this, something like: "allow to combine choices and choicesAllMatching" which would be default to false).

I guess we should only combine these two if both a choices annotation _and_ a choicesAllMatching annotation are present. Otherwise I wouldn't clutter the drop-down menu with other stuff than what is explicitly listed in the choices menu and, most importantly, I'd avoid wasting time looking for it.

**Comment by casella** [comment] 2022-01-06 22:56
> The last choice does not have a comment

Yes, that was deliberate.

> you however suggest to put the comment of the class C in there but that is wrong.

Why would it be wrong? This is exactly what we we do with the choicesAllMatching annotation, we put the comment of the class. It's the best explanation we have of what EnchancementDropDown.Database.C is for. Otherwise the poor user is only left with the name of the class to figure out what it means.

Or maybe I missed your point?

**Comment by adrpo** [comment] 2022-01-06 22:57
Ok. I will play with this. Note that currently we always consider `choicesAllMatching=true` for redeclares even if the annotation is not present (the specification suggests it should be done so) or even if is present with `choicesAllMatching=false`.
I will fix it so that we at least don't do it when `choicesAllMatching=false`.

**Comment by adrpo** [comment] 2022-01-06 22:59
Reference: https://specification.modelica.org/master/inheritance-modification-and-redeclaration.html#annotation-choices-for-suggested-redeclarations-and-modifications

- [The behavior when choicesAllMatching is not specified; ideally it should present (at least) the same choices as for choicesAllMatching = true; but if it takes (too long) time to present the list it is better to have choicesAllMatching = false.]

**Comment by adrpo** [comment] 2022-01-06 23:10
> > The last choice does not have a comment
> 
> Yes, that was deliberate.
> 
> > you however suggest to put the comment of the class C in there but that is wrong.
> 
> Why would it be wrong? This is exactly what we we do with the choicesAllMatching annotation, we put the comment of the class _declaration._ It's the best explanation we have of what EnchancementDropDown.Database.C stands for. Otherwise the poor user is only left with the name of the class to figure out what it means.
> 
> Or maybe I missed your point?

This is a redeclare of the component, not the class. If it would be the class maybe. It would be possible to get the type path and fetch the comment, I will see what I can do.

Just for comparison, this is how some other tool is showing it:
![image](https://user-images.githubusercontent.com/4192979/148465156-6b8eeb2a-5de7-4fc9-8df4-a824a307b64e.png)

**Comment by casella** [comment] 2022-01-07 01:18
> This is a redeclare of the component, not the class. If it would be the class maybe. It would be possible to get the type path and fetch the comment, I will see what I can do.

OK. Don't waste too much time on this, it's more important to support modifiers in redeclarations.

**Comment by casella** [comment] 2022-01-13 17:30
I checked the status with the latest nightly build after @adrpo's last commits, playing around a bit with the two example cases.

Regarding the original example case, I think it is now quite good. The first time you set the replaceable item, you get exactly what @sbaetzing was expecting. The next time you double-click there, what you see in the input field is the actual redeclare statement, which can actually be edited. I think this is a good feature, because advanced users may want to input or edit this stuff manually. What is still not so nice is that when you activate the drop-down menu:

- you also get the full redeclare statement in the drop-down menu. This is pointless, because if you want to keep it the same, you just hit Cancel. This item should be removed from the drop-down menu.
- when you activate the drop-down menu, rather than pre-selecting the row with the full redeclare statement (which should go, see above), you should rather see that the relevant item with the description comment only (e.g. Dataset B) is pre-selected
- regarding the full redeclare statement that you see in the input field (which is ok, we should just get rid of it in the drop-down menu), I find the use of escapes for the comment very annoying. Most end-user have no idea what an escape sequence is. I understand they are needed to build the string passed to some API function call, but that's not in the end-user interest, it's just confusing. The escape backslashes should be removed.

@adpo, do you think you can quickly fix these three points (or ask someone to do that)? Then I think we could close this issue.

**Comment by adrpo** [comment] 2022-01-14 13:14
Could you post some pictures? I don't get point 1. 
For point 3, there should be no `\"` in any of the choices, if you get that (picture please) then is a bug.

**Comment by casella** [comment] 2022-01-14 23:53
Point 1:
![immagine](https://user-images.githubusercontent.com/4233148/149599292-155e83d8-d4b7-4fce-975a-68f9b37b315f.png)

Point 3:
![Screenshot (4)](https://user-images.githubusercontent.com/4233148/149599382-0fc6e4e3-5460-47d0-8828-e4fefba55e45.png)

**Comment by adrpo** [comment] 2022-03-05 12:10
I cannot reproduce this (\" in comments), @casella can you check again with the latest nightly and update the code you use if it has changed.

**Comment by adrpo** [comment] 2022-03-05 12:12
Never mind, I could reproduce it by adding a comment in the modifier when redeclaring.

![image](https://user-images.githubusercontent.com/4192979/156882430-0bba9a28-23e3-4b54-8c61-9139f6359c09.png)

**Comment by niklwors** [comment] 2022-06-21 15:50
I think it works fine now

**Closed** 2022-06-21 15:49 UTC
Labels: COMP/GUI/OMEdit
