### ISSUE TITLE
ClaRa: DASKR error at simulation 

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#8466] opened 2022-01-25 12:13 UTC
### Description

For the developer version of ClaRa some models are failing at simulation time with an error reported by DASKR. It seems the internal non-linear solver is failing.

Check [the reports](https://libraries.openmodelica.org/branches/master/ClaRa_dev/ClaRa_dev.html) for

- ClaRa.Components.TurboMachines.Pumps.Check.TestPump_L1_OffDesign 
- ClaRa.Components.TurboMachines.Pumps.Check.TestPump_L1_WithEMotor

### Steps to Reproduce

Simulate `ClaRa.Components.TurboMachines.Pumps.Check.TestPump_L1_OffDesign` with omc

```
assert            | warning | The following assertion has been violated at time 0.000000
|                 | |       | pump.Delta_p >= 0.0
assert            | warning | Variable violating min constraint: 0.0 <= pump.Delta_p, has value: -500000
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
DASKR--  AT T (=R1) AND STEPSIZE H (=R2) THE                                    
      In above,  R1 =   3.9337974294677E+02   R2 =   3.4984349100943E-08
DASKR--  NONLINEAR SOLVER FAILED TO CONVERGE                                    
DASKR--  REPEATEDLY OR WITH ABS(H)=HMIN                                         
stdout            | warning | The corrector could not converge.
stdout            | warning | can't continue. time = 393.379743
stdout            | info    | model terminate | Integrator failed. | Simulation terminated at time 393.38
```

### Version and OS

- OpenModelica Version: OMCompiler v1.19.0-dev.545+g5c10d4c725
- OS: Ubuntu 20.04.3 LTS
- Versions of used Modelica libraries: ClaRa_dev @ c57bace0acbe86a8ae2ccf3e427c60093c5ac95c

**Comment by casella** [comment] 2022-01-26 17:17
If the causalized ODEs fulfill Cauchy's sufficient conditions for local solvability, DASSL should be able to go on with the simulation, by taking small enough steps to keep the error estimation below the threshold. For some reason this does not happen here. There are two possible root causes: one is that the causalized ODEs are numerically ill-posed, so there are large rounding errors that prevent the solver to behave as expected; another one is that the causalized ODEs are actually singular, so the solver gets as close as possible to the singularity, but then gives up.

One way to tell these two cases apart is to check the behaviour of state derivative immediately before the integrator gives up. Maybe some of them seem to be going through the roof, and that can be a tell-tale sign of something wrong, that can be investigated by looking at how those derivatives are computed in the BLT.

Another option, which is available in Dymola, is to have DASSL report which state(s) dominate the error estimation during that simulation phase. This is again a way to pinpoint where in the model the problem is originated. I'm not sure if there is some way to get this kind of diagnostic information from the solver.

**Comment by casella** [comment] 2022-02-09 17:16
Did you try setting `-d=initialization`, to see if OMC sets some default initial equations?

**Comment by AnHeuermann** [comment] 2022-02-10 15:44
> Did you try setting -d=initialization, to see if OMC sets some default initial equations?

There isn't any output from `-d=initialization`.

----------------

We have some alias conflicts:
```
"Warning: Alias set with conflicting nominal values
 * Candidate: pump.iCom.Delta_p_max_var(nominal = 100000.0, confidence number = 8)
 * Candidate: pump.Delta_p_max_var(nominal = 0.0, confidence number = 7)
=> Select value from pump.Delta_p_max_var(nominal = 0.0) for variable: pump.Delta_p_max_var
Warning: Alias set with conflicting nominal values
 * Candidate: pump.summary.outline.Delta_p(nominal = 0.0, confidence number = 9)
 * Candidate: pump.energetics.Delta_p_ps(nominal = 100000.0, confidence number = 8)
 * Candidate: pump.iCom.Delta_p(nominal = 100000.0, confidence number = 8)
 * Candidate: pump.Delta_p(nominal = 100000.0, confidence number = 7)
=> Select value from pump.Delta_p(nominal = 100000.0) for variable: pump.Delta_p
```

But changing the nominal value of `pump.Delta_p_max_var` to `100000.0` doesn't improve the initial solution.

------------

I'm not sure how to debug the initialization system and figure out what went wrong.

**Comment by phannebohm** [comment] 2022-02-10 15:53
> But changing the nominal value of `pump.Delta_p_max_var` to `100000.0` doesn't improve the initial solution.

How about changing the nominal value of `pump.Delta_p` to `0.0` for the second alias conflict?

**Comment by casella** [comment] 2022-02-10 18:55
@phannebohm a nominal value of zero is really a bad idea. The nominal value gives a a-priori order of magnitude of the variable for proper scaling, so zero is not a good value, even if the solution turns out to be zero. I see that for a number of variables, and IMHO this is a bad library design and should be fixed upstream in ClaRa.

OpenModelica actually does use nominal values for scaling (see [EOOLT paper](http://dx.doi.org/10.1145/3158191.3158192)), if I'm not mistaken it actually takes `max(nominal, abs(start))`. I'm not sure if the start attributes of those variables that have zero nominal attributes are also zero, if that is the case, I'm not too surprised that the initialization goes bad.

If you have access to Dymola, you can also try to initialize the model with it, and then compare the initial values of the chosen states (the list can be obtained with -d=stateselection) to see if it is really an initialization problem or something else.

Last, but not least, the current algorithm for start (and nominal) attribute selection should be fixed according to the new specification, see #5813, this will for sure have a positive impact on a large number of initialization failures across libraries.

**Comment by casella** [comment] 2022-02-16 09:26
@AlesVojacek reports that they improved the model and it now runs fine, let's wait for the CI report to confirm that.

The zero nominal values are an omc bug because they are not set in the library, we should open another ticket for that.

**Comment by casella** [comment] 2022-06-07 22:43
[TestPump_L1_WithEMotor.sim](https://libraries.openmodelica.org/branches/master/ClaRa_dev/files/ClaRa_dev_ClaRa.Components.TurboMachines.Pumps.Check.TestPump_L1_WithEMotor.sim) now works fine, including [verification](https://libraries.openmodelica.org/branches/master/ClaRa_dev/ClaRa_dev.html).

Unfortunately [TestPump_L1_OffDesign](https://libraries.openmodelica.org/branches/master/ClaRa_dev/files/ClaRa_dev_ClaRa.Components.TurboMachines.Pumps.Check.TestPump_L1_OffDesign.sim) still fails.

**Comment by phannebohm** [comment] 2023-07-18 15:49
As of OMCompiler v1.22.0-dev.245+g6a88ed1a95, both models simulate and only suffer from numerical noise.

**Closed by phannebohm** 2023-07-18 15:49 UTC
Labels: COMP/SimRT/C
