### ISSUE TITLE
Model instantiation inconsistency

### ISSUE THREAD

**Issue by matteodepascali** [OpenModelica/OpenModelica#12279] opened 2024-04-18 20:00 UTC
Consider the following models

```modelica
package ModelsExpansionEquations
  model Model1
    Real x[3];
  equation
  end Model1;

  model Model2
    Real y[3];
    Model1 mod1(x=y);
  equation
  end Model2;
  
  model Model3
    Real y[3];
    Model1 mod1;
  equation
  mod1.x = y;
  end Model3;

end ModelsExpansionEquations;
```

Instantiating Model2 produces the following instantiated model:

```modelica
class ModelsExpansionEquations.Model2
  Real y[1];
  Real y[2];
  Real y[3];
  Real mod1.x[1];
  Real mod1.x[2];
  Real mod1.x[3];
equation
  mod1.x = y;
end ModelsExpansionEquations.Model2;
```

Instantiating Model3 produces the following instantiated model:

```modelica
class ModelsExpansionEquations.Model3
  Real y[1];
  Real y[2];
  Real y[3];
  Real mod1.x[1];
  Real mod1.x[2];
  Real mod1.x[3];
equation
  mod1.x[1] = y[1];
  mod1.x[2] = y[2];
  mod1.x[3] = y[3];
end ModelsExpansionEquations.Model3;

```

The two outputs are inconsistent even if the two model are basically the same.

OpenModelica version: v1.24.0-dev-20-gde46d5b2f7 (64-bit)
Windows version: 11

@casella

**Comment by Arinomo** [comment] 2024-04-19 05:18
``` .mo
model Model2
  Real y[3] = {6, 7, 8};
  Model1 mod1(x=y);
equation
end Model2;
```
but the above example resulting in the, i assume, intended behavior in simulation, i.e the value of x would also be `[6, 7, 8]`, is it not?

**Comment by matteodepascali** [comment] 2024-04-19 19:05
Yes, the problem is not there for actual BaseModelica. Sorry for the confusion. 
The inconsistency is just related to the model instantiation output without --BaseModelica flag.
I'll edit the issue and if this behavior is not a real issue, we can close this thread.

**Comment by casella** [comment] 2024-04-21 18:40
@perost I tried to run `omc --BaseModelica -i=ModelsExpansionEquations.Model1 ModelsExpansionEquations.mo`. The output is:
```modelica
package 'Model1'
  model 'Model1'
    Real[3] 'x';
  end 'Model1';
end 'Model1';
```
Now, I haven't set `-d=nonfScalarize`, why don't I get
```modelica
package 'Model1'
  model 'Model1'
    Real 'x[1]';
    Real 'x[2]';
    Real 'x[3]';
  end 'Model1';
end 'Model1';
```
as I would (except for the Q-IDENTs) when I instantiate the model without `--BaseModelica`?

**Comment by perost** [comment] 2024-04-21 18:53
> @perost I tried to run `omc --BaseModelica -i=ModelsExpansionEquations.Model1 ModelsExpansionEquations.mo`. The output is:
> 
> ```modelica
> package 'Model1'
>   model 'Model1'
>     Real[3] 'x';
>   end 'Model1';
> end 'Model1';
> ```
> 
> Now, I haven't set `-d=nonfScalarize`, why don't I get
> 
> ```modelica
> package 'Model1'
>   model 'Model1'
>     Real 'x[1]';
>     Real 'x[2]';
>     Real 'x[3]';
>   end 'Model1';
> end 'Model1';
> ```
> 
> as I would (except for the Q-IDENTs) when I instantiate the model without `--BaseModelica`?

Base Modelica is dumped after flattening but before scalarization, so arrays of simple types won't be expanded. You can use `--dumpFlatModel` to see the result after each phase.

**Comment by casella** [comment] 2024-04-21 22:09
From the perspective of somebody who wants to import Base Modelica to minimize the compiler development effort and who is not interested in array-preserving code generation, having non-scalarized equations and variables is just an unnecessary complication, as he or she will have to take care of handling them. 

Since the NF can actually take care of that very well, I think it would be best to let it do that, unless `-d=nonfScalarize` is set, in which case the BaseModelica importing tool is prepared to handle arrays in order to gain some advantage with large models. That would be the case of "real" compliers, like MARCO. If you want to import a flat Modelica model into Pyomo (as @matteodepascali needs) or into any tool that cannot handle arrays natively, arrays would just be a nuisance.

If you consider this MWE
```modelica
package P
  model M
    Real x[2];
  end M;
  
  model S
    M m[2];
  end S;
end P;
```
I think flattening P.S should either return
```modelica
package 'S'
  model 'S'
    Real[2, 2] 'm.x';
  end 'S';
end 'S';
```
or 
```modelica
package 'S'
  model 'S'
    Real m[1].x[1];
    Real m[1].x[2];
    Real m[2].x[1];
    Real m[2].x[2];
  end 'S';
end 'S';
```
I don't see much of a point having this hybrid
```modelica
package 'S'
  model 'S'
    Real[2] 'm[1].x';
    Real[2] 'm[2].x';
  end 'S';
end 'S';
```
except of course for the case of array equations. But even in that case, if I wanted to build a "cheap" Base Modelica importer, I would rather prefer the NF to take care of handling them, and get the scalarized equations directly.

**Comment by casella** [comment] 2024-04-21 22:14
To me the only question is how to design the user interface to allow the end user to get the Base Modelica he or she needs. One simple option, which may be unnecessarily crude, is to only have the two extremes: flatten everything to scalars, or preserve everything as arrays. These are the two use-cases that we have now.

Maybe we should start supporting them, and then add more flexibility as soon as there is need for it.

**Comment by matteodepascali** [comment] 2024-04-21 22:55
> From the perspective of somebody who wants to import Base Modelica to minimize the compiler development effort and who is not interested in array-preserving code generation, having non-scalarized equations and variables is just an unnecessary complication, as he or she will have to take care of handling them.
> 
> Since the NF can actually take care of that very well, I think it would be best to let it do that, unless `-d=nonfScalarize` is set, in which case the BaseModelica importing tool is prepared to handle arrays in order to gain some advantage with large models. That would be the case of "real" compliers, like MARCO. If you want to import a flat Modelica model into [Pyomo.DAE](https://pyomo.readthedocs.io/en/stable/modeling_extensions/dae.html) (as @matteodepascali needs) or into any tool that cannot handle arrays natively, arrays would just be a nuisance.
> 
> If you consider this MWE
> 
> ```modelica
> package P
>   model M
>     Real x[2];
>   end M;
>   
>   model S
>     M m[2];
>   end S;
> end P;
> ```
> 
> I think flattening P.S should either return
> 
> ```modelica
> package 'S'
>   model 'S'
>     Real[2, 2] 'm.x';
>   end 'S';
> end 'S';
> ```
> 
> or
> 
> ```modelica
> package 'S'
>   model 'S'
>     Real m[1].x[1];
>     Real m[1].x[2];
>     Real m[2].x[1];
>     Real m[2].x[2];
>   end 'S';
> end 'S';
> ```
> 
> I don't see much of a point having this hybrid
> 
> ```modelica
> package 'S'
>   model 'S'
>     Real[2] 'm[1].x';
>     Real[2] 'm[2].x';
>   end 'S';
> end 'S';
> ```
> 
> except of course for the case of array equations. But even in that case, if I wanted to build a "cheap" Base Modelica importer, I would rather prefer the NF to take care of handling them, and get the scalarized equations directly.

Based on the experience of these days writing the BaseModelica-pyomo parser, I agree with these considerations.
The easiest output one may get is with all scalarized variable and also with all the equations made just of scalar variables.
I haven't tested BaseModelica generations thoroughly and so far I haven't noticed the following behavior (which I encountered in the output of the model instantiation), but it is also very useful to put all the equations in the equation section, even if some of those are written in the variable section, like `Real x = y;`

**Comment by perost** [comment] 2024-04-22 08:28
> Based on the experience of these days writing the BaseModelica-pyomo parser, I agree with these considerations. The easiest output one may get is with all scalarized variable and also with all the equations made just of scalar variables. I haven't tested BaseModelica generations thoroughly and so far I haven't noticed the following behavior (which I encountered in the output of the model instantiation), but it is also very useful to put all the equations in the equation section, even if some of those are written in the variable section, like `Real x = y;`

We could move the dumping of Base Modelica to the end of the frontend, so you get about the same structure as the flat model we normally output. But it seems doing so breaks some things currently, so it'll need some work before we can do that.

As for moving binding equations, we currently do it for array variables of at least discrete variability to avoid having to scalarize the binding as well as for record bindings that we couldn't split into separate bindings for each field. We could change it for Base Modelica and do it for all variables regardless of type. But I'm not sure how useful it really is since you can't move e.g. binding equations for constants, so a tool using Base Modelica will still need to support binding equations.

**Comment by casella** [comment] 2024-04-22 10:33
> We could move the dumping of Base Modelica to the end of the frontend, so you get about the same structure as the flat model we normally output. But it seems doing so breaks some things currently, so it'll need some work before we can do that.

I hope it's not too much work, otherwise @matteodepascali could be in trouble 😅 

To me, the requirement is clear: at least for some applications, you'd rather want to get rid of arrays entirely. How do you achieve that with the NF, I have no strong opinion.

> As for moving binding equations, we currently do it for array variables of at least discrete variability to avoid having to scalarize the binding as well as for record bindings that we couldn't split into separate bindings for each field. We could change it for Base Modelica and do it for all variables regardless of type. But I'm not sure how useful it really is since you can't move e.g. binding equations for constants, so a tool using Base Modelica will still need to support binding equations.

Not necessarily, if you constant-evaluate all constants and parameters, there won't be any need of that, right? So, this could be one option. In fact, the main point of binding equations _for non-protected variables in Modelica_, which is that you can change them when instantiating components, is lost in BaseModelica, which has no instantiation process left. Binding equations only make sense for parameters and constants, if you don't evaluate them, that is.

The point is: there is a single Base Modelica standard, but depending on the end-user application, starting from the same model, we may generate different Base Modelica outputs, depending on whether or not

1. Constant expressions are constant-evaluated
2. All parameter expressions are constant-evaluated
3. Most parameter expressions are constant-evaluated, except some which are relevant e.g. for sensitivity analysis or grey-box parameter identification, see #4960 
4. Functions are inlined (whenever possible)
5. Array declarations and array equations are flattened to scalars
6. Record declarations and record expressions are flattened to their scalar counterparts (e.g. Complex operator record declarations and expressions)

Most of these requirements are orthogonal, so I guess they should be handled as such, by each having a flag. Depending on the specific application, one could activate the needed ones. For example, as of today:
- @matteodepascali needs 1., 2., 4., and 5. Feature 6. is currently not required, as there are no record variables in his model, but if there were some, he'd also need 6
- the MARCO compiler needs 1., 2., maybe 3. in the future, and 6.
- other potential end-users of OMC's Base Modelica output may need other combinations

@perost I think we should discuss thoroughly, come up with a list, and then get them implemented with some priority order.
8. Fully scalarized equations, evalutated constant expressions, evaluated parameter expressions, all binding equations for variables moved to the equation section
9. Fully scalarized

**Comment by casella** [comment] 2024-04-27 20:49
I summarized all the requirements i #12333, so we can close this ticket.

**Closed by casella** 2024-04-27 20:49 UTC
Labels: COMP/OMC/Frontend
