### ISSUE TITLE
Model is not simulating in both Windows and Ubuntu versions of OpenModelica

### ISSUE THREAD

**Issue by NehaSPatwardhan** [OpenModelica/OpenModelica#13194] opened 2024-11-12 11:27 UTC
### Description

The solver fails to simulate with a pop up "OME is not responding" with both Windows and Ubuntu versions of OpenMoedlica.

The given model is having this issue:
```
Buildings.Fluid.Examples.FlowSystem.Simplified3
```
The log report of the model is given below:
https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Fluid.Examples.FlowSystem.Simplified3.sim
```
LOG_STDOUT        | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.000000. That might raise performance issues, for more information use -lv LOG_LS.
LOG_STDOUT        | warning | Error solving linear system of equations (no. 10168) at time 0.000000.
LOG_STDOUT        | warning | Solving linear system 10168 fails at time 0. For more information use -lv LOG_LS.
LOG_ASSERT        | debug   | Solving linear system 10168 failed at time=0.
|                 | |       | For more information please use -lv LOG_LS.
LOG_ASSERT        | info    | simulation terminated by an assertion at initialization

```

The error report of the model is given below:
https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Fluid.Examples.FlowSystem.Simplified3.err
```
1.Warning: The model contains alias variables with redundant start and/or conflicting nominal values.
 It is recommended to resolve the conflicts, because otherwise the system could be hard to solve.
 To print the conflicting alias sets and the chosen candidates please use -d=aliasConflicts.

"2.Warning: The linear system: 
1 : valCoo.m_flow + spl1.res1.m_flow + valNorth.res3.m_flow + valSouth.res3.m_flow + (-tabsSouth1[2].m_flow) - tabsSouth1[1].m_flow - tabsSouth1[3].m_flow - tabsSouth1[4].m_flow - tabsSouth2[1].m_flow - tabsSouth2[2].m_flow - tabsSouth2[3].m_flow - tabsSouth2[4].m_flow - tabsSouth2[5].m_flow - tabsSouth2[6].m_flow - tabsSouth2[7].m_flow - tabsSouth2[8].m_flow - tabsNorth1[1].m_flow - tabsNorth1[2].m_flow - tabsNorth1[3].m_flow - tabsNorth1[4].m_flow - tabsNorth2[1].m_flow - tabsNorth2[2].m_flow - tabsNorth2[3].m_flow - tabsNorth2[4].m_flow - tabsNorth2[5].m_flow - tabsNorth2[6].m_flow - tabsNorth2[8].m_flow - tabsNorth2[7].m_flow = 0.0
2 : valNorth.res1.m_flow + valSouth.res1.m_flow + (-valHea.m_flow) - valCoo.m_flow = 0.0
3 : 0.0 = spl1.res1.m_flow + (-bou.ports[1].m_flow) - valHea.m_flow
[
  1.0 , 0.0 , 1.0 ;
  0.0 , -1.0 , -1.0 ;
  -1.0 , 1.0 , 0.0
]
  *
[
  spl1.res1.m_flow ;
  valHea.m_flow ;
  valCoo.m_flow
]
  =
[
  tabsSouth1[2].m_flow + tabsNorth2[8].m_flow + tabsNorth2[7].m_flow + tabsNorth2[6].m_flow + tabsNorth2[5].m_flow + tabsNorth2[4].m_flow + tabsNorth2[3].m_flow + tabsNorth2[2].m_flow + tabsNorth2[1].m_flow + tabsNorth1[4].m_flow + tabsNorth1[3].m_flow + tabsNorth1[2].m_flow + tabsNorth1[1].m_flow + tabsSouth2[8].m_flow + tabsSouth2[7].m_flow + tabsSouth2[6].m_flow + tabsSouth2[5].m_flow + tabsSouth2[4].m_flow + tabsSouth2[3].m_flow + tabsSouth2[2].m_flow + tabsSouth2[1].m_flow + tabsSouth1[4].m_flow + tabsSouth1[3].m_flow + tabsSouth1[1].m_flow + (-valSouth.res3.m_flow) - valNorth.res3.m_flow ;
  (-valNorth.res1.m_flow) - valSouth.res1.m_flow ;
  -bou.ports[1].m_flow
]
 might be structurally or numerically singular for variable valCoo.m_flow since U(3,3) = 0.0. It might be hard to solve. Compilation continues anyway."

"3.Warning: The linear system: 
1 : valCoo.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + spl1.res1.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + valNorth.res3.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + valSouth.res3.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + (-tabsNorth2.8.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24) - tabsNorth2.7.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsNorth2.6.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsNorth2.5.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsNorth2.4.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsNorth2.3.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsNorth2.2.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsNorth2.1.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsNorth1.4.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsNorth1.3.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsNorth1.2.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsNorth1.1.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsSouth2.8.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsSouth2.7.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsSouth2.6.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsSouth2.5.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsSouth2.4.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsSouth2.3.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsSouth2.2.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsSouth2.1.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsSouth1.4.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsSouth1.3.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsSouth1.1.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 - tabsSouth1.2.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 = 0.0
2 : valNorth.res1.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + valSouth.res1.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + (-valHea.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24) - valCoo.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 = 0.0
3 : 0.0 = spl1.res1.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + (-bou.ports.1.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24) - valHea.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24
[
  1.0 , 0.0 , 1.0 ;
  0.0 , -1.0 , -1.0 ;
  -1.0 , 1.0 , 0.0
]
  *
[
  spl1.res1.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 ;
  valHea.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 ;
  valCoo.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24
]
  =
[
  tabsNorth2.8.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsSouth1.1.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsSouth1.2.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsSouth1.3.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsSouth1.4.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsSouth2.1.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsSouth2.2.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsSouth2.3.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsSouth2.4.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsSouth2.5.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsSouth2.6.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsSouth2.7.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsSouth2.8.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsNorth1.1.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsNorth1.2.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsNorth1.3.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsNorth1.4.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsNorth2.1.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsNorth2.2.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsNorth2.3.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsNorth2.4.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsNorth2.5.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsNorth2.6.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + tabsNorth2.7.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 + (-valSouth.res3.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24) - valNorth.res3.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 ;
  (-valNorth.res1.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24) - valSouth.res1.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 ;
  -bou.ports.1.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24
]
 might be structurally or numerically singular for variable valCoo.m_flow.$pDERStateSetJac24.dummyVarStateSetJac24 since U(3,3) = 0.0. It might be hard to solve. Compilation continues anyway."
```
### Steps to Reproduce

Load the Modelica-Buildings master library (Source: https://github.com/lbl-srg/modelica-buildings/)
Simulate the examples model present in  
Buildings.Fluid.Examples.FlowSystem.Simplified3

### Expected Behavior
The model should simulate successfully.

### Version and OS

 - OpenModelica Version: OpenModelica 1.25.0~dev-152-g78d9a41
- OS: 11.1.0ubuntu4
- Windows 11 Version 23H2
 - Versions of used Modelica libraries:
Modelica 4.0.0
Buildings 12.0.0

**Comment by casella** [comment] 2024-11-12 14:33
Likely the same issue as #13192

**Comment by casella** [comment] 2024-12-05 09:14
Duplicate of #13191.

**Closed** 2024-12-05 09:14 UTC
