### ISSUE TITLE
Duplicate model function in OMEdit should work without compromises

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#5346] opened 2020-06-27 10:55 UTC

**Comment by casella** [comment] 2022-10-22 15:08
Original trac ticket: https://trac.openmodelica.org/OpenModelica/ticket/5346

**Comment by casella** [comment] 2022-11-02 23:58
As suggested by @AHaumer in #9646, should also work fine when duplicating entire packages.

**Comment by foobarbecue** [comment] 2023-06-04 23:19
Trying to teach myself OMEdit now and it's pretty much a non-starter when you can't copy or modify the examples.

**Comment by casella** [comment] 2023-06-05 08:41
> Trying to teach myself OMEdit now and it's pretty much a non-starter when you can't copy or modify the examples.

@foobarbecue we are aware of that, this development is planned for the second half of 2023.

**Comment by scls19fr** [comment] 2023-09-20 11:45
Coming form https://github.com/OpenModelica/OpenModelica/discussions/11221
That's definately a very important feature to have!

**Comment by casella** [comment] 2024-02-29 14:04
After discussing this at the last devmeeting, the solution for duplicating a _model_ while keeping the formatting seems to be that we just copy the text of the model verbatim, then analyze all the types used in there and adapt them according to the lookup rules based on the old and new location.

This should also work for other classes, e.g. records or functions, but not to duplicate packages, which may be spread over multiple files - this would take a bit more work.

@perost can you please take care of that?

**Comment by perost** [comment] 2024-02-29 14:17
> This should also work for other classes, e.g. records or functions, but not to duplicate packages, which may be spread over multiple files - this would take a bit more work.

Would it? It doesn't seem like it would take any extra work as duplicating a class defined in a single file, you just update all the filenames so the directory is correct.

The trickier case seems to me to be when duplicating a class that only makes up part of a file, where should that go? Should it be placed in a new file, or should it be added to an existing file? I guess we could check if the existing classes in the package the class is being added to are defined in separate files or not.

**Comment by casella** [comment] 2024-02-29 14:25
> Would it? It doesn't seem like it would take any extra work as duplicating a class defined in a single file, you just update all the filenames so the directory is correct.

I just meant that you need to figure out what is the set of files to duplicate. If that is no big deal, that's good 😃 

> The trickier case seems to me to be when duplicating a class that only makes up part of a file, where should that go? Should it be placed in a new file, or should it be added to an existing file?

It depends on the target path. If you copy to a package that is stored into a single file, the text should be added in the proper place, if instead the package is spread as several files in a directory, then you should add one more file.

**Comment by perost** [comment] 2024-02-29 14:40
> > The trickier case seems to me to be when duplicating a class that only makes up part of a file, where should that go? Should it be placed in a new file, or should it be added to an existing file?
> 
> It depends on the target path. If you copy to a package that is stored into a single file, the text should be added in the proper place, if instead the package is spread as several files in a directory, then you should add one more file.

It's actually quite common that packages are stored in both `package.mo` and separate files for some classes. Take `Modelica.Math` for example, where e.g. `Modelica.Math.Vectors` is defined in the `package.mo` file and `Modelica.Math.BooleanVectors` is defined in a separate `BooleanVectors.mo` file.

In that case I don't really see any actual pattern for how the classes are stored, so without asking the user there's not really any way to make the correct choice. But I guess we can just check how the class we're moving was defined, or maybe it would be better to just always put it in a separate file in that case?

**Comment by casella** [comment] 2024-02-29 17:26
I guess if it's not clear where to put it, we should just ask the user. Specifically, if the destination path is a directory with a package.mo the choices are: inside package.mo or in a separate file in that directory. If the destination path is some packageName.mo, then it has to be in there. If it's the global scope, we should ask for a file name and path.

Do I miss something?

**Comment by bilderbuchi** [comment] 2024-03-01 07:09
Doesn't OM already track the information if a given package is single-file or file-per-model? Otherwise, how would it know what to do when you "add model"?
If yes, can you tell which destination package a duplicate is desired to end up in, and decide based on that package's setting automatically?
That is, if you duplicate a model into a single-file package, append it to `package.mo`, if you duplicate into a file-per-model package, put it into `duplicated-model.mo`?

**Comment by adeas31** [comment] 2024-03-01 09:51
With the current implementation the `copyClass` API makes a copy of the class and OMEdit is responsible for saving it. OMEdit asks the user how to save it.

![image](https://github.com/OpenModelica/OpenModelica/assets/4007231/95968089-07b8-4a50-9836-fde3cdcb3522)

So why are you worried about how they will be stored?

**Comment by adeas31** [comment] 2024-03-01 10:32
I guess you need this information when using it from the command line. OMEdit doesn't use the API for saving files.

**Comment by casella** [comment] 2024-03-01 17:07
I don't think we need this feature in the command line or interactive environment. Having it in OMEdit is good enough.

**Comment by perost** [comment] 2024-03-19 12:13
#10342 should improve the `copyClass` API to update paths in the copied classes such that they are valid in the new location when possible. I've tried to test it as much as I can, but e.g. the MSL mostly uses absolute paths instead of relative ones so it's a bit hard to find good test models, so please try it out and let me know if you find any issues.

**Comment by casella** [comment] 2024-03-19 18:51
@GallLeo, you are our best tester here!

**Comment by casella** [comment] 2024-03-19 18:55
@perost I guess #10342 is not the right link, you probably meant #12120, right?

**Comment by casella** [comment] 2024-03-19 19:00
@AndreaBartolini, you can also test this when you have time.

**Comment by casella** [comment] 2024-03-19 19:04
@bilderbuchi you are also very welcome to test and report 😃

**Comment by perost** [comment] 2024-03-19 20:58
> @perost I guess #10342 is not the right link, you probably meant #12120, right?

Yes, I'm used to my commit being mentioned in the issue and just copied the number from above my comment... Anyway, it's merged now so should be in tomorrows nightly build if the nightly builds are working correctly.

**Comment by casella** [comment] 2024-03-20 16:36
And, of course, the latest nightly was broken, so this feature is not yet available. I scheduled another nightly, it will run ASAP.

**Comment by christiankral** [comment] 2024-03-27 20:14
I created a lot of duplicates from the MSL. They worked with no problem except for one case I found:

Creating a duplicate of `Modelica.Electrical.Machines.Utilities.ParameterRecords`. 

![image](https://github.com/OpenModelica/OpenModelica/assets/4184218/243ee3eb-5d45-40f2-bccb-9a3b3a6762b0)

as a new package:

![image](https://github.com/OpenModelica/OpenModelica/assets/4184218/d191afd7-2bfc-4c20-8a57-0851433bd6e6)

This causes an issues when checking the package and the individual records, respectively:

```modelica
[1] 21:09:14 Translation Error
[ParameterRecords.InductionMachineData: 6:3-6:59]: [Class SI.Inertia not found in scope InductionMachineData.](omeditmessagesbrowser:///ParameterRecords.InductionMachineData?lineNumber=6)
```

I have to admit, this this is not a duplicate model, but a duplicate package. The ticket description is *"[Duplicate model function in OMEdit should work without compromises](https://github.com/OpenModelica/OpenModelica/issues/5346#top)"* so the package may be out of scope.


This case was produced with the following OMEdit version:

```
Connected to OpenModelica 1.23.0~dev-407-g1fb3195
Connected to OMSimulator 2.1.2-linux-notlm-debug
```

**Comment by casella** [comment] 2024-03-27 22:10
@christiankral thanks for reporting!

@perost is the `copyClass` API meant to copy any kind of class, including packages? 

If so, please check @christiankral's reported issue. Otherwise, we should restrict the application of the Duplicate menu item to those kind of classes where it is meant to work.

**Comment by perost** [comment] 2024-03-27 22:12
> @perost is the `copyClass` API meant to copy any kind of class, including packages?

Yes, it doesn't care about what kind of class it is.

**Comment by casella** [comment] 2024-03-27 22:16
OK, then, with reference to the issue that @christiankral reported, maybe there is some problem with imports or something?

**Comment by perost** [comment] 2024-03-28 12:16
I tried to replicate the issue that @christiankral found with `Modelica.Electrical.Machines.Utilities.ParameterRecords`, but for me it works fine. The error message implies that some `SI.*` paths weren't updated when duplicating the class, but for me they are fully qualified to `Modelica.Units.SI.*` as intended (because the import is in `Modelica.Electrical` and doesn't apply to the new location).

 So I'm not sure what's going on, the new `copyClass` should definitely be in the version used and I haven't changed it since the initial commit. Maybe someone else could try it out and see if they can replicate the issue?

**Comment by casella** [comment] 2024-03-28 14:17
I'm also not getting any problem when duplicating ParameterRecords to the global scope, except that the formatting is lost. I'm using v1.23.0-dev-409-ga5a3ab3b6f. @christiankral can you try again with that?

@perost, could you try it out once more and try to figure out why the diff thing fails? If the original has some clever formatting, losing it when you duplicate the class is not really nice.

**Comment by adeas31** [comment] 2024-03-28 20:17
Works fine for me as well. I tried to duplicate `Modelica.Electrical.Machines.Utilities.ParameterRecords` to the global scope. I selected `keep structure` when asked for file type. Calling `Check All Models` on the newly created `ParameterRecords` gives `Number of classes checked / failed: 11/0`.

**Closed** 2024-03-29 17:11 UTC
Labels: COMP/GUI/OMEdit, COMP/GUI/InstBased Interface

**Comment by christiankral** [comment] 2024-03-31 10:31
I re-checked the recently reported issue with duplicating `Modelica.Electrical.Machines.Utilities.ParameterRecords`

This issue does not occur any more in the following version:

```
Connected to OpenModelica 1.23.0~dev-413-gfc210a9
Connected to OMSimulator 2.1.2-linux-notlm-debug
```

**Comment by ceraolo** [comment] 2024-09-23 10:38
Duplicate is still faulty in some cases, see #11442
