### ISSUE TITLE
Constant var in record not initialized

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#9036] opened 2022-05-30 13:31 UTC
### Description

A constant variable from a record is not initialized with a start value.

### Steps to Reproduce

Run

```Modelica
model Test
  record R
    constant Integer m = 0;
  end R;

  function foo
    "Documentation"
    input R r;
    output Integer n;
  algorithm
    assert(r.m == 7, "n not 7");
    n := r.m + 1;
  end foo;

  R r = R(m=7);
  Integer n;
equation
  n = foo(r);
end Test;
```

### Expected Behavior

Generate a equation for the constant `r.m = 7`.

For parameters

```Modelica
record R
  parameter Integer m = 0;
end R;
```

we get the start value from the init file (?).

### Version and OS

 - OpenModelica Version: v1.20.0-dev-106-gd31fbb2d46
 - OS: Ubuntu Focal

### Additional Context

From #9021 and needed for `ClaRa.Components.Mills.HardCoalMills.Check.combineMillandFurnace` from ClaRa dev version.

**Comment by AnHeuermann** [comment] 2022-05-31 13:16
During removeSimpleEquations we replace
```
Equations (2, 2)
========================================
1/1 (1): r.k = 42   [binding |0|0|0|0|]
2/2 (1): n = Test.foo(r)   [unknown |0|0|0|0|]
```
with
```
Equations (1, 1)
========================================
1/1 (1): n = Test.foo(Test.R(r.m, 42, r.l))   [unknown |0|0|0|0|]
```

We need to do the same for constants in `replaceExp`.

https://github.com/OpenModelica/OpenModelica/blob/a906e3affaa7b1b2dd855cd9f17bede6a0442737/OMCompiler/Compiler/BackEnd/BackendVarTransform.mo#L988-L1250

But the binding equations are missing from `t = DAE.T_COMPLEX(varLst = varLst)` in case `case (DAE.RECORD(path, expl, fields, t), repl, cond)`
 I'm not sure where to add the bindings. Should we do this in the FrontEnd or in the BackEnd?

@kabdelhak and myself need to investiage more.

**Comment by perost** [comment] 2022-05-31 14:37
> I understood that the frontend always constant-evaluates constant expressions, replacing them with their literal value, _even in the case where they are modified upon instantiation_. I guess this should also be the case here. @perost do I miss something?

Which expression are you referring to? We have `r` in `foo(r)`, but that's not in itself a constant (I guess `r` could be expanded to `R(r.m) => R(7)`, but I'm not sure that's a good idea). And inside the function we have `r.m` which is a constant, but that's an input so it's only constant while the function is executed.

**Comment by casella** [comment] 2022-05-31 15:57
Hmm, I checked the specification,[ Section 12.6](https://specification.modelica.org/maint/3.5/functions.html#record-constructor-functions). It says
> Whenever a record is defined, a record constructor function with the same name and in the same scope as the record class is implicitly defined according to the following rules:
>
> The declaration of the record is partially flattened including inheritance, modifications, redeclarations, and expansion of all names referring to declarations outside of the scope of the record to their fully qualified names.
>
> All record elements (i.e., components and local class definitions) of the partially flattened record declaration are used as declarations in the record constructor function with the following exceptions:
> -  Component declarations which do not allow a modification (such as final parameter Real) are declared as protected components in the record constructor function.
> -  **Prefixes** (constant, parameter, final, discrete, …) of the remaining record components **are removed**.
> -  The prefix input is added to the public components of the record constructor function.

So it seems that the flat Test model should be something like
```
model Test
  record R
    input Integer m = 0;
  end R;

  function foo
    "Documentation"
    input R r;
    output Integer n;
  algorithm
    assert(r.m == 7, "n not 7");
    n := r.m + 1;
  end foo;

  R r = R(m=7);
  Integer n;
equation
  n = foo(r);
end Test;
```
I guess before removing the prefix, the frontend should check that the modifying expression doesn't have higher variability than the corresponding element, but then it would be up to the backend to take care of it.

BTW, I tried to flatten the example provided by @AnHeuermann with 1.19.0-dev.beta5, but I got this error:
```
[1] 17:08:21 Translation Error
[Test: 15:3-15:15]: No matching function found for Test.R(m = /*Integer*/ 7).
Candidates are:
  Test.R() => R
```
has this changed on master in the meantime?

**Comment by perost** [comment] 2022-05-31 22:03
> BTW, I tried to flatten the example provided by @AnHeuermann with 1.19.0-dev.beta5, but I got this error:
> 
> ```
> [1] 17:08:21 Translation Error
> [Test: 15:3-15:15]: No matching function found for Test.R(m = /*Integer*/ 7).
> Candidates are:
>   Test.R() => R
> ```
> 
> has this changed on master in the meantime?

Yes, we recently changed this, see #9014. That change has not been ported to 1.19, and I'm not sure if it should be.

**Comment by AnHeuermann** [comment] 2022-06-01 15:20
For
```Modelica
record R
  constant Integer m = 0;
  Integer k;
  final constant Integer l = 8;
end R;
```

we can dump the simCode and get:
```
algebraicEquations (1 systems):
========================================
3: r.k=42 [Integer]
4: n=Test.foo(Test.R(7, 42, 8)) [Integer]
========================================

initialEquations: (2)
========================================
1: alias of 3
2: n=Test.foo(r) [Integer]
========================================
```

So in the algebraicEquations the replacement is done correctly, but in the initial equaton we should have the same?

**Comment by casella** [comment] 2022-06-01 21:59
> So in the algebraicEquations the replacement is done correctly, but in the initial equaton we should have the same?

I guess so, why not?

**Comment by perost** [comment] 2022-06-10 10:36
> This won't:
> 
> ```modelica
> R r R(m=7, k=42);
> ```

Obviously, but I assume you meant `R r(m=7, k=42)`? Like I said when talking with kabdelhak, those cases should ideally be equivalent. But it's complicated since one uses modifiers and the other a binding equation, so internally they're very different.

**Comment by AnHeuermann** [comment] 2022-06-10 10:48
I switched the cases around. The one with the modifiers works, the one with the bindings not (yet).

**Comment by AnHeuermann** [comment] 2022-07-05 12:19
I have a new example that should work but won't with PR #9186:

```Modelica
package Test2
  model SimCenter
    replaceable parameter ExtendedRecord1 rec constrainedby EmptyRecord;
  end SimCenter;

  record BaseRecord
    constant Integer m;
  end BaseRecord;

  record ExtendedRecord1
    extends BaseRecord(m=1);
  end ExtendedRecord1;

  record ExtendedRecord2
    extends BaseRecord(m=6);
  end ExtendedRecord2;

  partial record EmptyRecord
  end EmptyRecord;

  function foo
    input BaseRecord rec;
    output Integer m;
  algorithm
    assert(rec.m == 7, "m not 7");
    m := rec.m;
  end foo;

  model Test
    Integer m;
    inner SimCenter simCenter(replaceable ExtendedRecord2 rec(m=7));
  equation
    m = foo(simCenter.rec);
  end Test;
end Test2;
```

@kabdelhak Do you have an idea what is missing in your PR?

**Comment by AnHeuermann** [comment] 2022-07-15 14:33
In https://github.com/OpenModelica/OpenModelica/pull/9186 this gets fixed.

`ClaRa.Components.Mills.HardCoalMills.Check.combineMillandFurnace` is now simulating as well. I haven't checked the results yet, though.

**Comment by casella** [comment] 2022-07-16 15:39
I'm sorry folks, but I am afraid this had some negative impact on Buildings, see [report](https://libraries.openmodelica.org/branches/history/master/2022-07-14%2004:46:18..2022-07-16%2000:54:08.html).

In some cases, models that were previously simulating now fail silently in the backend, see e.g. [Buildings.Applications.DataCenters.ChillerCooled.Examples.IntegratedPrimarySecondaryEconomizer](https://libraries.openmodelica.org/branches/master/Buildings_8/files/Buildings_8_Buildings.Applications.DataCenters.ChillerCooled.Examples.IntegratedPrimarySecondaryEconomizer.err).

In some other cases, models that were previously simulating now fail during codegen, see e.g. [Buildings.Experimental.DHC.Loads.BaseClasses.Validation.BenchmarkFlowDistribution1.err](http://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Experimental.DHC.Loads.BaseClasses.Validation.BenchmarkFlowDistribution1.err)

**Comment by AnHeuermann** [comment] 2022-07-19 08:20
The first two issues should be resolved. Now we need to check why `ClaRa.StaticCycles.Boundaries.Check.TestNewBoundaries` still has unbound bindings.

Here is a new MWE to play with:
```Modelica
package DispatcherExample
  record EmptyRecord
  end EmptyRecord;

  record BaseRecord
    extends EmptyRecord;
    constant Integer N_c=5;
    parameter Real C_LHV[N_c] = {1,1,1,1,1};
    constant Real defaultComposition[N_c - 1];
  end BaseRecord;

  record ExtendedRecord
    extends BaseRecord(
      N_c=3,
      C_LHV={30769230.769230768,0,-2500e3},
      defaultComposition={0.975,0.025});
  end ExtendedRecord;

  function foo
    input BaseRecord fuelType = ExtendedRecord();
    output Real LHV;
  algorithm
    LHV := 1.2345;
  end foo;

  model SimCenter
    replaceable parameter ExtendedRecord fuelModel1 constrainedby EmptyRecord;
  end SimCenter;

  model Dispatcher
    outer SimCenter simCenter;
    parameter BaseRecord fuelModel = simCenter.fuelModel1;
    final parameter Real LHV = foo(fuelModel);
  end Dispatcher;

  model TestNewBoundaries
    inner SimCenter simCenter;
    Dispatcher dispatcher;
  end TestNewBoundaries;
end DispatcherExample;
```

**Comment by AnHeuermann** [comment] 2022-07-19 13:38
We don't have any equations to find the binding in.
I added a function to collect record types from binding equations of `DAE.CALLS` from the global known variables (parameters and so on).

```
(dispatcher.fuelModel, composite(record{Integer N_c CONST UNBOUND, array(Real)[3] C_LHV PARAM UNBOUND, array(Real)[2] defaultComposition CONST UNBOUND}))
```

And then I called that patch function in Initialization.mo where the equations for the initialization system are created from global known vars.
It's not pretty but it works.

**Comment by casella** [comment] 2022-07-19 13:53
I'm not much into the programming style of the backend, but the regressions on Buildings 8 and master [were all fixed](https://libraries.openmodelica.org/branches/history/master/2022-07-18%2023:12:11..2022-07-19%2011:55:08.html), so we can close this for good.

Thanks @AnHeuermann for the quick feedback!

**Comment by casella** [comment] 2022-07-19 13:58
@AnHeuermann are you looking for a better solution?

**Comment by AnHeuermann** [comment] 2022-07-19 14:00
> @AnHeuermann are you looking for a better solution?

Nope, but the issue itself is concerned with the constants being uninitialized and I haven't fixed that for https://github.com/OpenModelica/OpenModelica/issues/9036#issuecomment-1188748366 yet.

**Comment by casella** [comment] 2022-07-19 14:01
OK, you can close it yourself when that is done.

**Closed** 2022-07-19 16:54 UTC
Labels: COMP/OMC/Backend
