### ISSUE TITLE
Modelica-Buildings Library (master): Simulation fails at initialization

### ISSUE THREAD

**Issue by NehaSPatwardhan** [OpenModelica/OpenModelica#13223] opened 2024-11-15 06:49 UTC
### Description
The solver fails to simulate at initialization.

The following below listed models have same issues:
```
 Buildings.ThermalZones.Detailed.Examples.FFD.NaturalConvectionWithControl 
```
On checking the model in OpenModelica leads to following errors/warnings:
```
Failed to solve linear system of equations (no. 683) at time 0.000000. Residual norm is 2.25601391016567.
The default linear solver fails, the fallback solver with total pivoting is started at time 0.000000. That might raise performance issues, for more information use -lv LOG_LS.
Failed to solve linear system of equations (no. 219) at time 0.000000. Residual norm is 0.636363615108131.
The default linear solver fails, the fallback solver with total pivoting is started at time 0.000000. That might raise performance issues, for more information use -lv LOG_LS.
Failed to copy array. Dimension sizes are not equal and destination array is not flexible.
Failed to solve the initialization problem with global homotopy with equidistant step size.
Unable to solve initialization problem.
simulation terminated by an assertion at initialization
```
The log report of the model is given below:
https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.ThermalZones.Detailed.Examples.FFD.NaturalConvectionWithControl.sim
```
LOG_STDOUT        | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.000000. That might raise performance issues, for more information use -lv LOG_LS.
LOG_STDOUT        | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.000000. That might raise performance issues, for more information use -lv LOG_LS.
GC Warning: Failed to expand heap by -4096 bytes
GC Warning: Out of Memory! Heap size: 0 MiB. Returning NULL!
src->dim_size[0] != dst->dim_size[0], 0 != -1
LOG_ASSERT        | debug   | Failed to copy array. Dimension sizes are not equal and destination array is not flexible.
LOG_ASSERT        | error   | Failed to solve the initialization problem with global homotopy with equidistant step size.
LOG_ASSERT        | debug   | Unable to solve initialization problem.
LOG_ASSERT        | info    | simulation terminated by an assertion at initialization

```
The error report of the model is given below:
https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.ThermalZones.Detailed.Examples.FFD.NaturalConvectionWithControl.err
```
1.Warning: The model contains alias variables with redundant start and/or conflicting nominal values.
 It is recommended to resolve the conflicts, because otherwise the system could be hard to solve.
 To print the conflicting alias sets and the chosen candidates please use -d=aliasConflicts.
```
### Steps to reproduce
Load the Modelica-Buildings master library (Source: https://libraries.openmodelica.org/branches/master/Buildings_latest/Buildings_latest.html)
Simulate the models 
 Buildings.ThermalZones.Detailed.Examples.FFD.NaturalConvectionWithControl 

### Additional Context
Related tickets:#7839,#579

### Expected behavior
The simulation should compile successfully.

### Version and OS
 - OpenModelica Version: OpenModelica 1.25.0~dev-152-g78d9a41
 - OS: 11.1.0ubuntu4
 -  Versions of used Modelica libraries: 
     Modelica 4.0.0
     Buildings 12.0.0

**Comment by casella** [comment] 2024-11-21 08:23
Duplicate of #10074

**Closed** 2024-11-21 08:24 UTC
