### ISSUE TITLE
Assert triggered incorrectly on variable computed with conditional expression

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#6195] opened 2020-06-27 12:26 UTC
This is a placeholder created during migration to preserve original issue numbers.

----

Migrated-From: https://trac.openmodelica.org/OpenModelica/ticket/6195

**Comment by casella** [comment] 2021-11-08 10:55
Opened duplicate of original trac ticket for the [Buildings project](https://github.com/OpenModelica/OpenModelica/projects/1).

**Comment by AnHeuermann** [comment] 2021-11-11 15:43
Here is a minimal working example:

```modelica
loadString("model mwe
  Modelica.Blocks.Sources.Ramp load_y(duration=0.5, startTime=0.2);
  constant Real eps = 1E-10;
equation
  assert(load_y.y<=1+eps, \"load_y.y must be smaller or equal then 1\");
end mwe;"); getErrorString();

simulate(mwe); getErrorString();
```

The assert is it's own equation and is checked each time `mwe_functionDAE()` is called. This happens before the zero-crossing function is called, so the solver doesn't know yet that there is an event to happen.
So I don't see an easy way to suppress asserts, because here we are in continuous time mode and don't know of any events yet.

Maybe we can save the information, that an assert needs to trigger, but continue until after the zero-crossing function. If an event needs to happen we'll do that and forget about the assert. Otherwise we issue an error.
But for this approach we need to rewrite some parts of the assert and error handling wich affects a lot of parts of the runtime.

**Comment by casella** [comment] 2021-11-11 16:12
We can leave with "non-fatal" assert statements popping up here and there, because the solver is somehow too bold and ventures in places which are verboten. What is essential, though, is that these statements should not abort the simulation. They should simply prevent the current step from being accepted. In this specific case, it won't be accepted anyway because the zero-crossing function would report that an event time has been passed already.

Could you just inhibit the termination of the simulation unless the final computations of the accepted step are being performed?

**Comment by AnHeuermann** [comment] 2021-11-11 16:21
I have some idea on how to get around this while suppressing the assert text as well. Maybe we should keep it as a info, though.

Basically I'm introducing an information if we are in a mode where it is allowed to ignore asserts. We switch that on at the beginning of the "find-events" function and switch it off at the end of it. If an assert should have been thrown (is this actually a sensible English statement?) and no event was detected throw an error.

**Comment by casella** [comment] 2021-11-11 16:47
I'm still not 100% sure. Consider this model
```Modelica
model M
  Real x(start = 0, fixed = true);
  parameter Real a = 1e-8;
equation
  der(x) = (1 - tanh((x - 0.5) / a)) / 2;
  assert(x < 0.5 + 1e-6, "x should be <= 0.5");
  annotation(
    experiment(StartTime = 0, StopTime = 1, Tolerance = 0.001, Interval = 0.002),
    __OpenModelica_simulationFlags(lv = "LOG_STATS", noEquidistantTimeGrid = "()", s = "dassl"));
end M;
```
The derivative gets very abruptly (but smoothly) from 1 to zero when x gets close to 0.5. If we simulate with noEquidistantTimeGrid, the first steps are taken at time 0, 0.0035, 0.0075, 0.0315, 0.0635, 0.2555, 0.4455. Then, I see steps at 0.4635, 0.4955, 0.5, 0.500996, 0.503996, 0.507996, 0.515996, 0.531996, 0.0564996, etc.

Clearly, after 0.4455, the ODE solver took another big bold step, bringing x way beyond 0.5. The error estimator clearly went through the roof, and then the solver backtracked and figured out the right steps to go past the sharp (but smooth) change in f(x) while staying within the tolerance limit. In this case the assert was not triggered. 

During this whole process, no assert was triggered, even though I'm 100% sure x went beyond 0.5 in a number of attemped (and rejected) steps. Why is it triggered in the case of event handling, but not here?

**Comment by AnHeuermann** [comment] 2021-11-11 17:43
> During this whole process, no assert was triggered, even though I'm 100% sure x went beyond 0.5 in a number of attemped (and rejected) steps. Why is it triggered in the case of event handling, but not here?

The function `M_functionDAE()` gets only called at initialization and at the terminal event. There are no other events, so the assert won't get checked at `time=0.5`. Maybe that could be an issue, but I was not able to change your example to something that should trigger an assert but won't.

**Comment by casella** [comment] 2021-11-12 00:14
> 
> 
> `mwe` now looks like this:
> 
> ```shell
> record SimulationResult
>     resultFile = "/home/andreas/workspace/Testitesttest/issue-6195/temp/mwe_res.mat",
>     simulationOptions = "startTime = 0.0, stopTime = 1.0, numberOfIntervals = 500, tolerance = 1e-06, method = 'dassl', fileNamePrefix = 'mwe', options = '', outputFormat = 'mat', variableFilter = '.*', cflags = '', simflags = ''",
>     messages = "LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
> stdout            | info    | The following assertion has been violated at time 0.702000
> |                 | |       | load_y.y <= 1.0000000001
> stdout            | info    | The following assertion has been violated at time 0.700000
> |                 | |       | load_y.y <= 1.0000000001
> stdout            | info    | Found event, previous asserts are ignored.
> LOG_SUCCESS       | info    | The simulation finished successfully.
> ",
>     timeFrontend = 0.9417499,
>     timeBackend = 0.0051729,
>     timeSimCode = 0.0016612,
>     timeTemplates = 0.0026529,
>     timeCompile = 0.4232381,
>     timeSimulation = 0.0145042,
>     timeTotal = 1.3890622
> end SimulationResult;
> "
> ```
> 
> We can still remove the messages, but in a case where an assert was triggered but no event was found, we throw later and can't re-throw the assert message.

LGTM

**Comment by casella** [comment] 2021-11-12 00:16
> > During this whole process, no assert was triggered, even though I'm 100% sure x went beyond 0.5 in a number of attemped (and rejected) steps. Why is it triggered in the case of event handling, but not here?
> 
> The function `M_functionDAE()` gets only called at initialization and at the terminal event. There are no other events, so the assert won't get checked at `time=0.5`. Maybe that could be an issue, but I was not able to change your example to something that should trigger an assert but won't.

Yet I cannot understand why this function got called called in the mwe example - when it failed it was not doing initialization or terminal event handling. Why was it ever called? I'm a bit confused.

**Comment by AnHeuermann** [comment] 2021-11-15 10:16
There seem to be some regressions on latest test reports:

For example [this test report](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Obsolete.DistrictHeatingCooling.Validation.HeatingCoolingHotWaterSmall.sim) is for sure affected by 1cbaefaede641a04c749459ab8eca5bdc70a04d6.

There are some asserts as warnings (so they were not ignored) during initialization. Then we have some asserts as info at different times. Because the integrator didn't stop they were triggered during event search and an event was found. 
Then we have an assert at time `7398345.6` where no event was found, so the assert is thrown again.

In the previous version of omc the integrator would re-try the step with half the step sizes. I hoped my code would trigger the same, but apparently I'm not using the exactly same throw function so the integrator doesn't try again with half the step size.

**Comment by AnHeuermann** [comment] 2021-11-15 17:00
I'm debugging in the following model:
```modelica
//installPackage(Buildings, "9.0.0-master", exactMatch=false); getErrorString();
loadModel(Buildings, {"9.0.0-master"}); getErrorString();

cd("temp/"); getErrorString();
simulate(Buildings.Obsolete.DistrictHeatingCooling.Examples.HeatingCoolingHotWater3ClustersBaseCase); getErrorString();
```

We get an assert, but don't throw. Then we want to re-throw the assert later, but that is not cached at the correct location in https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/c/simulation/solver/perform_simulation.c.inc#L552-L554.

Even when I catch the global jump buffer there the `retrySimulationStep()` get's called, but fails in `updateDiscreteSystem`.

I don't think it will change much leaving it at it is now. Only that a non-working simulation fails without a re-try and the error message is bad. But I can't see what I need to change to get the same behavior as before 1cbaefa.

**Comment by sjoelund** [comment] 2021-11-16 06:53
> ```modelica
> //installPackage(Buildings, "9.0.0-master", exactMatch=false); getErrorString();
> loadModel(Buildings, {"9.0.0-master"}); getErrorString();

I use the following when installing/loading master branches. It's quite convenient to not have to remember versions:
```modelica
installPackage(Buildings, "master");
loadModel(Buildings, {"master"});
```

**Comment by AnHeuermann** [comment] 2021-11-16 09:01
@sjoelund You know a bit more about the try-catch we are using in the runtime.

I can't see why it is not working as I'm expecting it to. Basically I have something that looks like:

```C
/* Most outer try block in simulation_runtime.cpp#L718 */
MMC_TRY_INTERNAL(mmc_jumper)
MMC_TRY_INTERNAL(globalJumpBuffer)

    /* Try block in perform_simulation.c.inc#L460 */
    MMC_TRY_INTERNAL(simulationJumpBuffer)
    
    /* Do a lot of stuff */
    prefixedName_updateContinuousSystem(data, threadData);
    
    /* Detect that we need to throw */
    omc_throw(threadData);
    
    MMC_CATCH_INTERNAL(simulationJumpBuffer)

MMC_CATCH_INTERNAL(mmc_jumper)
MMC_CATCH_INTERNAL(globalJumpBuffer)
```

In most cases the `omc_throw` works as expected and I end up in the catch location of `simulationJumpBuffer`. But for the HeatingCoolingHotWater3ClustersBaseCase example we will end up in the `globalJumpBuffer`.
What can influence the omc_throw to jump to different locations?
Where do I need to look in `threadData_t` to see where it will jump to?

**Comment by sjoelund** [comment] 2021-11-16 09:25
> Where do I need to look in `threadData_t` to see where it will jump to?

https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/c/simulation/simulation_omc_assert.c#L75

**Comment by AnHeuermann** [comment] 2021-11-16 11:39
Yeah, I jumped through that with a debugger, bun in both cases it is in the 
```C
  case ERROR_SIMULATION:
    va_errorStreamPrintWithEquationIndexes(LOG_ASSERT, 0, indexes, msg, args);
    longjmp(*threadData->simulationJumpBuffer,1);
    break;
```
case, but ends up in a different catch.
But maybe I did something wrong while debugging it.

**Comment by casella** [comment] 2021-11-21 19:54
> There seem to be some regressions on latest test reports:
> 
> For example [this test report](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Obsolete.DistrictHeatingCooling.Validation.HeatingCoolingHotWaterSmall.sim) is for sure affected by [1cbaefa](https://github.com/OpenModelica/OpenModelica/commit/1cbaefaede641a04c749459ab8eca5bdc70a04d6).

I'm not sure why you say so. This regression report includes [1cbaefa](https://github.com/OpenModelica/OpenModelica/commit/1cbaefaede641a04c749459ab8eca5bdc70a04d6), but I can't see `Buildings.Obsolete.DistrictHeatingCooling.Validation.HeatingCoolingHotWaterSmall` showing up in there.

**Comment by casella** [comment] 2021-11-21 19:55
@AnHeuermann any progress on this issue?

**Comment by AnHeuermann** [comment] 2021-11-22 10:09
The change is not really causing regressions, at least I couldn't see any.
Some models that previously failed with asserts are failing now as well, but don't retry and directly stop the simulation.


It loks somewhat like this (I made up an example).
Before:
```
[ERROR][testAssertFMI] [error][FMU status:Error] fmiCompletedIntegratorStep: terminated by an assertion.
assert            | debug   | fmiCompletedIntegratorStep failed with status : Error
stdout            | warning | Integrator attempt to handle a problem with a called assert.
assert            | warning | The following assertion has been violated at time 0.202853
|                 | |       | x < 1.5
assert            | error   | x is too big at time = 0.202853
[ERROR][testAssertFMI] [error][FMU status:Error] fmiCompletedIntegratorStep: terminated by an assertion.
assert            | debug   | fmiCompletedIntegratorStep failed with status : Error
assert            | warning | The following assertion has been violated at time 0.202853
|                 | |       | x < 1.5
assert            | error   | x is too big at time = 0.202853
[ERROR][testAssertFMI] [error][FMU status:Error] fmiCompletedIntegratorStep: terminated by an assertion.
assert            | debug   | fmiCompletedIntegratorStep failed with status : Error
stdout            | info    | model terminate | Simulation terminated by an assert at time: 0.202853
```

Now:
```
[ERROR][testAssertFMI] [error][FMU status:Error] fmiCompletedIntegratorStep: terminated by an assertion.
assert            | debug   | fmiCompletedIntegratorStep failed with status : Error
stdout            | warning | Integrator attempt to handle a problem with a called assert.
assert            | warning | The following assertion has been violated at time 0.202853
|                 | |       | x < 1.5
assert            | info | x is too big at time = 0.202853
assert            | error   | No event found, but assert was triggered. Throwing now!
```

But as I could not find any regressions and omc is not crashing I would ignore this for now.
@phannebohm Not sure if #7848 is having troubles with this.

**Comment by AnHeuermann** [comment] 2021-11-22 13:56
Closing this for now. If it becomes a problem we should open a new ticket for this.

**Closed** 2021-11-22 13:55 UTC
Labels: bug, COMP/Runtime

**Comment by phannebohm** [comment] 2021-11-22 14:13
> @phannebohm Not sure if #7848 is having troubles with this.

I would guess those are more or less independent problems.

**Comment by casella** [comment] 2021-11-22 15:43
OK. I have to say that "No event found, but assert was triggered. Throwing now!" is not particularly clear to the uninitiated. Specifically:

- I guess "no event found but assert was triggered" means that a condition was triggered (x < 1.5 in this case) but it was in an assert, not in an if- or when-clause. Do I get it right?
- What does "Throwing now!" means? Yeah, I understand that you are throwing an exception when this message is printed on stdout or stderr, but from an end-user perspective this message is a bit puzzling.

Maybe we could make those messages a bit more informative for the layman end-user 😃

**Comment by AnHeuermann** [comment] 2021-11-23 10:11
This ticket is getting overloaded. Let's continue in #8200
