### ISSUE TITLE
Can't use Buildings.BoundaryConditions.SolarIrradiation.DirectTiltedSurface in my models

### ISSUE THREAD

**Issue by n-marci** [OpenModelica/OpenModelica#12548] opened 2024-06-10 16:12 UTC
### Description
When using `Buildings.BoundaryConditions.SolarIrradiation.DirectTiltedSurface` in my model and connecting the input to `Buildings.BoundaryConditions.WeatherData.Bus`, I get the errors:
```
[27] 13:43:20 Translation Error
[Buildings.BoundaryConditions.SolarIrradiation.DirectTiltedSurface: 15:3-18:73]: [Illegal access of protected element incAng.](omeditmessagesbrowser:///Buildings.BoundaryConditions.SolarIrradiation.DirectTiltedSurface?lineNumber=15)

[28] 13:43:20 Translation Error
[vertical_farm: 178:5-179:114]: [Variable plant1.HDirRoo.incAng.weaBus not found in scope airvolume.](omeditmessagesbrowser:///vertical_farm?lineNumber=178)
```

### Steps to reproduce
1. Load Buildings library 11.0.0
2. Make new model `plant`
3. Place `Buildings.BoundaryConditions.SolarIrradiation.DirectTiltedSurface`
4. Place `Buildings.BoundaryConditions.WeatherData.Bus`
5. Connect the weaBus elements
6. Make a second model `airvolume`
7. Place `plant` inside `airvolume`
7. Observe Translation error

### Expected behavior
You should be able to use the DirectTiltedSurface inside of a nested model.

### Version and OS
 - Modelica Buildings Library: 11.0.0
 - OpenModelica 1.23.0~dev.beta.1-1-g379f714
 - Ubuntu 24.04

### Additional context
First reported [here](https://github.com/lbl-srg/modelica-buildings/issues/3872)

> That looks like a problem with the OpenModelica parser.

**Comment by casella** [comment] 2024-06-10 16:48
@n-marci can you please post a test model that reproduces the problem?

**Comment by n-marci** [comment] 2024-06-10 17:05
[bug_report.txt](https://github.com/user-attachments/files/15776681/bug_report.txt)
The error happens when opening the model `plant` or `airvolume`.

**Comment by casella** [comment] 2024-06-10 22:40
@adeas31, please follow the steps from 1. to 5. When trying to connect the weaBus connector to the HDirTil.weaBus connector, which should be connected directly, I get this odd dialog instead:
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/d9bc009f-0305-4a16-9627-3deba489e6e6)

Can you please check why I don't just get a chance to connect the weaBus expandable connector with the HDirTil.weaBus connector?

Not sure if this is an OMEdit issue or inst-based API issue.

**Comment by adeas31** [comment] 2024-06-11 10:28
The dialog is supposed to be shown since you are connecting expandable connectors.

PR #12554 fixes the actual issue reported in the ticket. We were showing the protected components and skipping the extends. Now it goes recursively and lists all the public components.

**Comment by casella** [comment] 2024-06-11 19:07
> The dialog is supposed to be shown since you are connecting expandable connectors.

Sure, but of course the first option should be to connect the top-level expandable connectors together, rather than any sub-component.

> PR #12554 fixes the actual issue reported in the ticket. We were showing the protected components and skipping the extends. Now it goes recursively and lists all the public components.

Sounds good. 

@n-marci can you please test with tomorrow's nightly build?

**Comment by adeas31** [comment] 2024-06-13 11:56
> Sure, but of course the first option should be to connect the top-level expandable connectors together, rather than any sub-component.

Yes. The dialog automatically selects the top level expandable connectors but allow also to add new stuff to expandable connectors and connect with them.

**Comment by n-marci** [comment] 2024-06-13 13:34
Hi the original error is now gone.
However when using as a nested model I still get an error:
```
[1] 13:22:24 Translation Error
[bug_report_2: 18:3-19:84]: [plant1.HDirTil.weaBus is not a valid form for a connector, connectors must be either c1.c2...cn or m.c (where c is a connector and m is a non-connector).](omeditmessagesbrowser:///bug_report_2?lineNumber=18)
```

I can avoid it when specifically choosing to connect plant1.weaBus instead of plant1.HDirTil.weaBus at step 9. The default does not work though.
Here a minimal example: 
[bug_report_2.txt](https://github.com/user-attachments/files/15821278/bug_report_2.txt)


# Steps to reproduce
1. Load Buildings library 11.0.0
2. Make new model plant
3. Place Buildings.BoundaryConditions.SolarIrradiation.DirectTiltedSurface
4. Place Buildings.BoundaryConditions.WeatherData.Bus
5. Connect the weaBus elements
6. Make a second model airvolume
7. Place plant inside airvolume
8. Place Buildings.BoundaryConditions.WeatherData.ReaderTMY3
9. Connect the weatherBus
10. Simulate and observe translation error

# Version and OS
- Modelica Buildings Library: 11.0.0
- OpenModelica 1.24.0~dev-132-g7055b41
- Fedora 40

**Comment by adeas31** [comment] 2024-06-14 10:03
Bit confused now what should be shown in the hierarchy of the expandable connector.
With PR #12579 we list all the expandable connectors including the inherited ones and all the elements inside them.

@n-marci please test with tomorrow's nightly build. Should work fine now.

**Comment by casella** [comment] 2024-06-14 13:37
IMHO when you connect two bus connectors the first choice is just to connect them as a whole. This choice should be at the top of the list. Then you can list the contents, in case one wants to connect to some sub-components.

**Comment by perost** [comment] 2024-06-18 12:18
> [bug_report.txt](https://github.com/user-attachments/files/15776681/bug_report.txt) The error happens when opening the model `plant` or `airvolume`.

With #12608 the invalid access of a protected component error is now ignored by the API used by OMEdit. I'm not sure if just ignoring the error is really the best option, but it's consistent with how we handle e.g. connectors that don't even exist.

But in case it wasn't clear, the model is in fact invalid since `incAng` is protected inside of `DirectTiltedSurface`, so you're not allowed to access it in your models. So you'll still get the error if you e.g. try to simulate the model.

**Comment by adeas31** [comment] 2024-06-18 12:53
Isn't the actual issue solved with #12554. OMEdit allowed creating connection using the protected component but that shouldn't be the case now.

**Comment by perost** [comment] 2024-06-18 12:59
> Isn't the actual issue solved with #12554. OMEdit allowed creating connection using the protected component but that shouldn't be the case now.

In this case the invalid connection already exists in the model.

**Comment by adeas31** [comment] 2024-09-04 12:30
@n-marci please test this again. The issue is already fixed.

**Comment by casella** [comment] 2024-09-13 07:33
I'm going to close this ticket. @n-marci please reopen if you still see some issues.

**Closed by casella** 2024-09-13 07:33 UTC
Labels: COMP/OMC/Frontend
