### ISSUE TITLE
Model Buildings.ThermalZones.EnergyPlus_24_2_0.Examples.SmallOffice.IdealHeatingCoolingSpring fails the simulation due to the coarse tolerance

### ISSUE THREAD

**Issue by AndreaBartolini** [OpenModelica/OpenModelica#13281] opened 2024-11-25 14:29 UTC
The model `Buildings.ThermalZones.EnergyPlus_24_2_0.Examples.SmallOffice.IdealHeatingCoolingSpring` fails the simulation in the CI by rising the following error:
```
LOG_ASSERT        | info    | [/home/hudson/saved_omc/libraries/.openmodelica/libraries/Buildings 12.0.0-master/Media/Air.mo:149:5-150:57:writable]
|                 | |       | The following assertion has been violated at time 7347801.600000
|                 | |       | ((noEvent(flo.att.vol.medium.T >= 200.0))) --> "In IdealHeatingCoolingSpring.flo.att.vol.medium: Temperature T exceeded its minimum allowed value of -73.15 degC (200 Kelvin)
|                 | |       | as required from medium model "Buildings.Media.Air"."
LOG_ASSERT        | error   | No event found, but assert was triggered. Throwing now!
```

The same result is obtained by simulating the model under Win11-Pro (64 bit) - OpenModelica v1.25.0-dev-191-g9288a73aaf (64-bit).

Under Win11 the model simulates successfully by changing the tolerance from the default (`1e-6`) to `1e-7`, the temperature that triggers the `assert` overlaps the same calculated by Dymola by using either the default tolerance (`1e-6`) or the lower tolerance (`1e-7`).

The following figure reports the trend of said temperature:
![image](https://github.com/user-attachments/assets/499987af-8d33-44bd-ae14-18936a4dc9f2)

The initial oscillation that triggers the `assert`@ 7347801s in Omc if the tolerance is `1e-6` is completely dumped (@ the same time) by using the tolerance `1e-7`, probably the default tolerance `1e-6` is coarse for Omc, leading the initial oscillation to be unstable, as depicted in the following trend:
![image](https://github.com/user-attachments/assets/30c12b40-cbf9-4d50-9462-e33f39eae847)

Note that the trend has been obtained by uncheck the `equidistant time grid`, so it should report exactly the solver steps.

The presence of high-frequency numerical oscillations at the beginning of the transient could be a symptom of a not perfect initialization that should be investigated by the modeler.

**Comment by AndreaBartolini** [comment] 2024-11-25 14:54
the same analysis is applicable to the model `Buildings.ThermalZones.EnergyPlus_24_2_0.Examples.SmallOffice.IdealHeatingCoolingSummer`

**Comment by casella** [comment] 2024-11-27 12:57
The problem is now fixed upstream, see lbl-srg/modelica-buildings#4063.

Our package indexing update is currently broken, so we haven't updated the sources for testing since Nov 21. Hence, the problem is still not solved in the [CI report](https://libraries.openmodelica.org/branches/master/Buildings_latest/Buildings_latest.html).

That should be fixed soon.

**Comment by Pavanrajhr** [comment] 2024-12-03 07:40
@casella @AndreaBartolini The models 'Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.IdealHeatingCoolingSpring' and `Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.IdealHeatingCoolingSummer` 
are currently passing.
We can close this ticket.

**Closed** 2024-12-04 16:20 UTC
