### ISSUE TITLE
Missing each when setting start values for arrays with dialog

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#7750] opened 2021-08-10 15:02 UTC
### Description

When changing a start value of an array state variable with a dialog in diagram view in OMEdit and setting it to `true: start value is used to initialize` the resulting model is missing the `each` key word. Because of that the model can't be simulated.

### Steps to Reproduce

Create some model with an array state variable:
```modelica
model TestComp
  parameter Real a[2]={10,5};
  Real x[2](start={0,0}) annotation (Dialog(tab="Setting",showStartAttribute=true));
equation
  der(x[1]) = a[1]*x[1];
  der(x[2]) = a[2]*x[2];
end TestComp;
```

Drag the model `TestComp` into a new model `mwe` using the diagram view in OMEdit.
![image](https://user-images.githubusercontent.com/38031952/128889655-6900efca-1dac-4eab-bfc6-703ff1fbc5dc.png)

Then change the start value of `x` to `{1,2}` with the `Element Parameter` dialog and activate `true: start-value is used to initialize`. 
![image](https://user-images.githubusercontent.com/38031952/128888897-faba0e1d-ee9e-40bc-8935-95178834ebcf.png)

The resulting model will look like:
```modelica
model mwe
  TestComp testComp(x(fixed = true, start = {1, 2}))  annotation(
    Placement(visible = true, transformation(origin = {-2, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
end mwe;
```

Simulating this will result in an error message:
```
[2] 16:56:28 Translation Notification
[mwe: 2:23-2:35]: From here:

[3] 16:56:28 Translation Error
[TestComp: 3:3-3:84]: Non-array modification ‘true‘ for array component ‘fixed‘, possibly due to missing ‘each‘.
```

### Expected Behavior

OMC should detect that the variable `testComp.x` has type array and needs `each`.
The resulting model should have the `each` key word in front of `fixed=true`:
```modelica
model mwe
  TestComp testComp(x(each fixed = true, start = {1, 2}))  annotation(
    Placement(visible = true, transformation(origin = {-2, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
end mwe;
```

### Version and OS

 - OpenModelica Version: OpenModelica v1.18.0-dev-232-g187041202b (64-bit)

**Comment by AnHeuermann** [comment] 2021-08-10 15:13
@adeas31 I guess [ElementProperties.cpp](https://github.com/OpenModelica/OpenModelica/blob/master/OMEdit/OMEditLIB/Element/ElementProperties.cpp) needs to be changed a bit.

**Comment by casella** [comment] 2021-08-22 15:03
Duplicate of [#5405](https://trac.openmodelica.org/OpenModelica/ticket/5045).

There are several such long-standing issues that really need to be resolved - this one is particularly nasty because it generates invalid code that the new front end does not handle. 

@adeas31 do you need changes to the interactive environment to fix this?

**Closed by casella** 2021-08-22 15:03 UTC
Labels: duplicate, COMP/GUI/OMEdit, COMP/OMC/Interactive Environment

**Comment by AnHeuermann** [comment] 2021-08-23 08:17
Sorry, I don't see why this is a duplicate of #5405. This issue has nothing to do with the check, the by OMEdit generated code is simply wrong for arrays.

**Comment by casella** [comment] 2021-08-25 11:19
I had provided the wrong link, sorry. Now it points where it should.

**Comment by adeas31** [comment] 2021-08-25 12:52
If I remember correctly this is because of `updateComponent` api. The interactive environment need to be fixed first.
