### ISSUE TITLE
FMU Export HTML documentation

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#12465] opened 2024-05-24 15:00 UTC
### Description

It would be great that the "header" "info" and "revision" HTML code of a model will be exported to the folder "documentation" and merged in the file "index.html" as follows:

![Screenshot_2024-06-01-23-04-26-482_cn.wps.moffice_eng.xiaomi.lite.png](https://github.com/OpenModelica/OpenModelica/assets/93596576/437f9f50-83b2-4fb0-884f-7e3d71bf1a5e)

It is possible to add this functionality?

**Comment by BasilioPV** [comment] 2024-05-30 18:50
Please find the following example in bot .mo Modelica file and FMU output:

[Test FMU.zip](https://github.com/OpenModelica/OpenModelica/files/15504543/Test.FMU.zip)

**Comment by arun3688** [comment] 2024-06-04 10:28
@BasilioPV Thanks for the example and i will implement this feature

**Comment by BasilioPV** [comment] 2024-06-04 11:32
I suggest that the result looks similar to the "documentation window" on OMedit

**Comment by arun3688** [comment] 2024-06-07 12:26
@BasilioPV the issue is fixed with this commit cf9f18c85d285adb074107eec98ea365046f022c, Please test with nightly builds tomorrow.

**Comment by BasilioPV** [comment] 2024-06-07 12:43
One question, why on fmi_attributes_23.mos file shows the documentation text of the example? It is only an example to show how the documentation set on modelica file (.mo) is copied to the FMU.

**Comment by arun3688** [comment] 2024-06-07 12:52
@BasilioPV the aim of the test case fmi_attributes_23.mos is to generate the fmu with documentation and check whether the index.html is exported to documentation and the we just display the index.html

**Comment by BasilioPV** [comment] 2024-06-08 05:59
@arun3688 Thanks for the work!

I have new features to propose:

When comparing side to side:

<img width="737" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/dc7eae0e-53d4-4cef-b542-e0d57c48d6b5">

I suggest the following:

- Underline the sections name as usual on OMedit ("Information" and "Revisions")
- Include FMU name, and also on italics just below the FMU description.
- It will be also great that on OMedit the model description appears just below component name on italics. Please find the example below:

<img width="864" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/c4625cc4-eb35-43cc-9a07-8bb9c73364a8">

**Comment by arun3688** [comment] 2024-06-10 12:07
> * Include the component "version" on fmiModelDescription->version.

where is this information is put in the modelica model ?

**Comment by casella** [comment] 2024-06-10 12:22
@arun3688 if the version is meant to be the version of the library the component is taken from (or the version of the model itself if it is placed in the top-level scope), I guess you need to look for the corresponding version annotation.

**Comment by BasilioPV** [comment] 2024-06-10 12:50
Regarding the export of the model to FMU, the version that shall be copied to the FMU is the own model version (and not the versions of the libraries from where internal components are used).
On MLS 3.6 (18.8 - Versions) show an example:

<img width="228" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/a65de02a-2371-4e1e-8794-0bebedcad62c">

Where "1.0" should be the version copied to the FMU.

*** Additional Issue: (please advise if I need to open a new ticket):
Why OMedit shows correctly the Documentation window here:

<img width="766" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/c33379f9-edfb-41e1-91de-2d6a636765e1">

And here, all in the same "annotation" sentence not:

<img width="702" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/9d01f5c5-53d6-424e-9e8b-eb29bc8cea7b">

**Comment by arun3688** [comment] 2024-06-10 12:52
@BasilioPV you must open seperate ticket for issues related with `OMEdit`

**Comment by BasilioPV** [comment] 2024-06-10 17:40
Ok, this is the case. Is a standalone model (top-level class) defined only to be exported to FMU.
But, until now you can define "version" in all models into a package in OMedit without errors. OM just ignore this.

**Comment by casella** [comment] 2024-06-10 22:45
According to the MLS [Section 18.8.2](https://specification.modelica.org/maint/3.6/annotations.html#version-handling), version annotations are only defined for top-level classes. I would not use undocumented/non-standard Modelica features to support FMI options. 

Maybe it's best to ask for such version number when generating the FMU?

**Comment by arun3688** [comment] 2024-06-10 22:53
@casella We must just use the standalone version of the model if it is defined and export to FMU as the version of the model in the `modeldescription.xml `, otherwise the version should be just an empty string 

```
model a
annotation(version="1.0.1")
end a;
```

see the fmispecification 

![image](https://github.com/OpenModelica/OpenModelica/assets/6870949/75bef3a5-f32e-41b2-9708-42b3e1452e60)

**Comment by arun3688** [comment] 2024-06-11 13:48
@BasilioPV I have now implemented the proposed features you have asked for with this commit e2c9283809f4c68eddf8064dec2b1120e7529768, Please test it from the nightly builds tomorrow

**Comment by casella** [comment] 2024-06-11 19:10
@BasilioPV if you want to export the FMU from some package with a given version number, you can generate the FMU from

```modelica
model MyFMU
  extends SomePackage.SomePath.SomeModel;
  annotation(version = "x.y.z");
end MyFMU
```

**Comment by BasilioPV** [comment] 2024-06-11 19:31
Ok! That's good!
Thanks a lot for all this work!

**Comment by BasilioPV** [comment] 2024-06-12 07:02
I have tested now and the FMU output is fine! Thanks for the work!
Regarding to OMedit Documentation window:

I't is possible to show the model description just below model name on italics: 

<img width="272" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/cecef26a-b8b7-4372-b275-c59ff4baf0e5">

<img width="164" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/3a5a0367-0f4c-471b-bf05-bb9a849da1e9">

@casella what do you think?

**Comment by arun3688** [comment] 2024-06-12 07:47
@BasilioPV It should be possible to do that in OMEdit, I will look into this

**Comment by arun3688** [comment] 2024-06-12 14:00
@BasilioPV the model description display is fixed with this https://github.com/OpenModelica/OpenModelica/pull/12565, now the documentation of OMEdit looks like this, Please test it from the nightly builds tomorrow(13-6-2024)

![image](https://github.com/OpenModelica/OpenModelica/assets/6870949/2037b0ff-07ef-48c5-b7c3-0eae9867bc32)

**Comment by BasilioPV** [comment] 2024-06-13 16:02
I see changes today. Tomorrow I will test the solution.

**Comment by BasilioPV** [comment] 2024-06-14 12:42
Ok, now all the wanted features was implemented. Please note that description text in OMedit has bold style, while on FMU documentation is on italics. I prefer italics because the bold style can cause confusion with the model name.
But from my side this is acceptable and this issue is closed.

**Comment by arun3688** [comment] 2024-06-14 13:02
> Please note that description text in OMedit has bold style, while on FMU documentation is on italics. I prefer italics because the bold style can cause confusion with the model name.

I had discussion with @adeas31 yesterday and in OMEdit the bold style is used to be consistent with other tools like Dymola, Wolfram etc..

**Comment by BasilioPV** [comment] 2024-08-06 14:21
> @BasilioPV if you want to export the FMU from some package with a given version number, you can generate the FMU from
> 
> ```modelica
> model MyFMU
>   extends SomePackage.SomePath.SomeModel;
>   annotation(version = "x.y.z");
> end MyFMU
> ```

When perform this way of generate a FMU from a library, the FMU description and documentation folder and HTML archive dissapears. Why do not copy these values from the exteded class? It this behaviour good?

**Comment by casella** [comment] 2024-08-07 10:31
> When perform this way of generate a FMU from a library, the FMU description and documentation folder and HTML archive disapears. Why do not copy these values from the exteded class? It this behaviour good?

I guess not. @arun3688 can you please check?

**Comment by arun3688** [comment] 2024-08-28 12:44
> When perform this way of generate a FMU from a library, the FMU description and documentation folder and HTML archive disapears. Why do not copy these values from the exteded class? It this behaviour good?

@BasilioPV I guess no, because what if we have multiple inheritance and then it is not possible to select which Documentation version to use for example

```
model MyFMU
  extends SomePackage.SomePath.SomeModel1;
  extends SomePackage.SomePath.SomeModel2;

  annotation(version = "x.y.z");
end MyFMU
```

**Comment by BasilioPV** [comment] 2024-08-28 13:20
Ok, understood. Issue closed.

**Closed** 2024-08-28 13:20 UTC
Labels: COMP/FMI
