### ISSUE TITLE
Model built under OMEdit v1.19.2 much slower in v1.22.1 than v1.19.2

### ISSUE THREAD

**Issue by JordiGC-UPC** [OpenModelica/OpenModelica#11926] opened 2024-02-01 14:19 UTC
### Version and OS

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by JordiGC-UPC** [comment] 2024-02-01 14:20
I also found the same model built on v1.19.2 was faster than in v1.22.1. Any modification in the arrangement of the objects or the connections generates the same message:

[186] 15:08:52 Scripting Notification
GetFullPathName failed for  with error code 123 

[187] 15:08:54 Scripting Warning
Could not preserve the formatting of the model instead internal pretty-printing algorithm is used.

**Comment by adeas31** [comment] 2024-02-01 14:22
See #11887, #11902 and #11918

**Comment by dershow** [comment] 2024-02-12 20:12
I recently found that the default build is much slower than the Release build.  My understanding is that debug builds typically use lower optimization settings, so the resultant binary are slower (but easier to debug).
I'm not sure what the default settings are for the different build combinations on different architectures.  
For me, on a Mac, adding -DCMAKE_BUILD_TYPE=Release to the cmake command made the resultant binary much faster.

**Comment by casella** [comment] 2024-02-14 17:16
I'm sorry but I'm afraid "same model built on v1.19.2 was faster than in v1.22.1. " is too generic to be really useful. Can you please be more specific: how much faster? Are we talking about code generation, code compilation, runtime execution, graphical editing, ...? Could you provide some working example that we could test?

Thanks

**Comment by JordiGC-UPC** [comment] 2024-02-15 09:35
Ok, yes, I'am sorry for not being more specific. Essentially, I find a very slow response of OMEdit when doing graphical editting. Trying to move icons, change their size, unconnect and connect, add or delete elements from a library or editing parameters in the dialogue boxes last for about 1 minute, even for a simple icon drag and drop movement. And for every single graphical modification, I get the message:

[186] 15:08:52 Scripting Notification
GetFullPathName failed for with error code 123

And sometimes get this:
[187] 15:08:54 Scripting Warning
Could not preserve the formatting of the model instead internal pretty-printing algorithm is used.

Also, whenever I pretend to do a duplicate of an element, OMEdit cannot preserve the value of the original parameters, and I get this message:

[9] 09:41:20 Scripting Error
Unable to set the element modifier value using command setElementModifierValue(...)

All this happens to me in models built with Modelica (v4.0.0) and Buildings Library (v9.1.0) in OMEdit (v1.19.2) launched in OMEdit (v1.22.0). Recently I also migrated to Buildings Library (v10.0.0), and I had to make modifications in the annotation commands to avoid problems when launching my models. 
Concerning compiling and simulating, I do not have any relevant issue in compiling and simulating, maybe slower, but I cannot really tell since I cannot compare quantitatively because I do not have the v1.19.2 version installed anymore...

I do not have problems in graphical edditing in models constructed under v1.22.0 or in v.1.19.2 if they just contain Modelica Standard Library components.

In any case (old and new models, with any component of any library), I still have the issue of not being able to preserve the original parameter values when duplicating a component (see last Scripting Error message, above)

**Comment by adeas31** [comment] 2024-02-15 10:00
> Ok, yes, I'am sorry for not being more specific. Essentially, I find a very slow response of OMEdit when doing graphical editting. Trying to move icons, change their size, unconnect and connect, add or delete elements from a library or editing parameters in the dialogue boxes last for about 1 minute, even for a simple icon drag and drop movement. And for every single graphical modification, I get the message:

The response of OMEdit should be better now since #11887 and #11902 are fixed. You can try the latest nightly build or 1.22.2 (coming out soon).

> 
> [186] 15:08:52 Scripting Notification GetFullPathName failed for with error code 123
> 
> And sometimes get this: [187] 15:08:54 Scripting Warning Could not preserve the formatting of the model instead internal pretty-printing algorithm is used.

There is already a ticket about it #11918 
> 
> Also, whenever I pretend to do a duplicate of an element, OMEdit cannot preserve the value of the original parameters, and I get this message:
> 
> [9] 09:41:20 Scripting Error Unable to set the element modifier value using command setElementModifierValue(...)

Can you please make a new ticket about it and provide a test model.

**Comment by JordiGC-UPC** [comment] 2024-02-15 10:49
Sorry, I just do not see how to upload a .mo file to the issue. It only allow image format files, right? . Is that what you are asking for? What am I missing?

Thanks for helping out

 



    Jordi García Céspedes

    Physicist and Energy engineer

    Enginyeria Minera. Industrial i TIC. 

    Edifici MN1. Despatx 1323

    Av. de les Bases de Manresa, 61-73, 

    08240 Manresa, Catalonia, Spain.

    correu-e:  ***@***.***> ***@***.***

    mòbil: +34 644 352 849

 

P Please consider the environment before printing 

 

De: Adeel Asghar ***@***.***> 
Enviat: dijous, 15 de febrer de 2024 11:01
Per a: OpenModelica/OpenModelica ***@***.***>
A/c: Jordi García-Céspedes ***@***.***>; Mention ***@***.***>
Tema: Re: [OpenModelica/OpenModelica] Model built under OMEdit v1.19.2 much slower in v1.22.1 than v1.19.2 (Issue #11926)

 

Ok, yes, I'am sorry for not being more specific. Essentially, I find a very slow response of OMEdit when doing graphical editting. Trying to move icons, change their size, unconnect and connect, add or delete elements from a library or editing parameters in the dialogue boxes last for about 1 minute, even for a simple icon drag and drop movement. And for every single graphical modification, I get the message:

The response of OMEdit should be better now since #11887 <https://github.com/OpenModelica/OpenModelica/issues/11887>  and #11902 <https://github.com/OpenModelica/OpenModelica/issues/11902>  are fixed. You can try the latest nightly build or 1.22.2 (coming out soon).

[186] 15:08:52 Scripting Notification GetFullPathName failed for with error code 123

And sometimes get this: [187] 15:08:54 Scripting Warning Could not preserve the formatting of the model instead internal pretty-printing algorithm is used.

There is already a ticket about it #11918 <https://github.com/OpenModelica/OpenModelica/issues/11918> 

Also, whenever I pretend to do a duplicate of an element, OMEdit cannot preserve the value of the original parameters, and I get this message:

[9] 09:41:20 Scripting Error Unable to set the element modifier value using command setElementModifierValue(...)

Can you please make a new ticket about it and provide a test model.

**Comment by adeas31** [comment] 2024-02-15 11:04
You can rename the .mo file to .txt and then upload it. Alternatively, you can paste the code as text directly in the comment.

**Comment by casella** [comment] 2024-02-16 00:10
Or make a .zip file of it, that you can drag and drop directly in the comment.

**Comment by JordiGC-UPC** [comment] 2024-02-16 11:03
Hello, today I realised in a much more precise way what really happens. If I try to work on the graphical editing of a submodel while the upper layer (or main model that instantiate the sub-model) is loaded in the Libraries browser, then is when I see this super-slow response in OMEdit v1.22.1. However, it does not happen the other way round. If I have loaded the main model and the submodels, then, the only model that does not show slow response in graphical editting is the main one, let's say, the "top layer". Does it make sense to you?
Therefore, I think it won't be useful to share any test example, since it does no have to do with the model themselves, but with the way OMEdit deals with the different layers of a model.
I realised that through making a duplicate of a submodel in the Libraries Browser. Right after doing so, the duplicate model works fine, but whenever I instantiate this new duplicate from a layer above it (which is already loaded), then it turns slow as the rest when doing graphical editing.
I hope this helps to fix the problem.

**Comment by casella** [comment] 2024-02-16 11:44
Let's hear from @adeas31. I think having a concrete example helps a lot anyway, because we can see which API calls are slow. Otherwise it will mostly be guesswork.

**Comment by adeas31** [comment] 2024-02-16 12:03
I don't think it depends on how the models are loaded. However, it will take more time if you have dependent models opened in the diagram view e.g., if you open model A diagram and then open model B diagram. Update something in B. Now if A depends on B then an update for A is also triggered.

**Comment by JordiGC-UPC** [comment] 2024-02-16 13:19
What @adeas31 describes is exactly what I see. Yes, it does not depend on how the models are loaded, but on the dependence between the ones which are loaded. However, this was not an issue in OMEdit v1.19.2, or at least the process was much faster so I could not perceive it.

**Comment by adeas31** [comment] 2024-06-18 12:07
@AnHeuermann can you please take a look at error `GetFullPathName failed for  with error code 123`? Seems `longabspath` in `omc_file.c` is called with null string. The error code 123 means,

```
ERROR_INVALID_NAME
123 (0x7B)
The filename, directory name, or volume label syntax is incorrect.
```

Load all the provided models and then open the diagram of `DistributionNetworkSimple`.

**Comment by AnHeuermann** [comment] 2024-06-24 12:21
I'll take a look and check if I can reproduce the error and then intercept the error with gdb.

**Comment by AnHeuermann** [comment] 2024-06-24 12:59
longpath is called with an empty wide string `L""` from omc_stat. So `omc_stat` tries to figgure out if a file called `""` exists, and to do so needs the long absolute path of it.

![grafik](https://github.com/OpenModelica/OpenModelica/assets/38031952/d17ab107-ca3a-4317-a73c-7baaf1dced66)

Looks like `OpenModelica_uriToFilename_impl` is doing something wrong for `uri_om=<_OMC_LIT_STRUCT12+3>=""`. That's not an uri at all. The path is coming from [`loadLibraryFunction` NFEvalFunction.mo#L1344](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Compiler/NFFrontEnd/NFEvalFunction.mo#L1344)

So I guess the issue is that there is an empty path passed to `uriToFilename`. In other locations this is prevented by checking `stringEmpty(path)` beforehand.

**Comment by AnHeuermann** [comment] 2024-06-24 12:59
longpath is called with an empty wide string `L""` from omc_stat. So `omc_stat` tries to figgure out if a file called `""` exists, and to do so needs the long absolute path of it.

![grafik](https://github.com/OpenModelica/OpenModelica/assets/38031952/d17ab107-ca3a-4317-a73c-7baaf1dced66)

Looks like `OpenModelica_uriToFilename_impl` is doing something wrong for `uri_om=<_OMC_LIT_STRUCT12+3>=""`. That's not an uri at all. The path is coming from [`loadLibraryFunction` NFEvalFunction.mo#L1344](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Compiler/NFFrontEnd/NFEvalFunction.mo#L1344)

```modelica
  if not found then
    paths := list("  " + Testsuite.friendly(uriToFilename(p)) for p in paths);
    Error.addSourceMessage(Error.EXTERNAL_FUNCTION_NOT_FOUND,
      {fnName, stringDelimitList(paths, "\n")}, info);
    fail();
  end if;
```

So I guess the issue is that there is an empty path passed to `uriToFilename`. In other locations this is prevented by checking `stringEmpty(path)` beforehand.

**Comment by adeas31** [comment] 2024-06-24 13:19
Can you load more stack frames and see where it originated from? Maybe some API function called by OMEdit.

@perost can you please take a look at it?

**Comment by AnHeuermann** [comment] 2024-06-24 13:37
```
libOpenModelicaRuntimeC.dll!OpenModelica_uriToFilename_impl(threadData_t * threadData, modelica_string uri_om, const char * resourcesDir) (d:\workspace\OM\OpenModelica\OMCompiler\SimulationRuntime\c\util\utility.c:316)
libOpenModelicaCompiler.dll!omc_NFEvalFunction_loadLibraryFunction(threadData_t * threadData, modelica_string _libName, modelica_string _fnName, modelica_metatype _extAnnotation, modelica_boolean _debug, modelica_metatype _info) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\NFFrontEnd\NFEvalFunction.mo:1344)
libOpenModelicaCompiler.dll!omc_NFEvalFunction_callExternalFunction(threadData_t * threadData, modelica_string _extName, modelica_metatype _fn, modelica_metatype _args, modelica_metatype _extArgs, modelica_metatype _outputRef, modelica_metatype _extAnnotation, modelica_boolean _debug) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\NFFrontEnd\NFEvalFunction.mo:1165)
libOpenModelicaCompiler.dll!omc_NFEvalFunction_evaluateExternal(threadData_t * threadData, modelica_metatype _fn, modelica_metatype _args, modelica_metatype _target) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\NFFrontEnd\NFEvalFunction.mo:183)
libOpenModelicaCompiler.dll!omc_NFEvalFunction_evaluate(threadData_t * threadData, modelica_metatype _fn, modelica_metatype _args, modelica_metatype _target) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\NFFrontEnd\NFEvalFunction.mo:88)
libOpenModelicaCompiler.dll!omc_NFCeval_evalNormalCall(threadData_t * threadData, modelica_metatype _fn, modelica_metatype _args, modelica_metatype _target) (d:\workspace\OM\OpenModelica\build_cmake\OMCompiler\Compiler\c_files\NFCeval.c:7131)
libOpenModelicaCompiler.dll!omc_NFCeval_evalNormalCallExp(threadData_t * threadData, modelica_metatype _callExp, modelica_metatype _target) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\NFFrontEnd\NFCeval.mo:1980)
libOpenModelicaCompiler.dll!closure6_NFCeval_evalNormalCallExp(threadData_t * thData, modelica_metatype closure, modelica_metatype callExp) (d:\workspace\OM\OpenModelica\build_cmake\OMCompiler\Compiler\c_files\NFCeval.c:7743)
libOpenModelicaCompiler.dll!omc_NFExpression_mapSplitExpressions(threadData_t * threadData, modelica_metatype _exp, modelica_fnptr _func) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\NFFrontEnd\NFExpression.mo:5831)
libOpenModelicaCompiler.dll!omc_NFCeval_evalCall(threadData_t * threadData, modelica_metatype _call, modelica_metatype _target) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\NFFrontEnd\NFCeval.mo:1853)
libOpenModelicaCompiler.dll!omc_NFCeval_evalExp(threadData_t * threadData, modelica_metatype __omcQ_24in_5Fexp, modelica_metatype _target) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\NFFrontEnd\NFCeval.mo:162)
libOpenModelicaCompiler.dll!omc_NFEvalFunction_evaluateAssignment(threadData_t * threadData, modelica_metatype _lhsExp, modelica_metatype _rhsExp, modelica_metatype _source) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\NFFrontEnd\NFEvalFunction.mo:759)
libOpenModelicaCompiler.dll!omc_NFEvalFunction_evaluateStatement(threadData_t * threadData, modelica_metatype _stmt) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\NFFrontEnd\NFEvalFunction.mo:732)
libOpenModelicaCompiler.dll!omc_NFEvalFunction_evaluateStatements(threadData_t * threadData, modelica_metatype _stmts) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\NFFrontEnd\NFEvalFunction.mo:713)
libOpenModelicaCompiler.dll!omc_NFEvalFunction_evaluateNormal(threadData_t * threadData, modelica_metatype _fn, modelica_metatype _args) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\NFFrontEnd\NFEvalFunction.mo:133)
libOpenModelicaCompiler.dll!omc_NFEvalFunction_evaluate(threadData_t * threadData, modelica_metatype _fn, modelica_metatype _args, modelica_metatype _target) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\NFFrontEnd\NFEvalFunction.mo:94)
libOpenModelicaCompiler.dll!omc_NFCeval_evalNormalCall(threadData_t * threadData, modelica_metatype _fn, modelica_metatype _args, modelica_metatype _target) (d:\workspace\OM\OpenModelica\build_cmake\OMCompiler\Compiler\c_files\NFCeval.c:7131)
libOpenModelicaCompiler.dll!omc_NFCeval_evalNormalCallExp(threadData_t * threadData, modelica_metatype _callExp, modelica_metatype _target) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\NFFrontEnd\NFCeval.mo:1980)
libOpenModelicaCompiler.dll!closure6_NFCeval_evalNormalCallExp(threadData_t * thData, modelica_metatype closure, modelica_metatype callExp) (d:\workspace\OM\OpenModelica\build_cmake\OMCompiler\Compiler\c_files\NFCeval.c:7743)
libOpenModelicaCompiler.dll!omc_NFExpression_mapSplitExpressions(threadData_t * threadData, modelica_metatype _exp, modelica_fnptr _func) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\NFFrontEnd\NFExpression.mo:5831)
libOpenModelicaCompiler.dll!omc_NFCeval_evalCall(threadData_t * threadData, modelica_metatype _call, modelica_metatype _target) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\NFFrontEnd\NFCeval.mo:1853)
libOpenModelicaCompiler.dll!omc_NFCeval_evalExp(threadData_t * threadData, modelica_metatype __omcQ_24in_5Fexp, modelica_metatype _target) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\NFFrontEnd\NFCeval.mo:162)
libOpenModelicaCompiler.dll!omc_NFApi_dumpJSONBinding(threadData_t * threadData, modelica_metatype _binding, modelica_metatype _originalBinding, modelica_boolean _evaluate) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\Script\NFApi.mo:1524)
libOpenModelicaCompiler.dll!omc_NFApi_dumpJSONComponent(threadData_t * threadData, modelica_metatype _component, modelica_metatype _originalBinding, modelica_metatype _cls) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\Script\NFApi.mo:1387)
libOpenModelicaCompiler.dll!omc_NFApi_dumpJSONElements(threadData_t * threadData, modelica_metatype _elements, modelica_metatype _scope, modelica_boolean _isDeleted) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\Script\NFApi.mo:1246)
libOpenModelicaCompiler.dll!omc_NFApi_dumpJSONInstanceTree(threadData_t * threadData, modelica_metatype _tree, modelica_metatype _scope, modelica_boolean _root, modelica_boolean _isDeleted) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\Script\NFApi.mo:1120)
libOpenModelicaCompiler.dll!omc_NFApi_dumpJSONComponentType(threadData_t * threadData, modelica_metatype _cls, modelica_metatype _node, modelica_metatype _ty, modelica_boolean _isDeleted) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\Script\NFApi.mo:1418)
libOpenModelicaCompiler.dll!omc_NFApi_dumpJSONComponent(threadData_t * threadData, modelica_metatype _component, modelica_metatype _originalBinding, modelica_metatype _cls) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\Script\NFApi.mo:1375)
libOpenModelicaCompiler.dll!omc_NFApi_dumpJSONElements(threadData_t * threadData, modelica_metatype _elements, modelica_metatype _scope, modelica_boolean _isDeleted) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\Script\NFApi.mo:1246)
libOpenModelicaCompiler.dll!omc_NFApi_dumpJSONInstanceTree(threadData_t * threadData, modelica_metatype _tree, modelica_metatype _scope, modelica_boolean _root, modelica_boolean _isDeleted) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\Script\NFApi.mo:1120)
libOpenModelicaCompiler.dll!omc_NFApi_dumpJSONExtends(threadData_t * threadData, modelica_metatype _ext, modelica_boolean _isDeleted) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\Script\NFApi.mo:1278)
libOpenModelicaCompiler.dll!omc_NFApi_dumpJSONElements(threadData_t * threadData, modelica_metatype _elements, modelica_metatype _scope, modelica_boolean _isDeleted) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\Script\NFApi.mo:1244)
libOpenModelicaCompiler.dll!omc_NFApi_dumpJSONInstanceTree(threadData_t * threadData, modelica_metatype _tree, modelica_metatype _scope, modelica_boolean _root, modelica_boolean _isDeleted) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\Script\NFApi.mo:1120)
libOpenModelicaCompiler.dll!omc_NFApi_dumpJSONComponentType(threadData_t * threadData, modelica_metatype _cls, modelica_metatype _node, modelica_metatype _ty, modelica_boolean _isDeleted) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\Script\NFApi.mo:1418)
libOpenModelicaCompiler.dll!omc_NFApi_dumpJSONComponent(threadData_t * threadData, modelica_metatype _component, modelica_metatype _originalBinding, modelica_metatype _cls) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\Script\NFApi.mo:1375)
libOpenModelicaCompiler.dll!omc_NFApi_dumpJSONElements(threadData_t * threadData, modelica_metatype _elements, modelica_metatype _scope, modelica_boolean _isDeleted) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\Script\NFApi.mo:1246)
libOpenModelicaCompiler.dll!omc_NFApi_dumpJSONInstanceTree(threadData_t * threadData, modelica_metatype _tree, modelica_metatype _scope, modelica_boolean _root, modelica_boolean _isDeleted) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\Script\NFApi.mo:1120)
libOpenModelicaCompiler.dll!omc_NFApi_getModelInstance(threadData_t * threadData, modelica_metatype _classPath, modelica_string _modifier, modelica_boolean _prettyPrint) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\Script\NFApi.mo:902)
libOpenModelicaCompiler.dll!omc_CevalScriptBackend_cevalInteractiveFunctions4(threadData_t * threadData, modelica_metatype _inCache, modelica_metatype _inEnv, modelica_string _inFunctionName, modelica_metatype _inVals, modelica_metatype _msg, modelica_metatype * out_outValue) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\Script\CevalScriptBackend.mo:3066)
libOpenModelicaCompiler.dll!omc_CevalScriptBackend_cevalInteractiveFunctions3(threadData_t * threadData, modelica_metatype _inCache, modelica_metatype _inEnv, modelica_string _inFunctionName, modelica_metatype _inVals, modelica_metatype _msg, modelica_metatype * out_outValue) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\Script\CevalScriptBackend.mo:1737)
libOpenModelicaCompiler.dll!omc_CevalScript_cevalInteractiveFunctions2(threadData_t * threadData, modelica_metatype _cache, modelica_metatype _env, modelica_string _functionName, modelica_metatype _args, modelica_metatype _msg, modelica_metatype * out_outValue) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\Script\CevalScript.mo:1546)
libOpenModelicaCompiler.dll!omc_OpenModelicaScriptingAPI_getModelInstance(threadData_t * threadData, modelica_string _className, modelica_string _modifier, modelica_boolean _prettyPrint) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\Script\OpenModelicaScriptingAPI.mo:645)
OMCInterface::getModelInstance(class OMCInterface * this, class QString className, class QString modifier, modelica_boolean prettyPrint) (d:\workspace\OM\OpenModelica\OMCompiler\Compiler\Script\OpenModelicaScriptingAPIQt.cpp:2351)
OMCProxy::getModelInstance(class OMCProxy * this, const class QString & className, const class QString & modifier, bool prettyPrint, bool icon) (d:\workspace\OM\OpenModelica\OMEdit\OMEditLIB\OMC\OMCProxy.cpp:3568)
ModelWidget::loadModelInstance(class ModelWidget * this, bool icon, const class ModelInfo & modelInfo) (d:\workspace\OM\OpenModelica\OMEdit\OMEditLIB\Modeling\ModelWidgetContainer.cpp:6138)
ModelWidget::loadDiagramViewNAPI(class ModelWidget * this) (d:\workspace\OM\OpenModelica\OMEdit\OMEditLIB\Modeling\ModelWidgetContainer.cpp:6181)
ModelWidgetContainer::addModelWidget(class ModelWidgetContainer * this, class ModelWidget * pModelWidget, bool checkPreferedView) (d:\workspace\OM\OpenModelica\OMEdit\OMEditLIB\Modeling\ModelWidgetContainer.cpp:9493)
LibraryTreeModel::showModelWidget(class LibraryTreeModel * this, class LibraryTreeItem * pLibraryTreeItem, bool show) (d:\workspace\OM\OpenModelica\OMEdit\OMEditLIB\Modeling\LibraryTreeWidget.cpp:1896)
LibraryTreeView::libraryTreeItemDoubleClicked(class LibraryTreeView * this, const class QModelIndex & index) (d:\workspace\OM\OpenModelica\OMEdit\OMEditLIB\Modeling\LibraryTreeWidget.cpp:3339)
LibraryTreeView::qt_static_metacall(class QObject * _o, enum QMetaObject::Call _c, int _id, void ** _a) (d:\workspace\OM\OpenModelica\build_cmake\OMEdit\OMEditLIB\OMEditLib_autogen\IN6LQU4AT7\moc_LibraryTreeWidget.cpp:799)
Qt5Core.dll![Unknown/Just-In-Time compiled code] (Unknown Source:0)
main(int argc, char ** argv) (d:\workspace\OM\OpenModelica\OMEdit\OMEditGUI\main.cpp:192)
```

**Comment by adeas31** [comment] 2024-09-06 09:28
All the issues reported are fixed now.

**Closed by adeas31** 2024-09-06 09:28 UTC
Labels: COMP/GUI/OMEdit
