### ISSUE TITLE
OMEdit doesn't seem to consider choices annotations

### ISSUE THREAD

**Issue by rfranke** [OpenModelica/OpenModelica#7631] opened 2021-06-29 19:08 UTC
The current nightly build of OMEdit 1.18-dev doesn't seem to consider choices annotations. For instance, the model `PowerSystems.AC3ph.Inverters.Rectifier` defines:
```
  replaceable model Rectifier =
    PowerSystems.AC3ph.Inverters.Components.RectifierEquation "rectifier model"
      annotation (choices(
        choice(redeclare model Rectifier =
           PowerSystems.AC3ph.Inverters.Components.RectifierEquation "equation, with losses"),
        choice(redeclare model Rectifier =
           PowerSystems.AC3ph.Inverters.Components.RectifierModular "modular, with losses")));
```
But its use in `PowerSystems.Examples.AC3ph.Inverters.Rectifier`, component `rectifier` shows different choices:

![image](https://user-images.githubusercontent.com/4224368/123852516-afff7c00-d91c-11eb-8425-8d8d1372c368.png)

**Comment by adrpo** [comment] 2021-06-30 08:14
I didn't implemented support for this yet. Is on my list.

**Comment by casella** [comment] 2021-06-30 11:48
Looks like a duplicate of #7487.

**Closed by casella** 2021-06-30 11:48 UTC
Labels: COMP/OMEdit, enhancement
