### ISSUE TITLE
FMU compiles with `OMCv1.21`, but not with `OMCv1.22` or `OMCv1.23`

### ISSUE THREAD

**Issue by JavierArroyoBastida** [OpenModelica/OpenModelica#11411] opened 2023-10-20 14:23 UTC
### Description

When using `ModelicaSystem.convertMo2Fmu` of OMPython it many times does not succeed without throwing any log or error prompt. This makes it very difficult to debug where the issue may be coming from. It'd be great if the error information from the OMC could be passed somehow to the user. 

### Steps to Reproduce
```bash
git clone git@gitlab.kuleuven.be:positive-energy-districts/moped.git
cd moped
git checkout issue130_updateOmc
cd MoPED/Resources/Scripts/tests
make build # This builds a Docker image with all dependencies, included OMC and OMPython
make run # Starts the associated container which is called moped and mounts our Modelica library
docker exec -it moped bash # Get into the container
cd MoPED/Resources/Scripts/fmu # Go to folder with script that compiles FMU
python3 parser.py # Try to compile the FMU model MoPED.Districts.Layout4RC
```

That script basically aims to compile model `MoPED.Districts.Layout4RC` of our library and then parse certain instances in the model. Just FYI: the script invokes the following Python method for the compilation:

```Python
def compile_fmu(model_path, file_name):
    '''Compile the fmu.

    Returns
    -------
    model_path : str
        Path to Modelica class model to be compiled.
    file_name : str
        Path to .mo file with the Modelica model.

    '''

    # COMPILE FMU
    from OMPython import OMCSessionZMQ, ModelicaSystem
    omc = OMCSessionZMQ()
    model = ModelicaSystem(fileName=file_name, modelName=model_path,
                           lmodel=[os.path.join(get_root_path(),'MoPED','package.mo')],
                           commandLineOptions="-d=evaluateAllParameters")
    print('List of defined Modelica class names: {}'.format(omc.sendExpression("getClassNames()")))
    print('Compiling FMU model...')
    fmu_path = model.convertMo2Fmu(version="2.0", fmuType="cs", fileNamePrefix="<default", includeResources=True)
    print("FMU model compiled to: {}".format(fmu_path))

    return fmu_path
```

In the steps above, the compilation works when using the `main` branch (that is, if you skip the third like to checkout `issue130_updateOmc`. In [this merge request](https://gitlab.kuleuven.be/positive-energy-districts/moped/-/merge_requests/128/diffs#1f650494a7ddfa34971e63019077fbd5fbe81327) you can see that the only difference between both branches is that in the main one, we use `OpenModelica 1.21` whereas in the other one we use the nightly `OpenModelica 1.23` version. Note that I've implemented a check with `OpenModelica 1.22` and it does not work either. 

### Expected Behavior

Either the FMU compiles or some error prompt is passed to the user to give an idea of how the issue can be fixed. 

### Screenshots

The output that I get when following the steps above is:
![image](https://github.com/OpenModelica/OMPython/assets/22677958/7afebdc2-af02-4bd8-837d-26c6d656019d)

Notice that the errors shown there take place after the FMU is not being compiled. 

### Version and OS
 - Python Version: `Python 3.10.12`
 - OMPython Version: `OMPython 3.4.0`
 - OpenModelica Version: `OpenModelica 1.23.0~dev-59-g7a41456`
 - OS: `ubuntu:20.04, 64 bit`
 
(These are the versions inside the Docker container environment)

### Additional Context
When the FMU compilation is successful, everything works like a charm, and the compilation of this particular model used to work when using previous versions of the OMC, namely with `OpenModelica 1.21.0-1`. I'm not clear on whether this is an issue with the OMC or with OMPython, so I have opened an issue in OMPython too: https://github.com/OpenModelica/OMPython/issues/177.

**Comment by arun3688** [comment] 2023-10-25 11:06
@JavierArroyoBastida this commit https://github.com/OpenModelica/OMPython/commit/a45ee14ff4ecc4f0bf9a9344b1467b611d624d23 will return you a proper error message, please pull the latest changes from the master. Based on the testing i can confirm that this issue is related with `omc` and not `OMPython` see below


```
>>> from OMPython import ModelicaSystem
>>> mod = ModelicaSystem("C:/OPENMODELICAGIT/moped-main/MoPED/package.mo", "MoPED.Districts.Layout4RC")
>>> mod.simulate()
LOG_STDOUT        | info    | ... loading "data" from "C:\OPENMODELICAGIT\moped-main\MoPED\Resources\Profiles\Household\building0001_FTE_FTE.txt"
LOG_STDOUT        | info    | ... loading "data" from "C:\OPENMODELICAGIT\moped-main\MoPED\Resources\Profiles\Household\building0002_FTE_PTE_School.txt"
LOG_STDOUT        | info    | ... loading "data" from "C:\OPENMODELICAGIT\moped-main\MoPED\Resources\Profiles\Household\building0003_FTE_PTE_School_School.txt"
LOG_STDOUT        | info    | ... loading "data" from "C:\OPENMODELICAGIT\moped-main\MoPED\Resources\CO2Emissions\BE_HourlyEmissionIntensity2021.txt"
LOG_STDOUT        | info    | ... loading "data" from "C:\OPENMODELICAGIT\moped-main\MoPED\Resources\EnergyPrices\BE_Belpex_consumer_2021.txt"
LOG_SUCCESS       | info    | The initialization finished successfully with 3 homotopy steps.
LOG_SUCCESS       | info    | The simulation finished successfully.
>>> mod.convertMo2Fmu()
[C:/OPENMODELICAGIT/OpenModelica/OMCompiler/Compiler/Template/CodegenUtil.tpl:216:14-216:14:writable] Error: Template error: initial value of unknown type: threePortNetwork.V_nominal.
```
However the model successfully simulates it is problem when generating the fmu,  during code generation we are getting unknow type for the following variable `Template error: initial value of unknown type: threePortNetwork.V_nominal.  
`
and looking into the code we support the following types

```
template initValXml(Exp exp)
::=
  match exp
  case ICONST(__) then integer
  case RCONST(__) then real
  case SCONST(__) then '<%Util.escapeModelicaStringToXmlString(string)%>'
  case BCONST(__) then if bool then "true" else "false"
  case ENUM_LITERAL(__) then '<%index%>'
  else error(sourceInfo(), 'initial value of unknown type: <%dumpExp(exp,"\"")%>')
end initValXml;
```
I will continue to debug more and update the status

**Comment by arun3688** [comment] 2023-10-25 11:12
looking into the `_init.xml`, the variable `threePortNetwork.V_nominal` is of type Real  it looks fine, something is happening when converting to fmu i guess

```
  <ScalarVariable
    name = "threePortNetwork.V_nominal"
    valueReference = "12045"
    description = "Nominal voltage of the line"
    variability = "parameter" isDiscrete = "true"
    causality = "calculatedParameter" isValueChangeable = "false"
    alias = "noAlias"
    classIndex = "7468" classType = "rPar"
    isProtected = "false" hideResult = "" initNonlinear = "false"
    fileName = "C:/OPENMODELICAGIT/moped-main/MoPED/Networks/Electric/TinyCluster/ThreePortNetwork.mo" startLine = "5" startColumn = "3" endLine = "6" endColumn = "34" fileWritable = "true">
    <Real fixed="true" useNominal="true" nominal="230.0" min="0.0" unit="V" />
  </ScalarVariable>
```

**Comment by JavierArroyoBastida** [comment] 2023-10-25 11:28
@arun3688 thanks a ton for looking into this. Outputting the error string will help a lot not only for this issue but in general for future usage of `OMPython`. 
Here you have the location where that variable is declared in case it's of any help: 
https://gitlab.kuleuven.be/positive-energy-districts/moped/-/blob/main/MoPED/Networks/Electric/TinyCluster/ThreePortNetwork.mo#L5

**Comment by casella** [comment] 2023-10-26 16:28
@JavierArroyoBastida can you try with tomorrow's nightly build if @arun3688's PR fixed the issue for you?

**Comment by JavierArroyoBastida** [comment] 2023-10-26 16:33
Sure, tomorrow I'll give it a try and let you know how it goes. Thanks a lot for the fast response!

**Comment by arun3688** [comment] 2023-10-26 19:34
@JavierArroyoBastida the PR is merged into master and the issue is fixed now, please test from the nightly builds tomorrow and see if it works for you as well.

**Comment by JavierArroyoBastida** [comment] 2023-10-27 07:55
I've tested with the latest nightly build (`1.23.0~dev-97-g7e09cdd-1`) but I'm getting a different error now:
![errormsg](https://github.com/OpenModelica/OpenModelica/assets/22677958/ae6792dd-cb7e-47f9-8cfe-c4ac54b533a6)

I've just followed the [steps above](https://github.com/OpenModelica/OpenModelica/issues/11411#issue-1954402468) which builds the environment image using the latest omc version (see [here](https://gitlab.kuleuven.be/positive-energy-districts/moped/-/commit/7c7235a24470b3296e5de71133bb34b3f78d557b) for the change and [here](https://gitlab.kuleuven.be/positive-energy-districts/moped/-/jobs/891105#L88) for the full error log).

**Comment by arun3688** [comment] 2023-10-27 08:35
@JavierArroyoBastida I see that you are using pyfmi and the errors are related to your python script, based on the above error message i see that `load_fmu()` could not load the fmu from the path you specified. see the error message properly, The important  thing is,  can you check whether you could generate the fmu from the latest nightly build either from OMPython or directly in OpenModelica, I tested from OMPython and it works


```
>>> from OMPython import ModelicaSystem
>>> mod = ModelicaSystem("C:/OPENMODELICAGIT/moped-main/MoPED/package.mo", "MoPED.Districts.Layout4RC")
>>> mod.convertMo2Fmu()
'C:/Users/arupa54/AppData/Local/Temp/tmpj0hn1ac8/MoPED.Districts.Layout4RC.fmu'
```

Please adjust the fmu path according to your location

**Comment by JavierArroyoBastida** [comment] 2023-10-27 09:41
The fmu is not generated (error log shows: `FMU model compiled to: None` where `None` is the output of `model.convertMo2Fmu`) which is what causes the error of pyfmi that is not being able to find it. 
Now that I see your commands I was expecting that the difference was coming from the flags I was using to evaluateAllParameters, includeResources and compile for cosimulation:

```Python
model = ModelicaSystem(fileName=file_name, modelName=model_path,
                           lmodel=[os.path.join(get_root_path(),'MoPED','package.mo')],
                           commandLineOptions="-d=evaluateAllParameters")
fmu_path = model.convertMo2Fmu(version="2.0", fmuType="cs", fileNamePrefix="<default", includeResources=True)
print("FMU model compiled to: {}".format(fmu_path))
```

Unfortunately that's not the case. I've tried to reproduce exactly your commands in Python (without running the full script) but without success. I do:

```Python
from OMPython import ModelicaSystem
mod = ModelicaSystem("package.mo", "MoPED.Districts.Layout4RC")
mod.convertMo2Fmu()
```

and the output is:

```
[/home/developer/.openmodelica/libraries/Buildings 9.1.1/Electrical/Interfaces/Load.mo:19:3-22:28:writable] Warning: Parameter V_nominal has annotation(Evaluate=true) and no binding.
[/home/developer/.openmodelica/libraries/IDEAS 3.0.0/BoundaryConditions/Interfaces/PartialSimInfoManager.mo:151:3-154:55:writable] Warning: Connector weaBus is not balanced: The number of potential variables (20) is not equal to the number of flow variables (0).
[/home/developer/moped/MoPED/BoundaryConditions/Occupancy/OccSimInfoManager.mo:21:2-27:22:writable] Warning: Connector occBus is not balanced: The number of potential variables (7) is not equal to the number of flow variables (0).
[/home/developer/.openmodelica/libraries/IDEAS 3.0.0/BoundaryConditions/Interfaces/PartialSimInfoManager.mo:151:3-154:55:writable] Warning: Connector weaBus is not balanced: The number of potential variables (20) is not equal to the number of flow variables (0).
[/home/developer/moped/MoPED/Agents/Demand/BuildingAgents/HVAC/BaseClasses/PartialHvac.mo:41:3-44:72:readonly] Warning: Conditional component 'nAirPorts' is used in a non-connect context.
[/home/developer/moped/MoPED/Agents/Demand/BuildingAgents/HVAC/BaseClasses/PartialHvac.mo:45:3-48:70:readonly] Warning: Conditional component 'nAirPorts' is used in a non-connect context.
[/home/developer/moped/MoPED/BoundaryConditions/Occupancy/OccSimInfoManager.mo:21:2-27:22:writable] Warning: Connector occBus is not balanced: The number of potential variables (7) is not equal to the number of flow variables (0).
[/home/developer/.openmodelica/libraries/IDEAS 3.0.0/BoundaryConditions/Interfaces/PartialSimInfoManager.mo:151:3-154:55:writable] Warning: Connector weaBus is not balanced: The number of potential variables (20) is not equal to the number of flow variables (0).
[/home/developer/moped/MoPED/Agents/Demand/BuildingAgents/HVAC/BaseClasses/PartialHvac.mo:41:3-44:72:readonly] Warning: Conditional component 'nAirPorts' is used in a non-connect context.
[/home/developer/moped/MoPED/Agents/Demand/BuildingAgents/HVAC/BaseClasses/PartialHvac.mo:45:3-48:70:readonly] Warning: Conditional component 'nAirPorts' is used in a non-connect context.
[/home/developer/moped/MoPED/BoundaryConditions/Occupancy/OccSimInfoManager.mo:21:2-27:22:writable] Warning: Connector occBus is not balanced: The number of potential variables (7) is not equal to the number of flow variables (0).
[/home/developer/.openmodelica/libraries/IDEAS 3.0.0/BoundaryConditions/Interfaces/PartialSimInfoManager.mo:151:3-154:55:writable] Warning: Connector weaBus is not balanced: The number of potential variables (20) is not equal to the number of flow variables (0).
[/home/developer/moped/MoPED/Agents/Demand/BuildingAgents/HVAC/BaseClasses/PartialHvac.mo:41:3-44:72:readonly] Warning: Conditional component 'nAirPorts' is used in a non-connect context.
[/home/developer/moped/MoPED/Agents/Demand/BuildingAgents/HVAC/BaseClasses/PartialHvac.mo:45:3-48:70:readonly] Warning: Conditional component 'nAirPorts' is used in a non-connect context.
[/home/developer/moped/MoPED/BoundaryConditions/CO2Emissions/EmissionsSimInfoManager.mo:21:3-27:26:writable] Warning: Connector co2Bus is not balanced: The number of potential variables (1) is not equal to the number of flow variables (0).
[/home/developer/moped/MoPED/BoundaryConditions/EnergyPrices/EnergyPricesInfoManager.mo:5:3-12:26:readonly] Warning: Connector priceBus is not balanced: The number of potential variables (6) is not equal to the number of flow variables (0).
[/home/developer/moped/MoPED/Electrical/Converters/Inverter.mo:15:41-15:52:readonly] Warning: Conditional component 'Vscale' is used in a non-connect context.
Warning: The model contains alias variables with redundant start and/or conflicting nominal values. It is recommended to resolve the conflicts, because otherwise the system could be hard to solve. To print the conflicting alias sets and the chosen candidates please use -d=aliasConflicts.
[/home/developer/.openmodelica/libraries/Buildings 9.1.1/Electrical/Transmission/BaseClasses/PartialBaseLine.mo:6:3-7:34:writable] Warning: Parameter threePortNetwork.l23.V_nominal has no value, and is fixed during initialization (fixed=true), using available start value (start=threePortNetwork.V_nominal) as default value.
[/home/developer/.openmodelica/libraries/Buildings 9.1.1/Electrical/Transmission/BaseClasses/PartialBaseLine.mo:6:3-7:34:writable] Warning: Parameter threePortNetwork.l12.V_nominal has no value, and is fixed during initialization (fixed=true), using available start value (start=threePortNetwork.V_nominal) as default value.
[/home/developer/.openmodelica/libraries/Buildings 9.1.1/Electrical/Transmission/BaseClasses/PartialBaseLine.mo:6:3-7:34:writable] Warning: Parameter threePortNetwork.gridLine.V_nominal has no value, and is fixed during initialization (fixed=true), using available start value (start=threePortNetwork.V_nominal) as default value.
[/home/developer/.openmodelica/libraries/Buildings 9.1.1/Electrical/Interfaces/Load.mo:19:3-22:28:writable] Warning: Parameter house3.P2AC.load.V_nominal has no value, and is fixed during initialization (fixed=true), using available start value (start=230.0) as default value.
[/home/developer/.openmodelica/libraries/Buildings 9.1.1/Electrical/Interfaces/Load.mo:19:3-22:28:writable] Warning: Parameter house2.P2AC.load.V_nominal has no value, and is fixed during initialization (fixed=true), using available start value (start=230.0) as default value.
[/home/developer/.openmodelica/libraries/Buildings 9.1.1/Electrical/Interfaces/Load.mo:19:3-22:28:writable] Warning: Parameter house1.P2AC.load.V_nominal has no value, and is fixed during initialization (fixed=true), using available start value (start=230.0) as default value.
Warning: The initial conditions are not fully specified. For more information set -d=initialization. In OMEdit Tools->Options->Simulation->Show additional information from the initialization process, in OMNotebook call setCommandLineOptions("-d=initialization").
Warning: There are tearing variables with annotation attribute 'tearingSelect = never'. Use -d=tearingdump and -d=tearingdumpV for more information.
Error: Error building simulator. Build log: /bin/sh: 1: cmake: not found
```

which is almost the same error except for the first line which is slightly different, I believe because now I'm compiling for `me` instead of `cs`.  

Then I ensure that I'm using the latest nightly build by exiting Python and doing: 

```bash
developer@251c37f4a2ff:~/moped/MoPED$ omc --version
OpenModelica 1.23.0~dev-97-g7e09cdd
```

I'm sorry but at this point I can't figure what's different. I'll come back if I can think of something.

**Comment by arun3688** [comment] 2023-10-27 09:48
@JavierArroyoBastida i suspect this is a problem related with omc i guess, may be the omc is corrupted , to verify that can you just  create a file called `a.mos` and run it with `omc `, see below

### a.mos
```
loadFile("C:/OPENMODELICAGIT/moped-main/MoPED/package.mo");
getErrorString();

buildModelFMU(MoPED.Districts.Layout4RC);
getErrorString();
```
you can run it as 
`>>> omc a.mos`

If this does not work, it means there is a problem with the omc installed may be multiple version exists, I suggest you to uninstall older versions and install a clean one,  The other thing you can do is, test whether you can simulate the model direclty in omc which can tell us some clue.

**Comment by mahge** [comment] 2023-10-27 09:52
> Error: Error building simulator. Build log: /bin/sh: 1: cmake: not found

There is also this. I am not sure about the details of how `OMPython` uses `omc` but it looks like the CMake executable needed to compile the generated FMU sources is not not found on your machine.

**Comment by JavierArroyoBastida** [comment] 2023-10-27 09:59
Running `a.mos` does not work either:
```
developer@e35101255bcf:~/moped/MoPED$ omc a.mos
true
"Notification: Automatically loaded package Modelica 4.0.0 due to uses annotation from MoPED.
Notification: Automatically loaded package Complex 4.0.0 due to uses annotation from Modelica.
Notification: Automatically loaded package ModelicaServices 4.0.0 due to uses annotation from Modelica.
Notification: Automatically loaded package Buildings 9.1.1 due to uses annotation from MoPED.
Notification: Automatically loaded package IDEAS 3.0.0 due to uses annotation from MoPED.
"
""
"[/home/developer/.openmodelica/libraries/Buildings 9.1.1/Electrical/Interfaces/Load.mo:19:3-22:28:writable] Warning: Parameter V_nominal has annotation(Evaluate=true) and no binding.
[/home/developer/.openmodelica/libraries/IDEAS 3.0.0/BoundaryConditions/Interfaces/PartialSimInfoManager.mo:151:3-154:55:writable] Warning: Connector weaBus is not balanced: The number of potential variables (20) is not equal to the number of flow variables (0).
[/home/developer/moped/MoPED/BoundaryConditions/Occupancy/OccSimInfoManager.mo:21:2-27:22:writable] Warning: Connector occBus is not balanced: The number of potential variables (7) is not equal to the number of flow variables (0).
[/home/developer/.openmodelica/libraries/IDEAS 3.0.0/BoundaryConditions/Interfaces/PartialSimInfoManager.mo:151:3-154:55:writable] Warning: Connector weaBus is not balanced: The number of potential variables (20) is not equal to the number of flow variables (0).
[/home/developer/moped/MoPED/Agents/Demand/BuildingAgents/HVAC/BaseClasses/PartialHvac.mo:41:3-44:72:readonly] Warning: Conditional component 'nAirPorts' is used in a non-connect context.
[/home/developer/moped/MoPED/Agents/Demand/BuildingAgents/HVAC/BaseClasses/PartialHvac.mo:45:3-48:70:readonly] Warning: Conditional component 'nAirPorts' is used in a non-connect context.
[/home/developer/moped/MoPED/BoundaryConditions/Occupancy/OccSimInfoManager.mo:21:2-27:22:writable] Warning: Connector occBus is not balanced: The number of potential variables (7) is not equal to the number of flow variables (0).
[/home/developer/.openmodelica/libraries/IDEAS 3.0.0/BoundaryConditions/Interfaces/PartialSimInfoManager.mo:151:3-154:55:writable] Warning: Connector weaBus is not balanced: The number of potential variables (20) is not equal to the number of flow variables (0).
[/home/developer/moped/MoPED/Agents/Demand/BuildingAgents/HVAC/BaseClasses/PartialHvac.mo:41:3-44:72:readonly] Warning: Conditional component 'nAirPorts' is used in a non-connect context.
[/home/developer/moped/MoPED/Agents/Demand/BuildingAgents/HVAC/BaseClasses/PartialHvac.mo:45:3-48:70:readonly] Warning: Conditional component 'nAirPorts' is used in a non-connect context.
[/home/developer/moped/MoPED/BoundaryConditions/Occupancy/OccSimInfoManager.mo:21:2-27:22:writable] Warning: Connector occBus is not balanced: The number of potential variables (7) is not equal to the number of flow variables (0).
[/home/developer/.openmodelica/libraries/IDEAS 3.0.0/BoundaryConditions/Interfaces/PartialSimInfoManager.mo:151:3-154:55:writable] Warning: Connector weaBus is not balanced: The number of potential variables (20) is not equal to the number of flow variables (0).
[/home/developer/moped/MoPED/Agents/Demand/BuildingAgents/HVAC/BaseClasses/PartialHvac.mo:41:3-44:72:readonly] Warning: Conditional component 'nAirPorts' is used in a non-connect context.
[/home/developer/moped/MoPED/Agents/Demand/BuildingAgents/HVAC/BaseClasses/PartialHvac.mo:45:3-48:70:readonly] Warning: Conditional component 'nAirPorts' is used in a non-connect context.
[/home/developer/moped/MoPED/BoundaryConditions/CO2Emissions/EmissionsSimInfoManager.mo:21:3-27:26:writable] Warning: Connector co2Bus is not balanced: The number of potential variables (1) is not equal to the number of flow variables (0).
[/home/developer/moped/MoPED/BoundaryConditions/EnergyPrices/EnergyPricesInfoManager.mo:5:3-12:26:readonly] Warning: Connector priceBus is not balanced: The number of potential variables (6) is not equal to the number of flow variables (0).
[/home/developer/moped/MoPED/Electrical/Converters/Inverter.mo:15:41-15:52:readonly] Warning: Conditional component 'Vscale' is used in a non-connect context.
Warning: The model contains alias variables with redundant start and/or conflicting nominal values. It is recommended to resolve the conflicts, because otherwise the system could be hard to solve. To print the conflicting alias sets and the chosen candidates please use -d=aliasConflicts.
[/home/developer/.openmodelica/libraries/Buildings 9.1.1/Electrical/Transmission/BaseClasses/PartialBaseLine.mo:6:3-7:34:writable] Warning: Parameter threePortNetwork.l23.V_nominal has no value, and is fixed during initialization (fixed=true), using available start value (start=threePortNetwork.V_nominal) as default value.
[/home/developer/.openmodelica/libraries/Buildings 9.1.1/Electrical/Transmission/BaseClasses/PartialBaseLine.mo:6:3-7:34:writable] Warning: Parameter threePortNetwork.l12.V_nominal has no value, and is fixed during initialization (fixed=true), using available start value (start=threePortNetwork.V_nominal) as default value.
[/home/developer/.openmodelica/libraries/Buildings 9.1.1/Electrical/Transmission/BaseClasses/PartialBaseLine.mo:6:3-7:34:writable] Warning: Parameter threePortNetwork.gridLine.V_nominal has no value, and is fixed during initialization (fixed=true), using available start value (start=threePortNetwork.V_nominal) as default value.
[/home/developer/.openmodelica/libraries/Buildings 9.1.1/Electrical/Interfaces/Load.mo:19:3-22:28:writable] Warning: Parameter house3.P2AC.load.V_nominal has no value, and is fixed during initialization (fixed=true), using available start value (start=230.0) as default value.
[/home/developer/.openmodelica/libraries/Buildings 9.1.1/Electrical/Interfaces/Load.mo:19:3-22:28:writable] Warning: Parameter house2.P2AC.load.V_nominal has no value, and is fixed during initialization (fixed=true), using available start value (start=230.0) as default value.
[/home/developer/.openmodelica/libraries/Buildings 9.1.1/Electrical/Interfaces/Load.mo:19:3-22:28:writable] Warning: Parameter house1.P2AC.load.V_nominal has no value, and is fixed during initialization (fixed=true), using available start value (start=230.0) as default value.
Warning: The initial conditions are not fully specified. For more information set -d=initialization. In OMEdit Tools->Options->Simulation->Show additional information from the initialization process, in OMNotebook call setCommandLineOptions(\"-d=initialization\").
Error: Error building simulator. Build log: /bin/sh: 1: cmake: not found
"
```
I'm installing OMC in a Docker container so there should be only one omc version. However, it might have happened that the Docker cache is messing up with previous builds somehow so I'll rebuild without cache and let you know how that goes. 

@mahge thanks a lot for the idea! but I think `OMPython` is discarded since the `a.mos` file is not using it and I keep getting the same error.

**Comment by arun3688** [comment] 2023-10-27 10:01
@JavierArroyoBastida So now it is clear that `omc` installation has some problem, fixing the omc, will solve the issue automatically

**Comment by mahge** [comment] 2023-10-27 10:03
> developer@e35101255bcf:~/moped/MoPED$ omc a.mos

It does look like a general omc related issue. Where are you running this command? Is it on a Windows CMD or Powershell? If so that might be the problem here since we expect things to run in an MSYS shell.

**Comment by mahge** [comment] 2023-10-27 10:04
Ahh never mind. You are actually on Ubuntu 🙂. You just need to install CMake. It is required by OpenModelica.

**Comment by arun3688** [comment] 2023-10-27 10:05
@mahge he is running inside the docker container, may be he should install `cmake` to the docker container

**Comment by JavierArroyoBastida** [comment] 2023-10-27 10:48
Yes I'm using Ubunto and define my environment in a [Dockerfile](https://gitlab.kuleuven.be/positive-energy-districts/moped/-/blob/issue130_updateOmc/MoPED/Resources/Scripts/tests/Dockerfile?ref_type=heads). I'm installing `cmake` now [here](https://gitlab.kuleuven.be/positive-energy-districts/moped/-/blob/issue130_updateOmc/MoPED/Resources/Scripts/tests/Dockerfile?ref_type=heads#L20) and that has fixed the issue. Thank you VERY MUCH for your fast and effective support! 👍

**Comment by arun3688** [comment] 2023-10-27 11:08
@JavierArroyoBastida Great it worked, I am closing this issue, if you face further issue please open a new issue

**Closed by arun3688** 2023-10-27 11:08 UTC
