### ISSUE TITLE
Severe Problem with Event Generation

### ISSUE THREAD

**Issue by AHaumer** [OpenModelica/OpenModelica#8262] opened 2021-12-05 22:32 UTC
Please have a look at the enclosed models which are boiled down from a model of an incremental encoder, which should generate a series of Boolean pulses dependent on the angle phi:
Yes uses an intermediate varable to compare w.r.t. pi -> events are generated.
WhyNot uses the expression (as used for the intermediate variable) to compare w.r.t pi -> no events are generated.
It seems that the expression suppresses the event generation of the comparison.
Zoom into the trajectories of the result y:
From Yes, the edges of y are infinitely steep while from WhyNot, the edges are "smoothed".
![GenerateEvent](https://user-images.githubusercontent.com/6900273/144766547-87ca6a18-1c0d-47c1-a825-cdb9bd2b2c82.png)
OM v1.18.0 (64bit)
OS Windows 10 (64bit)
MSL 4.0.0
[GenerateEvent.zip](https://github.com/OpenModelica/OpenModelica/files/7656946/GenerateEvent.zip)

**Comment by AnHeuermann** [comment] 2021-12-06 11:39
Duplicate of https://github.com/OpenModelica/OpenModelica/issues/8090 and should be fixed with  https://github.com/OpenModelica/OpenModelica/pull/8138.

@AHaumer Could you try again with the nightly build?

**Comment by casella** [comment] 2021-12-06 19:29
> Duplicate of #8090 and should already be fixed with #8138.

It seems this is not the case, I tried @AHaumer's test case with v1.19.0-dev-429-g962c2112c3, which should contain #8138, and I still get this behaviour:
![immagine](https://user-images.githubusercontent.com/4233148/144909621-a3bd02d1-701b-4491-955f-a4701bc94976.png)

**Comment by AnHeuermann** [comment] 2021-12-07 09:16
Not sure what exactly is the difference to #8090. Maybe because `y` it is a boolean variable.

Check out the following minimal example:
```Modelica
model mwe
  Real x(start=1);
  Boolean y;
equation
  x = exp(2*time);
  y = mod(x, 2)<=1;
end mwe;
```
![image](https://user-images.githubusercontent.com/38031952/145000454-0232dcdb-21be-416e-b54d-d4ecbcc80230.png)

From `-lv=LOG_EVENTS`:
```
LOG_EVENTS        | info    | state event at time=0.34657359028
|                 | |       | | [1] mod(x, 2.0, 0)
LOG_EVENTS        | info    | state event at time=0.69314718056
|                 | |       | | [1] mod(x, 2.0, 0)
LOG_EVENTS        | info    | state event at time=0.895879734615
|                 | |       | | [1] mod(x, 2.0, 0)
```

I guess I need to check the zero-crossing functions.

**Comment by phannebohm** [comment] 2022-02-11 17:24
Thanks to the MWE by @AnHeuermann I was able to identify the problem.
The operators `div`, `mod` and `rem` were falsely categorized as returning discrete values. That means any relation like `mod(x,const) < const` was regarded as not being able to produce an event. This is obviously wrong behavior, so I opened #8537 to address this.

**Closed** 2022-02-11 18:14 UTC
Labels: bug, COMP/Backend

**Comment by casella** [comment] 2022-02-12 00:16
Very good, nice job!

I guess this may also fix some pending issues with MSL verification. We'll see tomorrows regression report.

**Comment by casella** [comment] 2022-02-12 17:42
> I guess this may also fix some pending issues with MSL verification. We'll see tomorrows regression report.

Hmm, [not really](https://libraries.openmodelica.org/branches/history/master/2022-02-11%2011:23:50..2022-02-11%2022:23:29.html). Anyway, it needed to be fixed.
