### ISSUE TITLE
Modelica-Buildings Library (master): Simulation fails at initialization

### ISSUE THREAD

**Issue by NehaSPatwardhan** [OpenModelica/OpenModelica#13238] opened 2024-11-18 06:32 UTC
### Description

The solver fails to simulate at initialization.

The given model is having this issue:
```
Buildings.ThermalZones.Detailed.Examples.FFD.Tutorial.NaturalConvection
```
On simulating the model in OpenModelica leads to following errors/warnings:
```
1.Failed to solve linear system of equations (no. 221) at time 0.000000. Residual norm is 0.636363615108131.
2.The default linear solver fails, the fallback solver with total pivoting is started at time 0.000000. That might raise performance issues, for more information use -lv LOG_LS.
3.Failed to copy array. Dimension sizes are not equal and destination array is not flexible.
4.Failed to solve the initialization problem with global homotopy with equidistant step size.
5.Unable to solve initialization problem.
6.simulation terminated by an assertion at initialization

```

The log report of the model is given below:
https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.ThermalZones.Detailed.Examples.FFD.Tutorial.NaturalConvection.sim
```
LOG_STDOUT        | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.000000. That might raise performance issues, for more information use -lv LOG_LS.
LOG_STDOUT        | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.000000. That might raise performance issues, for more information use -lv LOG_LS.
GC Warning: Failed to expand heap by -4096 bytes
GC Warning: Out of Memory! Heap size: 0 MiB. Returning NULL!
src->dim_size[0] != dst->dim_size[0], 0 != -1
LOG_ASSERT        | debug   | Failed to copy array. Dimension sizes are not equal and destination array is not flexible.
LOG_ASSERT        | error   | Failed to solve the initialization problem with global homotopy with equidistant step size.
LOG_ASSERT        | debug   | Unable to solve initialization problem.
LOG_ASSERT        | info    | simulation terminated by an assertion at initialization

```

The error report of the model is given below:
https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.ThermalZones.Detailed.Examples.FFD.Tutorial.NaturalConvection.err
```
1.Warning: The model contains alias variables with redundant start and/or conflicting nominal values.
 It is recommended to resolve the conflicts, because otherwise the system could be hard to solve.
 To print the conflicting alias sets and the chosen candidates please use -d=aliasConflicts.

```

### Steps to Reproduce

Load the Modelica-Buildings master library (Source: https://github.com/lbl-srg/modelica-buildings/)
Simulate the examples model present in  
Buildings.ThermalZones.Detailed.Examples.FFD.Tutorial.NaturalConvection

### Additional Context
Related tickets:#579 

### Expected Behavior
The model should simulate successfully.

### Version and OS

 - OpenModelica Version: OpenModelica 1.25.0~dev-152-g78d9a41
- OS: 11.1.0ubuntu4
 - Versions of used Modelica libraries:
Modelica 4.0.0
Buildings 12.0.0

**Comment by bilderbuchi** [comment] 2024-11-18 06:52
Is it really necessary to create essentially duplicated issues if several models fail while exhibiting the same error mode?
AFAICT, this issue and #13236 are identical, and similarly for #13225 and #13226 (and #13239 which has an OOM error on top).

In the past, the Buildings project (e.g. @deepak19015 ) opened issues clustering failing models by error type they exhibit, which avoided littering the issue tracker with (near-)duplicates. Is that strategy not attractive for you anymore?

**Comment by Pavanrajhr** [comment] 2024-11-18 10:33
@bilderbuchi 
In our last meeting with Francesco, it was suggested to create separate tickets for each model. While some issues appeared similar across models, our debugging revealed that resolving the issue for one model did not always resolve it for others. Hence, we felt it would be more effective to create individual tickets for each model. However, if this approach is not ideal, we are okay to revert to grouping similar issues under a single ticket.

**Comment by bilderbuchi** [comment] 2024-11-18 11:21
OK then. If it's an intentional change that's alright. :-)
I guess we'll see the impact of having 6+ tickets with _identical_ titles, soon. Luckily I'm just a bystander and don't have to keep everything straight. ;-)

**Comment by casella** [comment] 2024-11-21 08:23
Duplicate of #10074

**Closed** 2024-11-21 08:24 UTC

**Comment by casella** [comment] 2024-11-22 00:29
> @bilderbuchi In our last meeting with Francesco, it was suggested to create separate tickets for each model. While some issues appeared similar across models, our debugging revealed that resolving the issue for one model did not always resolve it for others. Hence, we felt it would be more effective to create individual tickets for each model. However, if this approach is not ideal, we are okay to revert to grouping similar issues under a single ticket.

I think it will be more efficient to start with the one issue -> one ticket policy. You can always spawn new tickets if and when it turns out that there were actually multiple different issues.
