### ISSUE TITLE
Crash on simulating a model

### ISSUE THREAD

**Issue by bilderbuchi** [OpenModelica/OpenModelica#11262] opened 2023-09-26 12:34 UTC
### Description
I have the following Medium and model definitions that use ExternalMedia. They are probably not working correctly (I'm exploring how far mixtures are working in ExternalMedia), but that should not be the concern here.
```
package MixTestMedium
  extends ExternalMedia.Media.CoolPropMedium(
    mediumName = "CarbonDioxide",
    substanceNames = {"CO2[0.99]&Methane[0.01]"},
    ThermoStates = Modelica.Media.Interfaces.Choices.IndependentVariables.ph,
    SpecificEnthalpy(start=2e5));
end MixTestMedium;

model MixtureTest
  extends Modelica.Icons.Example;
  extends ExternalMedia.Test.GenericModels.TestStates(
    redeclare package Medium = MixTestMedium);
equation
  p1 = 8e6;
  h1 = 1.0e5 + 6e5*time;
  p2 = 8e6;
  T2 = 280 + 50*time;
  annotation(experiment(StopTime = 1, Interval = 0.001));
end MixtureTest;
```
When I simulate `MixtureTest`, shortly after OMEdit crashes without a crash reporter dialog.
The last lines of omeditcommunications.log are
```
cd("C:/Users/bla/AppData/Local/Temp/OpenModelica/OMEdit/MixtureTest") 14:21:15:366
"C:/Users/bla/AppData/Local/Temp/OpenModelica/OMEdit/MixtureTest" 14:21:15:366
#s#; 0.000000; 17.868000; 'cd("C:/Users/bla/AppData/Local/Temp/OpenModelica/OMEdit/MixtureTest")'

clearCommandLineOptions() 14:21:15:369
true 14:21:15:369
#s#; 0.000000; 17.868000; 'clearCommandLineOptions()'

setCommandLineOptions("--matchingAlgorithm=PFPlusExt --indexReductionMethod=dynamicStateSelection -d=initialization,NLSanalyticJacobian --unitChecking -d=nfAPI,nfAPIDynamicSelect ") 14:21:15:369
true 14:21:15:369
#s#; 0.000000; 17.868000; 'setCommandLineOptions("--matchingAlgorithm=PFPlusExt --indexReductionMethod=dynamicStateSelection -d=initialization,NLSanalyticJacobian --unitChecking -d=nfAPI,nfAPIDynamicSelect ")'

setCommandLineOptions("--simCodeTarget=C") 14:21:15:369
true 14:21:15:369
#s#; 0.000000; 17.868000; 'setCommandLineOptions("--simCodeTarget=C")'

setCommandLineOptions("--target=gcc") 14:21:15:369
true 14:21:15:369
#s#; 0.000000; 17.868000; 'setCommandL
```
### Expected Behavior
OMEdit should not **crash**, even if there is a problem with an external library (I suspect this could be the ultimate cause), but fail without crashing. 
OMEdit should definitely not crash without some error message or other indication what went wrong. 
Ideally, OMEdit should produce a meaningful error message.

### Version and OS

 - OpenModelica Version: v1.22.0-dev-337-g2c8441d604 (64-bit)
 - OS: Windows 10, 64 bit
 - ExternalMedia 4.0.0

**Comment by perost** [comment] 2023-09-26 13:28
Should be fixed in #11263. The issue was that the compiler tried to evaluate an external function during the compilation by loading the shared library an executing the function via libffi, but the function threw an exception that we didn't catch. We'll still have similar issues if the external library just crashes though.

**Closed** 2023-09-26 14:49 UTC

**Comment by mahge** [comment] 2023-09-27 09:50
These are functions generated by the `omc` code generator. There seems to be some kind of typing issue here. I mad e a quick check but I am not sure what the root cause is yet.

@perost flattening the model in the issue gives this output (only the relevant part here)

```mo
function MixtureTest.completeState2.Medium.ThermodynamicState "Automatically generated record constructor for MixtureTest.completeState2.Medium.ThermodynamicState"
  input Real T;
  input Real a;
  input Real beta;
  input Real cp;
  input Real cv;
  input Real d;
  input Real ddhp;
  input Real ddph;
  input Real eta;
  input Real h;
  input Real kappa;
  input Real lambda;
  input Real p;
  input Integer phase;
  input Real s;
  output ThermodynamicState res;
end MixtureTest.completeState2.Medium.ThermodynamicState;

function MixtureTest.completeState2.Medium.density "Return density from state"
  input MixtureTest.completeState2.Medium.ThermodynamicState state "Thermodynamic state record";
  output Real d(quantity = "Density", unit = "kg/m3", displayUnit = "g/cm3", min = 0.0, max = 100000.0, start = 1.0, nominal = 1.0) "Density";
algorithm
  d := state.d;
end MixtureTest.completeState2.Medium.density;

function MixtureTest.completeState2.Medium.density_derh_p "Return derivative of density wrt enthalpy at constant pressure from state"
  input MixtureTest.completeState2.Medium.ThermodynamicState state "Thermodynamic state record";
  output Real ddhp(unit = "kg.s2/m5") "Density derivative w.r.t. specific enthalpy";
algorithm
  ddhp := state.ddhp;
end MixtureTest.completeState2.Medium.density_derh_p;

function MixtureTest.completeState2.Medium.density_derp_h "Return derivative of density wrt pressure at constant enthalpy from state"
  input MixtureTest.completeState2.Medium.ThermodynamicState state "Thermodynamic state record";
  output Real ddph(unit = "s2/m2") "Density derivative w.r.t. pressure";
algorithm
  ddph := state.ddph;
end MixtureTest.completeState2.Medium.density_derp_h;

function MixtureTest.completeState2.Medium.isobaricExpansionCoefficient "Return isobaric expansion coefficient from state"
  input MixtureTest.completeState2.Medium.ThermodynamicState state "Thermodynamic state record";
  output Real beta(unit = "1/K", min = 0.0, max = 100000000.0) "Isobaric expansion coefficient";
algorithm
  beta := state.beta;
end MixtureTest.completeState2.Medium.isobaricExpansionCoefficient;

function MixtureTest.completeState2.Medium.isothermalCompressibility "Return isothermal compressibility from state"
  input MixtureTest.completeState2.Medium.ThermodynamicState state "Thermodynamic state record";
  output Real kappa(quantity = "Compressibility", unit = "1/Pa") "Isothermal compressibility";
algorithm
  kappa := state.kappa;
end MixtureTest.completeState2.Medium.isothermalCompressibility;

function MixtureTest.completeState2.Medium.molarMass "Return the molar mass of the medium"
  input MixtureTest.completeState2.Medium.ThermodynamicState state;
  output Real MM(quantity = "MolarMass", unit = "kg/mol", min = 0.001, max = 0.25, nominal = 0.032) "Mixture molar mass";
algorithm
  MM := completeState2.Medium.fluidConstants[1].molarMass;
end MixtureTest.completeState2.Medium.molarMass;
```

most of these functions look fine to me and I can see the pattern. 

However, the last one, `MixtureTest.completeState2.Medium.molarMass`, looks unusual. 

```mo
function MixtureTest.completeState2.Medium.molarMass "Return the molar mass of the medium"
  input MixtureTest.completeState2.Medium.ThermodynamicState state;
  output Real MM(quantity = "MolarMass", unit = "kg/mol", min = 0.001, max = 0.25, nominal = 0.032) "Mixture molar mass";
algorithm
  MM := completeState2.Medium.fluidConstants[1].molarMass;
end MixtureTest.completeState2.Medium.molarMass;
```

The function input is not used. Guessing from the other functions, I would expect it to return `state.molarMass`. On the other hand, there is no member named `molarMass` in the record definition at the top so I am not sure.  Perhaps a redeclare extends class is not handled as it should be or a value that should be constant evaluated is not evaluated.  Can you please do a quick check before I start going back from the codegen?

**Comment by perost** [comment] 2023-09-27 10:04
> However, the last one, `MixtureTest.completeState2.Medium.molarMass`, looks unusual.
> 
> ```modelica
> function MixtureTest.completeState2.Medium.molarMass "Return the molar mass of the medium"
>   input MixtureTest.completeState2.Medium.ThermodynamicState state;
>   output Real MM(quantity = "MolarMass", unit = "kg/mol", min = 0.001, max = 0.25, nominal = 0.032) "Mixture molar mass";
> algorithm
>   MM := completeState2.Medium.fluidConstants[1].molarMass;
> end MixtureTest.completeState2.Medium.molarMass;
> ```
> 
> The function input is not used. Guessing from the other functions, I would expect it to return `state.molarMass`. On the other hand, there is no member named `molarMass` in the record definition at the top so I am not sure. Perhaps a redeclare extends class is not handled as it should be or a value that should be constant evaluated is not evaluated. Can you please do a quick check before I start going back from the codegen?

The function is defined as:
```Modelica
redeclare function molarMass "Return the molar mass of the medium"
  input ThermodynamicState state;
  output MolarMass MM "Mixture molar mass";
algorithm
  MM := fluidConstants[1].molarMass;
end molarMass;
```
So it's correct that the input isn't used, it's using a package constant instead. However, the package constant needs to be evaluated since the code generation can't handle functions that refer to constants outside the function, but that hasn't happened here for some reason.

The value of the `molarMass` constant is defined through the `getMolarMass` external function, so I guess the issue is that that function fails (probably by throwing an exception which was the original issue) and then we ignore that and just continue anyway. But I'll need to take a closer look to be sure.

**Comment by bilderbuchi** [comment] 2023-09-27 10:34
You can find (AFAICT) an equivalent definition in the MSL `Modelica.Media.Interfaces.PartialTwoPhaseMedium.molarMass`: 
```modelica
function extends molarMass
      "Return the molar mass of the medium"
    algorithm
      MM := fluidConstants[1].molarMass;
    end molarMass;
```
the ancestor function comes from `PartialMedium` AFAICT:
```modelica
partial function molarMass
      "Return the molar mass of the medium"
      extends Modelica.Icons.Function;
      input ThermodynamicState state "Thermodynamic state record";
      output MolarMass MM "Mixture molar mass";
    end molarMass;
```
So it seems that in the general case this pattern of using outside constant should work. 
The failing function call could indeed be the root cause.

**Comment by casella** [comment] 2023-09-27 20:30
@bilderbuchi if you are interested at using ExternalMedia for mixtures, let's talk about it.

**Comment by casella** [comment] 2023-09-27 21:21
@mahge the fact that the state input of the molarMass() function is not used is correct. For pure media, the molar mass is a (package) constant. It is actually a function of the state only for mixtures, in which case it depends on the composition array X.

**Comment by bilderbuchi** [comment] 2023-09-28 06:35
> @bilderbuchi if you are interested at using ExternalMedia for mixtures, let's talk about it.

Yeah, I filed https://github.com/modelica-3rdparty/ExternalMedia/issues/94 for this in the meantime.

**Comment by bilderbuchi** [comment] 2023-09-28 06:37
Should this codegen problem go into a separate issue so it does not get lost?

**Comment by casella** [comment] 2023-09-28 07:47
Yes, please 😃

**Comment by bilderbuchi** [comment] 2023-09-28 08:57
Done, let's continue this in #11273
