### ISSUE TITLE
CCCV-stack and CCCV-stackRC examples (Electrical/Batteries) don't work

### ISSUE THREAD

**Issue by lbfzsze** [OpenModelica/OpenModelica#9866] opened 2022-12-06 15:19 UTC
[1] 15:47:08 Übersetzung Fehler 
[/var/lib/jenkins2/ws/LINUX_BUILDS/tmp.build/openmodelica-1.20.0~dev.beta4/OMCompiler/Compiler/NFFrontEnd/NFType.mo: 1112:13-1113:80]: Internal error NFType.subscript got unsubscriptable type Modelica.Electrical.Batteries.Interfaces.CellBus

**Comment by perost** [comment] 2022-12-06 15:27
Duplicate of #9052. The error message has changed since that was reported, but the issue is still the same.

**Closed by perost** 2022-12-06 15:27 UTC
