### ISSUE TITLE
ClaRa chattering

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#8461] opened 2022-01-25 11:20 UTC
### Description

There is event chattering in `ClaRa.Components.Electrical.Check.TestAsynchronousMotorWithPump`, see the [simulation log](https://libraries.openmodelica.org/branches/master/ClaRa_dev/files/ClaRa_dev_ClaRa.Components.Electrical.Check.TestAsynchronousMotorWithPump.sim).

Since Dymola can simulate these models we should investigate what's the issue.

### Steps to Reproduce

Run `ClaRa.Components.Electrical.Check.TestAsynchronousMotorWithPump` with omc
```
./ClaRa_dev_ClaRa.Components.Electrical.Check.TestAsynchronousMotorWithPump -abortSlowSimulation -alarm=480 -lv LOG_STATS
LOG_SUCCESS       | info    | The initialization finished successfully with 3 homotopy steps.
stdout            | info    | Chattering detected around time 98.2847701823..98.2848697851 (100 state events in a row with a total time delta less than the step size 0.1). This can be a performance bottleneck. Use -lv LOG_EVENTS for more information. The zero-crossing was: sign(pump.rpm / pump.iCom.rpm_nom * pump.Delta_p / pump.Delta_p_max_var * pump.V_flow / pump.iCom.V_flow_max * pump.tau_fluid) <= 0
assert            | debug   | Aborting simulation due to chattering being detected and the simulation flags requesting we do not continue further.
```

### Expected Behavior

Don't have event shattering.

### Version and OS

- OpenModelica Version: OMCompiler v1.19.0-dev.545+g5c10d4c725
- OS: Ubuntu 20.04.3 LTS
- Versions of used Modelica libraries: ClaRa_dev @ c57bace0acbe86a8ae2ccf3e427c60093c5ac95c

**Comment by casella** [comment] 2022-01-26 17:20
From the error message, I understand the event is caused by `pump.rpm*pump.Delta_p` changing sign a lot of times around `time = 98.284`. What is the behaviour of those variables in the successful Dymola simulation around that time point?

**Comment by AnHeuermann** [comment] 2022-02-09 15:58
Dymola is reporting issues for this model as well:

```
... Error message from dymosim
At time T = 9.731987e+01 and stepsize
H = 5.518297e-07 the corrector could not converge.
Repeated convergence test failures occurred on the last attempted step
in the code. An inaccurate or ill-conditioned Jacobian may be the
problem. Integration will be terminated.


Integration terminated before reaching "StopTime" at T = 97.3
```

![image](https://user-images.githubusercontent.com/38031952/153239085-93ce2f72-8cf8-4fbb-b5ef-9cca227ad3cc.png)


`pump.Delta_p` is getting bigger and comes very close to `pump.Delta_p_max`. When changing that parameter to something smaller (`3.6e+7` instead of `3.8+e7` ) Dymola reports an error that get's very close to what we say chattering is:

```
Warning message from dymosim
At time T = 9.278223e+01 in current integration interval
T_interval = 9.270729e+01 ... 9.280719e+01
a large amount of work has been expended
(about 500 steps) in the integrator. Probably the communication
interval is too large or the system is stiff.


... Error message from dymosim
At time T = 9.340691e+01 and stepsize
H = 1.355887e-07 the corrector could not converge.
Repeated convergence test failures occurred on the last attempted step
in the code. An inaccurate or ill-conditioned Jacobian may be the
problem. Integration will be terminated.


Integration terminated before reaching "StopTime" at T = 93.4
```

**Comment by AnHeuermann** [comment] 2022-02-09 16:03
So I would argue it is a problem with the model and not OpenModelica/Dymola.

It just happens, that OpenModelica reaches `Delta_p_max` a bit faster then Dymola.
![image](https://user-images.githubusercontent.com/38031952/153239953-948c38e0-adf7-443c-9bbc-5f802c70e011.png)

**Comment by casella** [comment] 2022-06-07 22:45
I guess we can close this issue as far as OpenModelica is concerned. A separate issue could be opened on the ClaRa issue tracker.

**Closed by casella** 2022-06-07 22:45 UTC
Labels: wontfix, COMP/SimRT/C
