### ISSUE TITLE
Conditional connectors not handled by OMEdit

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#2081] opened 2020-06-27 00:43 UTC

**Comment by adeas31** [comment] 2021-05-26 10:49
See also #5913 and #7492

**Comment by casella** [comment] 2021-11-10 23:56
@adrpo, I'm trying to figure out myself why this is so difficult. I tried a simple example case, see
[TestConditionalConnectors.txt](https://github.com/OpenModelica/OpenModelica/files/7516576/TestConditionalConnectors.txt); I opened TestConditionalConnectors.Test1 and checked omedicommunication.log.

As I understand the problem is that currently OMEdit fetches display information from the class definitions
```
getElements(TestConditionalConnectors.Test1, useQuotes = true) 00:34:00:407
{{"co", "-", "TestConditionalConnectors.M1", "m1", "", "public", "false", "false", "false", "false", "unspecified", "none", "unspecified", "$Any", "{}"}} 00:34:00:407
#s#; 0.000000; 0.317000; 'getElements(TestConditionalConnectors.Test1, useQuotes = true)'

getElementAnnotations(TestConditionalConnectors.Test1) 00:34:00:407
{{Placement(true,0.0,0.0,-10.0,-10.0,10.0,10.0,0.0,-,-,-,-,-,-,)}} 00:34:00:408
#s#; 0.000000; 0.317000; 'getElementAnnotations(TestConditionalConnectors.Test1)'

getDiagramAnnotation(TestConditionalConnectors.Test1) 00:34:00:408
{} 00:34:00:408
#s#; 0.000000; 0.317000; 'getDiagramAnnotation(TestConditionalConnectors.Test1)'

countMessages() 00:34:00:409
(0,0,0) 00:34:00:409
#s#; 0.000000; 0.317000; 'countMessages()'

getElements(TestConditionalConnectors.M1, useQuotes = true) 00:34:00:409
{{"co", "-", "Boolean", "activateOutput", "", "public", "false", "false", "false", "false", "parameter", "none", "unspecified", "$Any", "{}"},{"co", "-", "TestConditionalConnectors.RealOutput", "y", "", "public", "false", "false", "false", "false", "unspecified", "none", "unspecified", "$Any", "{}"}} 00:34:00:409
#s#; 0.000000; 0.317000; 'getElements(TestConditionalConnectors.M1, useQuotes = true)'

getElementAnnotations(TestConditionalConnectors.M1) 00:34:00:409
{{},{Placement(true,100.0,2.0,-10.0,-10.0,10.0,10.0,0.0,100.0,1.77636e-15,-20.0,-20.0,20.0,20.0,0.0)}} 00:34:00:409
#s#; 0.000000; 0.317000; 'getElementAnnotations(TestConditionalConnectors.M1)'

getElements(TestConditionalConnectors.RealOutput, useQuotes = true) 00:34:00:410
{} 00:34:00:410
#s#; 0.000000; 0.317000; 'getElements(TestConditionalConnectors.RealOutput, useQuotes = true)'

getDiagramAnnotation(TestConditionalConnectors.RealOutput) 00:34:00:410
{-100.0,-100.0,100.0,100.0,true,-,-,, {Polygon(true, {0.0, 0.0}, 0.0, {0, 0, 127}, {255, 255, 255}, LinePattern.Solid, FillPattern.Solid, 0.25, {{-100.0, 50.0}, {0.0, 0.0}, {-100.0, -50.0}}, Smooth.None), Text(true, {0.0, 0.0}, 0.0, {0, 0, 127}, {0, 0, 0}, LinePattern.Solid, FillPattern.None, 0.25, {{30.0, 60.0}, {30.0, 110.0}}, "%name", 0.0, {-1, -1, -1}, "", {}, TextAlignment.Center)}} 00:34:00:411
#s#; 0.000000; 0.317000; 'getDiagramAnnotation(TestConditionalConnectors.RealOutput)'
```
but not from the actual instances. Specifically, it gets the information that TestConditionalConnectors.Test1 contains an instance of class TestConditionalConnectors.M1 named m1, but then it asks about elements of the class M1, not of the specific instance m1, which is were the information about the activation of conditional connectors is defined.

Do I understand correctly?

Is the problem that we should switch from gathering information about classes to gathering information about their instances?

**Comment by casella** [comment] 2021-11-11 10:47
We need a plan to implement an "instance-based" mechanism in place of the current one, which will also solve other long-standing issues. @perost and @adeas31 will work on that, with input from @adrpo that has ideas how to do this.

**Comment by casella** [comment] 2021-11-29 18:48
The current situation is that all conditional connectors are always shown. There were some cases where this did not happen, see #8172 and #8210, they were fixed in #8237.

Eventually, #8237 should be reverted and the visibility attribute should be correctly evaluated in OMEdit based on the latest parameter value input.

**Comment by casella** [comment] 2022-01-10 13:22
Additionally, we need to update the icons that depend on parameters dynamically.

**Comment by casella** [comment] 2022-07-14 11:50
Prototype implementation available since PR #9230, start OMEdit with `./OMEdit --NAPI=true`

**Comment by adrpo** [comment] 2022-07-14 14:38
@niklwors I suspect the getModelInstance API has some issues with some complex models for now. @perost will fix them when he comes back from the holidays. They have started with small models so they can do proper testing.

**Comment by casella** [comment] 2022-07-14 14:57
@niklwors, thanks for reporting!

What we have now is just a demo. It shows we are on the right track, but is still far from being usable. Work on that will resume from mid-August.

**Comment by adeas31** [comment] 2022-07-15 09:00
@niklwors please send your library to me. I will do some testing.

**Comment by niklwors** [comment] 2022-07-15 09:21
@adeas31 Thank you, @adrpo can provide you with this information

**Comment by adeas31** [comment] 2022-12-04 13:47
@niklwors several improvements are done. Can you please test this again and report.

**Comment by casella** [comment] 2023-01-11 09:28
This functionality is now implemented for good in the new instance-based API, currently activated by running `OMEdit --NAPI=true`.

Please reopen this ticket if there are any problems which are specific of this feature.

**Closed by casella** 2023-01-11 09:28 UTC
Labels: COMP/GUI/OMEdit, COMP/OMC/Interactive Environment, COMP/GUI/InstBased Interface
