### ISSUE TITLE
References of instantiated classes not adapted when duplicating a package

### ISSUE THREAD

**Issue by AHaumer** [OpenModelica/OpenModelica#9646] opened 2022-11-02 09:52 UTC
Duplicating a package with different name, the references of instantiated classes still point to the class definitions in the old package,

Assume you have library LibA with component CompA and an example instantiating `LibA.CompA compA`.
Duplicating LibA as LibB, the example still uses the intantiation `LibA.CompA compA`.
I'd expect an adaption of the instantiation to `LibB.CompA compA`
Of course, a work-around would remove "LibA.", leaving the instantiation `CompA compA`.
Then after duplicating, the instantioation remians the same and points to LibB.CompA.

Additionally, I missing "Replace" additionally to "Dupilcate".
![Unbenannt](https://user-images.githubusercontent.com/6900273/199458323-4494153c-92a7-4383-b18a-7523d930ff30.PNG)

OM v1.19.2
Windows 10 64bit

**Comment by casella** [comment] 2022-11-02 23:57
Duplicate of #5346 (no pun intended 😄).

**Closed by casella** 2022-11-02 23:57 UTC
