### ISSUE TITLE
The 'within' statement can be used to get access of a package in OMEdit translate - and should not be possible.

### ISSUE THREAD

**Issue by janpeter19** [OpenModelica/OpenModelica#13047] opened 2024-10-21 19:36 UTC
### Description
The 'within' can be used to get access of a package in OMEdit translate - and should not be possible.  The simulation works fine. The export to FMU does not work though, but the error text could be more clarifying. It seems that OMEdit tries to make an FMU: 

### Steps to Reproduce
The following package DEMO_v90 together with  the 'un-correct' model D90_2 illustrates the problem.

    package DEMO_v90
       package A
	      constant Real a=1;
	      constant Real b=2;
	      constant Real c=3;
       end A;	
       model M1
          replaceable package A = DEMO_v90.A;
          Real x, y, z;
       equation
          x = A.a;
          y = A.b;
          z = A.c;
       end M1;
       model M2
          replaceable package A = DEMO_v90.A;
          Real x, y, z;
       equation
          x = 2*A.a;
          y = 2*A.b;
          z = 2*A.c;
       end M2;
    end DEMO_v90;

And the 'un-correct' model D90_2 (separate file), which I must admit initially thought was an elegant solution 

    within DEMO_v90;
    model D90_2	
        M1 m1(redeclare package A = A);
        M2 m2(redeclare package A = A);
    end D90_2;

The correct model is D_90_1 below.

    model D90_1
       import DEMO_v90;	
       DEMO_v90.M1 m1(redeclare package A = DEMO_v90.A);
       DEMO_v90.M2 m2(redeclare package A = DEMO_v90.A);
    end D90_1;

### Expected Behavior
It would be helpful that during translation an error text comes that says something like that 'within' should not be used in this way and urge the use to instead use 'import'. The same error statement if export to FMU is tried. 

### Screenshots
The error text you get today after trying to export and FMU for D90_2 you see below.

![Screenshot 2024-10-19 at 15 13 14](https://github.com/user-attachments/assets/09d56fc5-f0e4-48f2-9d5e-7ffcc9151ad5)

### Version and OS
OpenModelica version 1.25.0-dev-71g4fcfbbf
OS Linux Ubuntu 22.04, 64-bit

### Additional Context
The problem is discussed at Stackoverrflow 
https://stackoverflow.com/questions/79105169/use-of-modelica-concepts-within-or-import

**Comment by casella** [comment] 2024-10-21 21:56
@janpeter19 it is not clear to me where the code from `package DEMO_v90` to `end D90_2;` is located. Is it saved in a single file? Or are there two files, one with the package `DEMO_v90` and one with the model `D90_2`?

**Comment by janpeter19** [comment] 2024-10-22 05:34
@casella, I have updated the post and made it clearer. DEMO_v90, D90_1, and D90_2 are three different files.

**Comment by perost** [comment] 2024-10-22 08:41
I don't think there's anything actually wrong with `D90_2`, `within DEMO_v90` simply means that the model is placed inside the `DEMO_v90` package. It might not be what you want in this particular case, but I don't think there's anything the compiler can complain about in this case. So the issue seems more to be that it somehow breaks FMU export than that `within` is used incorrectly.

**Comment by janpeter19** [comment] 2024-10-22 08:46
I would like just to refer to Hans Olsson comment on Stackoverflow yesteday, see link above.
He is very firm here, and say essentially that it is OK that FMU export does not work. 
The problem is that the translation in OMEdit works.
Further JModelica does not accept D90_2 either.

**Comment by casella** [comment] 2024-10-22 11:01
> I don't think there's anything actually wrong with `D90_2`, `within DEMO_v90` simply means that the model is placed inside the `DEMO_v90` package. It might not be what you want in this particular case, but I don't think there's anything the compiler can complain about in this case.

The matter is regulated by [Section 13.4](https://specification.modelica.org/maint/3.6/packages.html#file-system-mapping-of-package-class) of the MLS, which I understand must be considered in his entirety. From this point of view, if model `D90_2` is defined in a separate file and meant to be contained within package `DEMO_v90`, I understand the only legal configuration is that package `DEMO_v90` is contained within a directory with the same name, where the first file mentioned by @janpeter19 is named `package.mo` and the second is named `D90_2.mo`.

_Additionally_, the `D90_2.mo` file shall begin with a `within DEMO_v90;` clause, but that clause by itself is not enough to determine that model `D90_2` belongs to package `DEMO_v90`. I'd say that Hans is correct in his statement on stackoverflow that this clause is essentially a safety measure, so that the belonging of a class contained in a certain file is not determined _exclusively_ by its location in the file system, but _also_ by a `within` statement, which acts as a double-check.

Regarding the third file, it could be placed anywhere. It goes without saying that it is very different to state that a certain model _belongs_ to a package or simply _imports_ it.

@perost I think the OMC class loader should be very strict in following the rules of Section 13.4, otherwise people will frequently experience trouble when developing Modelica code in OMC and then switching to other tools that follow the standard.

**Comment by perost** [comment] 2024-10-22 11:24
I guess the issue is that
> A non-top-level entity shall begin with a within-clause which for the class defined in the entity specifies the location in the Modelica class hierarchy.

is a bit ambiguous. I interpreted it to mean that `within` defines the class hierarchy, but it seems the intended meaning is that the class hierarchy is defined by the file locations and `within` merely indicates where a class should be.

**Comment by casella** [comment] 2024-10-22 17:49
> A non-top-level entity shall begin with a within-clause which for the class defined in the entity specifies the location in the Modelica class hierarchy.

The within class specifies the location, but not by itself. The other rules of Sub-sections 13.4.1 and 13.4.2 also apply.

**Comment by perost** [comment] 2024-10-24 11:55
Fixed in #13063. The compiler already checked these things when loading libraries, the issue was only with the `loadFile`/`loadString` API:s. Since they're usually only used to load top-level classes we just need to check if there is a `within` clause or not (other than `within ;`).

We do have some test cases that use this feature in various ways though, so I added a flag to these calls that disables the check if needed.

**Closed** 2024-10-24 14:27 UTC
Labels: COMP/GUI/OMEdit, COMP/OMC/Interactive Environment
