### ISSUE TITLE
Modelica-Buildings Library (master): Simulation fails at initialization

### ISSUE THREAD

**Issue by NehaSPatwardhan** [OpenModelica/OpenModelica#13225] opened 2024-11-15 06:59 UTC
### Description

The solver fails to simulate at initialization.

The given model is having this issue:
```
Buildings.ThermalZones.Detailed.Examples.FFD.RoomOnlyConstructionBoundary
```
On simulating the model in OpenModelica leads to following errors/warnings:
```
1.Failed to copy array. Dimension sizes are not equal and destination array is not flexible.
2.simulation terminated by an assertion at initialization

```

The log report of the model is given below:
https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.ThermalZones.Detailed.Examples.FFD.RoomOnlyConstructionBoundary.sim
```
GC Warning: Failed to expand heap by -4096 bytes
GC Warning: Out of Memory! Heap size: 1 MiB. Returning NULL!
src->dim_size[0] != dst->dim_size[0], 0 != -1
LOG_ASSERT        | debug   | Failed to copy array. Dimension sizes are not equal and destination array is not flexible.
LOG_ASSERT        | info    | simulation terminated by an assertion at initialization
```

The error report of the model is given below:
https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.ThermalZones.Detailed.Examples.FFD.RoomOnlyConstructionBoundary.err
```
1.Warning: The model contains alias variables with redundant start and/or conflicting nominal values.
 It is recommended to resolve the conflicts, because otherwise the system could be hard to solve.
 To print the conflicting alias sets and the chosen candidates please use -d=aliasConflicts.

```

### Steps to Reproduce

Load the Modelica-Buildings master library (Source: https://github.com/lbl-srg/modelica-buildings/)
Simulate the examples model present in  
Buildings.ThermalZones.Detailed.Examples.FFD.RoomOnlyConstructionBoundary

### Additional Context
Related tickets:#579 

### Expected Behavior
The model should simulate successfully.

### Version and OS

 - OpenModelica Version: OpenModelica 1.25.0~dev-152-g78d9a41
- OS: 11.1.0ubuntu4
 - Versions of used Modelica libraries:
Modelica 4.0.0
Buildings 12.0.0

**Comment by casella** [comment] 2024-12-05 08:29
@phannebohm, there is clearly something wrong going on with the runtime here. This should be debugged.

**Comment by casella** [comment] 2024-12-05 08:34
Duplicate of #10074

**Closed** 2024-12-05 08:37 UTC
