### ISSUE TITLE
The NF produces unbalanced models in the Buildings library

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#7651] opened 2021-07-04 11:43 UTC
After the NF fixes listed in [this report](https://libraries.openmodelica.org/branches/history/master/2021-07-01%2012:27:40..2021-07-03%2000:10:06.html) there are 18 more models of Buildings passing the frontend. However, they end up having a few more equations than variables, see, e.g. [OnlyExteriorWallWithWindow](https://libraries.openmodelica.org/branches/master/Buildings_7.0.0/files/Buildings_7.0.0_Buildings.ThermalZones.Detailed.Validation.TestConditionalConstructions.OnlyExteriorWallWithWindow.err), which is the smallest one, which aborts with `The model has 1611 equation(s) and 1607 variable(s)`.

I understand the models were previously failing because of type issues related to array sizes. I guess there are still some cases that are not handled correctly. Dymola reports 1607 variables and equations on that test cases, so I guess there is something wrong in the flattened equations. Unfortunately, the matching algorithm is apparently not attempted, so we have no clue which could be the extra equations.

@perost, any clue regarding how to hunt down this issue?

**Comment by adrpo** [comment] 2021-07-04 12:38
Do they have implicit inner declarations?

**Comment by perost** [comment] 2021-07-04 12:40
> Do they have implicit inner declarations?
> I have seen unbalanced models that became balanced when I manually added the inner.

No, all of the Buildings examples are complete as far as I know.

**Comment by adrpo** [comment] 2021-07-04 12:43
I guess we should really check local balancing to be easier to detect compiler issues.

**Comment by casella** [comment] 2021-07-04 15:53
In some cases I have been able to successfully use some diagnostic messages from the backend to understand what were the missing or extra equations in case of unbalanced models, in cases where Dymola did me bogus responses because it misinterprets connector inputs.

Maybe we should just let the backend continue even if the frontend finds out the model is unbalanced. Is that possible?

**Comment by perost** [comment] 2021-07-04 16:06
> Maybe we should just let the backend continue even if the frontend finds out the model is unbalanced. Is that possible?

The frontend does not check balancing. The backend counts the variables and equations in `BackendDAEUtil.checkAdjacencyMatrixSolvability` and fails if it finds the model to be unbalanced, but changing the code to continue anyway just causes the backend to fail a bit later without any additional messages.

**Comment by casella** [comment] 2021-07-05 09:39
That is a bit strange. Consider this test case
```
model TestUnbalanced
  Real x, y, z;
equation
  x + y = 2;
  x - y = 3;
  annotation(__OpenModelica_commandLineOptions="-d=execstat");
end TestUnbalanced;
```
If I run it in OMEdit I get the following messages
```
[18] 11:37:12 Translation Notification
Performance of FrontEnd - DAE generated: time 2.6e-06/0.1491, allocations: 0 / 1.792 GB, free: 174.8 MB / 0.6394 GB

[19] 11:37:12 Translation Notification
Performance of FrontEnd: time 1.3e-06/0.1491, allocations: 0 / 1.792 GB, free: 174.8 MB / 0.6394 GB

[20] 11:37:12 Translation Notification
Performance of Transformations before backend: time 2.4e-06/0.1491, allocations: 0 / 1.792 GB, free: 174.8 MB / 0.6394 GB

[21] 11:37:12 Symbolic Error
Too few equations, under-determined system. The model has 2 equation(s) and 3 variable(s).

[22] 11:37:12 Symbolic Warning
[TestUnbalanced: 2:3-2:15]: Variable z does not have any remaining equation to be solved in.
  The original equations were:

```

Q1: Which module is issuing messages [21] and [22]? Maybe @kabdelhak or @AnHeuermann can comment on that
Q2: Why don't we get anything like this in the case under question in this issue?

**Comment by perost** [comment] 2021-07-05 09:48
> Q1: Which module is issuing messages [21] and [22]? Maybe @kabdelhak or @AnHeuermann can comment on that

Still BackendDAEUtil.checkAdjacencyMatrixSolvability, i.e. in the first phase of the backend. But for the Buildings models it doesn't seem to detect any variables that don't have any equations.

**Comment by casella** [comment] 2021-07-05 10:50
That is probably because there are more equations than variables 😄 

Too bad that case is not covered, it would be nice if we could just get a printout of the equations that remained orphaned at the end of matching. That would probably be a useful clue. @kabdelhak, @AnHeuermann, do you think that is possible?

**Comment by AnHeuermann** [comment] 2021-07-05 11:41
There is a Boolean for debugging in the code. I can try to enable it and see if the output is of any use. But it will be very verbose. But there is something to print "Remaining unsolved variables", I guess this is what you are looking for.

I'll compile it and add the output to this issue, so you can check if it is usefull.

**Comment by AnHeuermann** [comment] 2021-07-05 11:53
[ExteriorBoundaryConditionsWithWindow_log.txt](https://github.com/OpenModelica/OpenModelica/files/6763975/ExteriorBoundaryConditionsWithWindow_log.txt)

**Comment by perost** [comment] 2021-07-05 13:22
I implemented a check model feature for the FlatModel structure in the NF, and it says there are 1607 variables and 1607 equations. So it seems like the issue might occur during the DAE conversion. I'll try to find out what the difference is after the conversion.

**Comment by perost** [comment] 2021-07-05 13:40
The issue is that these crefs are added to the list of outputs by the old CheckModel / backend:
```Modelica
roo.conExtWinRad[1].abs.absRad[1,(1:2) + 1,1:1]
roo.conExtWinRad[1].abs.absRad[2,(1:2) + 1,1:1]
```
This seems to happen because the old CheckModel / backend just replaces the iterator with the range and then fails to expand the crefs since `(1:2) + 1` is not a valid operation. It seems like we might need to unroll the for-loops if we want to count individual scalar variables.

**Comment by perost** [comment] 2021-07-05 14:36
@mahge: The issue here is that `CheckModel.checkAndGetAlgorithmOutputs` does not expand the crefs because they belong to an array component. I think this behaviour is wrong in this case, because it will just add the crefs as they look in the flat model.

It seems to me like we want to just strip the last subscripts and add the whole array, but as the code is written I assume there's some issues with that approach?

**Comment by perost** [comment] 2021-07-06 11:37
I tried to fix the issue in #7655, but while it works fine for Buildings it breaks one of our test cases ([AlgorithmSize](https://github.com/OpenModelica/OpenModelica/blob/master/testsuite/simulation/modelica/algorithms_functions/AlgorithmSize.mos)). The issue seems to occur due to algorithms that the backend itself creates for some reason, where some arrays are expected to be counted as one variable. I don't know how to fix that though since CheckModel doesn't know where a cref comes from.

**Comment by mahge** [comment] 2021-07-06 11:45
You probably have figured it out by now but if not, the reason they were supposed to not be expanded is [here](https://trac.openmodelica.org/OpenModelica/ticket/2452#comment:21). The basic idea is that if an indexed cref is assigned to in an algorithm section then we assume the whole array as modified, i.e., count it as the whole array. 

However, there were cases where  whole algorithm sections come from an array model component. The crefs in them are indexed when the array component is expanded. In this case we can not count the assignments in them as "the whole array" since they are actually balanced models in their own scope.

For a better context, here is the issue. This model

```modelica
model test
  record R
    Real d;
  end R;

  R r[2];
algorithm 
  r[1].d := 0;
algorithm 
  r[2].d := 0;
end test;
```
is unbalanced because we count `r[1].d` as the whole array (size 2) first and then again in the second algorithm. Giving us 4 outputs.

On the other hand this
```modelica
model test
  model R
    Real d;
  algorithm
    d := 0;
  end R;

  R r[2];
end test;
```
is a balanced model.

However, when we reach the backend/checkModel the model is expanded and looks like this

```modelica
model test
 Real r[1].d;
 Real r[2].d;
algorithm 
  r[1].d := 0;
algorithm 
  r[2].d := 0;
end test;
```

which looks exactly like the first (invalid) model at first look. However, this one should be considered balanced. To differentiate between the two we check where the algorithm section originated from. For this I check the `DAE.SOURCE.instanceOpt` of the algorithm section. If the instance has subs then we assume it came from an expanded array component and do not count the whole thing.

The problem is, this is not full proof. It just works for **one level of nesting** like in the example above. If 'd' was an array in the above examples, this will probably break. I think we need some form of cref expansion that can be told specifically which parts of the cref it should expand. Right now we either expand the whole thing or not at all. I guess we probably run in to that case now.

**Comment by perost** [comment] 2021-07-06 12:57
>The problem is, this is not full proof. It just works for one level of nesting like in the example above. If 'd' was an array in the above examples, this will probably break. I think we need some form of cref expansion that can be told specifically which parts of the cref it should expand. Right now we either expand the whole thing or not at all. I guess we probably run in to that case now.

My fix only removes the last subscripts of a cref, so a cref like `r[1].d` is not affected. The issue with Buildings is that you get algorithms like this:
```Modelica
  roo.conExtWinRad[2].abs.absRad[1,1,:] := {0.0};
  roo.conExtWinRad[2].abs.absRad[1,4,:] := {0.0};
  roo.conExtWinRad[2].abs.absRad[2,1,:] := {0.0};
  roo.conExtWinRad[2].abs.absRad[2,4,:] := {0.0};

  for i in 1:2 loop
    for iSta in 1:1 loop
      roo.conExtWinRad[2].abs.absRad[1,i + 1,iSta] := ...
      roo.conExtWinRad[2].abs.absRad[2,i + 1,iSta] := ...
    end for;
  end for;
```
CheckModel.statementOutputs has a case for `DAE.STMT_ASSIGN_ARR` which justs expands the cref regardless of expansion policy, so because of any of the first four assignments each element of `roo.conExtWinRad[2].abs.absRad` is correctly added to the list of crefs.

But when it comes to the for-loops we have `DAE.STMT_ASSIGN` in them since they are subscripted to scalars. And the case for scalar assignments uses `statementOutputsCrefFinder` which will use the expansion policy and add `roo.conExtWinRad[2].abs.absRad[1,(1:2) + 1,1]` and `roo.conExtWinRad[2].abs.absRad[2,(1:2) + 1,1]` to the list of crefs, leading to too many algorithm outputs.

One solution that might work is to just set the expansion policy to expand when handling statements inside a for-loop. We don't handle statements with iterators correctly when not expanding anyway, so I don't think it should break anything. I'll try it and see.

**Comment by perost** [comment] 2021-07-07 08:14
Fixed in ##7662, but the models now either fail during SimCode creation or are found to be structurally singular.

**Closed by perost** 2021-07-07 08:14 UTC
Labels: COMP/New Instantiation

**Comment by casella** [comment] 2021-07-07 08:45
How can we be 100% sure that the backend gets the right equations after your fixes?

**Comment by perost** [comment] 2021-07-07 09:09
> How can we be 100% sure that the backend gets the right equations after your fixes?

We can't, but what I fixed was the counting that would miscount algorithm outputs in some cases. So that the models are now balanced is at least a good indication that the equations are correct. The SimCode issue is a known issue, but why some models are found to be structurally singular I have no idea about.

**Comment by casella** [comment] 2021-07-07 10:05
Sounds good.
