### ISSUE TITLE
Latest nightly build

### ISSUE THREAD

**Issue by stephanfevrier** [OpenModelica/OpenModelica#7060] opened 2020-12-23 07:42 UTC
I am using the latest nightly build of openModelica for Linux AMD64 to work on a modelling project using the Buildings 7.0 library. After the regular update of the nightly build this morning OMEdit messes up component symbols in diagram view. Something with the "annotation(transformation..." seems to have changed?
Interestingly, this problem seems to be limited to Fluid Systems.

See for instance Modelica.Fluid.Examples.HeatingSystem:
![Screenshot from 2020-12-23 08-39-52](https://user-images.githubusercontent.com/17869521/102971936-92c79c00-44fa-11eb-96b2-a147300eabba.png)

**Comment by Faark** [comment] 2021-01-12 18:48
Same for me with the Official Release for Windows from openmodelica.org (OpenModelica-v1.16.2-64bit.exe). Can pretty much only work text view. Did not make my first steps in modelica a great experience...

**Comment by adrpo** [comment] 2021-01-12 19:06
> Same for me with the Official Release for Windows from openmodelica.org (OpenModelica-v1.16.2-64bit.exe). Can pretty much only work text view. Did not make my first steps in modelica a great experience...

Please use 1.16.1 until we find out what the problem is. Unfortunately we cannot reproduce this yet. See ticket:
https://trac.openmodelica.org/OpenModelica/ticket/6307

**Comment by adrpo** [comment] 2021-02-19 13:20
Fixed in PR #7180.

**Closed by adrpo** 2021-02-19 13:20 UTC
