### ISSUE TITLE
FMU failed with an external look-up table

### ISSUE THREAD

**Issue by Arinomo** [OpenModelica/OpenModelica#7412] opened 2021-04-27 08:26 UTC
### Description
FMU exported from OMv1.17 failed to look-up an external table using FMUChecker. 

> assert            | debug   | Error in line 8 when reading numeric data of matrix "fault(5,2)" from file "C:\Users\trari\AppData\Local\Temp\fmucktmpa03292\resources\R\Eigene Dateien\TutorialPackage\ExterneDaten\Fault_Profile.txt"

Works for FMU exported from v1.14 with out problem. 

### Steps to reproduce
Export example model below as a fmu v2.0 co-simulation only with model decsription filter set to none. Test using FMUChecker-2.0.4-win64. 

```mo
within TutorialPackage.ExterneDaten;
model Fehlerprofil
import smoothness =  Modelica.Blocks.Types.Smoothness;
import extrapolation =  Modelica.Blocks.Types.Extrapolation;
import load = ModelicaServices.ExternalReferences.loadResource;
/* Model I/O */
input Boolean startTime_set(start=false, fixed=false);
output Boolean Fehlersignal;
/* Variables */
Real entryTime(start=0, fixed=true);
Real internalTime(start=0);
/* Parameter */
parameter String myTableName = "fault";
constant String myFileName = load("modelica://TutorialPackage/ExterneDaten/Fault_Profile.txt");
/* Blocks */
Modelica.Blocks.Tables.CombiTable1Ds table(tableOnFile = true, tableName = myTableName, fileName = myFileName,
                                           smoothness = smoothness.ConstantSegments, extrapolation = extrapolation.HoldLastPoint);
equation
  when edge(startTime_set) then
    entryTime = time;
  end when;
    internalTime = if startTime_set then (time- entryTime) else 0;
    table.u = internalTime;
    Fehlersignal =  table.y[1] > 0.5 ;
end Fehlerprofil;
```

with following matrix inside a text file located in a folder TutorialPackage/ExterneDaten (i did not save package as one file):
```
#1

double fault(5,2)
0	0
1	1
2	0
3	1
4	0
```

Input file for fmu chekcer was writen using ms-excel and saved as csv:
```
time startTime_set
0 1
1 1
```
### Expected behavior
FMU from v1.17 was expected to work similar to v1.14

### Screenshots
unable to upload screenshots

### Additional files
unable to upload files

### Version and OS
 - OpenModelica Version 1.17.0
 - OS: FMU export using Windows 7; FMU check using win10

### Additional context
There are also some discrapancy between modelName_FMU.c files from both version

From v1.14:

> comp->fmuData->modelData->integerParameterData[0].attribute.start = 2;
> comp->fmuData->modelData->integerParameterData[1].attribute.start = 1;
> comp->fmuData->modelData->integerParameterData[2].attribute.start = 1;
> comp->fmuData->modelData->integerParameterData[3].attribute.start = 3;
> comp->fmuData->modelData->booleanParameterData[0].attribute.start = 1;
> comp->fmuData->modelData->stringParameterData[2].attribute.start = mmc_mk_scon("fault");

Which are the settings from CombiTable1Ds table (columns, extrapolation, nout, smoothness, tabelOnFile and tableName respectively)

From v1.17: 

> comp->fmuData->modelData->integerParameterData[0].attribute.start = 2;
> comp->fmuData->modelData->integerParameterData[1].attribute.start = 0;
> comp->fmuData->modelData->integerParameterData[2].attribute.start = 0;
> comp->fmuData->modelData->integerParameterData[3].attribute.start = 0;
> comp->fmuData->modelData->booleanParameterData[0].attribute.start = 0;
> comp->fmuData->modelData->stringParameterData[2].attribute.start = mmc_mk_scon("");

Parameters and Variables detected by FMUChecker are also not identical
V1.14:
> 0 constants
> 3 parameters
> 5 discrete variables
> 3 continuous variables
> 1 inputs
> 1 outputs
> 6 local variables
> 0 independent variables
> 9 calculated parameters
> 6 real variables
> 2 integer variables
> 2 enumeration variables
> 7 boolean variables
> 3 string variables

v1.17:

> 0 constants
> 3 parameters
> 5 discrete variables
> 3 continuous variables
> 1 inputs
> 1 outputs
> 6 local variables
> 0 independent variables
> 8 calculated parameters
> 6 real variables
> 2 integer variables
> 2 enumeration variables
> 7 boolean variables
> 2 string variables

**Comment by Arinomo** [comment] 2021-04-27 08:32
I think it identical to #7409. should i close it?

**Comment by casella** [comment] 2021-04-27 12:55
Looks like it, but I'd keep it open anyway with a reference, maybe FMU has something to it

**Comment by Arinomo** [comment] 2021-05-01 09:45
[FMUs.zip](https://github.com/OpenModelica/OpenModelica/files/6409327/FMUs.zip)
Worked with FMU exported from v1.16 and v1.18 (1.5.2021)

**Comment by lochel** [comment] 2021-05-07 06:34
@Arinomo @casella So this is a regression in 1.17, but already fixed for 1.18? Do we have to patch 1.17, or should we just go ahead with 1.18?

**Comment by casella** [comment] 2021-05-07 06:42
If we know exactly what is the patch, it would be nice to, but I won't spend much time on this. @Arinomo, if you need this feature for your work, you can rely on the nightly.

We could also make a stable release of what we currently have on master, possibly after @kabdelhak has merged in the reactivation of reshuffle, and possibly after he has taken care of the ThermoPower library issue :)

**Comment by Arinomo** [comment] 2021-05-07 08:12
For me the 1.18 is ok. 

thanks.

**Closed** 2021-05-07 08:13 UTC
Labels: COMP/FMI
