### ISSUE TITLE
Hint for names when duplicating component (tiny useful enhancement)

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#11881] opened 2024-01-26 09:10 UTC
### Description
I remember there was a ticket on this, that was probably closed as fixed, but I cannot find it anymore.
OM hints for a name when dragging a new component from a library (correct) but does not when duplicating.

I propose to hint for a name also when duplicating.

tested with 1.23 - dev168.

**Comment by adeas31** [comment] 2024-03-19 15:09
Adding a hint is not so difficult. The only question is what will be the useful/meaningful name?

In case of components we simply add number suffix to names. Doing the same here doesn't make much sense. Maybe we can do something like `M_copy` or `M_duplicate`. And then add the number suffix in case of several duplicates e.g., `M_copy1`, `M_copy2` etc.

**Comment by ceraolo** [comment] 2024-03-19 17:26
there are two separated issues.

When you duplicate you already decide a name for the duplicated component. Only, you don't give a chance to the user to edit it immediately. This is different from what occurs when you drag a component from a library.

**issue 1: OM does not prompt for a name change when duplicating.** 
_proposal: please prompt for a name change_

**issue 2: OM does not use the same algorithm to determine the duplicated name as the one used when dragging a componet from a library**
_proposal: please use the same algorithm._

Take for example resistor: when you drag from library you get "resistor1" then, when you drag again you get "resistor2", because OMEdit understands that "resistor1" is already used.
The same should occur when duplicating: when we duplicate an object named "resistor", OMEdit should propose"resistor1", but if "resistor1" is already used it should propose "resistor2".
In general, it seems to me that if no digits are present at the end of the name, then 1 is added. E.g. "name" is duplicated into "name1"; if a number n (e.g. 1, 2, 3, ...) is already there, n+1 is used. E.g. "name3" is duplicated into "name4", if name4 is not already used, otherwise "name5", etc.

Note that currently, when duplicating, a different algorithm to determine the duplicated model name is used. For instance duplciating "resistor1" gives "resistor11" which I don't like.

Note that what I propose for the name of duplicates is the same as Dymola currently does.

**Comment by adeas31** [comment] 2024-03-19 22:17
Aha you are talking about duplicate of component. I thought it was about duplicate of model.

**Comment by adeas31** [comment] 2024-03-20 01:39
> **issue 1: OM does not prompt for a name change when duplicating.** _proposal: please prompt for a name change_
> 

Fixed. You should get a prompt now if `Tools|Options|Notifications|Always ask for the dragged/duplicated component name` is checked.

> **issue 2: OM does not use the same algorithm to determine the duplicated name as the one used when dragging a componet from a library** _proposal: please use the same algorithm._
> 
> Take for example resistor: when you drag from library you get "resistor1" then, when you drag again you get "resistor2", because OMEdit understands that "resistor1" is already used. The same should occur when duplicating: when we duplicate an object named "resistor", OMEdit should propose"resistor1", but if "resistor1" is already used it should propose "resistor2". In general, it seems to me that if no digits are present at the end of the name, then 1 is added. E.g. "name" is duplicated into "name1"; if a number n (e.g. 1, 2, 3, ...) is already there, n+1 is used. E.g. "name3" is duplicated into "name4", if name4 is not already used, otherwise "name5", etc.
> 
> Note that currently, when duplicating, a different algorithm to determine the duplicated model name is used. For instance duplciating "resistor1" gives "resistor11" which I don't like.
> 
> Note that what I propose for the name of duplicates is the same as Dymola currently does.

Both dragging and duplicating a component use the same code for finding the unique name.

The problem is the name you start with. In case of dragging a component you always start with `resistor` and when duplicating you are starting with `resistor1`. If you create a model named `resistor1` and drag it to diagram layer you will get `resistor1`, `resistor11`, `resistor12` and so on.

When duplicating, we know that `resistor1` belongs to the model named `resistor` so we can also start here with `resistor` but it will be bad when lets say you have renamed the component from `resistor` to `res`. Now when duplicating `res` you actually want the new name to be `res1` instead of `resistor1`. That is why in case of duplication we start with whatever is the component name.

**Comment by adeas31** [comment] 2024-03-20 13:41
Now I changed the implementation in a way that it checks if the name ends with a number then this number is used a starting point. So when dragging/duplicating you will get `resistor`, `resistor1`, `resistor2`, `resistor3` and so on. If your model name ends with a number lets say `resistor555` then you will get `resistor555`, `resistor556`, `resistor557` and so on.

**Closed** 2024-03-20 13:56 UTC
Labels: enhancement
