### ISSUE TITLE
Duplicating or copying/pasting loses array information

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#8258] opened 2021-12-03 13:52 UTC
### Description
If  I duplicate or copy/paste an array of models array information is lost on the mo text

### Steps to Reproduce
(use the following file without txt):
[Test.mo.txt](https://github.com/OpenModelica/OpenModelica/files/7650066/Test.mo.txt)

1. Load model Test.mo. Block phase is an array of 3 elements: 
```
  Modelica.Blocks.Sources.Constant phase[3](k = {0, -120, 120}) annotation(
    Placement(visible = true, transformation(origin = {-2, -2}, extent = {{-10, 10}, {10, -10}}, rotation = 180)));

```
(in attributes I see[3] as Dimensions)

2. duplicate phase. The newly created model const has the following text:
```
  Modelica.Blocks.Sources.Constant const(k = {0, -120, 120}) annotation(
    Placement(visible = true, transformation(origin = {-2, 36}, extent = {{-10, 10}, {10, -10}}, rotation = 180)));

```
i.e., [3] has disappeared. Nevertheless, in Attributes|Dimension [3] is still reported.

### Expected Behavior
The duplicate should have [3] after its name in the code.

### Version and OS

1.18.0 Win10 64 bit
 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by adeas31** [comment] 2021-12-06 08:56
I can't reproduce it. Steps I followed,

- Loaded the Test.mo
- Duplicated Test model with right-click duplicate and set the new name as `Test1`.
- The new model `Test1` is,

```
model Test1
  Modelica.Blocks.Sources.Constant phase[3](k = {0, -120, 120}) annotation(
    Placement(visible = true, transformation(origin = {-2, -2}, extent = {{-10, 10}, {10, -10}}, rotation = 180)));
equation

annotation(
    uses(Modelica(version = "3.2.3")));
end Test1;
```

**Comment by max-privato** [comment] 2021-12-07 08:13
I mean duplicating without changing name.
I replicated this ticket's steps and behaviour in both 1.18.0 and 1.19.0-dev-433

BTW, I think that uwhen duplicating OMEdit should prompt the user for a new name, as it does when dragging from MSL.

**Comment by adeas31** [comment] 2021-12-07 09:44
> I mean duplicating without changing name.

How do you duplicate without changing the name? Maybe you are inserting the model then in some package?

![image](https://user-images.githubusercontent.com/4007231/145005175-9b1e9f57-1222-4644-b0f2-2bfe85b55be3.png)

> BTW, I think that uwhen duplicating OMEdit should prompt the user for a new name, as it does when dragging from MSL.

Sure. Please create a new ticket for it so I don't forget about it.

**Comment by max-privato** [comment] 2021-12-08 22:23
> 
> How do you duplicate without changing the name? Maybe you are inserting the model then in some package?

To reproduce this ticket's issue just right-click on phase and select duplicate. The duplicated block takes automatically the name "const".

**Comment by adeas31** [comment] 2022-01-17 14:03
Ahh now I got it. I thought the problem is related to duplication of models but it is about duplication of elements. Should be fixed now.

**Closed** 2022-01-17 14:50 UTC
