### ISSUE TITLE
OpenIPSL dynamic select usage not working

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#13428] opened 2024-12-18 20:01 UTC
### Description
There are many models in OpenIPSL containing dynamicSelect fields that do not work well on OM.

For instance here's the output of DAEMode-SMIB_Examples.Example_1.Network1 at t=5s:
![image](https://github.com/user-attachments/assets/0f305493-32be-4aae-9c33-d5d0f693385c)

We see bus voltage and angle, but not other components' powers.
This is probably because buses contain simpler code:
```
textString=DynamicSelect("Vpu", String(v, significantDigits=3))),Text(
          visible=displayPF,
          origin={0,-160},
          extent={{-60,-20},{60,20}},
          lineColor={170,0,0},

```
while P and Q, e.g. in generator G1, resort to a function:
```
          textString=DynamicSelect("0.0 MW",
            OpenIPSL.NonElectrical.Functions.displayPower(P, " MW"))),Polygon(
          visible=displayPF,
          points=DynamicSelect({{-20,80},{-20,60},{20,70},{-20,80}}, if P >= 0
             then {{-20,80},{-20,60},{20,70},{-20,80}} else {{20,80},{20,60},{-20,
            70},{20,80}}),
          lineColor={255,0,0},
          fillColor={255,0,0},
          fillPattern=FillPattern.Solid),Text(
          visible=displayPF,
          extent={{-80,-80},{80,-160}},
          lineColor={0,255,0},

```
The displayPower function is:
```
function displayPower
  "A function to generate a nice string of a power variable with unit attached."
  extends Modelica.Icons.Function;
  input Real pwrVar "Variable to be converted into a string";
  input String unitStr "Unit string to be appended";
  output String pwrDsp "Resultant display string";
algorithm
  pwrDsp := String(abs(pwrVar)/1e6, format=".1f") + unitStr;
end displayPower;
```

I don't know whether there is something wrong with the OpenIpsl code above or  an issue with OpenModelica.
This code works well when using Dymola:

![image](https://github.com/user-attachments/assets/70d83a5d-332e-46f6-a8d9-e45a4827e842)

### Expected Behavior
Active and reactive powers should be probably displayed, as per Dymola's picture.

### Version and OS
OM 1.24.2

**Comment by adeas31** [comment] 2024-12-18 21:13
Seems duplicate of #13293

**Comment by ceraolo** [comment] 2024-12-18 21:58
Aha, clear.
After considering #13293,  I too am convinced that this is a duplicate of that one.
Now we just know that that ticket impacts OpenIPSL also.

**Closed** 2024-12-20 01:14 UTC
Labels: COMP/GUI/OMEdit
