### ISSUE TITLE
Feature Request: Support for top level parameter input

### ISSUE THREAD

**Issue by gwr69** [OpenModelica/OpenModelica#12184] opened 2024-04-03 11:51 UTC
Coming from Wolfram System Modeler I note significant differences in how **top level parameter input** is handled, which I found rather confusing. Having searched documentation in vain and having tried all kind of "obvious actions" in OMEdit, it seems that this may be indeed something that so far is not <s>(conveniently)</s> supported?

Consider the following **minimal example**:

```
model ParameterInput
  parameter Real in1 = 1 "Regular parameter without any annotation";
  parameter Real in2 = 2 "Parameter to be shown in another tab (Advanced)" annotation(Dialog(tab = "Advanced"));
  parameter Boolean sp1 = false "= true, if a component is to be activated" annotation(Evaluate = true, Dialog(group = "Structural Parameters"));
  
  block ConditionalBlock "Component conditional upon sp1"
    extends Modelica.Blocks.Icons.Block;
    parameter Real cbIn1 = 1 "Input for conditional block";
  end ConditionalBlock;

  ParameterInput.ConditionalBlock cb if sp1 annotation(...);

end ParameterInput;
``` 

In OMEdit (today's nightly build) in the modeling perspective for DiagramView I will see the following on Windows 10 (64bit):

![image](https://github.com/OpenModelica/OpenModelica/assets/17766670/1ed14d87-ecb0-4a56-865c-8ec96db0a31a)

While I do not know about Dymola, in System Modeler this perspective would be rather similar, but in the `Messages` pane we would also see the `General` tab for parameters and other tabs, if defined by the selected model's annotations, e.g., in the above example a modeler would see an `Advanced` tab. Not so in OMEdit, which seems to not "parse" a model at this stage?

Parameter input related tabs (`annotation(Dialog(...));`) will only be shown for a component like `ConditionalBlock` upon right click and selecting the `Parameters` entry in the context menu:

<img width = "300" src="https://github.com/OpenModelica/OpenModelica/assets/17766670/92e41860-1736-48da-9aaa-6a1bea433c2d"/>

**Where is this option for the top level scope of `model ParameterInput` in OMEdit?**

Certainly, there should be an obvious way --- other than changing values in Text View --- for a modeler to change the values of  `in1`, `in2`, and `sp1` _before_ running a simulation?

I have not found such a convenient way of changing top level parameters in any of the following places:

- View menu
- Context menu in Diagram View, e.g., right clicking on the canvas instead of any component
- Context menu in Libraries Menu, e.g., right clicking on the entry for `model ParameterInput` there
- Simulation Setup (which accidentally says "Parameter Input" and has a "General" tab ...)

**Comment by bilderbuchi** [comment] 2024-04-03 14:16
Have you seen https://github.com/OpenModelica/OpenModelica/issues/2891#issuecomment-1567189149 and #4408?

**Comment by gwr69** [comment] 2024-04-03 14:18
For completeness, here is the comparable view of `model ParameterInput` in Wolfram System Modeler, where users will find the `General` (and other tabs) next to the `Messages` tab. Something in the vein would be really nice.

![image](https://github.com/OpenModelica/OpenModelica/assets/17766670/40bf4805-2174-44b5-a6a0-b507b36a5d9a)

On a side note, comparison of how`model ParameterInput` in System Modeler works compared to OMEdit also reveals what I would consider a bug in OMEdit:

When you instantiate the `block ConditionalBlock` by "dragging and dropping" it in Diagram View in OMEdit, it will be instantiated as:

```
ParameterInput.ConditionalBlock cb;
```

Here WSM's Check Model complains:
> When looking up ParameterInput.ConditionalBlocks in scope ParameterInputs, ConditionalBlock is not encapsulated. Since ParameterInput is not a package nor an operator, ConditionalBlock must be looked up among encapsulated elements only.

**Comment by casella** [comment] 2024-04-03 21:23
@gwr69 in fact #4408 is seven years old, if you check the original ticket.

It seems that this feature was not really requested by anybody so far, or maybe they just resorted to manual editing of the source file. Anyway, that is definitely a nice to have feature.

I would consider this ticket as a duplicate of #4408 and continue the discussion there.

**Closed by casella** 2024-04-03 21:23 UTC
Labels: duplicate, enhancement
