### ISSUE TITLE
Regression on Buildings due to unbalanced equations or initial equations

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8958] opened 2022-05-14 11:34 UTC
### Description

There are many regressions from the last time the library test ran, see [report](https://libraries.openmodelica.org/branches/history/master/2022-04-24%2011:23:12..2022-05-14%2000:36:35.html). Many of them in Buildings fail with
```
Warning: It was not possible to solve the under-determined initial system (0 equations and 13 variables)
Error: No system for the symbolic initialization was generated
```
while many others fail with
```
Error: Too many equations, over-determined system. The model has 11237 equation(s) and 11045 variable(s).
```
@kabdelhak there are about 60 commits in that report, but maybe you have a clue, and/or you can do some bisection and find the offending one.

**Comment by mwetter** [comment] 2022-05-16 18:29
In case it helps with isolating it, a simple test case is
`Buildings.HeatTransfer.Windows.BaseClasses.Examples.AbsorbedRadiation`. If the instance `winAbs` is deleted, the model works. The problematic constructs therefore seem to be present in `Buildings.HeatTransfer.Windows.BaseClasses.AbsorbedRadiation`.

**Comment by perost** [comment] 2022-05-16 18:33
I forgot to update the issue, but I did a bisect earlier and found that it was caused by #8933. @kabdelhak is already aware of that.

**Comment by mwetter** [comment] 2022-05-25 19:39
I further isolated the case, as this causes many models to no longer translate. See https://github.com/lbl-srg/modelica-buildings/issues/3044

Essentially, in the section at
https://github.com/lbl-srg/modelica-buildings/blob/0960b8c691bbd61c19d0245d1995099e5ee6507c/Buildings/HeatTransfer/Windows/BaseClasses/RadiationData.mo#L26
there are two formulations of a parameter assignment. The first (commented out) works, it assigns directly 
```
...
traRef=zeros(3, N, N, HEM, NSta),
...
```
as a function argument. The second, which is immediately below, assigns
```
...
traRef=traRef,
...
```
in that function argument, and `traRef` is declared above as
```modelica
final parameter Real traRef[3, N, N, HEM, NSta]=zeros(3, N, N, HEM, NSta);
```

**Comment by casella** [comment] 2022-05-26 08:11
@mwetter, the root problem here is most likely the one described in #8772: there is some bug that causes parameter binding equations not to be sorted correctly in the BLT in some cases, which leads to wrong results because some parameters are actually used in expressions before having been assigned a value.

This is of course quite bad, because you silently get badly wrong results, without any kind of notification or warning.

@kabdelhak tried to solve the issue with #8933, but the solution only addressed half of the problem. As I understand, models that previously may (or would, I'm not sure) have led to wrong results now fail during compilation. So, this is probably not much of a regression, but rather unsweeping dirt from under the carpet 😅. It may be that your models would actually run fine, since the value was zero anyway, but this is just by chance, which is not good.

We are aware of the problem in #8722, which is also affecting other OSMC users, and we are giving it high priority, please refer to that ticket to check for further progress. This is probably not going to be fixed in 1.19.0, but we'll cherry pick into 1.19.1 as soon as we find a solution.

**Comment by casella** [comment] 2022-05-30 19:45
@mwetter, #8981 has improved the situation significantly, see [regression report](https://libraries.openmodelica.org/branches/history/master/2022-05-29%2022:30:42..2022-05-30%2011:35:57.html). In particular, the AbsorbedRadiation case that you isolated now runs correctly again.

@kabelhak this might still be not good enough, if you count the [models in Buildings 8 that stopped simulating successfully beteween Apr 24 and May 14](https://libraries.openmodelica.org/branches/history/master/2022-04-24%2011:23:12..2022-05-14%2000:36:35.html) you get 45. If you count the ones that [started simulating again with your last PR](https://libraries.openmodelica.org/branches/history/master/2022-05-29%2022:30:42..2022-05-30%2011:35:57.html) you get 27. Some others were fixed elsewhere, e.g. [Buildings.Fluid.HeatPumps.BaseClasses.Validation.EquationFitReversibler](https://libraries.openmodelica.org/branches/master/Buildings_8/files/Buildings_8_Buildings.Fluid.HeatPumps.BaseClasses.Validation.EquationFitReversible.sim), which was got broken in April but now works fine again. However, there are still some missing.

For example, [Buildings.Examples.HydronicHeating.TwoRoomsWithStorage](http://libraries.openmodelica.org/branches/master/Buildings_8/files/Buildings_8_Buildings.Examples.HydronicHeating.TwoRoomsWithStorage.err) and [Buildings.ThermalZones.Detailed.Examples.MixedAirFreeResponse](http://libraries.openmodelica.org/branches/master/Buildings_8/files/Buildings_8_Buildings.ThermalZones.Detailed.Examples.MixedAirFreeResponse.err) started failing in April because of `Error: Too many equations, over-determined system.` and still do.  Maybe you and/or @mwetter could have a quick look at them.

**Comment by casella** [comment] 2022-06-01 21:57
Great! I'll check with regression testing results tomorrow

**Comment by perost** [comment] 2022-06-02 08:36
The [report](https://libraries.openmodelica.org/branches/history/master/2022-05-31%2011:23:14..2022-06-02%2002:19:55.html) says that 16 models were improved. I went through all the Buildings 8 models that were broken and they are all now working as well as they did before, so I think we can close this now.

**Closed by perost** 2022-06-02 08:36 UTC
Labels: COMP/OMC/Backend, regression

**Comment by mwetter** [comment] 2022-06-02 14:51
Great to see them working again. Note however that with OpenModelica 1.20.0~dev-114-g9ac2542, `Buildings.ThermalZones.Detailed.Examples.MixedAirFreeResponse` has about 11,000 lines of the form
```
Failed to solve linear system of equations (no. 6615) at time 172800.000000. Residual norm is 0.00142383575439483.
The default linear solver fails, the fallback solver with total pivoting is started at time 172800.000000. That might raise performance issues, for more information use -lv LOG_LS.
```
This may indicate an issue, or you may want to suppress them after reporting them a few times?

**Comment by casella** [comment] 2022-06-02 16:41
Suppressing warnings about singular systems is maybe not a good idea. The warnings [posted by the CI](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.ThermalZones.Detailed.Examples.MixedAirFreeResponse.sim) are much less than 11K, but yet we should look into this.

**Comment by casella** [comment] 2022-06-02 16:44
See #9053.
