### ISSUE TITLE
Issue in the ClaRa library with number of mixture components passed through inner/outer

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8325] opened 2021-12-14 19:42 UTC
Most ClaRa_dev models currently fail during flattening with errors like [this](https://libraries.openmodelica.org/branches/master/ClaRa_dev/files/ClaRa_dev_ClaRa.Components.HeatExchangers.Check.Test_HEXvle2gas_L3_1ph_BU.err):
```
Error: Could not evaluate structural parameter (or constant): 
hex_ntu.tubes.heattransfer.iCom.mediumModel.nc_propertyCalculation which gives dimensions of array: mixingRatio_propertyCalculation. 
Array dimensions must be known at compile time.
```
Ales Vojacek reports:

> OM fails to resolve the Medium record correctly when the number of mixture components is passed from the simCenter through iCom (record for internal communication from the model to replaceable models) instance via inner/outer to the replaceable models.

**Comment by perost** [comment] 2022-01-14 12:40
Duplicate of #4908 mostly. There were still some models in ClaRa that failed with the same error message but for other reasons, which were fixed in #8413 (and then properly fixed in #8422 because I messed that one up). The mentioned model now fails due to issues in the library that have been reported to ClaRa internally.

**Closed by perost** 2022-01-14 12:40 UTC
Labels: COMP/New Instantiation
