### ISSUE TITLE
Building FMU with  -d=-disableDirectionalDerivatives fails

### ISSUE THREAD

**Issue by tobiaslatour** [OpenModelica/OpenModelica#13356] opened 2024-12-05 10:28 UTC
### Description
I want to export a model  as FMU that provides DirectionalDerivatives, but it fails when building the C object with

```bash
C:/Users/Tobia/AppData/Local/Temp/OpenModelica/OMEdit/437.fmutmp/sources/ExponentialGrowth.c:271:4: error: incompatible function pointer types initializing 'int (*)(void *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (*)(void *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') with an expression of type 'int (DATA *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (struct DATA *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') [-Wincompatible-function-pointer-types]
  271 |    ExponentialGrowth_initialAnalyticJacobianFMIDER,
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Tobia/AppData/Local/Temp/OpenModelica/OMEdit/437.fmutmp/sources/ExponentialGrowth.c:274:4: error: incompatible function pointer types initializing 'int (*)(void *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (*)(void *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') with an expression of type 'int (DATA *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (struct DATA *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') [-Wincompatible-function-pointer-types]
  274 |    ExponentialGrowth_initialAnalyticJacobianFMIDERINIT,
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```
Full traceback attached below. 

### Steps to reproduce

The model:
```modelica
model ExponentialGrowth
Real X(start = X0, fixed = true);
parameter Real X0 = 0.1;
parameter Real mu_max = 0.5;
equation
der(X) = mu_max*X;
end ExponentialGrowth;
```

The build script:
```modelica
getVersion(); getErrorString();
loadModel(Modelica,{"4.0"}); getErrorString();
loadFile("ExponentialGrowth.mo");getErrorString();
setCommandLineOptions("--fmiFlags=s:cvode"); getErrorString();
setCommandLineOptions("-d=-disableDirectionalDerivatives"); getErrorString();
buildModelFMU(ExponentialGrowth,"2.0","me_cs","<default>",{"static"},true); getErrorString();
countMessages(); getErrorString();
```
### Expected behavior
Exports a FMU that provides DirectionalDerivatives.

### Additional files
[traceback.txt](https://github.com/user-attachments/files/18021350/traceback.txt)

### Version and OS
 - OpenModelica v1.24.0 (64-bit)
 - OS:  Windows 11 Version 2009 on x86_64
I tried a nightly build OpenModelica v1.25.0-dev-218-gb7eae8a0e2 (64-bit) as well as running OM on Ubuntu 22.04, but the error is the same.

**Comment by arun3688** [comment] 2024-12-05 14:31
@tobiaslatour I can reproduce the issue, it seems it is `windows` only issue, otherwise we are having test cases in the testsuite which tests `-d=-disableDirectionalDerivatives` , It seems this issue is related with some latest changes, as @casella had tested the model in his computer and it works

@kabdelhak @phannebohm can you please comment on this ?

**Comment by phannebohm** [comment] 2024-12-05 17:02
I cannot reproduce the issue on Linux, but indeed the function interface was not uniform among those initialAnalyticJacobian-functions. Please test with the nightly once #13366 is merged.

**Comment by tobiaslatour** [comment] 2024-12-06 07:31
Building runs fine 🎉  Thanks a lot, also for your quick response  :) @phannebohm @arun3688

**Closed** 2024-12-06 09:13 UTC
