### ISSUE TITLE
Modelica-Buildings Library (master): Simulation fails while Compiling.

### ISSUE THREAD

**Issue by NehaSPatwardhan** [OpenModelica/OpenModelica#13208] opened 2024-11-13 06:41 UTC
### Description

Solver fails to check /compile the model. It throws translation error while checking.

The given models have same issues:
```
Buildings.Fluid.Geothermal.ZonedBorefields.Validation.FEFLOW.MassFlowRateStep100
```
On simulating the model in OpenModelica leads to following errors/warnings:
```
1.Translation error/ not simulating
2.Internal error NFCeval.evalLogicBinaryAnd  
3.failed to evaluate ‘true and borFie.borHol.borFieDat.conDat.borCon == Buildings.Fluid.Geothermal.Borefields.Types.BoreholeConfiguration.DoubleUTubeParallel‘
```

The error report of the model is given below:
https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Fluid.Geothermal.ZonedBorefields.Validation.FEFLOW.MassFlowRateStep100.err

### Steps to Reproduce

Load the Modelica-Buildings master library (Source: https://github.com/lbl-srg/modelica-buildings/)
Simulate the examples model present in Buildings.Fluid.Geothermal.ZonedBorefields.Validation.FEFLOW.MassFlowRateStep100

### Additional Context
Related tickets:#12677 , #12675 

### Expected Behavior
The model should simulate successfully.

### Version and OS

 - OpenModelica Version: OpenModelica 1.25.0~dev-152-g78d9a41
- OS: 11.1.0ubuntu4
 - Versions of used Modelica libraries:
Modelica 4.0.0
Buildings 12.0.0

**Comment by casella** [comment] 2024-12-05 09:27
Duplicate of #12675.

**Closed by casella** 2024-12-05 09:27 UTC
