### ISSUE TITLE
Compiling on macOS failed

### ISSUE THREAD

**Issue by mrtompet** [OpenModelica/OpenModelica#9334] opened 2022-08-27 12:48 UTC
### Description

Failed to compile OpenModelica on Intel-Mac (Monterey) following the instructions on
https://github.com/OpenModelica/OpenModelica/blob/master/README.cmake.md#33-macos

### Version and OS

- Monterey 12.5.1, Intel-Mac
 - OpenModelica Version: v1.20.0-dev

### Additional Context

Please improve instruction with following additional information 
On macOS you need to install: Java JRE

Replace content of OpenModelica/OMSimulator/3rdParty/PugiXml with Release-Version pugixml-1.12 (3 files).

**Comment by adrpo** [comment] 2022-09-05 17:03
A build trace where it fails to build due to pugixml errors:
[trace-macos.txt](https://github.com/OpenModelica/OpenModelica/files/9491358/trace-macos.txt)

**Comment by mahge** [comment] 2023-09-15 14:04
It is almost certain that this is fixed by https://github.com/OpenModelica/OpenModelica/pull/11075. Boost, the root cause of the issue here is no longer a dependency so the issue should be resolved now.

**Closed by mahge** 2023-09-15 14:04 UTC
