### ISSUE TITLE
Modelica compiler error use of undeclared identifier

### ISSUE THREAD

**Issue by paultjevdh** [OpenModelica/OpenModelica#8387] opened 2022-01-08 21:36 UTC
Hi,
### Description

I get a compiler error with the model below. The model should generate a clock with random intervals (a poisson process in physics)
Instead I get 

> test_Poisson_15syn.c:39:61: error: use of undeclared identifier '_omcQ_24CLKPRE'
>       data->simulationInfo->baseClocks[base_idx].interval = _omcQ_24CLKPRE._Poisson_source1._NextInterval;
>                                                             ^
> 1 error generated.
> mingw32-make: *** [<builtin>: test_Poisson_15syn.o] Error 1
> mingw32-make: *** Waiting for unfinished jobs....
> mingw32-make: Leaving directory 'C:/Tmp/OPENMO~1/OMEdit/SR9CA2~1.TES'
> Compilation process failed. Exited with code 0x00000002.
> 
Needless to say that the name _omcQ_24CLKPRE is not a model variable, but something made up by the modelica compiler.

### Steps to Reproduce
Please paste the model below in openmodelica and try to simulate. 
```
model test_Poisson

block PoissonProcess "Generate fixed magnitude events with exponentially distributed interval"
  import generator = Modelica.Math.Random.Generators.Xorshift128plus;
  import Modelica.Math.Random.Utilities.automaticLocalSeed;
  import distribution = Modelica.Math.Distributions.Uniform.quantile;
  extends Modelica.Blocks.Interfaces.SO;

  discrete Real NextInterval(start=1e-3) "Waiting time until next event";
  Clock Clock1 = Clock(NextInterval);
  parameter Real lambda=1440 "Event rate (#events per second)";
  Integer eventcounter(start=0) "Verification only (did we get the correct expected value?)";

    // Declare state and random number variables
  Integer state[generator.nState] "Internal state of random number generator";
  discrete Real r_raw "Uniform random number in the range (0,1]";
initial equation
   pre(state) = generator.initialState(0, 1);

equation
  when Clock1 then
    (r_raw, state) = generator.random(pre(state));
    NextInterval=-log(distribution(r_raw, 0, 1))/lambda; // Conversion from wikipedia exponential distribution https://en.wikipedia.org/wiki/Exponential_distribution
    y=1;
    eventcounter=previous(eventcounter)+1;
  end when;

  annotation (Icon(graphics={Line(points={{85,-40},{-85,-40}}, color={28,108,200}), Line(points={{-64,40},{-64,-40}}, color={28,108,200}), Line(points={{-54,40},{-54,-40}}, color={28,108,200}), Line(points={{-15,40},{-15,-40}}, color={28,108,200}), Line(points={{50,40},{50,-40}}, color={28,108,200}), Line(points={{70,40},{70,-40}}, color={28,108,200})}));
end PoissonProcess;

  PoissonProcess Poisson_source1 annotation (Placement(transformation(extent={{-12,30},{8,50}})));
  inner Modelica.Blocks.Noise.GlobalSeed globalSeed(useAutomaticSeed=false) annotation (Placement(transformation(extent={{-80,52},{-60,72}})));
  annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(coordinateSystem(preserveAspectRatio=false)));
end test_Poisson;

```

### Expected Behavior

Succesfull compilation, as in dymola

### Version and OS
v1.19.0-dev-504-g8291efd717 (64-bit) on windows 10

**Comment by casella** [comment] 2022-01-09 00:35
@mahge, @AnHeuermann, @phannebohm, could you please have a look? It seems that real interval clocks ([Section 16.3, operator 16.3](https://specification.modelica.org/maint/3.5/synchronous-language-elements.html#modelica:clock-interval)) have some issues in code generation. 

Do we have any tests for kind of clocks?

**Comment by casella** [comment] 2022-01-09 00:37
Doesn't work with cpp as well, so the problem is upstream of C code generation, either SimCode or Templates.

**Comment by phannebohm** [comment] 2022-01-10 00:46
After fixing a small bug with the interval variable of real clocks (see #8390) the model compiles but initialization fails with the following mesasge
```
Simulation execution failed for model: test_Poisson
LOG_INIT          | error   | The initialization problem is inconsistent due to the following equation: 0 != -1.27391e+09 = $TMP_12[1]
stdout            | warning | Error in initialization. Storing results and exiting.
|                 | |       | Use -lv=LOG_INIT -w for more information.
```

**Comment by phannebohm** [comment] 2022-01-10 14:09
Oops seems linking a PR with an issue automatically closes the issue when the PR is merged.

The issue shifted form compilation to initialization. I'm pretty sure this is unrelated to clocks though.

**Comment by casella** [comment] 2022-01-10 17:23
In any case, the issue was fixed, so I would close this. The fix will be available tomorrow in the nightly build.

I would kindly ask @paultjevdh to open another one regarding the initialization problem, maybe after doing some analysis on it.

**Closed by casella** 2022-01-10 17:23 UTC
Labels: COMP/SimCode

**Comment by paultjevdh** [comment] 2022-01-11 10:31
Hi,
As you can see above, the initialization error was posted as a new issue.
Thanks all for fixing this one.
Best regards,
Paul
