### ISSUE TITLE
Parameters without explicit start attribute modifiers should cause compilation to fail

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10386] opened 2023-03-11 10:14 UTC
### Description

MLS 3.5 [Section 8.6](https://specification.modelica.org/maint/3.5/equations.html#initialization-initial-equation-and-initial-algorithm) states:

> If a parameter has a _modifier_ for the start attribute, does not have `fixed = false`, and neither has a binding equation nor is part of a record having a binding equation, the modifier for the start attribute can be used to add a parameter binding equation assigning the parameter to that start value. In this case a diagnostic message is recommended in a simulation model.

So, according to MSL 3.5, this model should be rejected:
```modelica
model M
  parameter Real p;
end M;
```

Unfortunately, OMC accepts it with a warning.

MLS 3.6 removed the default start attribute 0.0 from the predefined Real definition and accordingly [changed the definition in 8.6](https://specification.modelica.org/maint/3.6/equations.html#initialization-initial-equation-and-initial-algorithm):

> If a parameter has a _value_ for the start-attribute, does not have fixed = false, and neither has a binding equation nor is part of a record having a binding equation, the value for the start-attribute can be used to add a parameter binding equation assigning the parameter to that start value. In this case a diagnostic message is recommended in a simulation model.

but the net effect is the same.

### Expected behaviour

Parameters with `fixed = true` and no binding equations or explicit start attribute modifiers should cause a model to be rejected.

**Comment by casella** [comment] 2023-03-11 10:14
Adding @pierre-haessig to the loop.

**Comment by pierre-haessig** [comment] 2024-01-09 13:30
I've retested @casella Model example with `parameter Real p;` under OM 1.22.1 and it still simulates using a default value of 0.0.

**Comment by casella** [comment] 2024-01-09 20:58
@phannebohm is this a quick fix?

**Comment by casella** [comment] 2024-01-17 08:18
Also adding @ceraolo to the loop, this is critical for the PowerGrids library.

@phannebohm any thought on this issue? Is the backend aware of the difference between a Real having the default start value of zero and having any value (including zero) modified by a start attribute?

**Comment by phannebohm** [comment] 2024-01-17 15:58
> @phannebohm any thought on this issue? Is the backend aware of the difference between a Real having the default start value of zero and having any value (including zero) modified by a start attribute?

Yes, we can discriminate those cases. I opened #11805 which works as expected, on atomic MWEs at least.

This model fails to build:
```modelica
model M1
  parameter Real p;
end M1;
```
```
"[/path/to/M1.mo:2:3-2:19:writable] Error: Parameter p has neither binding nor start value, and is fixed during initialization (fixed=true).
Error: No system for the symbolic initialization was generated
"
```
This model gives a warning but simulates with `p = 0`:
```modelica
model M2
  parameter Real p(start = 0.0);
end M2;
```
```
"[/path/to/M2.mo:2:3-2:32:writable] Warning: Parameter p has no binding, and is fixed during initialization (fixed=true), using available start value (start=0.0) as default value.
"
```
This model simulates fine:
```modelica
model M3
  parameter Real p = 0.0;
end M3;
```
```
""
```

The problem is, removing default start values apparently affects many other things too. I don't know what exactly goes wrong. Something generating the initial system. Maybe it's a quick fix. I'll have to investigate.

@kabdelhak we should implement this in the NB directly I guess.

**Comment by phannebohm** [comment] 2024-03-04 13:26
> Parameters with `fixed = true` and no binding equations or explicit start attribute modifiers should cause a model to be rejected.

Talking with @kabdelhak we noticed this might already be detected by the frontend. It does not depend on the rest of the system, only a single parameter needs to be looked at. @perost what are your thoughts on this?

**Comment by perost** [comment] 2024-03-04 13:43
> > Parameters with `fixed = true` and no binding equations or explicit start attribute modifiers should cause a model to be rejected.
> 
> Talking with @kabdelhak we noticed this might already be detected by the frontend. It does not depend on the rest of the system, only a single parameter needs to be looked at. @perost what are your thoughts on this?

Yes, we could check that in the frontend. And we should probably also check constants, which are required to always have a binding equation.

Actually, can a constant even be non-fixed? It doesn't seem to be forbidden, but I'm not sure what that would even mean.

**Comment by casella** [comment] 2024-03-04 16:01
> Yes, we could check that in the frontend.

Please go ahead with that.

>  And we should probably also check constants, which are required to always have a binding equation.

Absolutely.

> Actually, can a constant even be non-fixed?

No, it can't, see [MLS, Section 8.6](https://specification.modelica.org/maint/3.6/equations.html#initialization-initial-equation-and-initial-algorithm):

> Constants shall be determined by declaration equations (see [section 4.4.4](https://specification.modelica.org/maint/3.6/class-predefined-types-and-declarations.html#component-variability-prefixes-discrete-parameter-constant)), and `fixed = false` is not allowed.

**Comment by phannebohm** [comment] 2024-03-05 09:29
I looked at the different versions of The MLS. I couldn't find a corresponding paragraph in [MLS 3.2](https://modelica.org/documents/ModelicaSpec32.pdf).

[MLS 3.3](https://modelica.org/documents/ModelicaSpec33.pdf) says

> If a parameter has a `start`-expression, does not have `fixed=false`, and neither has a binding equation nor is part of a record having a binding equation, the `start`-expression can be used as parameter-expression although a diagnostic message is recommended when initializing the model without setting the parameter value.
>
> _[This is used in libraries to give non-zero defaults so that users can quickly combine models and simulate without setting parameters; but still easily find the parameters that need to be set.
String parameters are also covered by this, since they lack a `fixed`-attribute they can never have `fixed=false`.]_

So this check would apply to all language standards starting from 3.3 right?

**Comment by casella** [comment] 2024-03-05 13:11
MLS 3.3 was released in 2013, I still remember that discussion. 

Those start values had been introduced in the MSL much earlier, see e.g. the [declaration of R](https://github.com/modelica/ModelicaStandardLibrary/blob/3d02855e89dd2628cf48a98f46404340e92e161e/Modelica/Electrical/Analog/Basic.mo#L94) in the Resistor model, MSL 3.0.0, released in 2008. This was simply not standardized, until someone noticed. 

We can apply this rule safely no matter what the version of the language we use.

**Comment by perost** [comment] 2024-03-07 10:29
#12071 implements the check in the frontend. It broke quite a lot of test cases, but for good reasons.

There's one test case that I'm unsure about though, which is [ModelExchange/2.0/fmi_attributes_08.mos](https://github.com/OpenModelica/OpenModelica/blob/master/testsuite/openmodelica/fmi/ModelExchange/2.0/fmi_attributes_08.mos). I don't know enough about FMI to tell if the parameter `p` is declared without a binding equation on purpose or if that's just a mistake, does anyone know?

**Comment by perost** [comment] 2024-03-07 14:50
#12071 is now finally merged. I'm not sure if that's enough to consider this issue solved, so I'll leave it to you to close it.

**Comment by phannebohm** [comment] 2024-03-07 15:07
I'd say `M1`, `M2`, `M3` do what they are supposed to do, so we can close this.

**Closed by phannebohm** 2024-03-07 15:07 UTC
Labels: COMP/OMC/Backend

**Comment by perost** [comment] 2024-03-08 10:56
The added check caused about a [100 regressions](https://libraries.openmodelica.org/branches/history/master/2024-03-06%2022:42:24..2024-03-07%2022:25:06.html), mainly in AixLib and ThermofluidStream. I've looked through some of them and there doesn't seem to be anything odd going on, just simple errors with parameters that are not given a value. So unless we want to bring back the old behaviour of assigning them to 0 I guess there's not really much we can do about it.

**Comment by phannebohm** [comment] 2024-03-08 13:59
Weird, [here](https://stackoverflow.com/questions/75663745/parameter-without-default-value-in-a-modelica-model#comment133575878_75670754) it is claimed that Dymola gives an error on those models. In what tool were the libraries developed?

**Comment by casella** [comment] 2024-03-09 18:19
> Weird, [here](https://stackoverflow.com/questions/75663745/parameter-without-default-value-in-a-modelica-model#comment133575878_75670754) it is claimed that Dymola gives an error on those models. In what tool were the libraries developed?

Not sure. I will open tickets on those libraries.
