### ISSUE TITLE
Wrong parameter values reported in BR library

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8418] opened 2022-01-13 23:36 UTC
As reported by @niklwors [here in #7485](https://github.com/OpenModelica/OpenModelica/issues/7485#issuecomment-1008817437), in the DirectValve component from test case ```DirectionalValve33_Easy_TC01``` the assignment  
```parameter Real[:,1] flowTableAT=   Rexroth_Generic.Hydraulics.Valves.Internal.ExtractTable(qNTableEasy, false)```  results in an array with zero elements, which is not correct.

Maybe there is something wrong with the inference of the first dimension of the array?

@perost, @mahge, could you have a quick look?

**Comment by niklwors** [comment] 2022-01-14 09:46
@perost That is not correct, or? Normally, all elements in the first row should be filled.

**Comment by niklwors** [comment] 2022-01-14 09:52
ok, than it is correct.

**Comment by casella** [comment] 2022-01-14 23:16
@niklwors I'm not sure what you meant by "an array with zero elements". `flowTableAT` is flattened to a Real[101,1] array by the frontend, and if you turn the output of protected variables (Simulation | Output menu), you can see all its elements in the variables browser and plot them. 

I don't see any problem with this model now. Please reopen with some more indication if I missed something.

**Comment by niklwors** [comment] 2022-01-17 11:03
@casella  with my OMEdit version from last week, the value for e.g flowTableAT[37,1], flowTableAT[37,1] are 0.0 but it should be 8.0 and 6.0. And also flowTableAT[40,1] is zero and it shoud be 2.0 and there are much more entries in this array that are not filled with values.

**Comment by casella** [comment] 2022-01-17 11:55
@niklwors, sorry, I misinterpreted " results in an array with zero elements" as "results in an array with **all** zero elements". So, you should get flowTableAT={80, 78, 76, 74, 72, 70, 68, ...} and instead you get a result with some elements replaces by zero, flowTableAT = {0, 78, 76, 0, 0, 70, 68, 0, 0, 62, ...}

**Comment by niklwors** [comment] 2022-01-17 12:05
yes this is the problem.

**Comment by casella** [comment] 2022-01-17 14:35
I also checked that `qNTableEasy` is computed correctly, so the problem is within the ExtractTable function. I ran that with the algorithmic debugger, this part of the algorithm is executed correctly:
```
algorithm

  /* Determine Index of valve stroke zero */
  indexOfZeroStroke := 0;
  for i in 1:sizeFlowTable loop
    if Modelica.Math.isEqual(
                flowTable[i, 1],
                0.0,
                Modelica.Constants.eps) then
      indexOfZeroStroke := i;
    end if;
  end for;
  assert(indexOfZeroStroke > 0, "\nError in " + getInstanceName() + ":\nThe flow table has to contain an entry for valve stroke zero.\n");
  assert(indexOfZeroStroke > 1, "\nError in " + getInstanceName() + ":\nThe flow table has to contain at least one entry for negative valve stroke.\n");
  assert(indexOfZeroStroke < sizeFlowTable, "\nError in " + getInstanceName() + ":\nThe flow table has to contain at least one entry for positive valve stroke.\n");
  assert(flowTable[indexOfZeroStroke, 2] == 0, "\nError in " + getInstanceName() + ":\nThe value of volume flow at zero stroke has to be zero.\n");

  /* Extract part of flow table for positive or negative stroke */
  flowTableExtracted := zeros(sizeFlowTable, 1);
```
with `positiveStroke = false` (that's an input) and `indexOfZeroStroke = 51` (computed correctly). The last statements of the algorithm are:
```
  if positiveStroke then
    flowTableExtracted[(indexOfZeroStroke + 1):sizeFlowTable, 1] := 
      flowTable[(indexOfZeroStroke + 1):sizeFlowTable, 2];
  else
    flowTableExtracted[1:(indexOfZeroStroke - 1), 1] :=
      flowTable[1:(indexOfZeroStroke - 1), 2];
  end if;
```
and of course the else branch is executed. With the found value of indexOfZeroStroke, the assignment there is equivalent to
```
flowTableExtracted[1:50, 1] :=  flowTable[1:50, 2];
```
apparently, something goes wrong there with the generated code. @mahge, you are the wizard of slicing, could you please have a look?

**Comment by mahge** [comment] 2022-01-19 13:03
> @casella with my OMEdit version from last week, the value for e.g flowTableAT[37,1], flowTableAT[37,1] are 0.0 but it should be 8.0 and 6.0. And also flowTableAT[40,1] is zero and it shoud be 2.0 and there are much more entries in this array that are not filled with values.

@niklwors Can you please check again. I am getting the results what you say are expected.  

flowTableAT[37,1] -> 7.999999999999801
flowTableAT[40,1] -> 1.999999999999947

**Comment by mahge** [comment] 2022-01-19 13:09
However, there are others that are zero. Are you sure everything should be non-zero? Just want to double check and make sure before I continue.

**Comment by niklwors** [comment] 2022-01-19 14:05
@mahge  for me the variable DirectionalValve33_Easy_TC01.SwitchValve33_Easy1.flowTableAT[37, 1] is 0.0 and also DirectionalValve33_Easy_TC01[end].SwitchValve33_Easy1.flowTableAT[40, 1] is 0.0. I will install the latest nightly build and test ist again.

**Comment by niklwors** [comment] 2022-01-19 14:30
I am using v1.19.0-dev-505-ga499198eb3

**Comment by casella** [comment] 2022-01-19 19:23
> However, there are others that are zero. Are you sure everything should be non-zero? 

Absolutely. If I understand correctly, `flowTableAT[j, 1] = 82 - j*2`

**Comment by mahge** [comment] 2022-01-20 11:45
The problem is probably down the line in the Mat file writer. As far as I can tell the function `ExtractTable` and the slicing are working as expected. @casella I think once the the value is becomes zero it is kept as zero. So elements 41 and up (`82-41*1`) are all zero in the array. This is what is given to `ExtractTable` function as input.

Once the array is updated in the function and returned, nothing else modifies it until simulation is over. The correct values reach the Mat result file writer. So there is something wrong with the writer. 

I tried to filter out some of the variables and it seems to work fine. Try this (or the equivalent of `variableFilter` in OMEdit)

```mo
simulate(Rexroth_Generic_Test.Hydraulics.DirectionalValves.DirectionalValve33_Easy_TC01, variableFilter="SwitchValve33_Easy1.flowTableAT");
getErrorString();

val(SwitchValve33_Easy1.flowTableAT[1,1]);
val(SwitchValve33_Easy1.flowTableAT[2,1]);
...
val(SwitchValve33_Easy1.flowTableAT[39,1]);
val(SwitchValve33_Easy1.flowTableAT[40,1]);
val(SwitchValve33_Easy1.flowTableAT[41,1]);
```
------------------------------------

Result file for the above script : [Rexroth_Generic_Test.Hydraulics.DirectionalValves.DirectionalValve33_Easy_TC01_res.mat.zip](https://github.com/OpenModelica/OpenModelica/files/7904797/Rexroth_Generic_Test.Hydraulics.DirectionalValves.DirectionalValve33_Easy_TC01_res.mat.zip)

**Comment by casella** [comment] 2022-01-20 22:30
Good point, @mahge . I commented out the protected keyword in the valve model and then added `Real ZZ_01 = SwitchValve33_Easy1.flowTableAT[1,1];` to the example case, and indeed ZZ_01 turned out to be 80, as expected, while flowTableAT[1,1] was reported as zero, which further confirms your conclusions.

**Comment by casella** [comment] 2022-01-20 22:49
I checked the .mat file, and indeed it also contains the right results for `flowTableAT`. Hence, the problem is OMEdit not reading the results correctly from the .mat file.

@adeas31 can you please check? This is high priority. Please not you need to also save the protected variables to see `flowTableAT`.

Thanks!

**Comment by mahge** [comment] 2022-01-21 13:23
@casella How did you verify that the .mat file is correct? I think the problem is somewhere in the writer or reader. I am not sure which yet but I suspect it is the writer.

I can see that most of the array members are marked as `parameter` and the others are not when the .mat file is read.  The ones that are not marked as parameter are the ones with the wrong value. 

Either way this is not @adeas31 problem unless he wants to make it his. OMEdit just shows what it is given.

**Comment by casella** [comment] 2022-01-21 16:47
> @casella How did you verify that the .mat file is correct?

I used Dymola's Matlab functions, renaming the .mat file first to res.mat to avoid problems with the long filename
```matlab
>> [s,n] = tload('res.mat');
>> idx = tnindex(n, 'SwitchValve33_Easy1.flowTableAT[1,1]')
>> idx = 3693
idx = tnindex(n, 'SwitchValve33_Easy1.flowTableAT[2,1]')
>> idx = 3694
idx = tnindex(n, 'SwitchValve33_Easy1.flowTableAT[3,1]')
>> idx = 3695
```
hence the array elements are stored contiguously in the result matrix, starting from column 3693. If I then type the first 11 of them at time 0 (first row of the s matrix), I get
```matlab
>> s(1,[3693:3703])'
>> ans =

   80.0000
   78.0000
   76.0000
   74.0000
   72.0000
   70.0000
   68.0000
   66.0000
   64.0000
   62.0000
   60.0000
```
You can actually skip the Dymola functions entirely
```matlab
>> load('res.mat')
>> name(:,3693:3703)'
ans =

  11×125 char array

    'SwitchValve33_Easy1.flowTableAT[1,1]                                                                                         '
    'SwitchValve33_Easy1.flowTableAT[2,1]                                                                                         '
    'SwitchValve33_Easy1.flowTableAT[3,1]                                                                                         '
    'SwitchValve33_Easy1.flowTableAT[4,1]                                                                                         '
    'SwitchValve33_Easy1.flowTableAT[5,1]                                                                                         '
    'SwitchValve33_Easy1.flowTableAT[6,1]                                                                                         '
    'SwitchValve33_Easy1.flowTableAT[7,1]                                                                                         '
    'SwitchValve33_Easy1.flowTableAT[8,1]                                                                                         '
    'SwitchValve33_Easy1.flowTableAT[9,1]                                                                                         '
    'SwitchValve33_Easy1.flowTableAT[10,1]                                                                                        '
    'SwitchValve33_Easy1.flowTableAT[11,1]
>> data_1(3693:3703,1)
ans =

   80.0000
   78.0000
   76.0000
   74.0000
   72.0000
   70.0000
   68.0000
   66.0000
   64.0000
   62.0000
   60.0000
```
> I can see that most of the array members are marked as `parameter` and the others are not when the .mat file is read. 

I'm not sure where you see this information in the .mat file.

> The ones that are not marked as parameter are the ones with the wrong value.

This is interesting, but I have no idea where this information comes from

Where do you see that? 

> Either way this is not @adeas31 problem unless he wants to make it his. OMEdit just shows what it is given.

I'm not sure. As far as I can see, the data is there and it can be read in tools other than OMEdit, so it looks like an OMEdit problem to me.

**Comment by mahge** [comment] 2022-01-21 17:50
> This is interesting, but I have no idea where this information comes from
Where do you see that?

I was debugging through our code and looking how we read it. As it turns out there are duplicate entries for these variables (e.g. `SwitchValve33_Easy1.flowTableAT[1,1]` appears twice). Can you check entries staring from index 247 ( or248?) 

We are investigating with @lochel. We checked the results with MatLab and it seems they indeed contain duplicate entries. This is interesting

**Comment by mahge** [comment] 2022-01-21 17:58
> ```matlab
>> [s,n] = tload('res.mat');
>> idx = tnindex(n, 'SwitchValve33_Easy1.flowTableAT[1,1]')
>> idx = 3693
```

This is odd. Is `tnindex` a lookup function? To map a name to index? If so it appears Dymola is actively skipping the first entries (e.g. idx=247) and reporting the second entries, while our reader appears to be unpredictable. 

We do sorting of these variables after reading for lookup and somehow it finds the second entries sometimes and the first other times. Which is odd because it should be either wrong consistently or correct. We will keep looking.

**Comment by casella** [comment] 2022-01-21 23:01
> I was debugging through our code and looking how we read it. As it turns out there are duplicate entries for these variables (e.g. `SwitchValve33_Easy1.flowTableAT[1,1]` appears twice).

I searched the entire `n` array for `SwitchValve33_Easy1.flowTableAT[1,1]` string but only found it at index 3693.

> Can you check entries **staring from index 247 ( or 248)?**
```matlab
>> name(:,[247:257])'

ans =

  11×125 char array

    'SwitchValve33_Easy1.AT.calculateDensityB.p                                                                                   '
    'SwitchValve33_Easy1.AT.calculatePressure.pA                                                                                  '
    'SwitchValve33_Easy1.AT.calculatePressure.pB                                                                                  '
    'SwitchValve33_Easy1.AT.port_A.p                                                                                              '
    'SwitchValve33_Easy1.AT.port_B.p                                                                                              '
    'SwitchValve33_Easy1.PA.calculateDensity.calculateDensityLiq.fC.C1                                                            '
    'SwitchValve33_Easy1.PA.calculateDensity.calculateDensityLiq.fC.C2                                                            '
    'SwitchValve33_Easy1.PA.calculateDensity.calculateDensityLiq.fC.C3                                                            '
    'SwitchValve33_Easy1.PA.calculateDensity.calculateDensityLiq.fC.C4                                                            '
    'SwitchValve33_Easy1.PA.calculateDensity.calculateDensityLiq.fC.E0                                                            '
    'SwitchValve33_Easy1.PA.calculateDensity.calculateDensityLiq.fC.Rgas 
```
> This is odd. Is `tnindex` a lookup function? To map a name to index?

Yes.
```matlab
help tnindex
 tnindex  get row-index of string in trajectory-name matrix
 
          tnindex(n,name) returns the row number of the string matrix "n",
          if the string "name" is identical to row i. If "name" does not
          match a row of "n", i=0.
```
> If so it appears Dymola is actively skipping the first entries (e.g. idx=247) and reporting the second entries, while our reader appears to be unpredictable.

Again, not sure where did you get `SwitchValve33_Easy1.flowTableAT[1,1]` in position 247. As I see it, there are no duplicate entries in the attached result file.
 
BTW, I don't understand how the variables are ordered in the .mat file. The first 11096 variable names seem to be sorted lexicographically, but then the ordering is reset and restarts again at 11097, and then again at 11918, and then again at 12041, i.e., there are four alphabetically ordered subsets in sequence. I don't know what these four subsets are.

**Comment by lochel** [comment] 2022-01-22 05:51
> > I was debugging through our code and looking how we read it. As it turns out there are duplicate entries for these variables (e.g. `SwitchValve33_Easy1.flowTableAT[1,1]` appears twice).
> 
> I searched the entire `n` array for `SwitchValve33_Easy1.flowTableAT[1,1]` string but only found it at index 3693.

I am not sure how you investigate the mat file, but maybe the api you are using isn't working as low-level as you expect. I opened the mat file and searched the `name` array for the same variable `SwitchValve33_Easy1.flowTableAT[1,1]`:

```matlab
var = "SwitchValve33_Easy1.flowTableAT[1,1]";
for i=1:13275
  if startsWith(name(:,i)', var)
      fprintf('%d: "%s"\n', i, name(:,i)')
  end
end
``` 

It is listed twice: index 248 and 4691.
```matlab
 248: "SwitchValve33_Easy1.flowTableAT[1,1]                                                                                         "
4691: "SwitchValve33_Easy1.flowTableAT[1,1]                                                                                         "
```

**Comment by lochel** [comment] 2022-01-22 08:42
> BTW, I don't understand how the variables are ordered in the .mat file. The first 11096 variable names seem to be sorted lexicographically, but then the ordering is reset and restarts again at 11097, and then again at 11918, and then again at 12041, i.e., there are four alphabetically ordered subsets in sequence. I don't know what these four subsets are.

There is some sorting, but it gets disturbed, e.g., by der variables. Besides that, these are the chunks in the `name` matrix of the mat file:
* first variable is time which is stored in data_1(1) for startTime/stopTime and data_2(1) for the steps
* next 998 variables are the signal series which are stored in data_2(2:999)
* next 12045 variables are the constant ones stored in data_1(2:12046)
* next 231 variables are aliases to signals which were definied earlier

Here is a dump of all variables with index and dataInfo: [vars.txt](https://github.com/OpenModelica/OpenModelica/files/7917924/vars.txt)

**Comment by mahge** [comment] 2022-01-23 20:40
> while the Dymola functions consistently return the constant values, 

@casella You might be using the _valid_ mat file again or basing the statement on what you saw earlier. 

I just downloaded Dymola and tested this. It gives me zero for all entries of `SwitchValve33_Easy1.flowTableAT`. 
_Simulation_ -> _Load Result_ and then plot them. So it is not the reader we use that is the problem it is how it is written or what the writer is given.

**Comment by casella** [comment] 2022-01-23 23:43
@mahge of course you're right. We should figure out why flowTableAT is also (wrongly) part of the time varying output, and fix that.

**Comment by casella** [comment] 2022-03-07 13:29
For 1.19.0 we can just change the order of reading the two data_1 and data_2 variables, so that the right results are not overwritten by the bogus one. We can do it on the 1.19.0 branch, and leave the thing on master so it's not lost.

**Closed** 2022-03-21 13:32 UTC
Labels: COMP/OMEdit
