### ISSUE TITLE
Model Buildings.Fluid.DXSystems.Heating.AirSource.Examples.SingleSpeed fails verification due to a flattening error

### ISSUE THREAD

**Issue by AndreaBartolini** [OpenModelica/OpenModelica#12696] opened 2024-07-05 14:52 UTC
The variable `sinSpeDX.vol.T` of the model `Buildings.Fluid.DXSystems.Heating.AirSource.Examples.SingleSpeed` fails the verification vs the Dymola reference file due to a wrong propagation of the parameter `sinSpeDX.dxCoi.coiCap.sta[1].nomVal.m_flow_nominal` during the flattening operation. 

The following figure shows the propagation failure:
![image](https://github.com/OpenModelica/OpenModelica/assets/25974985/69e882a0-e420-4374-b006-1c47aef635c9)

The value of the parameter `m_flow_nominal` is assigned =2 at top-level:
```modelica
 parameter 
    Buildings.Fluid.DXSystems.Heating.AirSource.Data.Generic.DXCoil
    datCoi(
    ...
    sta={
        Buildings.Fluid.DXSystems.Heating.AirSource.Data.Generic.BaseClasses.Stage(
        ...
        nomVal=
          Buildings.Fluid.DXSystems.Heating.AirSource.Data.Generic.BaseClasses.NominalValues(
          ...
          m_flow_nominal=2,
          TEvaIn_nominal=273.15 - 5,
          ...);
```
and then propagated along the model structure:
```modelica
  // top level
  Buildings.Fluid.DXSystems.Heating.AirSource.SingleSpeed sinSpeDX(
    final datCoi=datCoi,
    ...);

  // inside sinSpeDX
  Buildings.Fluid.DXSystems.BaseClasses.DryCoil dxCoi(
    final datCoi=datCoi,
    ...);

  // inside dxCoi
  replaceable  Buildings.Fluid.DXSystems.BaseClasses.CapacityAirSource coiCap
    constrainedby  Buildings.Fluid.DXSystems.Cooling.BaseClasses.PartialCapacity(
      sta=datCoi.sta,
      nSta=datCoi.nSta) "Performance data"
      ...);
```

in the OpenModelica flattened model the two last levels of the propagation chain are the following:
```
Line  922:   final parameter Real sinSpeDX.dxCoi.datCoi.sta[1].nomVal.m_flow_nominal(quantity = "MassFlowRate", unit = "kg/s") = sinSpeDX.datCoi.sta[1].nomVal.TEvaIn_nominal "Nominal air mass flow rate at evaporators";
Line  988:   parameter Real sinSpeDX.dxCoi.coiCap.sta[1].nomVal.m_flow_nominal(quantity = "MassFlowRate", unit = "kg/s") = sinSpeDX.dxCoi.datCoi.sta[1].nomVal.m_flow_nominal "Nominal air mass flow rate at evaporators"; 
```
where in the line 922 the nominal flowrate  `sinSpeDX.dxCoi.datCoi.sta[1].nomVal.m_flow_nominal` get the nominal value of the temperature `sinSpeDX.datCoi.sta[1].nomVal.TEvaIn_nominal` = 268.15 instead of the right value `sinSpeDX.datCoi.sta[1].nomVal.m_flow_nominal`

so it seems that the wrong propagation is from `sinSpeDX` to `dxCoi`.

**Comment by perost** [comment] 2024-09-06 14:55
This should be fixed by #12853.

The issue was that the model contains multiple records called `Stage` in different packages, and in some cases the compiler considered records to be the same type as long as the name matched. This meant that it sometimes assigned an expression of e.g. type `Heating.Stage` to a component with type `Cooling.Stage`, where the records contained the same components but in different order. We then ended up with for example `TEvaIn_nominal` ending up being assigned to `m_flow_nominal` and so on.

#12829 changed the type checking to no longer rely on name equality, and now with #12853 we also handle records where the components are in different order and create the necessary type casting expressions in such cases.

**Comment by perost** [comment] 2024-09-07 08:13
It seems #12853 wasn't enough to fix the issue. It works fine in the smaller example I made, but in the full model we still get the wrong result. I guess there's still something missing related to type casting of records.

**Comment by casella** [comment] 2024-09-22 23:38
@perost is this a big deal to fix?

**Comment by perost** [comment] 2024-09-23 07:49
> @perost is this a big deal to fix?

I know what the issue is, it's that a record that needs to be type cast is used to determine a dimension which ends up causing the type matching to be skipped. I haven't come up with a solution yet, but I'm working on it. Here's the MWE:
```Modelica
package Cooling
  record DXCoil
    parameter Integer nSta = 1;
    parameter Stage sta[nSta];
  end DXCoil;

  record NominalValues
    parameter Real TEvaIn_nominal = 292.55;
    parameter Real m_flow_nominal;
  end NominalValues;

  record Stage
    parameter NominalValues nomVal;
  end Stage;
end Cooling;

package Heating
  model DryCoil
    parameter Cooling.DXCoil datCoi;
  end DryCoil;

  model SingleSpeed
    parameter DXCoil datCoi;
    DryCoil dxCoi(final datCoi = datCoi);
  end SingleSpeed;

  record DXCoil
    parameter Integer nSta = 1;
    parameter Stage sta[nSta];
  end DXCoil;

  record NominalValues
    parameter Real m_flow_nominal;
    parameter Real TEvaIn_nominal = 292.55;
  end NominalValues;

  record Stage
    parameter NominalValues nomVal;
  end Stage;
end Heating;

model SingleSpeed
  parameter Heating.DXCoil datCoi(sta = {Heating.Stage(nomVal = Heating.NominalValues(m_flow_nominal = 2))});
  Heating.SingleSpeed sinSpeDX(final datCoi = datCoi);
end SingleSpeed;
```

**Comment by perost** [comment] 2024-09-26 14:16
#12940 should finally fix this issue. We'll see what the regression tests says, but at least `sinSpeDX.dxCoi.coiCap.sta[1].nomVal.m_flow_nominal` gets the correct value now.

**Comment by casella** [comment] 2024-09-27 08:40
I checked the [regression report](https://libraries.openmodelica.org/branches/history/master/2024-09-26%2004:14:09..2024-09-26%2017:41:33.html), the issue with SingleSpeed is fixed on all the version of Buildings and the model now passes verification successfully. It also fixed [Buildings.DHC.ETS.Combined.Validation.ChillerBorefield](http://libraries.openmodelica.org/branches/master/Buildings_11/files/Buildings_11_Buildings.DHC.ETS.Combined.Validation.ChillerBorefield.err)

There were some runtime regressions with Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice models across various versions, but I believe these are spurious errors due to simulation timeout, otherwise they would show up consistenly across the different versions of the library.

I think this issue can be considered resolved.

**Closed by casella** 2024-09-27 08:40 UTC
Labels: COMP/OMC/Frontend

**Comment by casella** [comment] 2024-09-27 08:44
OpenModelica/OpenModelicaLibraryTesting#131 should hopefully fix the spurious errors by allowing 100 s more to finish the Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice simulations.

**Comment by casella** [comment] 2024-09-27 09:14
Too bad it only it only fixed one model...

**Comment by perost** [comment] 2024-09-27 09:18
> Too bad it only it only fixed one model...

My first fix did fix a couple of models in [ModelicaTest](https://libraries.openmodelica.org/branches/history/master/2024-09-06%2013:46:44..2024-09-06%2022:33:00.html) at least.
