### ISSUE TITLE
Parameters are marked editable in Variables Browser in OMEdit with option Evaluate all parameters enabled 

### ISSUE THREAD

**Issue by adeas31** [OpenModelica/OpenModelica#7402] opened 2021-04-22 16:34 UTC
### Description

Parameters are marked as editable in the Variables Browser in OMEdit when a certain combination of flags are used.

#### Case 1

 - Run OMEdit and go to "Tools->Options->Simulation".
 - Check option "Evaluate all parameters (faster simulation, cannot change them at runtime)" and check option "Enable old frontend for code generation".
 - Open the file [CircuitoElectrico.zip](https://github.com/OpenModelica/OpenModelica/files/6359863/CircuitoElectrico.zip). 
 - Simulate the model "CircuitoElectrico".
 - The parameters "C1, L1, R1 and R2" are editable.

#### Case 2

 - Right click the model "CircuitoElectrico" and open "Simulation Setup".
 - Under the "Translation Flags" tab uncheck "Enable old frontend for code generation".
 - Simulate the model "CircuitoElectrico".
 - The parameters "C1, L1, R1 and R2" are not editable.

### Expected Behavior

The parameters should not be editable in both cases since the option "Evaluate all parameters (faster simulation, cannot change them at runtime)" is checked.

### Version and OS

 - OpenModelica Version: v1.17.0 (64-bit)
 - OS: Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable: Modelica Standard Library - Version 4.0.0

**Comment by adeas31** [comment] 2021-04-22 16:39
See also #7360

**Comment by adeas31** [comment] 2021-04-22 16:40
@kabdelhak seems to be some issue with code generation.

**Comment by kabdelhak** [comment] 2021-04-23 06:32
It seems more like a new to old frontend problem to me, but i can check!

**Comment by perost** [comment] 2021-04-26 13:13
The new frontend marks the parameters as final while the old doesn't. I'm not sure what's used to determine if a parameter can be changed or not though, but if a parameter is final it should obviously not be allowed to be modified.

**Comment by adeas31** [comment] 2021-04-26 13:22
There is an attribute `isValueChangeable` in the `model_init.xml` file that is used by OMEdit.

**Comment by perost** [comment] 2021-04-26 14:38
I took a closer look, and I get the exact behaviour mentioned in the description. I.e. the parameters are not editable when using the new frontend and evaluate all parameters, but they are when using the old frontend. 

So this is an issue with the old frontend, since the evaluated parameters shouldn't be editable. The old frontend doesn't mark evaluated parameters as final, which might not be so easy to fix. Is there a reason why you want to use the old frontend in this case?

**Comment by kabdelhak** [comment] 2021-04-26 14:44
> I took a closer look, and I get the exact behaviour mentioned in the description. I.e. the parameters are not editable when using the new frontend and evaluate all parameters, but they are when using the old frontend.
> 
> So this is an issue with the old frontend, since the evaluated parameters shouldn't be editable. The old frontend doesn't mark evaluated parameters as final, which might not be so easy to fix. Is there a reason why you want to use the old frontend in this case?

They are marked as editable but it doesn't actually change anything right? Seems bad, but the new frontend should be used anyways.

**Comment by perost** [comment] 2021-04-26 14:49
> > I took a closer look, and I get the exact behaviour mentioned in the description. I.e. the parameters are not editable when using the new frontend and evaluate all parameters, but they are when using the old frontend.
> > So this is an issue with the old frontend, since the evaluated parameters shouldn't be editable. The old frontend doesn't mark evaluated parameters as final, which might not be so easy to fix. Is there a reason why you want to use the old frontend in this case?
> 
> They are marked as editable but it doesn't actually change anything right? Seems bad, but the new frontend should be used anyways.

Not in this case, but the old frontend can be a bit inconsistent about where it evaluates parameters. I.e. it might evaluate a parameter only in some places and leave it in others, which could cause issues if the value of the parameter was later changed. The new frontend makes sure that if a parameter is evaluated anywhere it's also evaluated everywhere.

**Comment by adeas31** [comment] 2021-04-26 14:49
Yes. I guess the change is ignored and that is what reported in #7360 by @valfaro

**Comment by casella** [comment] 2021-04-26 18:45
If the issue is only present with the old front-end, I guess this ticket can be closed with milestone 1.17.0 (which we still don't have among the tags, I hope Adrian can get through that soon), since the new frontend is used there by default. 

Do I miss something?

**Comment by adeas31** [comment] 2021-04-27 12:00
But we still have option `Enable old frontend for code generation` in OMEdit. If we are providing a way to use old frontend then it should work as well. What's the point of having an option that is faulty.

Or maybe the option `Evaluate all parameters (faster simulation, cannot change them at runtime)` can be renamed to `"Evaluate all parameters (faster simulation, cannot change them at runtime. Do not work with old frontend)"` incase we don't want to put effort on fixing bugs in old frontend.

**Comment by perost** [comment] 2021-04-27 12:20
We generally don't fix issues in the old frontend anymore, it's just provided as a temporary fallback option right now and users can't expect that everything will work with it.

**Comment by casella** [comment] 2021-04-27 13:00
> But we still have option `Enable old frontend for code generation` in OMEdit. If we are providing a way to use old frontend then it should work as well. What's the point of having an option that is faulty.

It's meant as a backup option for the (now very rare) casese where the NF fails but the OF works. The chance that the NF fails, the OF works, _and_ we have this issue is very low, and we should accept it. We shouldn't spend any more time maintaining the OF, that decision was taken a long time ago.

Besides, this issue is slightly annoying, but not a critical one. There are hundreds of more pressing issues we should focus on right now.

> Or maybe the option `Evaluate all parameters (faster simulation, cannot change them at runtime)` can be renamed to `"Evaluate all parameters (faster simulation, cannot change them at runtime. Do not work with old frontend)"` incase we don't want to put effort on fixing bugs in old frontend.

I think there is already too much text there. Can we make is such that if you turn on the evaluate parameters option, the use old front-end is disabled automatically?

**Comment by adeas31** [comment] 2021-04-27 13:19
> I think there is already too much text there. Can we make is such that if you turn on the evaluate parameters option, the use old front-end is disabled automatically?

Agree but that is the easiest and quickest solution for now. We anyway I have longer texts than this one in the GUI. Disabling the option when the other option is checked will work but not in the case when we explicitly enable old frontend option when the simulation fails. In that case we need to disable evaluate all parameters and doing things that are not apparent to the user are not nice.

**Comment by casella** [comment] 2021-05-06 11:07
OK. I'm fine with `Evaluate all parameters (faster simulation, cannot change them at runtime, does not work with old frontend)`.

@adeas31, can you proceed this way and then close this ticket? Thanks!

**Closed** 2021-05-10 07:51 UTC
Labels: COMP/OMEdit, bug
