### ISSUE TITLE
Segmentation fault with wrong use of variableFilter

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#7945] opened 2021-09-28 13:52 UTC
### Description

A wrong use of `variableFilter` will result in a segmentation fault.

### Steps to Reproduce

```modelica
model mwe
  Real x;
  Real y;
equation
  der(x) = 2*time;
  der(y) = 3*time;
end mwe;
```

```bash
./mwe -override=variableFilter=x,y
```

Output from gdb:
```gdb
(gdb) bt
#0  0x00007ffff7bd2d62 in doOverride (mi=0x7fffffffcdc8, modelData=0x7fffffffd5e8, override=0x7fffffffdf7c "variableFilter=x,y", overrideFile=0x0)
    at ./simulation/simulation_input_xml.c:1008
#1  0x00007ffff7bcd643 in read_input_xml (modelData=0x7fffffffd5e8, simulationInfo=0x7fffffffd810) at ./simulation/simulation_input_xml.c:528
#2  0x00007ffff7bc7a3a in initRuntimeAndSimulation (argc=2, argv=0x7fffffffdbd8, data=0x7fffffffd3f0, threadData=0x7fffffffd2d0) at ./simulation/simulation_runtime.cpp:1048
#3  0x00007ffff7bc827a in _main_SimulationRuntime (argc=2, argv=0x7fffffffdbd8, data=0x7fffffffd3f0, threadData=0x7fffffffd2d0) at ./simulation/simulation_runtime.cpp:1160
#4  0x0000000000405463 in main ()
```

### Expected Behavior

Even though `-override=variableFilter=x|y` using a regex would be the correct input the simulation shouldn't crash for wrong input, but tell the user to use a regex.

### Version and OS

 - OpenModelica Version: OMCompiler v1.19.0-dev.237+g923be1b6c0
 - OS: Ubuntu Focal

**Comment by casella** [comment] 2021-09-28 15:45
@mahge, could you please check?

**Comment by mahge** [comment] 2021-09-29 08:00
#7948 should fix the segmentation fault. 

Idk if we should try to recover or ignore the error and continue. The fix just exits if it can not recognize the flags formatting.

**Comment by casella** [comment] 2021-09-29 09:51
Thanks @mahge! 

IMO if there are wrong flags an error message should be issued and the executable should exit with an error code, so that CI scripts would see that something went wrong.  Is that the current behaviour once #7948 is merged in?

The rationale is that an end user should receive clear feedback about his input. If there is something wrong he should get clear indication of what is wrong; of course crashing is not an option, but also carrying along as if all is fine, e.g. by simply ignoring the flag, is not a good idea, because you may get unexpected output without a clue why it is so.

**Comment by mahge** [comment] 2021-09-29 10:27
I agree. 


> IMO if there are wrong flags an error message should be issued and the executable should exit with an error code, so that CI scripts would see that something went wrong. Is that the current behaviour once #7948 is merged in?

Yes that would be the expected behavior. Right now it terminates with error code 255 which will be failure for anything that checks for success.

I will merge the PR then.

**Closed** 2021-09-29 10:28 UTC
Labels: COMP/Runtime
