### ISSUE TITLE
FMI export broken in OMEdit for Cpp

### ISSUE THREAD

**Issue by rfranke** [OpenModelica/OpenModelica#13103] opened 2024-11-01 07:58 UTC
### Description

OMEdit until 1.24.0 used to support multiple target languages for FMI export. Moreover, recently released versions of OpenModelica started to shorten and modify the model name during FMI export, e.g. `Integratore194` instead of `Modelica.Blocks.Continuous.Integrator`.

### Steps to Reproduce

- go to Tools -> Options -> Simulation -> Target Language: and configure Cpp
- browse to e.g. Modelica.Blocks.Continuous.Integrator
- right click on that model and select Export -> FMU

This triggers the following error message:
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_COLOR_MAKEFILE=OFF ..
CMake Error: The source directory "/tmp/OpenModelica/OMEdit/Integratore194/824.fmutmp/sources" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Generated cmake target files failed. Exited with code 1.
```

### Expected Behavior

The message should look like:
```
[7] 07:42:44 Scripting Notification
The FMU is generated at /tmp/OpenModelica/OMEdit/Modelica.Blocks.Continuous.Integrator/Modelica.Blocks.Continuous.Integrator.fmu.
```

### Version and OS

 - OpenModelica Version: v1.25.0-dev.106+g982563026f

**Comment by arun3688** [comment] 2024-11-01 09:06
@rfranke i guess the fmu export for the cpp runtime is not configured with cmake build i guess, We made some significant improvement of fmi export in OMEdit to be more interactive to users, The recent version do not shorten `modelName` but the fmu temp directories path are shortened to avoid long path conflicts. I will try to fix it

**Comment by casella** [comment] 2024-11-04 11:23
@arun3688 also please add one test case to the core testuite where you export an FMU using the C++ runtime, so we check that we don't break it when committing new stuff.

**Comment by arun3688** [comment] 2024-11-04 11:26
@casella we already do that `https://github.com/OpenModelica/OpenModelica/tree/master/testsuite/openmodelica/cppruntime/fmu/modelExchange/2.0`

**Comment by bilderbuchi** [comment] 2024-11-04 12:18
> @arun3688, please consider #13121 to fix this issue in a proper way.

If I understand https://github.com/OpenModelica/OpenModelica/issues/13103#issuecomment-2451555119 correctly, the cause is that something in the cpp cmake setup was not adjusted correctly to account for the new shorter hashed names.
Would then a "proper" fix rather be to adjust that cmake setup to the new situation?

Adding yet another option like in #13121 for things to subtly differ increases the combinatorical complexity of the option space, needing more tests to cover all equivalence classes (if that is something you strive for), and will heap more barriers onto the difficulty to reproduce problems between developers, as there is one more option to keep/make aligned.
Or am I totally off-track here?

**Comment by bilderbuchi** [comment] 2024-11-04 12:25
> ### Steps to Reproduce
> 
>     * go to Tools -> Options -> Simulation -> Target Language: and configure Cpp
> 
>     * browse to e.g. Modelica.Blocks.Continuous.Integrator
> 
>     * right click on that model and select Export -> FMU

For what it's worth, using OpenModelica v1.25.0-dev-125-gfb3dfb2cc5 on Windows 10, I cannot reproduce the problem as described.  I successfully get an FMU as desired.

**Comment by arun3688** [comment] 2024-11-04 12:27
> If I understand [#13103 (comment)](https://github.com/OpenModelica/OpenModelica/issues/13103#issuecomment-2451555119) correctly, the cause is that something in the cpp cmake setup (or in the choices made by the GUI vs plain omc) was not adjusted correctly to account for the new shorter hashed names.
> Would then a "proper" fix rather be to adjust that cmake setup to the new situation?

No this is completely different issue, the fmu export for cpp runtime is not configured with cmake build and it uses only makefile to compile the source code, So the code needs to be adjusted to use make file to export the fmu for cpp runtime

**Comment by bilderbuchi** [comment] 2024-11-04 12:28
> the fmu export for cpp runtime is not configured with cmake build and it uses only makefile to compile the source code

Why does his output then show a `cmake` invocation? :puzzled:?

**Comment by arun3688** [comment] 2024-11-04 12:29
> For what it's worth, using OpenModelica v1.25.0-dev-125-gfb3dfb2cc5 on Windows 10, I cannot reproduce the problem as described. I successfully get an FMU as desired.
> Maybe this is fixed already?

no this is not fixed, i guess the target language is not changed to `cpp`, may be you have to restart the OMEdit and then try to set the target language to CPP and then export the fmu and you should reproduce the problem

**Comment by bilderbuchi** [comment] 2024-11-04 12:30
> no this is not fixed, i guess the target language is not changed to `cpp`, may be you have to restart the OMEdit and then try to set the target language to CPP and then export the fmu and you should reproduce the problem

yes I just realised, I had some mixup, and actually reproduce the problem.

**Comment by casella** [comment] 2024-11-04 15:44
> Adding yet another option like in #13121 for things to subtly differ increases the combinatorical complexity of the option space, needing more tests to cover all equivalence classes (if that is something you strive for), and will heap more barriers onto the difficulty to reproduce problems between developers, as there is one more option to keep/make aligned.

OMC was developed in a Posix environment and then ported to Windows using MinGW. Unfortunately that doesn't work well with long filenames. If we could solve this issue at the root, there won't be any need of such hacks. Otherwise we have to balance the requirements of people like you running stuff in Windows, and people like @rfranke doing stuff on Linux.

**Comment by bilderbuchi** [comment] 2024-11-05 07:25
> Otherwise we have to balance the requirements of people like you running stuff in Windows, and people like @rfranke doing stuff on Linux.

And I'm not negating that! (We also use OM on Linux, not exclusively Linux)
I suspect that optionally disabling the shortened names will not fix the problem, though. After all, I observe the same thing on Windows. If you add an option to make the paths long again for rfranke, the Cpp FMU generation from OMEdit will _still_ be broken for all Windows users! What am I missing?

Isn't the root cause not the makefile-only build system for cpp only? Or have I not asked[ "why" often enough](https://en.wikipedia.org/wiki/Five_whys)? 
Would using cmake for cpp (to generate the makefiles), too, solve the issue at hand? And at the same time reduce your build system complexity by eliminating this duplication?

**Comment by casella** [comment] 2024-11-05 14:09
@bilderbuchi, absolutely. As far as I understand, this ticket is about **two** issues, not one

1. We switched to CMAKE and that broke something with C++ FMUs
2. Additionally, we shortened file names to avoid long path name problems on Windows, and @rfranke found this unnecessary and confusing as a Linux user

My comments were related to part 2. To which extent these two issues are related, I don't know, but @arun3688 does, so I'm confident everything will be fine.

I guess we should always try have single-issue tickets as much as we can. Otherwise managing them become even more frustrating and time consuming than it already is 😃

**Comment by casella** [comment] 2024-11-05 14:10
> @casella we already do that `https://github.com/OpenModelica/OpenModelica/tree/master/testsuite/openmodelica/cppruntime/fmu/modelExchange/2.0`

@arun3688  I guess we aren't doing that hard enough, otherwise @rfranke wouldn't have reported a problem. Do I miss something?

**Comment by arun3688** [comment] 2024-11-05 14:24
> @arun3688 I guess we aren't doing that hard enough, otherwise @rfranke wouldn't have reported a problem. Do I miss something?
The main problem is, our C runtime fmu's are using `cmake` to build the `fmu's` and the cpp runtime uses `Makefile` to build the `Fmu's` and still the command line API works for the cpp runtime. Apart from this i do not see any other problem as of now

**Comment by adrpo** [comment] 2024-11-05 14:57
It should be an easy fix, if a cpp FMU is build, call make instead of cmake to build it. I will have a quick look.

**Comment by casella** [comment] 2024-11-05 18:59
I had a chat with @adrpo, we figured this out. It's complicated, but the solution is simple.

In 2022-2023, @AnHeuermann worked on the CMake FMU builds and introduced the [--fmuCMakeBuild](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-fmucmakebuild) flag, which is currently true by default. Which means, if you don't set it, FMUs are generated with CMake, if you set it to false, the old GNU make/autotool stuff is used.

There is one exception, though, which is of course undocumented 😅: since Andreas only implemented the FMU CMake stuff for the C runtime, he made it so that if you set `--simCodeTarget=Cpp`, the [buildModelFMU()](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html#buildmodelfmu) API function automatically sets `--fmuCMakeBuild=false`. Hence:
- the generation of C++ FMUs from command line scripts still worked, 
- so did the C++ FMU export test case in the testsuite [exposeLocalIOs.mos](https://github.com/OpenModelica/OpenModelica/blob/master/testsuite/openmodelica/cppruntime/fmu/modelExchange/2.0/exposeLocalIOs.mos)
- the generation of C++ FMUs from OMEdit also still worked

On Sep 23, @arun3688 merged in PR #12891 in 1.25.0-dev, with the goal to give visual feedback about the FMI generation process. This separated the FMU build process in two steps. First `translateModelFMU()` is called to generate the C code. Then, OMEdit takes care of building the C code. But when it does it, it does not do the undocumented magicke of using make instead of cmake. Hence the trouble @rfranke is experiencing.

@arun3688 to fix this issue you just need to check the target language, and if it is set to Cpp, change from cmake to make build.

The problem here is that we are not testing the GUI in an automated way, so these issues are just discovered by end users. This has been in our wish list for a long time, but it's not easy, considering all possible combinations of user actions and OS platforms.

**Comment by casella** [comment] 2024-11-05 19:02
Regarding the hashed FMU names pointed out by @rfranke, this is a completely orthogonal issue, which is discussed in #13121. One enemy at a time, please 😃

**Comment by casella** [comment] 2024-11-05 19:11
@arun3688 please also see #13137.

**Comment by casella** [comment] 2024-11-05 19:15
In retrospect, the design of the `--fmuCMakeBuild` flag was probably not optimal. I would have called it `--fmuBuild` with values `default`, `make`, `cmake`, with default being defined based on the target language.

Maybe we could still change that now, but we need to be careful because there are other flags depending on it, e.g. [--fmuRuntimeDepends](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-fmuruntimedepends)

@adrpo, what do you think?

**Comment by casella** [comment] 2024-11-05 19:16
Of course we should also document the undocumented magicke. Not really sure where to do it and how to do it properly.

**Comment by arun3688** [comment] 2024-11-05 23:16
> It should be an easy fix, if a cpp FMU is build, call make instead of cmake to build it. I will have a quick look.

Yes that is what i am working on, i am fixing the code in OMEdit, It should be fixed by this week

**Comment by casella** [comment] 2024-11-11 10:36
@rfranke I'm closing this now since it works for us. Please re-open if there are any remaining issues on this topic.

**Closed by casella** 2024-11-11 10:36 UTC
Labels: bug, COMP/GUI/OMEdit

**Comment by rfranke** [comment] 2024-11-15 13:37
Thank you for the fix. Nice to see the compiler output in OMEdit now. I fixed a warning that had been there for a long time.

**Comment by casella** [comment] 2024-11-15 14:28
@bilderbuchi would you like to give it a try in your spare time? 😃

**Comment by bilderbuchi** [comment] 2024-11-15 14:42
That's unfortunately unrealistic. 
There's been some movement on the OSS contribution here aspect lately, maybe that will be resolved "soon" >.<. In the meantime, I can just document these things as completely and actionably as possible, e.g. like in #12821. :-/

**Comment by casella** [comment] 2024-11-15 16:35
> That's unfortunately unrealistic. There's been some movement on the OSS contribution here aspect lately, maybe that will be resolved "soon" >.

Quoting John Cleese in the immortal [skit on the argument clinic](https://www.google.com/search?client=firefox-b-d&q=argument+clinic#fpstate=ive&vld=cid:fa458ef5,vid:wxrbOVeRonQ,st:0), "I could be doing that in my spare time" 😄 

Seriously, I totally understand. Please keep us posted if the situation changes.

>In the meantime, I can only document these things as completely and actionably as possible, e.g. like in #12821

That is very much appreciated!

**Comment by bilderbuchi** [comment] 2024-11-18 06:59
> > That's unfortunately unrealistic. There's been some movement on the OSS contribution here aspect lately, maybe that will be resolved "soon" >.
> 
> Quoting John Cleese in the immortal [skit on the argument clinic](https://www.google.com/search?client=firefox-b-d&q=argument+clinic#fpstate=ive&vld=cid:fa458ef5,vid:wxrbOVeRonQ,st:0), "I could be coding in my spare time" 😄
> 
> Seriously, I totally understand. Please keep us posted if the situation changes.

Believe me, I'm well aware of the multifaceted pressures surrounding OSS development. For reasons that I'm not going to discuss here, last year I had to step back (for now) from maintaining/developing a [Python package](https://github.com/pymeasure/pymeasure/) in my spare time, that I had been helping to keep alive and active over several years. 
So no, that is currently simply not in the cards. :-/ I'll keep doing what I can.
