### ISSUE TITLE
Issue with the NB when handling when-algorithms

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12423] opened 2024-05-14 21:55 UTC
Follow-up of #12409. This MWE 
```modelica
model TestEnumerationWhen
  type T = enumeration(off, on);
  T t(start = T.off, fixed = true);
algorithm
  when t == T.off and time > 0.4 and time < 0.6 then
    t := T.on;
  elsewhen t == T.on and time > 0.8 then 
    t := T.off;
  end when;
end TestEnumerationWhen;
```
is such that the when-condition in the generated code looks something like this:
```C
if (0) {
  ...
} else if (0) {
  ...
}
```
This should be investigated and fixed since it will probably affect all PowerGrids models involving breaker opening and closing events.

**Comment by phannebohm** [comment] 2024-05-17 14:04
Took me a while to realize, but the model should use `pre(t)` in the conditions. Otherwise there is an algebraic loop between the conditions and the body of the equation.
```modelica
model TestEnumerationWhen
  type T = enumeration(off, on);
  T t(start = T.off, fixed = true);
algorithm
  when pre(t) == T.off and time > 0.4 and time < 0.6 then
    t := T.on;
  elsewhen pre(t) == T.on and time > 0.8 then 
    t := T.off;
  end when;
end TestEnumerationWhen;
```

**Comment by phannebohm** [comment] 2024-05-17 15:05
The problem is not with enumerations I think. It's with _when-statements in algorithms_.

Maybe the empty list in this line should not be an empty list:
https://github.com/OpenModelica/OpenModelica/blob/beb22abc38db58fecf6df847fbd47fb62554f644/OMCompiler/Compiler/NFFrontEnd/NFConvertDAE.mo#L1008

**Comment by casella** [comment] 2024-05-17 15:41
BTW, I also tried
```modelica
model TestEnumerationWhen
  type T = enumeration(off, on);
  T t(start = T.off, fixed = true);
equation
  when pre(t) == T.off and time > 0.4 and time < 0.6 then
    t = T.on;
  elsewhen pre(t) == T.on and time > 0.8 then 
    t = T.off;
  end when;
end TestEnumerationWhen;
```
It works with the OB, but it fails with the NB in the same way as the original model
```
Internal error NSimVar.SimVars.splitByType failed because of unhandled Variable t.
```

**Comment by phannebohm** [comment] 2024-05-17 15:51
> BTW, I also tried
> 
> ```modelica
> model TestEnumerationWhen
>   type T = enumeration(off, on);
>   T t(start = T.off, fixed = true);
> equation
>   when pre(t) == T.off and time > 0.4 and time < 0.6 then
>     t = T.on;
>   elsewhen pre(t) == T.on and time > 0.8 then 
>     t = T.off;
>   end when;
> end TestEnumerationWhen;
> ```
> 
> It works with the OB, but it fails with the NB in the same way as the original model
> 
> ```
> Internal error NSimVar.SimVars.splitByType failed because of unhandled Variable t.
> ```

Since #12419 this model should build and simulate. The results are wrong because we didn't enter the correct start value into the init.xml. That bug is fixed in #12436, so as soon as the PR is merged the model should work with the NB.

**Comment by casella** [comment] 2024-05-20 08:54
Just started job [#7894](https://test.openmodelica.org/jenkins/job/LibraryTesting/job/LibraryTest/7894/), let's see if it improves things.

**Comment by casella** [comment] 2024-05-20 18:15
This is the[ regression report](https://libraries.openmodelica.org/branches/history/newInst-newBackend/2024-05-17%2016:01:18..2024-05-20%2011:00:01.html). A couple of improvements on TestLeadLag and test DerivativeLag.

[PowerGrids.Electrical.Test.TestOneBusTransmissionLineWithBreakersOneLoad](https://libraries.openmodelica.org/branches/newInst-newBackend/PowerGrids/files/PowerGrids_PowerGrids.Electrical.Test.TestOneBusTransmissionLineWithBreakersOneLoad.err) now fails with
```
Error: Internal error NBDetectStates.collectPreAndPrevious failed because of unexpected expression pre(, true}).
```

**Comment by AustraleanPerson** [comment] 2024-05-22 21:39
Shouldn't we use here 
`time >= 0.8` insted of `time > 0.8`
to get time event insted of state event?

**Comment by casella** [comment] 2024-05-23 13:43
Absolutely, though I'm not sure OMC is smart enough to do so when the condition is combined with others. In any case, the MWE should be:
```modelica
model TestEnumerationWhenAlg
  type T = enumeration(off, on);
  T t(start = T.off, fixed = true);
algorithm
  when t == T.off and time >= 0.4 and time < 0.6 then
    t := T.on;
  elsewhen t == T.on and time >= 0.8 then 
    t := T.off;
  end when;
end TestEnumerationWhenAlg;
```
or
```modelica
model TestEnumerationWhenEq
  type T = enumeration(off, on);
  T t(start = T.off, fixed = true);
equation
  when pre(t) == T.off and time >= 0.4 and time < 0.6 then
    t = T.on;
  elsewhen pre(t) == T.on and time >= 0.8 then 
    t = T.off;
  end when;
end TestEnumerationWhenEq;
```

**Closed** 2024-09-13 15:07 UTC
Labels: COMP/OMC/New Backend
