### ISSUE TITLE
OMEdit does not show simple numerical parameter

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#9715] opened 2022-11-17 07:57 UTC
### Description
OMEdit does not show the numerical value of parameters anymore in a simple case

### Steps to Reproduce
- create a new model.
- drag a resistor
- select as value "1.0"
=> the diagram will show "R=R" instead of "R=1.0".

### Version and OS

 - OpenModelica Version: 1.21.0-dev30
 - OS: Ubuntu 22.04

**Comment by bilderbuchi** [comment] 2022-11-17 09:22
Is this not a duplicate of #8966, which you also participated in?

**Comment by bilderbuchi** [comment] 2022-11-17 09:23
Related: #8966

**Comment by casella** [comment] 2022-11-17 10:57
@ceraolo please check the latest comments in #8966. You can follow up there.

**Closed by casella** 2022-11-17 10:57 UTC

**Comment by ceraolo** [comment] 2022-11-17 15:03
> @ceraolo please check the latest comments in #8966. You can follow up there.

ok
