### ISSUE TITLE
FMU export using cross-compilation is broken on Windows

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#10462] opened 2023-03-28 21:02 UTC
### Description

Trying to export a simple FMU on OpenModelica 1.20.0 is broken on Windows. 

### Steps to Reproduce
Run: `"C:\Program Files\OpenModelica1.20.0-64bit\bin\omc.exe"  --fmuRuntimeDepends=none testFMU.mos` 
where testFMU.mos is:
```
loadModel(Modelica); getErrorString();
buildModelFMU(Modelica.Blocks.Sources.Sine, platforms={"arm-linux-gnueabihf docker run --pull=never multiarch/crossbuild"}); getErrorString();
```
Fails with `sh: 1: mingw32-make: not found`

(See also [Complete.log](https://github.com/OpenModelica/OpenModelica/files/11094091/Complete.log))

### Expected Behavior

It should generate `Modelica.Blocks.Sources.Sine.fmu` as it does on Linux.

### Version 

 - OpenModelica Version: OpenModelica v1.20.0 (64-bit)
 - OS: e.g. Windows 10, 64 bit
 - MSL 4.0.0

**Comment by AnHeuermann** [comment] 2023-03-29 10:10
Already fixed in https://github.com/OpenModelica/OpenModelica/commit/dd7b8e4592f8c54546c431f4005a2211bbe7469d.

Your example works for me with the nightly build (`v1.21.0-dev-398-g92b6780f6a-cmake`, Windows 11):

```
# omc testFMU.mos --fmuRuntimeDepends=none
true
""
"X:/path/to/issue-10462/Modelica.Blocks.Sources.Sine.fmu"
"[C:/Users/USERNAME/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Blocks/Sources.mo:295:5-295:63:writable] Warning: Parameter f has no value, and is fixed during initialization (fixed=true), using available start value (start=1.0) as default value.
Notification: OS is Windows and docker platform detected. Using CMake to build FMU.
```

For an installed OpenModelica `v1.20.0` this fails with the same error.
So you need to update to the nightly build or wait for the next release.

**Comment by AnHeuermann** [comment] 2023-03-29 10:11
Sorry for the confusion in https://github.com/OpenModelica/OpenModelica/discussions/10411. I thought this was already available in the last release, but apparently I did it in January this year.

**Comment by AnHeuermann** [comment] 2023-03-29 11:19
Duplicate of https://github.com/OpenModelica/OpenModelica/issues/10002, closing this.

**Closed by AnHeuermann** 2023-03-29 11:19 UTC
Labels: duplicate

**Comment by dietmarw** [comment] 2023-03-29 12:04
OK thanks, I will test it with a nightly install on the windows box then.

**Comment by dietmarw** [comment] 2023-03-29 12:45
Just tested with the nightly and it works for Euler but not for CVODE.

**Comment by AnHeuermann** [comment] 2023-03-29 13:05
Yes. Cross-compilation is really difficult and the more dependencies we add the harder it gets.
If you want to include CVODE into the FMU, the compiler would need SUNDIALS binaries for `arm-linux-gnueabihf`.

Generalizing the compilation process of SUNDIALS is tricky, so we didn't include it.
We would need to include all source files of SUNDIALS into the install directory of OpenModelica and cross-compile it from one arbitrary system to another arbitrary system. So I guess we won't include this feature in near future.
But anyway this should be new issue if you really need this.

**Comment by dietmarw** [comment] 2023-03-29 13:09
Ah OK, that makes sense. I'll see if I can live with Euler or do need CVODE and will eventually create a new ticket then.

**Comment by AnHeuermann** [comment] 2023-03-29 13:19
Oh yes, tt could be a good solution to have SUNDIALS (and KLU) inside that Docker image. Maybe we would need some minor changes to the CMakeLists.txt, but that should be way better than having everything inside the installation directory.

**Comment by casella** [comment] 2023-03-29 18:11
@AnHeuermann I wonder if we should include gbode instead of cvode for CS FMUs. After all, it seems to be working quite well. Maybe it is easier to handle, dependency-wise?

**Comment by dietmarw** [comment] 2023-03-29 21:03
It would be a shame to lose CVODE since that is one of the standard options of other tools and it is always good to be able to to comparisons. Also the dependencies would be not such an issue if this cab be solved via the docker image.

**Comment by AnHeuermann** [comment] 2023-03-30 08:38
> @AnHeuermann I wonder if we should include gbode instead of cvode for CS FMUs. After all, it seems to be working quite well. Maybe it is easier to handle, dependency-wise?

Probably easier to handle yes (at least without KLU, see https://github.com/OpenModelica/OpenModelica/issues/10219), but I also agree with @dietmarw that we should have CVODE available / improve our CVODE implementation.
But as always who will do it? Me and @bernhardbachmann are probably lacking the time to do it. Maybe we can find a student to do parts of it with some help from my side. But OpenModelica is quiet the beast to handle, so easy tasks become hard task very fast.
