### ISSUE TITLE
FMU exportation

### ISSUE THREAD

**Issue by HelenaShou** [OpenModelica/OpenModelica#8220] opened 2021-11-25 09:20 UTC
### Description
When exporting a Model as FMU (with v1.18 version in windows) a file is missing in the resources folder. As a result the FMIfunction fmi2instanciate  return a segmentation fault.

### Steps to reproduce
in OMEdit : right click in a model -> export as FMU
"the FMU is generated at "..location..."

### Expected behavior
a FMU compressed folder is generated in this folder there is a ressource folder with 3 files.  (the issue: there are only two)

### Version and OS
 - OpenModelica Version [run `omc --version` or check `Help->About OMEdit` from OMEdit]
 - Versions of used Modelica libraries if applicable
 - OS: [e.g. Windows 10, 64 bit]

**Comment by mahge** [comment] 2021-11-25 09:47
@HelenaShou is there any error message you are getting? Which file exactly is missing?

**Comment by HelenaShou** [comment] 2021-11-26 14:09
Hi no there is no error message, the file missing is : linux64.summary (or
maybe the corresponding windows one). I think it's called by the FMI
function:  fmu2instanciate (because when this file is not in the FMU
ressource folder it give a segmentation fault)

**Comment by mahge** [comment] 2022-10-19 16:22
Closing due to lack of additional information. If the issue is still there, please re-open or create a new issue.

**Closed by mahge** 2022-10-19 16:22 UTC
Labels: COMP/FMI
