### ISSUE TITLE
LOG_NLS_NEWTON_DIAG description messed up

### ISSUE THREAD

**Issue by bilderbuchi** [OpenModelica/OpenModelica#10320] opened 2023-03-06 09:32 UTC
The description string for `LOG_NLS_NEWTON_DIAG` seems to be missing, which leads to a wrong user guide and OMEdit tooltip
![image](https://user-images.githubusercontent.com/327442/223068669-81a9f2ad-f2cb-4ded-bbd5-f123f345553e.png) (pretty sure that belongs to `LOG_NLS_RES`.

Probably the same thing as #10259 #10268.

Also, when checking `LOG_SIMULATION`, `LOG_DSS` or `LOG_EVENTS_V`, I'm getting `Warning: unrecognized logging <flagname>"`, but those are documented in the latest user guide. 
I'm not sure if the logging flag setup is currently expected broken/in flux in the nightly (as also `LOG_STATS` does not report the quite useful simulation timer/event nr. information anymore 😕 ), so I haven't yet reported those separately.

OpenModelica v1.21.0-dev-313-g9dd29eec7f

**Comment by casella** [comment] 2023-03-06 09:48
@AnHeuermann would you mind having a look?

As the 1.21.0 release approaches, these last-minute regressions have a weird tendency to pile up 😅

**Comment by bilderbuchi** [comment] 2023-03-06 10:49
> Also, when checking `LOG_SIMULATION`, `LOG_DSS` or `LOG_EVENTS_V`, I'm getting `Warning: unrecognized logging <flagname>"`, but those are documented in the latest user guide.
> I'm not sure if the logging flag setup is currently expected broken/in flux in the nightly (as also `LOG_STATS` does not report the quite useful simulation timer/event nr. information anymore 😕 ), so I haven't yet reported those separately.

Should I open a separate issue for this, or is this known/WIP already?

**Comment by AnHeuermann** [comment] 2023-03-06 11:06
I think this is also fixed with #10322. Or at least I couldn't reproduce the issue, but I only checked after the changes I made.
I guess we can wait for the next nightly build and if that doesn't fix this please go ahead and open a new issue. Then I'll check again.

**Comment by casella** [comment] 2023-03-07 09:30
I confirm everything works fine with the new nightly build.

**Closed by casella** 2023-03-07 09:30 UTC
Labels: bug, COMP/OMC/Runtime

**Comment by bilderbuchi** [comment] 2023-03-07 09:55
> I confirm everything works fine with the new nightly build.

Funny, I still get, e.g. when simulating `Modelica.Blocks.Examples.PID_Controller`:

```
Warning: unrecognized logging LOG_DSS,LOG_EVENTS_V,LOG_SIMULATION
Supported are: LOG_EVENTS,LOG_INIT,LOG_LS,LOG_NLS,LOG_SOLVER,LOG_STATS
SimManager: Start initialization
SimManager: Start simulation at t = 0.000000
SimManager: Simulation stop time: 4.000000
Simulation info from solver:
DASSL: steps taken nst = 823
DASSL: last used order k = 4
DASSL: residual evaluations nre = 996
DASSL: jacobian evaluations nje = 158
DASSL: root evaluations nrt = 835
DASSL: error test failures netf = 33
DASSL: nonlinear convergence failures ncfn = 0
DASSL: nonlinear iterations nni = 996
DASSL: last evaluation time t = 4.006979
DASSL: last step size h = 0.008000
```

**Comment by AnHeuermann** [comment] 2023-03-07 11:30
Mhh... I can't reproduce the issue on Windows with the nightly build (v1.21.0-dev-318-gd7cb3a8558 (64-bit)).

```
C:/Users/USERNAME/AppData/Local/Temp/OpenModelica/OMEdit/Modelica.Blocks.Examples.PID_Controller/PID_Controller.exe -port=49201 -logFormat=xmltcp -override=startTime=0,stopTime=4,stepSize=0.008,tolerance=1e-06,solver=dassl,outputFormat=mat,variableFilter=.* -r=C:/Users/USERNAME/AppData/Local/Temp/OpenModelica/OMEdit/Modelica.Blocks.Examples.PID_Controller/PID_Controller_res.mat -w -lv=LOG_DSS,LOG_EVENTS_V,LOG_SIMULATION,LOG_STATS -inputPath=C:/Users/USERNAME/AppData/Local/Temp/OpenModelica/OMEdit/Modelica.Blocks.Examples.PID_Controller -outputPath=C:/Users/USERNAME/AppData/Local/Temp/OpenModelica/OMEdit/Modelica.Blocks.Examples.PID_Controller
state event at time=1.50000000025
state event at time=1.75331413759
state event at time=2.0707963271
state event at time=3.0707963272
terminal event at stop time 4
check for discrete changes at time=4
### STATISTICS ###
The simulation finished successfully.
read all the DefaultExperiment values:
Set tolerance for zero-crossing hysteresis to: 1.000000e-10
Initialized Jacobian:
check for discrete changes at time=0
status of relations at time=0
status of zero crossings at time=0
The initialization finished successfully with 3 homotopy steps.
state event at time=0.50000000015
```

**Comment by AnHeuermann** [comment] 2023-03-07 11:32
Ahh... found it. It's a Cpp issue. I was using the C runtime.
@bilderbuchi you might want to open a new ticket about this, but I'm not sure what we should do with this if the Cpp runtime simply doesn't use some log flags.

**Comment by bilderbuchi** [comment] 2023-03-07 12:41
>  It's a Cpp issue. I was using the C runtime.

Ah, I did not realise that, thanks!
