### ISSUE TITLE
Problem with PlanarLoops_analytic model in 1.19.0-dev.beta1

### ISSUE THREAD

**Issue by quorx** [OpenModelica/OpenModelica#8938] opened 2022-05-12 10:30 UTC
### Description
Running `Modelica.Mechanics.MultiBody.Examples.Loops.PlanarLoops_analytic` with `1.19.0-dev.beta1` on Windows 10 64bit. In the animation, some of the cylinders representing revolute joints within the compound `JointRRR` joints are not correctly aligned. This is because the `shape_rev2` and `shape_rev3` have null vectors `{0,0,0}` for the `lengthDirection`.

The animation is fine in `v 1.18.1`, where those `lengthDirection` vectors are `{0,0,1}`

It seems unlikely that the actual example model has changed (but possible), so maybe it's an OpenModelica issue.

Thanks

**Comment by casella** [comment] 2022-05-13 22:33
I tried to reproduce this issue by running that model on version v1.20.0-dev-59-g0e39c77344 (64-bit) that I currently have installed, but it actually broke during C compilation:
```
PlanarLoops_analytic_02nls.c:147:58: error: invalid operands to binary expression ('real_array' (aka 'struct base_array_s') and 'double')
  real_array_copy_data(sub_alloc_real_array(tmp0, (tmp1) * (sqrt(tmp4))), tmp5);
                                                  ~~~~~~ ^ ~~~~~~~~~~~~
C:/Program Files/OpenModelica1.20.0-dev-64bit/include/omc/c/util/generic_array.h:48:76: note: expanded from macro 'real_array_copy_data'
#define real_array_copy_data(src,dst)               simple_array_copy_data(src, &dst, sizeof(modelica_real));
                                                                           ^~~
PlanarLoops_analytic_02nls.c:411:58: error: invalid operands to binary expression ('real_array' (aka 'struct base_array_s') and 'double')
  real_array_copy_data(sub_alloc_real_array(tmp0, (tmp1) * (sqrt(tmp4))), tmp5);
                                                  ~~~~~~ ^ ~~~~~~~~~~~~
C:/Program Files/OpenModelica1.20.0-dev-64bit/include/omc/c/util/generic_array.h:48:76: note: expanded from macro 'real_array_copy_data'
#define real_array_copy_data(src,dst)               simple_array_copy_data(src, &dst, sizeof(modelica_real));
                                                                           ^~~
PlanarLoops_analytic_02nls.c:675:58: error: invalid operands to binary expression ('real_array' (aka 'struct base_array_s') and 'double')
  real_array_copy_data(sub_alloc_real_array(tmp0, (tmp1) * (sqrt(tmp4))), tmp5);
                                                  ~~~~~~ ^ ~~~~~~~~~~~~
C:/Program Files/OpenModelica1.20.0-dev-64bit/include/omc/c/util/generic_array.h:48:76: note: expanded from macro 'real_array_copy_data'
#define real_array_copy_data(src,dst)               simple_array_copy_data(src, &dst, sizeof(modelica_real));
                                                                           ^~~
clang  -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse     -I"C:/Program Files/OpenModelica1.20.0-dev-64bit/include/omc/c" -I"C:/Program Files/OpenModelica1.20.0-dev-64bit/include/omc" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=PlanarLoops_analytic -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=5 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0  -c -o PlanarLoops_analytic_06inz.o PlanarLoops_analytic_06inz.c
3 errors generated.
mingw32-make: *** [<builtin>: PlanarLoops_analytic_02nls.o] Error 1
mingw32-make: *** Waiting for unfinished jobs....
PlanarLoops_analytic_06inz.c:11958:59: error: assigning to 'modelica_real' (aka 'double') from incompatible type 'real_array_t' (aka 'struct base_array_s')
  data->simulationInfo->nonlinearSystemData[0].nlsxOld[0] = division_alloc_real_array_scalar(threadData,tmp0,sqrt(tmp3),"sqrt(jointRRR1.jointUSR.revolute.n * jointRRR1.jointUSR.revolute.n)");
                                                          ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PlanarLoops_analytic_06inz.c:12151:59: error: assigning to 'modelica_real' (aka 'double') from incompatible type 'real_array_t' (aka 'struct base_array_s')
  data->simulationInfo->nonlinearSystemData[1].nlsxOld[0] = division_alloc_real_array_scalar(threadData,tmp0,sqrt(tmp3),"sqrt(jointRRR2.jointUSR.revolute.n * jointRRR2.jointUSR.revolute.n)");
                                                          ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PlanarLoops_analytic_06inz.c:12389:59: error: assigning to 'modelica_real' (aka 'double') from incompatible type 'real_array_t' (aka 'struct base_array_s')
  data->simulationInfo->nonlinearSystemData[2].nlsxOld[0] = division_alloc_real_array_scalar(threadData,tmp0,sqrt(tmp3),"sqrt(jointRRR3.jointUSR.revolute.n * jointRRR3.jointUSR.revolute.n)");
                                                          ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 errors generated.
mingw32-make: *** [<builtin>: PlanarLoops_analytic_06inz.o] Error 1
mingw32-make: Leaving directory 'C:/Users/FRANCE~1/AppData/Local/Temp/OPENMO~1/OMEdit/MODELI~1.PLA'
Compilation process failed. Exited with code 0x00000002.
```
I have no special setting, just deleted them all recently. Unfortunately the most recent test report is three weeks old, so I can't say if this is a recent regression, I'll check when the library test has been run again.

**Comment by casella** [comment] 2022-05-13 23:41
Are you testing MSL 3.2.3 or MSL 4.0.0?

**Comment by quorx** [comment] 2022-05-14 09:07
> Are you testing MSL 3.2.3 or MSL 4.0.0?

I'm not too sure. It looks like 4.0.0
![image](https://user-images.githubusercontent.com/22444994/168418739-6a34c90d-314b-4d0a-a893-5efdcc1404ec.png)

But then when it runs, it fails
![image](https://user-images.githubusercontent.com/22444994/168418787-03cdc099-a674-485e-9810-3ba053febbfc.png)

... so on selecting try with old frontend once
![image](https://user-images.githubusercontent.com/22444994/168418798-51ebce63-8890-4774-a5c7-023d4d18c610.png)

It runs okay
![image](https://user-images.githubusercontent.com/22444994/168418842-4ca001ff-3746-4074-80d4-1bc316790048.png)

Sorry I can't be more specific, but I don't know what the differences between the old and new frontends are.

Thanks for looking!

**Comment by casella** [comment] 2022-05-16 11:11
Complex and ModelicaServices 4.0.0 are always loaded, since they are backwards-compatible. You can double-click on Modelica in the package browser and then look at the Documentation window to see which version you have loaded, or just hover with the pointer on the Modelica package icon. 

BTW, you can decide which version to load by clicking on the System Libraries button in the Welcome Screen, or by going to Options | Libraries and selecting which version you want to load by default.

Anyway, I reinstalled 1.19.0-beta.1 and repeated the test, I confirm that we (incorrectly) get, e.g., jointRR2.shape_rev2.lengthDirection = {0, 0, 0}. I'll investigate further and report.

**Comment by casella** [comment] 2022-05-16 11:14
@quorx however I don't get the translation errors you are reporting, nor I get the option of using the old front-end in case of errors, which I understand we have removed because the new front end is now much better than the old one in virtually all cases.

Are you sure you are running 1.19.0-beta.1?

**Comment by casella** [comment] 2022-05-16 13:37
The flattened model contains the equation
```modelica
  final parameter Real jointRRR2.e_b[1](unit = "1") = jointRRR2.jointUSR.revolute.e[1] "Unit vector along axes of rotations, resolved in frame_b, frame_ib and frame_im";
  final parameter Real jointRRR2.e_b[2](unit = "1") = jointRRR2.jointUSR.revolute.e[2] "Unit vector along axes of rotations, resolved in frame_b, frame_ib and frame_im";
  final parameter Real jointRRR2.e_b[3](unit = "1") = jointRRR2.jointUSR.revolute.e[3] "Unit vector along axes of rotations, resolved in frame_b, frame_ib and frame_im";
```
However, in the simulation results we see jointRRR2.e_b = {0, 0, 0}, even though  jointRRR2.jointUSR.revolute.e = {0, 0, 1}. Apparently, there is something wrong with how dependent parameters are computed.

Most likely this has the same root cause as #8772. We are investigating the issue and will solve it ASAP. @quorx thanks for reporting!

**Comment by casella** [comment] 2022-05-16 14:06
@kabdelhak, I ran this case in 1.19.0-dev.beta1 (before your 7227538 commit) with `-d=optdaedump`. I noticed that the parameter getting assigned the wrong value initially shows up as
```modelica
jointRRR2.shape_rev2.lengthDirection[3]:VARIABLE(unit = "1" fixed = true protected = true )  = jointRRR2.e_b[3] 
```
from a certain point onwards it is reported as
```
jointRRR2.shape_rev2.lengthDirection[3]:PARAM(unit = "1" fixed = false protected = true )  = jointRRR2.e_b[3] 
```
still with a binding equation but with fixed = false; the corresponding equation starts appearing
```
jointRRR2.shape_rev2.lengthDirection[3] = jointRRR2.e_b[3]   [initial |0|0|0|0|]
```
I'm not 100% sure this is the expected behaviour

**Comment by quorx** [comment] 2022-05-16 17:44
@casella Thanks very much for the tips and your endeavors in finding the error source. I had indeed switched back to v 1.18.1, which generated the messages above and can confirm the MSL is 4.0.0. Cheers, quorx

**Comment by casella** [comment] 2022-05-16 22:23
@quorx thank you for reporting. We'll try to get this fixed in 1.19.0, though it may be a nontrivial issue.

**Comment by casella** [comment] 2022-05-17 13:41
It seems quite likely that the root cause of this is the same as #8772, which is non-trivial. I'll mark this for 1.19.1, if we manage to solve it in time for 1.19.0, that would be even better.

**Comment by quorx** [comment] 2022-05-18 07:33
@casella Okay, thanks for the update. Good luck!

**Comment by casella** [comment] 2022-05-30 19:19
This is likely to be fixed by #8938, I'll check with the next nightly build.

**Comment by casella** [comment] 2022-06-05 15:57
I confirm that the problem was solved in the latest nightly build.

@kabdelhak could you please cherry-pick #8981 into maintenance/v1.19? Thanks!

**Comment by casella** [comment] 2022-06-20 21:21
Fixed by #8981 in 1.20.0 and by #9073 in 1.19.2

**Closed by casella** 2022-06-20 21:21 UTC

**Comment by casella** [comment] 2022-07-05 23:27
Works fine in 1.19.2-dev.beta2.

**Comment by quorx** [comment] 2022-07-06 07:55
Thank you!

Bob

**Comment by casella** [comment] 2022-07-06 08:17
Thanks for reporting 😄
