### ISSUE TITLE
Matlab mingw fmu not work in OpenModelica

### ISSUE THREAD

**Issue by lucas-luo** [OpenModelica/OpenModelica#8080] opened 2021-11-03 02:21 UTC
I get a Matlab mingw fmu，and import to OpenModelica，but it's wrong in output:
The message:
Process crashed 
Simulation process failed. Exited with code 0xffffffffc0000005.

**Comment by casella** [comment] 2021-11-03 12:00
Can you attach the FMU and be more precise so we can reproduce the issue?

**Comment by AnHeuermann** [comment] 2021-11-03 12:07
Check out my [post on the forum](https://openmodelica.org/forum/default-topic/3374-matlab-mingw-fmu-not-work-in-openmodelica#p11181) where you asked this question as well. We'll need the same information here to investigate the issue.

In short, add the following information to your issue:
- What does your Matlab model look like? Or add the FMU to this issue.
- How did you export the FMU (which settings, which target, what FMI version, ME or CS, ....)?
- How did you import the FMU in OpenModelica/OMSimulator?
- What version of OpenModelica/OMSimulator are you using?
- Did you try to import the FMU in other tools to validate that it's a problem with OM?

**Comment by lucas-luo** [comment] 2021-11-04 05:55
> Can you attach the FMU and be more precise so we can reproduce the issue?

Sorry, I read the FMIKit again, and it's not support mingw on windows, so i have to export fmu again in maltlab by set  
"CMake generator" to "Visual Stuido 14 2015 Win64", this is my fmu, [csthl20_trim.fmu](https://github.com/OpenModelica/OpenModelica/files/7472557/csthl20_trim.zip). I can't attach fmu file, so rename to zip.

when i set Target Build to  MinGW, the error is 
`Process crashed Simulation process failed. Exited with code 0xffffffffc0000005. `  in Output.
when i set Target Build to Visual Studio 2015, the error is 
`LINK : fatal error LNK1181: cannot open input file 'omcgc.lib'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE"' : return code '0x2'
Stop.
Compilation process failed. Exited with code 0x00000002.` in Compilation.

**Comment by lucas-luo** [comment] 2021-11-04 06:02
> Check out my [post on the forum](https://openmodelica.org/forum/default-topic/3374-matlab-mingw-fmu-not-work-in-openmodelica#p11181) where you asked this question as well. We'll need the same information here to investigate the issue.
> 
> In short, add the following information to your issue:
> 
> * What does your Matlab model look like? Or add the FMU to this issue.
> * How did you export the FMU (which settings, which target, what FMI version, ME or CS, ....)?
> * How did you import the FMU in OpenModelica/OMSimulator?
> * What version of OpenModelica/OMSimulator are you using?
> * Did you try to import the FMU in other tools to validate that it's a problem with OM?

What does your Matlab model look like?
My Matlab model is csthl20_trim，you can type "open_system('csthl20_trim')" in matlab to open the model, or download the attach which i upload in my reply to @casella 

How did you export the FMU (which settings, which target, what FMI version, ME or CS, ....)?
I try another way to export FMU by FMIKit-simulink-3.0-alpha.2，ME，CMake generator: Visual Studio 14 2015 Win64

How did you import the FMU in OpenModelica?
I import the FMU in OpenModelica, Tools->Options->Simulation, Target Build: Visual Stuidio 2015(msvc15), then simulate, error in compilation:
LINK: fatal error LNK1181: cannot open input file 'omcgc.lib'
NMAKE: fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE"' : return code '0x2' Stop.
Compilation process failed. Exited with code 0x00000002.

What version of OpenModelica are you using?
V1.19

Did you try to import the FMU in other tools?
no

**Comment by AnHeuermann** [comment] 2021-11-04 09:07
Not sure how you imported the FMU, the setting in Tools->Options->Simulations is for the generated code for modelica models and has nothing to do with FMUs.

But the recomended way would be via a new SSP model (File->New->New SSP Model; Then add FMU as SubModule).

Doing so gives the following error in OMEdit:
```
python C:/Program Files/OpenModelica1.19.0-dev-64bit/share/OMSimulator/scripts/OMSimulatorServer.py --model=C:/Users/myname/AppData/Local/Temp/OpenModelica/OMEdit//csthl20_trim.ssp --endpoint-pub=tcp://127.0.0.1:60231 --logLevel=0 --option "--suppressPath=true"
warning: [csthl20_trim: resources/0001_csthl20_trim.fmu] The FMU lists 0 initial unknowns but actually exposes 36 initial unknowns.
         The following unknowns are missing: 4: pqr13[0], 5: pqr13[1], 6: pqr13[2], 7: phithetapsi46[0], 8: phithetapsi46[1], 9: phithetapsi46[2], 10: alpha7, 11: beta8, 12: Mach9, 13: AxAyAz1012[0], 14: AxAyAz1012[1], 15: AxAyAz1012[2], 16: ContinuousStates.pqr_CSTATE[1], 17: der(ContinuousStates.pqr_CSTATE[1]), 18: ContinuousStates.pqr_CSTATE[2], 19: der(ContinuousStates.pqr_CSTATE[2]), 20: ContinuousStates.pqr_CSTATE[3], 21: der(ContinuousStates.pqr_CSTATE[3]), 22: ContinuousStates.phithetapsi_CSTATE[1], 23: der(ContinuousStates.phithetapsi_CSTATE[1]), 24: ContinuousStates.phithetapsi_CSTATE[2], 25: der(ContinuousStates.phithetapsi_CSTATE[2]), 26: ContinuousStates.phithetapsi_CSTATE[3], 27: der(ContinuousStates.phithetapsi_CSTATE[3]), 28: ContinuousStates.ubvbwb_CSTATE[1], 29: der(ContinuousStates.ubvbwb_CSTATE[1]), 30: ContinuousStates.ubvbwb_CSTATE[2], 31: der(ContinuousStates.ubvbwb_CSTATE[2]), 32: ContinuousStates.ubvbwb_CSTATE[3], 33: der(ContinuousStates.ubvbwb_CSTATE[3]), 34: ContinuousStates.xeyeze_CSTATE[1], 35: der(ContinuousStates.xeyeze_CSTATE[1]), 36: ContinuousStates.xeyeze_CSTATE[2], 37: der(ContinuousStates.xeyeze_CSTATE[2]), 38: ContinuousStates.xeyeze_CSTATE[3], 39: der(ContinuousStates.xeyeze_CSTATE[3])
info:    [csthl20_trim: resources/0001_csthl20_trim.fmu] The FMU contains bad initial unknowns. This might cause problems, e.g. wrong simulation results.
server:  OMS Server 2.1.1.post102
server:  ZMQ 4.2.3
server:  PUB socket connected to tcp://127.0.0.1:60231
Process crashedProcess crashed
Simulation process failed. Exited with code 0xffffffffc0000005.
```

Running the same FMU with [FMPy](https://github.com/CATIA-Systems/FMPy) gives a similar error:
```
>>> simulate_fmu(fmu)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\fmpy\simulation.py", line 787, in simulate_fmu
    result = simulateME(model_description, fmu, start_time, stop_time, solver, step_size, relative_tolerance, start_values, apply_default_start_values, input, output, output_interval, record_events, timeout, step_finished)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fmpy\simulation.py", line 943, in simulateME
    fmu.enterInitializationMode()
  File "C:\ProgramData\Anaconda3\lib\site-packages\fmpy\fmi2.py", line 283, in enterInitializationMode
    return self.fmi2EnterInitializationMode(self.component)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fmpy\fmi2.py", line 206, in w
    res = f(*args)
OSError: exception: access violation writing 0x0000000000000000
```

I can't tell if the FMU export itself is broken or you did choose some export setting wrong (but it still shouldnt crash).
Maybe the Simulink help or support can help you with this.

But it seems to be a problem with the FMU, so I'm closing this issue.

**Closed** 2021-11-04 09:07 UTC
Labels: invalid
