### ISSUE TITLE
shiftSample(u,shiftCounter) does not shift

### ISSUE THREAD

**Issue by paultjevdh** [OpenModelica/OpenModelica#8105] opened 2021-11-09 11:16 UTC
Hello

### Description
I try to shift a clocked (sampled) signal with shiftSample, and the output is the same as the clocked input signal, although it should be shifted 4 samples.
I also try to shift a clock signal, which is not calculated at all.

### Steps to reproduce
Simulated the model below

```model test_sample
  Real u,y1,u1;
  Clock Clk_row = Clock(1, 100) "Base row clock = 6.25MHz.";
  Clock y2;
initial equation
  u=0;
equation
  der(u)=1;
  u1 = sample(u,Clk_row);
     y1 = shiftSample(u1,4);
     y2 = shiftSample(Clk_row,4);
end test_sample;
```
Plot signals u, u1, y1.
Notice that y2 does not appear in the output list.
Notice also that y1 is exactly the same as u1
![image](https://user-images.githubusercontent.com/59084059/140913459-fd09a95b-ec65-474a-86f2-d1eee315d08b.png)

### Expected behavior
I expect the signal y1 to start sampling 4 samples later than u1 as in the image below.
I also expect he signal y2 to be calculated (!) and to start sampling 4 samples later than signal u1.

The results from Dymola are shown below:
![image](https://user-images.githubusercontent.com/59084059/140913942-02c7d14c-f1a7-4175-8bba-d635acfddc8e.png)

### Version and OS
 - OpenModelica Version 1.18.0
 - OS: Windows 10, 64 bit

Best regards,
Paul van der Hulst

**Comment by AnHeuermann** [comment] 2021-11-18 10:35
This is a known issue and a duplicate of #7854, so I'm closing this one but will add the example to #7854.

**Closed by AnHeuermann** 2021-11-18 10:35 UTC
Labels: duplicate

**Comment by paultjevdh** [comment] 2022-01-08 21:18
Hi,
This issue was redirected to #7854, and is closed also there. However, it seems a part of the issue was overseen.
I tested the example code above with v1.19.0-dev-504-g8291efd717 (64-bit) which is the current nightly build, and in my opinion, the issue is fixed only partly: _signal y2 is still not calculated._ 
I'm now sure if this remaining issue should now reside under this issue or #7854, please inform me if it should be posted elsewhere.

Best regards,
Paul

**Comment by casella** [comment] 2022-01-09 00:23
@paultjevdh, as I understand your test case, `y2` is not a signal (i.e. a Real, Integer, or Boolean variable), it is just a clock. I'm not sure what you mean by "is not calculated": clocks are not something that you can plot, only variables are.

The clock partition of `y2` is empty, so it can be actually ignored by omc outright. However, the clock definition is valid and correct, as you can see if you simulate this model
```
model test_sample
 Real u,y1,u1;
  Clock Clk_row = Clock(1, 100) "Base row clock = 6.25MHz.";
  Clock y2;
  Real z;
initial equation
  u=0;
equation
  der(u)=1;
  u1 = sample(u,Clk_row);
     y1 = shiftSample(u1,4);
     y2 = shiftSample(Clk_row,4);
  when y2 then
    z = previous(z) + 0.01;
  end when;
end test_sample;
```
Now the clock partition of `y2` contains an actual variable, `z`, whose evolution is consistent with the expected evolution of the `y2` clock.

![immagine](https://user-images.githubusercontent.com/4233148/148664443-c536b513-bc00-40ff-a411-71cb6d63557a.png)

**Comment by paultjevdh** [comment] 2022-01-09 11:57
Hi,
Thanks for your reaction. 
This may be my misunderstanding, but isn't a clock just a variable with different properties?
And why are u1 and y1 plotted as solid staircase signals, while they only have a defined value _at_ the samples and no value in between (exactly the same as a clock in my opinion)?
I included a picture in my original report which was generated with dymola. The clock variable y2 is plotted with circles in the lower plot. This is consistent with signals u1 and y1 which are also accented with small circles.
Also the 2015 book by Fritzson is littered with plots of clock signals.
So I don't understand why 'clock' signals are not possible to plot in openmodelica.

Best regards,
Paul

**Comment by casella** [comment] 2022-01-09 17:29
> Hi, Thanks for your reaction. This may be my misunderstanding, but isn't a clock just a variable with different properties?

Not really. Clock variables _do not have a value_, see [Definition 16.2](https://specification.modelica.org/maint/3.5/synchronous-language-elements.html#clocks-and-clocked-variables) of the Modelica Specification. Clock**ed** variables have a value, and are associated to a clock. 

> And why are u1 and y1 plotted as solid staircase signals, while they only have a defined value _at_ the samples and no value in between (exactly the same as a clock in my opinion)? 

This is a known current limitation in the way OpenModelica saves the results to files and plots them, i.e., as if they were discrete variables. Indeed it should be as you mention. I just opened #8388 on this topic.

>I included a picture in my original report which was generated with dymola. The clock variable y2 is plotted with circles in the lower plot. This is consistent with signals u1 and y1 which are also accented with small circles. Also the 2015 book by Fritzson is littered with plots of clock signals. So I don't understand why 'clock' signals are not possible to plot in openmodelica.

This is one possibility, that we plot them as fake Boolean variable, always taking the value of true, though this is a bit of an abuse of notation, since they really have no value at all. Maybe we should just plot the small circles on the time axis, that would be more appropriate. I don't have Peter's book at hand now, but we can check how he did it and do the same.

**Comment by paultjevdh** [comment] 2022-01-09 20:42
Hi,

OK, I understand. Then this should be considered a feature request rather than a bug I guess
Below is a shot of page 704 in Fritzson (2015). 

![image](https://user-images.githubusercontent.com/59084059/148699847-d6c84407-ce46-430c-a9ee-73ef7565129b.png)
_How_ he did those graphs, I don't know.

I'll leave you at it and wait for the appropriate commit.
Does this issue get reopened, or should this be resubmitted as a feature request?

Best regards,
Paul van der Hulst

**Comment by casella** [comment] 2022-01-10 00:04
This issue was about shiftSample and I understand this is fixed, so I'd keep it closed - best to avoid combo tickets with multiple issues that remain dangling forever.

The new feature is already mentioned in #8388, I'll mention you there so you get notified.
