### ISSUE TITLE
Instantiating a class with error lets whole diagram layer disappear

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#10173] opened 2023-02-07 13:18 UTC
### Description

Take a class that has an error when checking it and one that has none. When instantiating the error prone class after the correct class in a third all icons disappear from the diagram layer when using the new API. With the new API both icons are shown.

### Steps to Reproduce
1. Open the following package: 
[EmptyDiagram.txt](https://github.com/OpenModelica/OpenModelica/files/10675312/EmptyDiagram.txt)
2. Create a new class.
3. Instantiate the class `EmptyDiagram.CorrectClass`.
4. Instantiate the class `EmptyDiagram.WrongClass`, which includes two variables with the same name as an error. Its icon does not appear and the icon of `EmptyDiagram.CorrectClass` is removed from the diagram layer view. However, in the text layer both instances are still present. 

### Expected Behavior

The instantiation of classes with errors does not remove anything from the diagram layer.

### Version and OS

 - OpenModelica Version: 1.21-dev
 - OS: Windows 10, 64 bit

Thanks for looking into it.
Aaron Buntrock - Bosch rexroth

**Comment by casella** [comment] 2023-02-07 15:32
This is basically another duplicate of #9673. The issue is that in case of errors, the instance-based API breaks down, because it cannot instantiate stuff. @perost is working on it.

**Comment by abuntrock** [comment] 2023-02-07 15:40
Sorry for the duplicate reporting. I thought it was two different things.

**Comment by casella** [comment] 2023-04-03 14:38
@abuntrock this is now fixed with the latest nightly build:
![immagine](https://user-images.githubusercontent.com/4233148/229542574-5030719f-7700-4274-a4db-a47210aca4d8.png)

**Closed by casella** 2023-04-03 14:38 UTC
Labels: COMP/GUI/InstBased Interface
