### ISSUE TITLE
Windows CMake FMU export with CVODE missing dependencies

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#11604] opened 2023-11-17 19:16 UTC
### Description

The following error on simulation appears when using a OpenModelica 1.22 FMU:

<img width="348" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/cd041037-5f1a-4d24-b0ec-dd0a134d8ca2">

I have tested FMU export with the same settings on the following OM versions:

1.18 - Ok (335 KB size)
1.19 - Ok (562 KB size)
1.20 - Ok (565 KB size)
1.21 - Ok (569 KB size)
1.22 - Not Work! (287 KB size) (Why less size than FMU from version 1.21?)

[FMU Test.zip](https://github.com/OpenModelica/OpenModelica/files/13397304/FMU.Test.zip)

The FMU's have been created with the options:

<img width="299" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/09fdad30-aa98-4eec-987a-ee0af27db54c">

### Version and OS

 - OpenModelica Version: 1.22.0
 - OS: Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable

**Comment by AnHeuermann** [comment] 2023-11-20 09:14
The difference between 1.22 and 1.21 FMUs is the use of CMake instead of Autotools+Make.

Using dependency walker I can see that the .dll is missing a `libsundials_cvode.dll` what we use as the Co-Simulation ODE solver. So it is an issue with the OpenModelica FMU export.

You can try adding command [`--fmuRuntimeDepends=modelica`](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-fmuruntimedepends) to your options: OMEdit->Tools->Options->Simulation->Additional Translation Flags. If you have a new enough CMake installed (>= v3.21) and OpenModelica can find it this should solve the issue.

## Workaround

If the above solution isn't working you can try:

  - Use the Makefiles FMU export instead of the CVODE export: `[--fmuCMakeBuild=false](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-fmucmakebuild)`
  - Don't use Co-Simulation FMUs, only Model Export
  - Use Explicit Euler instead of CVODE for Co-Simulation
  - Install CMake and add it to your Windows path and remove `C:\Program Files\OpenModelica1.22.0-64bit\tools\msys\mingw64\bin\cmake.exe` from your OpenModelica installation.
  - Unzip your FMU, copy all libsundials_*.dll from `C:\Program Files\OpenModelica1.22.0-64bit\bin` into your `TEST 1.22.fmu\binaries\win64` directory and re-zip it.

**Comment by AnHeuermann** [comment] 2023-11-20 09:23
@adrpo we need fix https://github.com/OpenModelica/OpenModelica/issues/9566 to fix this issue for all Windows users.

**Comment by BasilioPV** [comment] 2023-11-20 10:08
> Use Explicit Euler instead of CVODE for Co-Simulation

Thanks for your response, I have tested with Explicit Euler with the same error as result.

**Comment by BasilioPV** [comment] 2024-01-25 08:35
@AnHeuermann  What about this issue? By now, it's impossible to export FMU for windows users, so the last version running this is 1.21

**Comment by AnHeuermann** [comment] 2024-01-25 09:16
This needs https://github.com/OpenModelica/OpenModelica/issues/9566 to be solved.

**Comment by AnHeuermann** [comment] 2024-01-29 13:33
@BasilioPV the nightly build should now have a recent version of CMake (3.28.1). Can you test if it is working for you? Then we can close this issue as solved.

**Comment by BasilioPV** [comment] 2024-01-29 16:52
@AnHeuermann I have downloaded the v1.23.0-dev-257-gcfdfeb87e5 (29/01/2024) version and still producing 287 KB file with the same initial error.

The following zip contains FMU made by 1.21 (Last good OM version) and 1.23 (today version), among with the original modelica model:

[Test_FMU.zip](https://github.com/OpenModelica/OpenModelica/files/14087269/Test_FMU.zip)

**Comment by AnHeuermann** [comment] 2024-01-30 08:45
Okay, I'll take some time to do this in February.
Please provide a minimal example to reproduce the issue, so I know when I've fixed it.

**Comment by BasilioPV** [comment] 2024-01-30 12:33
Hi @AnHeuermann,

This is the very simple model to export to FMU:

model Test_FMU
  parameter Real A=2;
  output Real B;
equation
  B=A*time;
end Test_FMU;

On this Zip you can find:

[Test_FMU (2).zip](https://github.com/OpenModelica/OpenModelica/files/14097686/Test_FMU.2.zip)

- Test_FMU_CVODE: FMU with CVODE as solver with Today (30-1-2024) nightly build (v1.23.0-dev-260-gae4103059c)
- Test_FMU_EULER: FMU with Euler as solver with Today (30-1-2024) nightly build (v1.23.0-dev-260-gae4103059c)
- Test_FMU_1.23: same as "Test_FMU_CVODE"
- Test_FMU_1.21: FMU created with OM v1.21 (official release)
- Test_FMU.mo: modelica file to test

Please follow the FMU export instructions on the initial conversation.

When I import the FMU (after v1.21) on other software:

- I cannot see the internal parameters of the FMU
- Simulation cannot star due to missing dll error

![image](https://github.com/OpenModelica/OpenModelica/assets/93596576/d45490e6-004b-4605-8295-815f3b23394e)

Making the same in OM v1.21 all works fine. Please see also the difference in FMU sizes between versions.

Thanks,
Basilio

> ### Description
> The following error on simulation appears when using a OpenModelica 1.22 FMU:
> 
> <img alt="image" width="348" src="https://private-user-images.githubusercontent.com/93596576/283927306-cd041037-5f1a-4d24-b0ec-dd0a134d8ca2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTczOTcsIm5iZiI6MTcwNjYxNzA5NywicGF0aCI6Ii85MzU5NjU3Ni8yODM5MjczMDYtY2QwNDEwMzctNWYxYS00ZDI0LWIwZWMtZGQwYTEzNGQ4Y2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDEyMTgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MDQxNDEwOTVjMTY4YTUwYmFhNmI3ODY5NmM1NjlkNmY5OGZiZTg5ZThiOTU1ZGUxZjczZWNiZGIzMTg0NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2ObRCmhktE7vTBUqp51nbH7-wpml2DuGhM3ZDEuUxRo">
> I have tested FMU export with the same settings on the following OM versions:
> 
> 1.18 - Ok (335 KB size) 1.19 - Ok (562 KB size) 1.20 - Ok (565 KB size) 1.21 - Ok (569 KB size) 1.22 - Not Work! (287 KB size) (Why less size than FMU from version 1.21?)
> 
> [FMU Test.zip](https://github.com/OpenModelica/OpenModelica/files/13397304/FMU.Test.zip)
> 
> The FMU's have been created with the options:
> 
> <img alt="image" width="299" src="https://private-user-images.githubusercontent.com/93596576/283927473-09fdad30-aa98-4eec-987a-ee0af27db54c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTczOTcsIm5iZiI6MTcwNjYxNzA5NywicGF0aCI6Ii85MzU5NjU3Ni8yODM5Mjc0NzMtMDlmZGFkMzAtYWE5OC00ZWVjLTk4N2EtZWUwYWYyN2RiNTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDEyMTgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1YzI4MGQ3ZjgwNDNkM2E2NGU5NDMxNDkyNDA3MmIwOTZhZWM2ZWE3Y2IyZTg1MzVkZTFhYjk2NDdjN2I1YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5WkshbN-zWGTS6TSXuTEs6cpdF_yun0n2xv9GFsYjLE">
> ### Steps to Reproduce
> ### Expected Behavior
> ### Screenshots
> ### Version and OS
> * OpenModelica Version: 1.22.0
> * OS: Windows 10, 64 bit
> * Versions of used Modelica libraries if applicable
> 
> ### Additional Context

**Comment by BasilioPV** [comment] 2024-01-31 14:59
More info:

I create a SSP in OMedit and load two FMU (exported with Version 1.23 and version 1.21). For the version 1.23 (current), the parameters of the model did'n appear:
<img width="498" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/8029dbcb-f356-4f88-8f0c-170df0144cd9">

And for the good exported V1.21, the parameters are good:
<img width="341" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/9d60b376-eb69-46e6-a0c8-81859d789809">

(this also happen in third part software).

But in OMedit the SSP is executed without warnings both FMU ?¿?¿ and the results are ok?¿ 

Why the kb size of the "bad" FMU is half the "good" FMU ?? Why on third part software doesn work?

**Comment by BasilioPV** [comment] 2024-02-26 07:07
Update OMedit v1.22.2 : The issue remais. The FMU created with v1.22.2 does not work and the size still have 290 kb.

**Comment by bilderbuchi** [comment] 2024-02-26 09:52
@casella given that this worked up to 1.21, and broke from 1.22, should this get a `regression` label (and appropriate milestone)?

**Comment by AnHeuermann** [comment] 2024-02-27 15:56
As far as I can tell most of the automated dependency installation is fixed with https://github.com/OpenModelica/OpenModelica/pull/12014.

But the Pendulum.dll still can't be loaded. Dependency.exe isn't showing any errors:

![grafik](https://github.com/OpenModelica/OpenModelica/assets/38031952/c5a1f02c-9e07-436e-99e1-74c7c42de132)

I think `Pendulum.dll` is still missing a dependency to `libsundials_nvecserial.dll`.

The static case (`libsundials_cvode.a` and `libsundials_nvecserial.a`) is working fine, since there are no DLLs to copy in that case. I need to recompile with `-DSUNDIALS_BUILD_SHARED_LIBS=ON`.

Turns out I need to set the CVODE library to public to link against it's dependencies.

**Comment by AnHeuermann** [comment] 2024-02-28 10:23
Oh I'm very deep in dll hell.

Dependencies isn't showing any load errors.
When simulating with FMPy Python is crashing without any error message, but all CVODE initialization is done at that point.

```
>>> result = simulate_fmu(fmu)
LOG_SOLVER        | info    | CVODE linear multistep method CV_BDF
LOG_SOLVER        | info    | CVODE maximum integration order CV_ITER_NEWTON
LOG_SOLVER        | info    | CVODE use equidistant time grid YES
LOG_SOLVER        | info    | CVODE Using relative error tolerance 1.000000e-06
LOG_SOLVER        | info    | CVODE Using dense internal linear solver SUNLinSol_Dense.
LOG_SOLVER        | info    | CVODE Use internal dense numeric jacobian method.
LOG_SOLVER        | info    | CVODE uses internal root finding method NO
LOG_SOLVER        | info    | CVODE maximum absolut step size 0
LOG_SOLVER        | info    | CVODE initial step size is set automatically
LOG_SOLVER        | info    | CVODE maximum integration order 5
LOG_SOLVER        | info    | CVODE maximum number of nonlinear convergence failures permitted during one step 10
LOG_SOLVER        | info    | CVODE BDF stability limit detection algorithm OFF
LOG_SOLVER        | info    | ### Finished initialize of CVODE solver successfully ###

(FMPy) D:\workspace\Testitesttest\issue-11604>
```

Simulating with FMI.jl results in crashing Julia.

Using `LoadLibraryA` (e.g. OMSimulator) only results in:

```
Failed to load DLL D:\workspace\Testitesttest\issue-11604\win64\Pendulum.dll:
The specified module could not be found.
```

**Comment by AnHeuermann** [comment] 2024-02-28 14:13
I removed pthreads from the FMU (`OM_HAVE_PTHREADS=OFF` and `Threads_FOUND=false`), but still the same issue.

I wrote a C program that loads `libsundials_cvode.dll`, `libsundials_nvecserial.dll` and `libwinpthread-1.dll`, compiled it with Visual Studio and that can load these DLLs just fine.
So it has to be something in Pendulum.dll or in the combination with the sundials DLLs.

I don't understand why this works in the static case, but maybe I'm missing some more SUNDIALS DLLs:

  - libsundials_sunlinsoldense.dll
  - libsundials_sunmatrixdense.dll
  
Also the import *.dll.a libraries are missing. So maybe CMake isn't linking to them but the .dll libs.

**Comment by AnHeuermann** [comment] 2024-02-28 14:15
And when I try to force CMake to link to the static links I get a bunch of
```
cvode_solver.c:546:(.text+0x94c): undefined reference to `__imp_N_VMake_Serial'
```
errors.

I have to give up on this for now.
Maybe @adrpo has some time and ideas how to get this mess running.

**Comment by BasilioPV** [comment] 2024-02-28 16:36
I don't know if this helps:

Inside FMU files, modelDescription change:

OM v1.21 (Good FMU)
<img width="407" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/6f8b60c5-fe26-44ac-be28-dd5fcc1875c3">
<img width="316" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/05100dae-7866-4bb1-b0a0-e5713912f22c">


OM v1.23 (Bad FMU)
<img width="431" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/6afec57b-ad8e-4089-8bf7-be4d978ec387">
<img width="274" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/da5e9fb2-a339-41fe-9a1d-74c3dd5b5664">

In addition, binaries are quite different in names and size:

OM v1.21 (Good FMU)
<img width="178" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/5153a64d-5246-434d-add7-d57b0b58bcb7">

OM v1.23 (Bad FMU)
<img width="153" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/7611f289-2936-441f-860f-63371b089071">

**Comment by mahge** [comment] 2024-02-28 20:06
> And when I try to force CMake to link to the static links I get a bunch of
> 
> ```
> cvode_solver.c:546:(.text+0x94c): undefined reference to `__imp_N_VMake_Serial'
> ```
> 
> errors.
> 
> I have to give up on this for now. Maybe @adrpo has some time and ideas how to get this mess running.

If you want to link to static sundials libs you have to also define -DLINK_SUNDIALS_STATIC on the compilation command line. This tells the sundials headers not to add the dll import/export qualifiers to the function declarations.

**Comment by AnHeuermann** [comment] 2024-02-29 10:49
Thanks @mahge. I saw the `-DLINK_SUNDIALS_STATIC ` comment in some CMakeLists.txt, but couldn't put two and two together.

**Comment by casella** [comment] 2024-02-29 11:09
I'm in complete awe that you guys can handle this stuff. I would have given up long time ago, it's really crazy 😅

**Comment by adrpo** [comment] 2024-03-01 16:02
Why don't we just copy all the needed .dll into binaries/win64?

**Comment by adrpo** [comment] 2024-03-01 16:11
Something like this should suffice:
`cp %OPENMODELICAHOME%/bin/libwinpthread*.dll %OPENMODELICAHOME%/lib/omc/libsundials* binaries/win64/.`

**Comment by adrpo** [comment] 2024-03-01 16:18
Basically we are missing the dll dependencies in the FMU here: binaries/win64/. 

Those that have %OPENMODELICAHOME%/bin in the PATH or that run things from OMEdit (like SSP) would be OK as it will find the dependencies in the PATH. But if you try to run it from python, it will not work. 

I tried with master 1.23 and it seems to pick up dependencies so it works fine.
We should fix 1.22.x as they are broken even if we updated to the latest cmake in 1.22.2 (which should find the deps).

**Comment by adrpo** [comment] 2024-03-01 16:26
It could be that  the mingw64 cmake 3.28.1 that I built for the old OMDev might not be able to detect the dependencies.

**Closed** 2024-03-01 16:32 UTC
Labels: COMP/FMI, regression

**Comment by BasilioPV** [comment] 2024-03-01 16:35
Thanks a lot!!

Tomorrow will be available the nightly build to test?

**Comment by adrpo** [comment] 2024-03-01 16:43
I will start one now.

**Comment by adrpo** [comment] 2024-03-01 16:44
When this job is done (if it doesn't fail) you should have it:
https://test.openmodelica.org/jenkins/job/Windows/job/OM_Win_NIGHTLY_BUILD_64bit/1872/

**Comment by AnHeuermann** [comment] 2024-03-01 16:59
I did some changes in 2e82712898a9aa04668991cb63635a8fe7d70fe5 that got on the master branch 25 minutes ago. Did that mess up something on your setup?

I'm forcing static installation of CVODE as a workaround.
The copying part seems to work, but the linking isn't correct.

We can have a meeting on Monday to look into this.

**Comment by adrpo** [comment] 2024-03-01 17:00
Do you link statically also with pthread?

**Comment by AnHeuermann** [comment] 2024-03-01 17:01
No, only cvode and nvec_serial.

**Comment by adrpo** [comment] 2024-03-01 17:04
Ok. I will do some more testing until Monday and see why sometimes it doesn't add libwinphread-1.dll in the FMU.

**Comment by AnHeuermann** [comment] 2024-03-01 17:04
> @AnHeuermann I have tested with the latest nightly and strangely it doesn't add the dependencies in the FMU, but if I compiled it myself it works fine. Very strange. The only difference is one is Windows 10 (works fine) and the other one is Windows 11 (doesn't add libwinpthread-1.dll).

Oh and the difference to the local build is that it only builds static versions of the libraries. The installed version has the dll as well.

**Comment by adrpo** [comment] 2024-03-01 17:06
Myself I still build with the old automake, not with the cmake so I guess it has everything.

**Comment by adrpo** [comment] 2024-03-02 11:42
cmake does weird things with RUNTIME_DEPENDENCIES.

I made a simple fmu.mos:
```
loadModel(Modelica); getErrorString();
buildModelFMU(Modelica.Electrical.Analog.Examples.Resistor); getErrorString();
```

If I build via command line using omc:
```
C:\Temp>"%OPENMODELICAHOME%\bin\"omc fmu.mos
true
""
"C:/Temp/Resistor.fmu"
""
```
I get a Resistor.fmu which doesn't contain libwinpthread-1.dll
If I unpack the Resistor.fmu and build from comand line with the same cmake then it installs it properly:
```
Install the project...
-- Install configuration: ""
-- Installing: C:/Temp/Resistor/sources/../binaries/win64/libResistor.dll.a
-- Installing: C:/Temp/Resistor/sources/../binaries/win64/Resistor.dll
-- Installing: C:/Temp/Resistor/sources/../binaries/win64/libwinpthread-1.dll
```

**Comment by adrpo** [comment] 2024-03-02 12:32
Found the issue:

This does NOT work; 
`cmake -G "MSYS Makefiles" -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" ..`

This works:
`cmake -G "MSYS Makefiles" ..`

I think this might be the issue:

```diff
-CMAKE_OBJDUMP:FILEPATH=C:/Program Files/OpenModelica1.23.0-dev-64bit/tools/msys/ucrt64/bin/llvm-objdump.ex
+CMAKE_OBJDUMP:FILEPATH=C:/Program Files/OpenModelica1.23.0-dev-64bit/tools/msys/ucrt64/bin/objdump.exe

```

**Comment by adrpo** [comment] 2024-03-02 12:36
Yep, this works as well:

`cmake -G "MSYS Makefiles" -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_OBJDUMP="C:/Program Files/OpenModelica1.23.0-dev-64bit/tools/msys/ucrt64/bin/objdump.exe" .. `

```
Install the project...
-- Install configuration: ""
-- Installing: C:/Temp/Resistor/sources/../binaries/win64/libResistor.dll.a
-- Installing: C:/Temp/Resistor/sources/../binaries/win64/Resistor.dll
-- Up-to-date: C:/Temp/Resistor/sources/../binaries/win64/libwinpthread-1.dll
```

**Comment by BasilioPV** [comment] 2024-03-02 13:07
@adrpo you're a genius!!!!

**Comment by adrpo** [comment] 2024-03-02 13:15
Still not clear why this happens, the result of `objdump -p Resistor.dll | grep DLL` and `llvm-objdump -p Resistor.dll | grep DLL` seems similar, it both lists `libwinpthread-1.dll` so it seems there is a bug in cmake on how it handles the output from the programs.

```
"C:\Program Files\OpenModelica1.23.0-dev-64bit\tools\msys\ucrt64\bin"\objdump.exe -p C:/Temp/Resistor/sources/build_cmake_dynamic/Resistor.dll 
	DLL
 vma:            Hint    Time      Forward  DLL       First
	DLL Name: KERNEL32.dll
	DLL Name: api-ms-win-crt-convert-l1-1-0.dll
	DLL Name: api-ms-win-crt-environment-l1-1-0.dll
	DLL Name: api-ms-win-crt-filesystem-l1-1-0.dll
	DLL Name: api-ms-win-crt-heap-l1-1-0.dll
	DLL Name: api-ms-win-crt-locale-l1-1-0.dll
	DLL Name: api-ms-win-crt-math-l1-1-0.dll
	DLL Name: api-ms-win-crt-private-l1-1-0.dll
	DLL Name: api-ms-win-crt-runtime-l1-1-0.dll
	DLL Name: api-ms-win-crt-stdio-l1-1-0.dll
	DLL Name: api-ms-win-crt-string-l1-1-0.dll
	DLL Name: api-ms-win-crt-time-l1-1-0.dll
	DLL Name: api-ms-win-crt-utility-l1-1-0.dll
	DLL Name: libwinpthread-1.dll

```

```
"C:\Program Files\OpenModelica1.23.0-dev-64bit\tools\msys\ucrt64\bin"\llvm-objdump.exe -p C:/Temp/Resistor/sources/build_cmake_dynamic/Resistor.dll 
	DLL
    DLL Name: KERNEL32.dll
    DLL Name: api-ms-win-crt-convert-l1-1-0.dll
    DLL Name: api-ms-win-crt-environment-l1-1-0.dll
    DLL Name: api-ms-win-crt-filesystem-l1-1-0.dll
    DLL Name: api-ms-win-crt-heap-l1-1-0.dll
    DLL Name: api-ms-win-crt-locale-l1-1-0.dll
    DLL Name: api-ms-win-crt-math-l1-1-0.dll
    DLL Name: api-ms-win-crt-private-l1-1-0.dll
    DLL Name: api-ms-win-crt-runtime-l1-1-0.dll
    DLL Name: api-ms-win-crt-stdio-l1-1-0.dll
    DLL Name: api-ms-win-crt-string-l1-1-0.dll
    DLL Name: api-ms-win-crt-time-l1-1-0.dll
    DLL Name: api-ms-win-crt-utility-l1-1-0.dll
    DLL Name: libwinpthread-1.dll
 DLL name: Resistor.dll

```

**Comment by adrpo** [comment] 2024-03-02 13:21
So if you select gcc & g++ as compilers in OMEdit->Tools->Options->Simulate then build the FMU, the runtime dependency should work fine.

**Comment by BasilioPV** [comment] 2024-03-02 13:53
Ok, by default I see:

<img width="896" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/d17d2a9d-2e8c-4606-b7e5-fc5ddefc4740">

And change to:

<img width="889" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/5a88ef7f-e9be-40d4-a5c2-2678ddcaa355">

The result FMU still hace 280 kb and fails to execute. What I'm doing wrong?

**Comment by adrpo** [comment] 2024-03-02 18:38
I didn't tried with the latest, I have tried with OpenModelica v1.23.0-dev-350-g2eae847cd0 (64-bit).

**Comment by adrpo** [comment] 2024-03-02 18:39
But yes, if I select gcc and g++ I get the libwinphread-1.dll dependency inside the .fmu

**Comment by BasilioPV** [comment] 2024-03-02 20:16
Ok, on the last nightly build it works! I suggest put as default the settings:

 select gcc & g++ as compilers in OMEdit->Tools->Options->Simulate

is that possible?

**Comment by adrpo** [comment] 2024-03-03 19:02
The compilation is a bit slower and consumes more memory with gcc and g++ but nothing else.

**Comment by bilderbuchi** [comment] 2024-03-04 07:23
> Still not clear why this happens, the result of `objdump -p Resistor.dll | grep DLL` and `llvm-objdump -p Resistor.dll | grep DLL` seems similar, it both lists `libwinpthread-1.dll` so it seems there is a bug in cmake on how it handles the output from the programs.
> 
> ```
> "C:\Program Files\OpenModelica1.23.0-dev-64bit\tools\msys\ucrt64\bin"\objdump.exe -p C:/Temp/Resistor/sources/build_cmake_dynamic/Resistor.dll 
> 	DLL
>  vma:            Hint    Time      Forward  DLL       First
> 	DLL Name: KERNEL32.dll
> 	DLL Name: api-ms-win-crt-convert-l1-1-0.dll
> 	DLL Name: api-ms-win-crt-environment-l1-1-0.dll
> 	DLL Name: api-ms-win-crt-filesystem-l1-1-0.dll
> 	DLL Name: api-ms-win-crt-heap-l1-1-0.dll
> 	DLL Name: api-ms-win-crt-locale-l1-1-0.dll
> 	DLL Name: api-ms-win-crt-math-l1-1-0.dll
> 	DLL Name: api-ms-win-crt-private-l1-1-0.dll
> 	DLL Name: api-ms-win-crt-runtime-l1-1-0.dll
> 	DLL Name: api-ms-win-crt-stdio-l1-1-0.dll
> 	DLL Name: api-ms-win-crt-string-l1-1-0.dll
> 	DLL Name: api-ms-win-crt-time-l1-1-0.dll
> 	DLL Name: api-ms-win-crt-utility-l1-1-0.dll
> 	DLL Name: libwinpthread-1.dll
> ```
> 
> ```
> "C:\Program Files\OpenModelica1.23.0-dev-64bit\tools\msys\ucrt64\bin"\llvm-objdump.exe -p C:/Temp/Resistor/sources/build_cmake_dynamic/Resistor.dll 
> 	DLL
>     DLL Name: KERNEL32.dll
>     DLL Name: api-ms-win-crt-convert-l1-1-0.dll
>     DLL Name: api-ms-win-crt-environment-l1-1-0.dll
>     DLL Name: api-ms-win-crt-filesystem-l1-1-0.dll
>     DLL Name: api-ms-win-crt-heap-l1-1-0.dll
>     DLL Name: api-ms-win-crt-locale-l1-1-0.dll
>     DLL Name: api-ms-win-crt-math-l1-1-0.dll
>     DLL Name: api-ms-win-crt-private-l1-1-0.dll
>     DLL Name: api-ms-win-crt-runtime-l1-1-0.dll
>     DLL Name: api-ms-win-crt-stdio-l1-1-0.dll
>     DLL Name: api-ms-win-crt-string-l1-1-0.dll
>     DLL Name: api-ms-win-crt-time-l1-1-0.dll
>     DLL Name: api-ms-win-crt-utility-l1-1-0.dll
>     DLL Name: libwinpthread-1.dll
>  DLL name: Resistor.dll
> ```

[This comment](https://gitlab.kitware.com/cmake/cmake/-/issues/20753#note_1377270) in the cmake issue tracker sounds quite relevant, and could be the root cause, and an easy fix. I guess that should be a separate cmake issue, but I don't have an account there. Anybody?
