### ISSUE TITLE
fmi2DoStep failed with status 3 (error) - Simulating with output-interval = None

### ISSUE THREAD

**Issue by BjorHart** [OpenModelica/OpenModelica#8709] opened 2022-03-16 11:27 UTC
### Description
I am having issues simulating an FMU created in OM, as soon as the output interval is not set or is larger than a certain value (iteratively found to be ~53)

The FMU is of type co-simulation.
The following works fine, but output-interval 54 does not:
```python
python -m fmpy simulate my_fmu.fmu --stop-time 1000 --output-interval 53
```

The error thrown is 
```python
Traceback (most recent call last):
  File "/home/bjorhart/miniconda3/envs/new_fmpy/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/bjorhart/miniconda3/envs/new_fmpy/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/bjorhart/miniconda3/envs/new_fmpy/lib/python3.8/site-packages/fmpy/__main__.py", line 4, in <module>
    main()
  File "/home/bjorhart/miniconda3/envs/new_fmpy/lib/python3.8/site-packages/fmpy/command_line.py", line 160, in main
    result = simulate_fmu(args.fmu_filename,
  File "/home/bjorhart/miniconda3/envs/new_fmpy/lib/python3.8/site-packages/fmpy/simulation.py", line 737, in simulate_fmu
    result = simulateCS(model_description, fmu, start_time, stop_time, relative_tolerance, start_values, apply_default_start_values, input, output, output_interval, timeout, step_finished, set_input_derivatives, use_event_mode, early_return_allowed, validate, initialize, terminate)
  File "/home/bjorhart/miniconda3/envs/new_fmpy/lib/python3.8/site-packages/fmpy/simulation.py", line 1246, in simulateCS
    raise e
  File "/home/bjorhart/miniconda3/envs/new_fmpy/lib/python3.8/site-packages/fmpy/simulation.py", line 1232, in simulateCS
    fmu.doStep(currentCommunicationPoint=time, communicationStepSize=output_interval)
  File "/home/bjorhart/miniconda3/envs/new_fmpy/lib/python3.8/site-packages/fmpy/fmi2.py", line 586, in doStep
    self.fmi2DoStep(self.component, currentCommunicationPoint, communicationStepSize, noSetFMUStatePriorToCurrentPoint)
  File "/home/bjorhart/miniconda3/envs/new_fmpy/lib/python3.8/site-packages/fmpy/fmi2.py", line 215, in w
    raise FMICallException(function=fname, status=res)
fmpy.fmi1.FMICallException: fmi2DoStep failed with status 3 (error).
```

In such a co-simulation, the communication steps-size or output-interval is just a "recording" of the state of the FMU at that interval, so why can the output-interval cause the simulation to fail at all?

Any help with this would be highly appreciated, thanks.  

### Version and OS

 - FMPy 0.3.7
 - Ubuntu 18.04 (WSL2)

**Comment by lochel** [comment] 2022-03-16 11:41
Can you share the model? That would help us to reproduce and investigate the issue.

**Comment by lochel** [comment] 2022-03-22 21:12
I close the issue due to lack of information. @BjorHart we will reopen the issue if you can provide further information.

**Closed by lochel** 2022-03-22 21:12 UTC

**Comment by BjorHart** [comment] 2022-03-23 08:28
> I close the issue due to lack of information. @BjorHart we will reopen the issue if you can provide further information.

yeah sorry for the long response time, We are not able to share the model at this stage.
