### ISSUE TITLE
The backend fails handling a system with composite connectors

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10501] opened 2023-04-04 12:26 UTC
Please consider the following MWE:
```modelica
package Expandable_MWEs
  package Interfaces
    expandable connector Bus
    end Bus;
  end Interfaces;

  package Components
    model Gen_pinA "connect an electric pin to bus, act as generator"
      Interfaces.Bus bus;
      model foo
         parameter Real A = 1;
         parameter Real w = 1;
         Modelica.Electrical.Analog.Interfaces.PositivePin a;
      equation
         a.v = A*sin(w*time);
      end foo;
      foo f;
    equation
      connect(f.a, bus.a);
    end Gen_pinA;

    model Usr_pinA "connect an electric pin to bus, act as utiliser"
      Interfaces.Bus bus;
      model foo
      parameter Real R = 1;
         Modelica.Electrical.Analog.Interfaces.PositivePin a;
      equation
         a.v = R*a.i;
      end foo;  
      foo f;
    equation
      connect(bus.a, f.a);
    end Usr_pinA;
  end Components;

  package Examples
    model Example_01_Gen_pinA_Usr_pinA
      Components.Gen_pinA G;
      Components.Usr_pinA U;
    equation
      connect(G.bus,U.bus);
    end Example_01_Gen_pinA_Usr_pinA;
  end Examples;
annotation(
    uses(Modelica(version = "4.0.0")));
end Expandable_MWEs;
```
If I flatten the equations I obtained the expected result
```modelica
class Expandable_MWEs.Examples.Example_01_Gen_pinA_Usr_pinA
  Modelica.Electrical.Analog.Interfaces.PositivePin G.bus.a "virtual variable in expandable connector";
  Modelica.Electrical.Analog.Interfaces.PositivePin U.bus.a "virtual variable in expandable connector";
  parameter Real G.f.A = 1.0;
  parameter Real G.f.w = 1.0;
  Real G.f.a.v(quantity = "ElectricPotential", unit = "V") "Potential at the pin";
  Real G.f.a.i(quantity = "ElectricCurrent", unit = "A") "Current flowing into the pin";
  parameter Real U.f.R = 1.0;
  Real U.f.a.v(quantity = "ElectricPotential", unit = "V") "Potential at the pin";
  Real U.f.a.i(quantity = "ElectricCurrent", unit = "A") "Current flowing into the pin";
equation
  G.f.a.v = G.bus.a.v;
  U.bus.a.v = U.f.a.v;
  U.f.a.i - U.bus.a.i = 0.0;
  G.bus.a.v = U.bus.a.v;
  G.bus.a.i + U.bus.a.i = 0.0;
  G.f.a.i - G.bus.a.i = 0.0;
  G.f.a.v = G.f.A * sin(G.f.w * time);
  U.f.a.v = U.f.R * U.f.a.i;
end Expandable_MWEs.Examples.Example_01_Gen_pinA_Usr_pinA;
```
However, if I try to run it I get the following error:
```
[1] 14:18:40 Scripting Notification
lowerType: composite(connector{Real v VAR UNBOUND, Real i VAR UNBOUND}) failed 

[2] 14:18:40 Translation Error
[C:/dev/OM64bit/OMCompiler/Compiler/BackEnd/BackendDAECreate.mo: 1558:9-1558:82]: Internal error function lowerKnownVarkind failed

[3] 14:18:40 Translation Error
Internal error BackendDAECreate.lowerKnownVar failed for   connector Modelica.Electrical.Analog.Interfaces.PositivePin
  Real v;
  flow Real i;
end Modelica.Electrical.Analog.Interfaces.PositivePin; U.bus.a "virtual variable in expandable connector";

[4] 14:18:40 Translation Error
Internal error BackendDAECreate.lowerVar failed for   connector Modelica.Electrical.Analog.Interfaces.PositivePin
  Real v;
  flow Real i;
end Modelica.Electrical.Analog.Interfaces.PositivePin; U.bus.a "virtual variable in expandable connector";
```
I have no idea why this happens. The flat equations are obviously well posed, linear and solvable.

**Comment by casella** [comment] 2023-04-04 12:27
Adding @albertoleva and @GianniFerretti to the loop.

**Comment by phannebohm** [comment] 2023-04-05 16:10
Changing the connector definition to

```patch
[...]
-  expandable connector Bus
+  connector Bus
+  Modelica.Electrical.Analog.Interfaces.PositivePin a;
   end Bus;
[...]
```

fixes this specific model.

At some point in the compiler _normal_ connectors are replaced with the variables inside but for some reason the lowering receives the full connector `composite(connector{Real v VAR UNBOUND, Real i VAR UNBOUND})` instead.

The flat model should look like this:

```patch
  class Expandable_MWEs.Examples.Example_01_Gen_pinA_Usr_pinA
-   Modelica.Electrical.Analog.Interfaces.PositivePin G.bus.a "virtual variable in expandable connector";
+   Real G.bus.a.v(quantity = "ElectricPotential", unit = "V") "Potential at the pin";
+   Real G.bus.a.i(quantity = "ElectricCurrent", unit = "A") "Current flowing into the pin";
-   Modelica.Electrical.Analog.Interfaces.PositivePin U.bus.a "virtual variable in expandable connector";
+   Real U.bus.a.v(quantity = "ElectricPotential", unit = "V") "Potential at the pin";
+   Real U.bus.a.i(quantity = "ElectricCurrent", unit = "A") "Current flowing into the pin";
    parameter Real G.f.A = 1.0;
    parameter Real G.f.w = 1.0;
    Real G.f.a.v(quantity = "ElectricPotential", unit = "V") "Potential at the pin";
    Real G.f.a.i(quantity = "ElectricCurrent", unit = "A") "Current flowing into the pin";
    parameter Real U.f.R = 1.0;
    Real U.f.a.v(quantity = "ElectricPotential", unit = "V") "Potential at the pin";
    Real U.f.a.i(quantity = "ElectricCurrent", unit = "A") "Current flowing into the pin";
  equation
    G.f.a.v = G.bus.a.v;
    U.bus.a.v = U.f.a.v;
    U.f.a.i - U.bus.a.i = 0.0;
    G.bus.a.v = U.bus.a.v;
    U.bus.a.i + G.bus.a.i = 0.0;
    G.f.a.i - G.bus.a.i = 0.0;
    G.f.a.v = G.f.A * sin(G.f.w * time);
    U.f.a.v = U.f.R * U.f.a.i;
  end Expandable_MWEs.Examples.Example_01_Gen_pinA_Usr_pinA;
```

So I guess this should already have happened in the frontend. @perost what do you think?

**Comment by perost** [comment] 2023-04-05 19:18
> So I guess this should already have happened in the frontend. @perost what do you think?

Yes, this is an issue with the handling of expandable connectors in the frontend, see #10502.

**Comment by perost** [comment] 2023-04-05 19:20
Closing as duplicate of #10502.

**Closed by perost** 2023-04-05 19:20 UTC
Labels: COMP/OMC/Backend
