### ISSUE TITLE
Wrongly displayed connector icon

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12074] opened 2024-03-06 09:26 UTC
### Steps to Reproduce

- Download https://github.com/PowerGrids/PowerGrids/tree/develop
- Open PowerGrids.Examples.IEEE14bus.ControlledGeneratorIEEE
- Switch to the Diagram view

The following diagram is displayed:
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/9255789e-bdf8-45a3-a141-78cfa9883a88)

Apparently, something goes badly wrong with the TerminalAC connector. Interestingly enough, a similar behaviour is also obtained when disabling the new inst-based interface

![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/5f0c6b5d-57d4-40a2-8a30-88301ab4db89)

### Expected Behavior

This is how the diagram looks like in Dymola, we should get something like this:
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/5c18b991-ece9-4871-af0d-c9f722489b64)

If it's a small issue, it would be nice to get it in 1.22.3, otherwise 1.23.0.

**Comment by casella** [comment] 2024-03-06 09:28
Adding @gwr69 to the loop, as he's getting a similar issue with his BusinessSimulation library.

**Comment by adeas31** [comment] 2024-03-06 10:34
There are 2 issues here. First is that you see huge `terminalAC` icon. That should be fixed with #12076.
The other is that we should see a blue rectangle for `terminalAC`. That is the issue on the library side. The annotation on `PowerGrids.Interfaces.TerminalAC` says ,

```Modelica
annotation (
    Icon(coordinateSystem(extent = {{-100, -100}, {100, 100}}, preserveAspectRatio = true, initialScale = 1, grid = {2, 2}), graphics={  Rectangle(origin = {92, 3}, fillColor = {85, 170, 255}, fillPattern = FillPattern.Solid, extent = {{-192, 97}, {8, -103}})}),
    Diagram(coordinateSystem(extent = {{-100, -100}, {100, 100}}, preserveAspectRatio = true, initialScale = 1, grid = {2, 2})))
```

The graphics is missing for the diagram layer.

**Comment by gwr69** [comment] 2024-03-06 10:59
I'll just add my issue in this regard here:

<h4>Steps to reproduce</h4>

1. Download https://github.com/bslMS/BusinessSimulation/tree/release
2. Open [`Examples.SimpleProductionChainIII`](https://github.com/bslMS/BusinessSimulation/blob/efcf8940ef004c8fbd8595beed11d06889ede34d/BusinessSimulation/Examples/SimpleProductionChainIII.mo)
3. Switch to Diagram View

You should see this:

![SimpleProductionChainIII](https://github.com/OpenModelica/OpenModelica/assets/17766670/eff8fb88-41e2-4191-a2fb-b8874d1f8a5d)


While the diagram in Wolfram System Modeler 14 looks like this:

![image](https://github.com/OpenModelica/OpenModelica/assets/17766670/8a73347e-2e43-42ef-9cef-8648815e64de)

So it seems like the expandable connector `bus` is screwing thing up.

**Comment by gwr69** [comment] 2024-03-06 11:09
Please also observe that the component `modelOutput` is not drawn correctly in OMEdit 1.22.2 imo. The `expandable connector ModelOutput` class extends from `Icons.DataOutport`.

```
expandable connector ModelOutput
    extends Icons.DataOutPort;
    ...
end ModelOutput;
```

If you take a look at [`Icons.DataOutPort`](https://github.com/bslMS/BusinessSimulation/blob/efcf8940ef004c8fbd8595beed11d06889ede34d/BusinessSimulation/Icons/DataOutPort.mo), you will see that the connector carries a yellow disk only in its `Icon` annotation, not in the `Diagram` annotation.

Since `modelOutput` is a connector belonging to the enclosing scope, i.e., its path is `SimpleProductionChainIII.modelOutput`, the diagram representation (without the disk as in System Modeler) should have been used not the icon.

**Comment by adeas31** [comment] 2024-03-06 14:02
The issue with the bus icon should be solved with #12076.

Icon for `modelOutput` is correct AFAICT. The `ModelOutput` is a connector but it doesn't have any annotation. The annotation comes from `Icons.DataOutPort` which is declared as a `class` and that is why its icon annotation is picked instead of diagram. I am not sure if we should consider the class or the top level class in this case. @casella any idea?

**Comment by adeas31** [comment] 2024-03-06 14:28
> The issue with the bus icon should be solved with https://github.com/OpenModelica/OpenModelica/pull/12076.

The issue that you see a bug bus icon will be solved with #12076. But you will still not see the bus icon since its declared same as ModelOutput.

**Comment by gwr69** [comment] 2024-03-06 14:46
So, what you are saying is that only the `Icon` annotation is inherited but not the `Diagram` annotation? (Sounds unsound to me) I would clearly expect an outer connector, e.g. one that is at the first level `m.c` to be shown in its diagram view specification.

In [Section 18.6.2](https://specification.modelica.org/maint/3.6/annotations.html#component-instance) it says:

>For connectors, the icon layer is used to represent a connector when it is shown in the icon layer of the enclosing model. The diagram layer of the connector is used to represent it when shown in the diagram layer of the enclosing model. Protected connectors are only shown in the diagram layer. Public connectors are shown in both the diagram layer and the icon layer. Non-connector components are only shown in the diagram layer.

**Comment by adeas31** [comment] 2024-03-06 14:56
> So, what you are saying is that only the `Icon` annotation is inherited but not the `Diagram` annotation? (Sounds unsound to me) I would clearly expect an outer connector, e.g. one that is at the first level `m.c` to be shown in its diagram view specification.
> 
> In [Section 18.6.2](https://specification.modelica.org/maint/3.6/annotations.html#component-instance) it says:
> 
> > For connectors, the icon layer is used to represent a connector when it is shown in the icon layer of the enclosing model. The diagram layer of the connector is used to represent it when shown in the diagram layer of the enclosing model. Protected connectors are only shown in the diagram layer. Public connectors are shown in both the diagram layer and the icon layer. Non-connector components are only shown in the diagram layer.

Yes, we are following this section of specification.

What I meant is that the `Icons.DataOutPort` which actually contains the annotation is defined as `class` and not a `connector` in the library.

```Modelica
partial class DataOutPort "Icon for an expandable connector for information output"
  annotation(defaultComponentName = "y", Icon(coordinateSystem(preserveAspectRatio = true, extent = {{-100, -100}, {100, 100}}, initialScale = 0.1, grid = {10, 10}), graphics = {Polygon(visible = true, lineColor = {1, 37, 163}, fillColor = {255, 255, 255}, fillPattern = FillPattern.Solid, points = {{-100, 100}, {100, 0}, {-100, -100}}), Ellipse(visible = true, origin = {-24.747, 0}, lineColor = {255, 170, 0}, fillColor = {255, 170, 0}, fillPattern = FillPattern.Solid, extent = {{-24.747, -24.747}, {24.747, 24.747}})}), Diagram(coordinateSystem(preserveAspectRatio = true, extent = {{-100, -100}, {100, 100}}, initialScale = 0.1, grid = {10, 10}), graphics = {Polygon(visible = true, origin = {100, 0}, lineColor = {1, 37, 163}, fillColor = {255, 255, 255}, fillPattern = FillPattern.Solid, points = {{-100, 50}, {0, 0}, {-100, -50}}), Text(visible = true, origin = {0, 80}, textColor = {128, 128, 128}, extent = {{-100, -12}, {100, 12}}, textString = "%name", fontName = "Lato", textStyle = {TextStyle.Bold})}), Documentation);
end DataOutPort;
```

**Comment by perost** [comment] 2024-03-06 15:05
> Icon for `modelOutput` is correct AFAICT. The `ModelOutput` is a connector but it doesn't have any annotation. The annotation comes from `Icons.DataOutPort` which is declared as a `class` and that is why its icon annotation is picked instead of diagram. I am not sure if we should consider the class or the top level class in this case. @casella any idea?

If I understand you correctly you're drawing `ModelOutput`, which is a `connector` that extends a `class`? In that case I think you should treat `ModelOutput` like a `connector`, because that's what it is in Modelica. But if you draw `DataOutPort` separately it should of course be treated like a `class`.

**Comment by gwr69** [comment] 2024-03-06 15:07
Ok, I hear you. But that would mean that we cannot use `partial class` as for other classes to insert `Icon` and `Diagram` related annotation, can we? For example, `Icons.DocumentationInfo` defines a textual display in diagram view that is to tell users that a class only contains documentation.

So the fix here would be to declare the class `partial connector DataOutputPort ...`?

**Comment by gwr69** [comment] 2024-03-06 15:09
> > Icon for `modelOutput` is correct AFAICT. The `ModelOutput` is a connector but it doesn't have any annotation. The annotation comes from `Icons.DataOutPort` which is declared as a `class` and that is why its icon annotation is picked instead of diagram. I am not sure if we should consider the class or the top level class in this case. @casella any idea?
> 
> If I understand you correctly you're drawing `ModelOutput`, which is a `connector` that extends a `class`? In that case I think you should treat `ModelOutput` like a `connector`, because that's what it is in Modelica. But if you draw `DataOutPort` separately it should of course be treated like a `class`.

Yes, that is my understanding of the specs: Once the `partial class DataOutputPort` is extended by a `connector` class it should be treated like one. But that presupposes that `Diagram` annotations are inherited as well, doesn't it?

**Comment by adeas31** [comment] 2024-03-06 15:10
> > Icon for `modelOutput` is correct AFAICT. The `ModelOutput` is a connector but it doesn't have any annotation. The annotation comes from `Icons.DataOutPort` which is declared as a `class` and that is why its icon annotation is picked instead of diagram. I am not sure if we should consider the class or the top level class in this case. @casella any idea?
> 
> If I understand you correctly you're drawing `ModelOutput`, which is a `connector` that extends a `class`? In that case I think you should treat `ModelOutput` like a `connector`, because that's what it is in Modelica. But if you draw `DataOutPort` separately it should of course be treated like a `class`.

Should we do it only for partial class or it doesn't matter?

**Comment by perost** [comment] 2024-03-06 15:13
> > > Icon for `modelOutput` is correct AFAICT. The `ModelOutput` is a connector but it doesn't have any annotation. The annotation comes from `Icons.DataOutPort` which is declared as a `class` and that is why its icon annotation is picked instead of diagram. I am not sure if we should consider the class or the top level class in this case. @casella any idea?
> > 
> > 
> > If I understand you correctly you're drawing `ModelOutput`, which is a `connector` that extends a `class`? In that case I think you should treat `ModelOutput` like a `connector`, because that's what it is in Modelica. But if you draw `DataOutPort` separately it should of course be treated like a `class`.
> 
> Should we do it only for partial class or it doesn't matter?

It shouldn't matter, 18.6.3 says "All graphical objects are by default inherited from a base class". What kind of class those bases classes are shouldn't influence the parent class in this case.

**Comment by gwr69** [comment] 2024-03-06 15:23
So let's wrap this up:

1. All graphical `Icon` and `Diagram` related annotations are inherited from a base class that can legally be extended by another.
2. A connector `m.c` of a class `m` is shown with its Icon definitions in the Icon View for `m` and its Diagram definitions in the Diagram View for `m`.

This to me means that the Diagram View for `Examples.SimpleProductionChainIII`in System Modeler 14 is correct and that the one shown in OMEdit is currently incorrect.

**Comment by adeas31** [comment] 2024-03-06 17:00
PR #12084 fixes the display of `modelOutput` and `bus`.

**Comment by casella** [comment] 2024-03-06 21:37
@adeas31 please cherry-pick #12076 and #12084 to maintenance/v1.22. Thanks!

**Comment by adeas31** [comment] 2024-03-07 09:47
Done in #12069

**Closed** 2024-03-07 09:48 UTC
Labels: COMP/GUI/OMEdit
