### ISSUE TITLE
ExperimentAnnotation are ignored and overwritten

### ISSUE THREAD

**Issue by olivleno** [OpenModelica/OpenModelica#12706] opened 2024-07-10 09:44 UTC
### Description
Using the experiment annotation has not the desired effect on the simulation.

### Steps to reproduce

1. open a simulation model
2. open the simulation setup dialog
3. change the start time
4. change the interval
5. tick "save experiment annotation inside model"
6. Choose Output Format: csv
7. open text view and edit experiment annotation StartTime = 1, Interval = 0.05
8. save the model
9. simulate
10. View the results.csv file in a text editor

The simulation is started at t=0 and dt=0.002.
The experiment annotation is overwritten with: Interval = 0.002

It is not clear how to enforce that the simulation setup is based on the experiment annotation.

### Expected behavior
The experiment annotation in the model should define start time, stop time, interval of the simulation.

### Version and OS
- OpenModelica v1.24.0-dev-149-g32fe465c6c (64-bit)
- MSL 4.0.0
 - OS: Windows 11, 64 bit

### Additional context
I'd like to simulate models using OMJulia, expecting that the experiment annotations take effect unless I overwrite them.
Currently I call:
`result = API.simulate(omc, test_model; outputFormat = "csv")`

**Comment by casella** [comment] 2024-07-10 17:38
@olivleno I think this is a duplicate of #11794. Do you agree or there is more to it?

**Comment by olivleno** [comment] 2024-07-11 06:00
> @olivleno I think this is a duplicate of #11794. Do you agree or there is more to it?

Maybe, but my main concern is the scripting. The steps to reproduce should be enhanced as follows:

### Script to  reproduce

Consider a simple model like the one below using experiment annotation with StartTime=1 and interval = 0.01.

```
loadModel(Modelica,{"4.0"}); getErrorString();
loadFile("ExperimentAnnotation.mo");getErrorString();
simulate(ExperimentAnnotation, outputFormat = "csv"); getErrorString();
```
Running this script should produce a res.csv file with time starting at 1 and an increment of 0.01.
This is not the case.

```
model ExperimentAnnotation
  Modelica.Blocks.Continuous.FirstOrder firstOrder(T = 1)  annotation(
    Placement(transformation(extent = {{-10, -10}, {10, 10}})));
  Modelica.Blocks.Sources.Constant const(k = 1)  annotation(
    Placement(transformation(origin = {-50, 0}, extent = {{-10, -10}, {10, 10}})));
equation
  connect(const.y, firstOrder.u) annotation(
    Line(points = {{-38, 0}, {-12, 0}}, color = {0, 0, 127}));

annotation(
    uses(Modelica(version = "4.0.0")),
  experiment(StartTime = 1, StopTime = 2, Tolerance = 1e-06, Interval = 0.01),
  __OpenModelica_simulationFlags(lv = "LOG_STDOUT,LOG_ASSERT,LOG_STATS", s = "euler", variableFilter = ".*"));
end ExperimentAnnotation;
```

**Comment by casella** [comment] 2024-07-11 12:40
@olivleno I tried to run your .mos file on you model and I got
```
 messages = "Simulation execution failed for model: ExperimentAnnotation
LOG_STDOUT        | warning | invalid command line option: -variableFilter=.*
```
Is that what the problem is?

**Comment by olivleno** [comment] 2024-07-11 13:02
No.
Sorry for this confusion, I'll remove the other flags.

**Comment by olivleno** [comment] 2024-07-22 07:39
To point out the core of this issue once more:
In the example a model including an experiment annotation with a non-default start time is called through OMJulia.API.
This simulation setting is **not** applied. 
Hence, it is currently not possible to run simulations based on the experiment annotation.

**Comment by casella** [comment] 2024-07-23 13:43
@olivleno can you please provide an example or MWE that reproduces exactly your issue. I understand you have a problem with scripting, but the script you provided had other issues.

Thanks!

**Comment by olivleno** [comment] 2024-07-23 16:12
Is this still the case? I modified the code in the comment above?

**Comment by casella** [comment] 2024-07-23 16:14
Sorry, I missed that 😅

**Comment by casella** [comment] 2024-07-23 22:09
I tried your edited script from the command line with the latest nightly build and I got a CSV file starting from 1 with a step of 0.01, as expected. I guess it's just a problem with OMJulia. Can you please confirm?

**Comment by olivleno** [comment] 2024-07-24 12:42
Yes, when calling: 
`result = OMJulia.API.simulate(omc, test_model; simflags="-lv=-LOG_ASSERT", outputFormat = "csv")`

the experiment annotations take no effect.

**Comment by casella** [comment] 2024-07-24 21:15
OK, please follow OpenModelica/OMJulia.jl#127

**Closed by casella** 2024-07-24 21:15 UTC
