### ISSUE TITLE
Wrong actualStream in ClaRa Text_Pipe_L1_TML

### ISSUE THREAD

**Issue by phannebohm** [OpenModelica/OpenModelica#12168] opened 2024-03-28 14:27 UTC
Debugging with @AlesVojacek revealed that there is probably an error in how we symbolically handle `actualStream` in [ClaRa_dev.Components.VolumesValvesFittings.Pipes.Check.OnePhaseFlow.Test_Pipe_L1_TML](https://libraries.openmodelica.org/branches/master/ClaRa_dev/files/ClaRa_dev_ClaRa.Components.VolumesValvesFittings.Pipes.Check.OnePhaseFlow.Test_Pipe_L1_TML.err).

```
division by zero at time 1501.000000000013, (a=0) / (b=0), where divisor b expression is: 1.0 - (if tube.inlet.m_flow > 0.0 then 0.0 else 1.0)
```

Changing `fluidInlet.h = actualStream(inlet.h_outflow)` to `fluidInlet.h = inStream(inlet.h_outflow)` seems to avoid the division by zero issue and the simulation finishes. (folowed by a process crash, but that's another story perhaps.)

**Comment by casella** [comment] 2024-03-28 15:02
I checked the model. The flat instantiated model contains:
```modelica
Real tube.fluidInlet.h(quantity = "SpecificEnergy", unit = "J/kg", stateSelect = StateSelect.default) = 
  if tube.inlet.m_flow > 0.0 then massFlowSource.steam_a.h_outflow else tube.inlet.h_outflow "Specific enthalpy";
```
which seems to me exactly what the [MLS Sect. 15.3](https://specification.modelica.org/maint/3.6/stream-connectors.html#actualstream) calls for.

The problem is what the backend does with it, please check the operations in the debugger:
```modelica
substitution: if tube.inlet.m_flow > 0.0 then massFlowSource.steam_a.h_outflow else tube.inlet.h_outflow
substitution: if tube.inlet.m_flow > 0.0 then massFlowSource.h else tube.fluidInlet.h
solved: tube.fluidInlet.h - (if tube.inlet.m_flow > 0.0 then massFlowSource.h else tube.fluidInlet.h) = 0.0
solved: tube.fluidInlet.h = (if tube.inlet.m_flow > 0.0 then massFlowSource.h else 0.0) / (1.0 - (if tube.inlet.m_flow > 0.0 then 0.0 else 1.0))
```
The substitution step looks good to me, but the "solution" step seems pure madness to me. I'm not sure which transformation rule of the backend does that, but for sure it not sound. I guess there's some flaw in the part that determines which equations can be solved for which variables. It goes without saying that
```modelica
tube.fluidInlet.h = if tube.inlet.m_flow > 0.0 then massFlowSource.steam_a.h_outflow else tube.inlet.h_outflow;
```
*cannot* be solved for `tube.inlet.h_outflow`.

Please investigate further.

**Comment by phannebohm** [comment] 2024-04-09 12:59
The model contains these two equations:
```modelica
tube.fluidInlet.h = if tube.inlet.m_flow > 0.0 then massFlowSource.steam_a.h_outflow else tube.inlet.h_outflow;
tube.inlet.h_outflow = tube.fluidInlet.h; // this is explicitly written in the model
```
or with simpler names
```modelica
a = if cond then c else b;
b = a;
```
which is clearly underdetermined once `tube.inlet.m_flow <= 0.0`. I'm not sure if this is a valid model. @AlesVojacek maybe you can comment on that.

I suppose the weird expression comes from the backend trying to solve `b = if cond then c else b;` for `b`, interpreting that as a linear equation and trying one symbolic newton step (though I'm not sure exactly).

**Comment by casella** [comment] 2024-04-09 17:50
> The model contains these two equations:
> 
> ```modelica
> tube.fluidInlet.h = if tube.inlet.m_flow > 0.0 then massFlowSource.steam_a.h_outflow else tube.inlet.h_outflow;
> tube.inlet.h_outflow = tube.fluidInlet.h; // this is explicitly written in the model
> ```
> 
> or with simpler names
> 
> ```modelica
> a = if cond then c else b;
> b = a;
> ```
> 
> which is clearly underdetermined once `tube.inlet.m_flow <= 0.0`. I'm not sure if this is a valid model.

For sure it isn't.

@AlesVojacek, I'm not much into the structure of the ClaRa TLM models, but if you read the [language specification](https://specification.modelica.org/maint/3.6/stream-connectors.html#actualstream), `actualStream()` is meant for monitoring purposes and to write balance equations, where it is multiplied by a flow rate. It is not meant to define fluid properties, _because that is prone to generating singularities_. We figured out the stream connector and `inStream()` concept precisely to avoid that issue.

> I suppose the weird expression comes from the backend trying to solve `b = if cond then c else b;` for `b`, interpreting that as a linear equation and trying one symbolic newton step (though I'm not sure exactly).

Yeah, kind of makes sense, even though the jacobian is zero on one branch, so this should probably generate a compile time error rather than a runtime error.

**Comment by casella** [comment] 2024-04-09 17:53
Besides, `tube.inlet.h_outflow = tube.fluidInlet.h` is of course going to be generate a cyclic singularity when the flow becomes negative, because you basically say h_in = h_out and then h_out = h_in.

I can try to help with that, but we need to do it in a live meeting, I need some guidance to understand what is the structure of the model in a reasonable amount of time.

**Comment by AlesVojacek** [comment] 2024-07-08 15:23
This was obviously bug. This model of pipe does not support the reverse flow, so I have set fluidInlet.h = inStream(inlet.h_outflow). The tester runs through. Many thanks for your comments.

**Comment by casella** [comment] 2024-07-10 17:46
OK, then I'm closing this ticket. Feel free to reopen it if there are further issues.

**Closed by casella** 2024-07-10 17:46 UTC
Labels: COMP/OMC/Backend, COMP/OMC/Runtime
