### ISSUE TITLE
getAllSubtypeOf API function is awfully slow in ThermofluidStream

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9268] opened 2022-07-28 13:28 UTC
### Steps to Reproduce

Activate support for replaceable in OMEdit, then load the ThermofluidStream library and open Examples.SimpleStream. Double-click on any flow resistance component. OMEdit gets stuck for a couple of minutes while it seeks all matching packages. This is visible in the omcommunication log
```
getAllSubtypeOf(ThermofluidStream.Media.myMedia.Interfaces.PartialMedium,ThermofluidStream.Interfaces.SISOFlow,false,false,false) 15:09:40:912
{ThermofluidStream.Media.XRGMedia.R245fa_ph,ThermofluidStream.Media.XRGMedia.R1234yf_ph,ThermofluidStream.Media.XRGMedia.CO2_ph,ThermofluidStream.Media.XRGMedia.NH3_ph,ThermofluidStream.Media.XRGMedia.R134a_ph,ThermofluidStream.Media.myMedia.Water.WaterIF97_R3ph,ThermofluidStream.Media.myMedia.Water.WaterIF97_R2ph,ThermofluidStream.Media.myMedia.Water.WaterIF97_R1ph,ThermofluidStream.Media.myMedia.Water.WaterIF97_R2pT,ThermofluidStream.Media.myMedia.Water.WaterIF97_R1pT,ThermofluidStream.Media.myMedia.Water.WaterIF97_R5ph,ThermofluidStream.Media.myMedia.Water.WaterIF97_R4ph,ThermofluidStream.Media.myMedia.Water.WaterIF97_ph,ThermofluidStream.Media.myMedia.Water.WaterIF97_pT,ThermofluidStream.Media.myMedia.Water.WaterIF97OnePhase_ph,ThermofluidStream.Media.myMedia.Water.StandardWaterOnePhase,ThermofluidStream.Media.myMedia.Water.StandardWater,ThermofluidStream.Media.myMedia.Water.ConstantPropertyLiquidWater,ThermofluidStream.Media.myMedia.Water.IdealSteam,ThermofluidStream.Media.myMedia.R134a.R134a_ph,ThermofluidStream.Media.myMedia.Incompressible.TableBased,ThermofluidStream.Media.myMedia.Incompressible.Examples.TestGlycol.Medium,ThermofluidStream.Media.myMedia.Incompressible.Examples.Essotherm650,ThermofluidStream.Media.myMedia.Incompressible.Examples.Glycol47,ThermofluidStream.Media.myMedia.IdealGases.MixtureGases.SimpleNaturalGasFixedComposition,ThermofluidStream.Media.myMedia.IdealGases.MixtureGases.SimpleNaturalGas,ThermofluidStream.Media.myMedia.IdealGases.MixtureGases.FlueGasSixComponents,ThermofluidStream.Media.myMedia.IdealGases.MixtureGases.FlueGasLambdaOnePlus,ThermofluidStream.Media.myMedia.IdealGases.MixtureGases.simpleMoistAir,ThermofluidStream.Media.myMedia.IdealGases.MixtureGases.AirSteam,ThermofluidStream.Media.myMedia.IdealGases.MixtureGases.CombustionAir,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.SO3,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.SO2,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.O2,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.Ne,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.N2O,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.N2,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.NO2,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.NO,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.NH3,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.He,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.H2O,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.H2,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.F2,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.CL2,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.C8H18_n_octane,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.C8H10_ethylbenz,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.C7H16_n_heptane,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.C7H14_1_heptene,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.C6H14_n_hexane,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.C6H12_1_hexene,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.C6H6,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.C5H12_n_pentane,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.C5H10_1_pentene,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.C4H10_n_butane,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.C4H8_1_butene,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.C3H8O_1propanol,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.C3H8,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.C3H6_propylene,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.C2H6,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.C2H5OH,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.C2H4,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.C2H2_vinylidene,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.CO2,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.CO,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.CH3OH,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.CH4,ThermofluidStream.Media.myMedia.IdealGases.SingleGases.Ar,ThermofluidStream.Media.myMedia.CompressibleLiquids.LinearWater_pT_Ambient,ThermofluidStream.Media.myMedia.CompressibleLiquids.LinearColdWater,ThermofluidStream.Media.myMedia.Air.ReferenceMoistAir,ThermofluidStream.Media.myMedia.Air.MoistAir,ThermofluidStream.Media.myMedia.Air.ReferenceAir.Air_dT,ThermofluidStream.Media.myMedia.Air.ReferenceAir.Air_pT,ThermofluidStream.Media.myMedia.Air.ReferenceAir.Air_ph,ThermofluidStream.Media.myMedia.Air.DryAirNasa,ThermofluidStream.Media.myMedia.Air.SimpleAir,ThermofluidStream.Media.myMedia.Examples.Tests.Components.ShortPipe.Medium,ThermofluidStream.Media.myMedia.Examples.Tests.Components.FixedAmbient.Medium,ThermofluidStream.Media.myMedia.Examples.Tests.Components.FixedMassFlowRate.Medium,ThermofluidStream.Media.myMedia.Examples.Tests.Components.PortVolume.Medium,ThermofluidStream.Media.myMedia.Examples.Tests.Components.FluidPort.Medium,ThermofluidStream.Media.myMedia.Examples.TestOnly.IdealGasN2Mix.Medium,ThermofluidStream.Media.myMedia.Examples.TestOnly.IdealGasN2.Medium,ThermofluidStream.Media.myMedia.Examples.TestOnly.N2AsMix,ThermofluidStream.Media.myMedia.Examples.TestOnly.FlueGas.Medium,ThermofluidStream.Media.myMedia.Examples.TestOnly.MixIdealGasAir.Medium,ThermofluidStream.Media.myMedia.Examples.Utilities.ShortPipe.Medium,ThermofluidStream.Media.myMedia.Examples.Utilities.FixedAmbient.Medium,ThermofluidStream.Media.myMedia.Examples.Utilities.FixedMassFlowRate.Medium,ThermofluidStream.Media.myMedia.Examples.Utilities.PortVolume.Medium,ThermofluidStream.Media.myMedia.Examples.Utilities.FluidPort.Medium,ThermofluidStream.Media.myMedia.Examples.SolveOneNonlinearEquation.Inverse_sh_TX.Medium,ThermofluidStream.Media.myMedia.Examples.SolveOneNonlinearEquation.InverseIncompressible_sh_T.Medium,ThermofluidStream.Media.myMedia.Examples.SolveOneNonlinearEquation.Inverse_sh_T.Medium,ThermofluidStream.Media.myMedia.Examples.ReferenceAir.MoistAir.Medium,ThermofluidStream.Media.myMedia.Examples.TwoPhaseWater,ThermofluidStream.Media.myMedia.Examples.PsychrometricData.Medium,ThermofluidStream.Media.myMedia.Examples.MoistAir.Medium,ThermofluidStream.Media.myMedia.Examples.MixtureGases.Medium2,ThermofluidStream.Media.myMedia.Examples.MixtureGases.Medium1,ThermofluidStream.Media.myMedia.Examples.WaterIF97.Medium,ThermofluidStream.Media.myMedia.Examples.IdealGasH2O.Medium,ThermofluidStream.Media.myMedia.Examples.SimpleLiquidWater.Medium,ThermofluidStream.Utilities.Functions.massFractionK.Medium,ThermofluidStream.Undirected.Internal.regStepState.Medium,ThermofluidStream.Undirected.Sensors.Tests.TestSensors.Medium2,ThermofluidStream.Undirected.Sensors.Tests.TestSensors.Medium,ThermofluidStream.Undirected.Sensors.SingleSensorX.Medium,ThermofluidStream.Undirected.Sensors.SensorState.Medium,ThermofluidStream.Undirected.Sensors.TwoPhaseSensorSelect.Medium2Phase,ThermofluidStream.Undirected.FlowControl.Tests.MCV.Medium,ThermofluidStream.Undirected.FlowControl.Tests.SpecificValveType.Medium,ThermofluidStream.Undirected.FlowControl.Tests.BasicControlValve.Medium,ThermofluidStream.Undirected.FlowControl.Tests.TanValve.Medium,ThermofluidStream.Undirected.FlowControl.Tests.CheckValve.Medium,ThermofluidStream.Undirected.HeatExchangers.Tests.TestDiscretizedHEXvsDir.MediumRefrigerant,ThermofluidStream.Undirected.HeatExchangers.Tests.TestDiscretizedHEXvsDir.MediumAir,ThermofluidStream.Undirected.HeatExchangers.Tests.ConductionElementTwoPhase.MediumRefrigerant,ThermofluidStream.Undirected.HeatExchangers.Tests.TestDiscretizedHEX.MediumRefrigerant,ThermofluidStream.Undirected.HeatExchangers.Tests.TestDiscretizedHEX.MediumAir,ThermofluidStream.Undirected.HeatExchangers.DiscretizedCounterFlowHEX.MediumB,ThermofluidStream.Undirected.HeatExchangers.DiscretizedCounterFlowHEX.MediumA,ThermofluidStream.Undirected.HeatExchangers.DiscretizedCrossFlowHEX.MediumB,ThermofluidStream.Undirected.HeatExchangers.DiscretizedCrossFlowHEX.MediumA,ThermofluidStream.Undirected.Processes.Tests.TransportDelay.Medium,ThermofluidStream.Undirected.Processes.Tests.ConductionElement.Medium,ThermofluidStream.Undirected.Topology.Tests.TestConnectors.Medium,ThermofluidStream.Undirected.Topology.Tests.TestJunction.Medium,ThermofluidStream.Undirected.Topology.JunctionRRRF.Medium,ThermofluidStream.Undirected.Topology.JunctionRRFF2.Medium,ThermofluidStream.Undirected.Topology.JunctionRRFF.Medium,ThermofluidStream.Undirected.Topology.JunctionRFFF.Medium,ThermofluidStream.Undirected.Topology.JunctionRRF2.Medium,ThermofluidStream.Undirected.Topology.JunctionRRF.Medium,ThermofluidStream.Undirected.Topology.JunctionRFF2.Medium,ThermofluidStream.Undirected.Topology.JunctionRFF.Medium,ThermofluidStream.Undirected.Topology.ConnectorInletOutletFore.Medium,ThermofluidStream.Undirected.Topology.ConnectRearRear.Medium,ThermofluidStream.Undirected.Topology.ConnectForeFore.Medium,ThermofluidStream.Undirected.Topology.ConnectForeOutlet.Medium,ThermofluidStream.Undirected.Topology.ConnectRearOutlet.Medium,ThermofluidStream.Undirected.Topology.ConnectInletRear.Medium,ThermofluidStream.Undirected.Topology.ConnectInletFore.Medium,ThermofluidStream.Undirected.Topology.JunctionMN.Medium,ThermofluidStream.Undirected.Boundaries.Tests.PhaseSeperator.Medium,ThermofluidStream.Undirected.Boundaries.Tests.VolumesDirectCoupling.MediumMix,ThermofluidStream.Undirected.Boundaries.Tests.VolumesDirectCoupling.Medium,ThermofluidStream.Undirected.Boundaries.Tests.Reservoir.Medium,ThermofluidStream.Undirected.Boundaries.Tests.TestVolumes.MediumMix,ThermofluidStream.Undirected.Boundaries.Tests.TestVolumes.Medium,ThermofluidStream.Undirected.Boundaries.TerminalRear.Medium,ThermofluidStream.Undirected.Boundaries.TerminalFore.Medium,ThermofluidStream.Undirected.Boundaries.BoundaryFore.Medium,ThermofluidStream.Undirected.Boundaries.BoundaryRear.Medium,ThermofluidStream.Undirected.Interfaces.Tests.Test_p_out_clipping.Medium,ThermofluidStream.Undirected.Interfaces.Rear.Medium,ThermofluidStream.Undirected.Interfaces.Fore.Medium,ThermofluidStream.Sensors.Internal.getTwoPhaseQuantity.Medium,ThermofluidStream.Sensors.Internal.getFlowQuantity.Medium,ThermofluidStream.Sensors.Internal.getQuantity.Medium,ThermofluidStream.Sensors.Tests.TestSensors.Medium3,ThermofluidStream.Sensors.Tests.TestSensors.Medium2,ThermofluidStream.Sensors.Tests.TestSensors.Medium1,ThermofluidStream.Sensors.MultiSensor_Tpm.Medium,ThermofluidStream.Sensors.SingleFlowSensor.Medium,ThermofluidStream.Sensors.DifferenceSensor_Tp.MediumB,ThermofluidStream.Sensors.DifferenceSensor_Tp.MediumA,ThermofluidStream.Sensors.DifferenceTwoPhaseSensorSensorSelect.MediumB,ThermofluidStream.Sensors.DifferenceTwoPhaseSensorSensorSelect.MediumA,ThermofluidStream.Sensors.DifferenceSensorSelect.MediumB,ThermofluidStream.Sensors.DifferenceSensorSelect.MediumA,ThermofluidStream.Sensors.MultiSensor_Tp.Medium,ThermofluidStream.Sensors.SingleSensorX.Medium,ThermofluidStream.Sensors.SensorState.Medium,ThermofluidStream.Sensors.TwoPhaseSensorSelect.Medium,ThermofluidStream.Sensors.SingleSensorSelect.Medium,ThermofluidStream.FlowControl.Tests.Switch.Medium,ThermofluidStream.FlowControl.Tests.PCV.Medium,ThermofluidStream.FlowControl.Tests.MCV.Medium,ThermofluidStream.FlowControl.Tests.SpecificValveType.medium,ThermofluidStream.FlowControl.Tests.BasicControlValve.medium,ThermofluidStream.FlowControl.Tests.TanValve.Medium,ThermofluidStream.FlowControl.Tests.CheckValve.Medium,ThermofluidStream.FlowControl.FourWaySwitch.Medium,ThermofluidStream.FlowControl.Switch.Medium,ThermofluidStream.HeatExchangers.Internal.calculateEfficency.MediumB,ThermofluidStream.HeatExchangers.Internal.calculateEfficency.MediumA,ThermofluidStream.HeatExchangers.Tests.FlowRes.MediumRefrigerant,ThermofluidStream.HeatExchangers.Tests.FlowRes.MediumAir,ThermofluidStream.HeatExchangers.Tests.Recuperator.MediumRefrigerant,ThermofluidStream.HeatExchangers.Tests.ElementTwoPhase.MediumRefrigerant,ThermofluidStream.HeatExchangers.Tests.Evaporator.MediumRefrigerant,ThermofluidStream.HeatExchangers.Tests.Evaporator.MediumAir,ThermofluidStream.HeatExchangers.Tests.Condenser.MediumRefrigerant,ThermofluidStream.HeatExchangers.Tests.Condenser.MediumAir,ThermofluidStream.HeatExchangers.Tests.CrossFlowNTU_zeroMassFlow.MediumB,ThermofluidStream.HeatExchangers.Tests.CrossFlowNTU_zeroMassFlow.MediumA,ThermofluidStream.HeatExchangers.Tests.CrossFlowNTU.MediumB,ThermofluidStream.HeatExchangers.Tests.CrossFlowNTU.MediumA,ThermofluidStream.HeatExchangers.Tests.CounterFlowNTU_parallel.MediumB,ThermofluidStream.HeatExchangers.Tests.CounterFlowNTU_parallel.MediumA,ThermofluidStream.HeatExchangers.Tests.CounterFlowNTU_serial.MediumB,ThermofluidStream.HeatExchangers.Tests.CounterFlowNTU_serial.MediumA,ThermofluidStream.HeatExchangers.Tests.CounterFlowNTU_zeroMassFlow.MediumB,ThermofluidStream.HeatExchangers.Tests.CounterFlowNTU_zeroMassFlow.MediumA,ThermofluidStream.HeatExchangers.Tests.CounterFlowNTU.MediumB,ThermofluidStream.HeatExchangers.Tests.CounterFlowNTU.MediumA,ThermofluidStream.HeatExchangers.DiscretizedCounterFlowHEX_FR.MediumB,ThermofluidStream.HeatExchangers.DiscretizedCounterFlowHEX_FR.MediumA,ThermofluidStream.HeatExchangers.DiscretizedCrossFlowHEX_FR.MediumB,ThermofluidStream.HeatExchangers.DiscretizedCrossFlowHEX_FR.MediumA,ThermofluidStream.HeatExchangers.DiscretizedCounterFlowHEX.MediumB,ThermofluidStream.HeatExchangers.DiscretizedCounterFlowHEX.MediumA,ThermofluidStream.HeatExchangers.DiscretizedCrossFlowHEX.MediumB,ThermofluidStream.HeatExchangers.DiscretizedCrossFlowHEX.MediumA,ThermofluidStream.HeatExchangers.CrossFlowNTU.MediumB,ThermofluidStream.HeatExchangers.CrossFlowNTU.MediumA,ThermofluidStream.HeatExchangers.CounterFlowNTU.MediumB,ThermofluidStream.HeatExchangers.CounterFlowNTU.MediumA,ThermofluidStream.Processes.Tests.Nozzle.Medium,ThermofluidStream.Processes.Tests.TransportDelay.Medium,ThermofluidStream.Processes.Tests.ConductionElement.Medium,ThermofluidStream.Processes.Tests.ConvectivePipe_serial.Medium,ThermofluidStream.Processes.Tests.ConvectivePipe.Medium,ThermofluidStream.Processes.Tests.Turbine.Medium,ThermofluidStream.Processes.Tests.Compressor.Medium,ThermofluidStream.Processes.Tests.Pump.Medium,ThermofluidStream.Processes.Tests.Flow_Resistance.Medium,ThermofluidStream.Topology.Internal.SplitterRatio.Medium,ThermofluidStream.Topology.Tests.TestNonPhysical.Medium,ThermofluidStream.Topology.Tests.TestJunctionNM.Medium,ThermofluidStream.Topology.Tests.TestDynamicTopology.Medium,ThermofluidStream.Topology.Tests.TestSplitter.Medium,ThermofluidStream.Topology.Tests.TestJunction.Medium,ThermofluidStream.Topology.NonPhysical.JunctionRatio.Medium,ThermofluidStream.Topology.DynamicJunctionNM.Medium,ThermofluidStream.Topology.DynamicSplitterN.Medium,ThermofluidStream.Topology.DynamicJunctionN.Medium,ThermofluidStream.Topology.JunctionNM.Medium,ThermofluidStream.Topology.JunctionN.Medium,ThermofluidStream.Topology.SplitterN.Medium,ThermofluidStream.Topology.JunctionX3.Medium,ThermofluidStream.Topology.JunctionX2.Medium,ThermofluidStream.Topology.JunctionX1.Medium,ThermofluidStream.Topology.SplitterX.Medium,ThermofluidStream.Topology.JunctionT2.Medium,ThermofluidStream.Topology.JunctionT1.Medium,ThermofluidStream.Topology.SplitterT2.Medium,ThermofluidStream.Topology.SplitterT1.Medium,ThermofluidStream.Boundaries.Tests.PhaseSeperator.Medium,ThermofluidStream.Boundaries.Tests.DynamicBoundaries.Medium,ThermofluidStream.Boundaries.Tests.VolumesDirectCoupling.MediumMix,ThermofluidStream.Boundaries.Tests.VolumesDirectCoupling.Medium,ThermofluidStream.Boundaries.Tests.TerminalSourceSink.Medium,ThermofluidStream.Boundaries.Tests.Reservoir.Medium,ThermofluidStream.Boundaries.Tests.Volumes.MediumMix,ThermofluidStream.Boundaries.Tests.Volumes.Medium,ThermofluidStream.Boundaries.Tests.SourceSink.Medium,ThermofluidStream.Boundaries.CreateState.Medium,ThermofluidStream.Boundaries.TerminalSink.Medium,ThermofluidStream.Boundaries.TerminalSource.Medium,ThermofluidStream.Boundaries.Sink.Medium,ThermofluidStream.Boundaries.Source.Medium,ThermofluidStream.Interfaces.Tests.Test_p_out_clipping.Medium,ThermofluidStream.Interfaces.StateOutput.Medium,ThermofluidStream.Interfaces.StateInput.Medium,ThermofluidStream.Interfaces.Outlet.Medium,ThermofluidStream.Interfaces.Inlet.Medium,ThermofluidStream.Examples.Utilities.Tests.BoilerEspresso.Water,ThermofluidStream.Examples.Utilities.Tests.Piston.Medium,ThermofluidStream.Examples.Utilities.CupSink.Medium,ThermofluidStream.Examples.Utilities.Piston.Medium,ThermofluidStream.Examples.Utilities.CoffeeStrainer.Medium,ThermofluidStream.Examples.Utilities.BoilerEspresso.Medium,ThermofluidStream.Examples.ReverseHeatPump.RefrigerantMedium,ThermofluidStream.Examples.ReverseHeatPump.SecondaryMedium,ThermofluidStream.Examples.HeatPump.Air,ThermofluidStream.Examples.HeatPump.Medium,ThermofluidStream.Examples.VaporCycle.RefrigerantMedium,ThermofluidStream.Examples.VaporCycle.SecondaryMedium,ThermofluidStream.Examples.VenturiPump.Medium,ThermofluidStream.Examples.EspressoMachine.Water,ThermofluidStream.Examples.WaterHammer.Medium,ThermofluidStream.Examples.SimpleCoolingCycle.Medium_air,ThermofluidStream.Examples.SimpleCoolingCycle.Medium_liquid,ThermofluidStream.Examples.SimpleGasTurbine.Medium,ThermofluidStream.Examples.SimpleEngine.Water,ThermofluidStream.Examples.SimpleAirCycle.Medium_bleed,ThermofluidStream.Examples.SimpleAirCycle.Medium_ram,ThermofluidStream.Examples.SimpleStream.Medium} 15:11:03:286
#s#; 82.370000; 89.384000; 'getAllSubtypeOf(ThermofluidStream.Media.myMedia.Interfaces.PartialMedium,ThermofluidStream.Interfaces.SISOFlow,false,false,false)'
```
When doing the same with Modelica.Fluid models, opening the parameter dialog that includes the replaceable Medium models only takes a few seconds. What is wrong here? Any chance of making it faster with the old, non-instance-based OMEdit interface?

Keeping @dzimmer in the loop.

**Comment by adrpo** [comment] 2022-07-28 16:28
First we do a lookup to find out the fully qualified name of the base class in the context where it appears. 
Then we basically walk all classes and for each extends we do a lookup to fully qualify it and a match with the fully qualified base class in the previous step. If it matches we add it to the list.

So there are 2 factors here: the number of loaded libraries and classes and the speed at witch we can qualify extends.

**Comment by adrpo** [comment] 2022-07-28 16:31
The only way we could possibly speed this up properly is to build all extends relationships when we load the libraries and cache it. That would get rid of the expensive walk of all loaded classes.

**Comment by adrpo** [comment] 2022-07-28 16:33
Note that this has nothing to do with new vs old API and frontends. The NF is used for the lookup from the beginning.

**Comment by perost** [comment] 2023-05-09 11:15
Duplicate of #10273.

**Closed by perost** 2023-05-09 11:15 UTC
