### ISSUE TITLE
Regression: Parameters with scientific notation are not displayed correctly in the parameter dialog

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#12009] opened 2024-02-19 12:48 UTC
### Description

With the current nightly build (v1.23.0-dev-316-g3a47d5ed12) parameters, which are defined in scientific notation, are not displayed correctly in the parameter dialog. Furthermore, changing the displayUnit of such a parameter via the dialog does not change the displayed value (both things worked fine in OMEdit 1.22.1). 

### Steps to Reproduce

1. Create the following modelica class:
```modelica
model DisplayUnitScientific
  parameter Modelica.Units.SI.Volume V1(displayUnit="cm3") = 1e-4;
  parameter Modelica.Units.SI.Volume V2(displayUnit="cm3") = 0.0001;
  
  parameter Modelica.Units.SI.Length L1(displayUnit="km") = 1e3;
  parameter Modelica.Units.SI.Length L2(displayUnit="km") = 1000;
  
end DisplayUnitScientific;
```
2. Instantiate this class in the current OMEdit nightly and in the stable 1.22.1 version and open its parameter dialog. Afterwards, change all four displayUnits to SI units. The four parameter dialogs are shown in the screenshot below. 
3. The pictures from the 1.23-dev should look like the ones from 1.22.1 (excpet for the rounding problems in 1.22.1). 
4. Also, there should be no rounding problem in 1.23-dev when displaying parameter `V2`. Especially since the conversion factor from `cm3` to `m3` is a factor of 10.

### Expected Behavior

It does not matter if the parameter value is initially defined with or without scientific notation. 
There is no rounding problem for parameters with unit conversion factors as a multiple of 10.

### Screenshots

My collegue @niklwors will add the screenshot as a comment.

### Version and OS

 - OpenModelica Version: v1.23.0-dev-316-g3a47d5ed12
 - OS: Windows 10, 64 bit
 - MSL 4.0.0

### Additional Context
Thanks for looking into this
Aaron Buntrock - Bosch Rexroth

**Comment by niklwors** [comment] 2024-02-19 13:25
picture:
![image001](https://github.com/OpenModelica/OpenModelica/assets/12269776/b4c7aac4-a133-4b75-b27e-3c0b34b29d70)

**Comment by casella** [comment] 2024-03-04 15:17
Most likely a duplicate of #12004.

**Comment by casella** [comment] 2024-03-04 22:50
Should be fixed by #12064 and OpenModelica/OMCompiler-3rdParty#155.

**Comment by casella** [comment] 2024-03-05 16:06
https://github.com/OpenModelica/OMCompiler-3rdParty/pull/156 is also needed to fix all cases.

**Comment by casella** [comment] 2024-03-06 23:10
@abuntrock this should be now fixed. Please try with the nightly build.

**Closed by casella** 2024-03-06 23:10 UTC
Labels: COMP/GUI/OMEdit

**Comment by abuntrock** [comment] 2024-03-11 08:08
I checked this with today's nightly and it looks as expected. Thanks a lot.
