### ISSUE TITLE
FMU export source code (gcc / CVODE) -> omc_config.h is missing

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#12568] opened 2024-06-12 15:01 UTC
### Description

When export any model to FMU under Solver CVODE and using gcc/g++ as compiler:
example:

```
model eee "Description of eee"
  Modelica.Units.SI.TemperatureDifference Tdiff;
  Modelica.Thermal.HeatTransfer.Components.HeatCapacitor heatCapacitor(C = 10000, T(start = 473.15, fixed = false))  annotation(
    Placement(transformation(origin = {-10, 38}, extent = {{-10, -10}, {10, 10}})));
  Modelica.Thermal.HeatTransfer.Components.ThermalConductor thermalConductor(G = 10)  annotation(
    Placement(transformation(origin = {10, 8}, extent = {{-10, -10}, {10, 10}})));
  Modelica.Thermal.HeatTransfer.Sources.FixedTemperature fixedTemperature(T = 303.15)  annotation(
    Placement(transformation(origin = {46, 8}, extent = {{10, -10}, {-10, 10}}, rotation = -0)));
equation
  connect(heatCapacitor.port, thermalConductor.port_a) annotation(
    Line(points = {{-10, 28}, {-10, 8}, {0, 8}}, color = {191, 0, 0}));
  connect(thermalConductor.port_b, fixedTemperature.port) annotation(
    Line(points = {{20, 8}, {36, 8}}, color = {191, 0, 0}));
  Tdiff=thermalConductor.port_a.T-thermalConductor.port_b.T;
  

annotation(version="1.0",
    uses(Modelica(version = "4.0.0")),
    Documentation(info = "<html><head></head><body>Text editor sample</body></html>", revisions = "<html><head></head><body>Revision text</body></html>", __OpenModelica_infoHeader = "<html><head></head><body>Header Text sample</body></html>"));

end eee;

```
Then I put the FMU into a raspberry Pi to compile it with FMPy (FMPY compile xxx.fmu), the following error appears:

<img width="401" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/2c581ba7-a11a-4aa6-ab17-d68598fe97c3">

This error does not occur using "Euler explicit" as solver, which compiles and works fine.

### Version and OS

 - OpenModelica Version: v1.24.0-dev-120-g4b5f3b42de
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by BasilioPV** [comment] 2024-06-29 09:32
Any news on this?

**Comment by casella** [comment] 2024-06-29 10:45
@AnHeuermann can you please help?

**Comment by bilderbuchi** [comment] 2024-07-01 06:02
@BasilioPV these `blabla.suffix.in` files are typically templated input files, which get processed into a real `blabla.suffix` file before being used, which is why just copying & renaming the file does not work -- `@something@` is a marker for a variable to be replaced.

**Comment by BasilioPV** [comment] 2024-07-01 06:10
Thanks for the clarification on the inner working! So, it seems that the processing of these files are not working?

**Comment by AnHeuermann** [comment] 2024-07-01 10:09
The error you encountered means, that the compiler definition for `OMC_FMI_RUNTIME` is missing.

```c
#ifndef OMC_FMI_RUNTIME
  #include "omc_config.h"
#endif
```

We set this compiler definition via CMake:

```cmake
# Set compiler definitions
target_compile_definitions(${FMU_NAME} PRIVATE OMC_MINIMAL_RUNTIME=1;OMC_FMI_RUNTIME=1;CMINPACK_NO_DLL${WITH_SUNDIALS})
```

If you want to re-compile a source-code FMU for some target the easiest way is to use the CMakeLists.txt from FMU/sources.
See the User's Guide: https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/fmitlm.html#compilation-process for a few settings you can change.

You used FMPy to recompile the sources, but it can't know the needed compiler definitions from the `modelDescription.xml` (it only lists the source files).
There is a way to automate this with a buildDescription.xml, but we have not implement that yet. Closing this in favor of https://github.com/OpenModelica/OpenModelica/issues/10548.

**Closed by AnHeuermann** 2024-07-01 10:09 UTC

**Comment by arun3688** [comment] 2024-11-13 21:35
@BasilioPV I guess we need to copy the FMI headers directly into sources to avoid this, i will try to fix this

**Comment by bilderbuchi** [comment] 2024-11-14 08:11
> @BasilioPV I guess we need to copy the FMI headers directly into sources to avoid this, i will try to fix this

@arun3688 Isn't it rather the problem that a left-over Windows path is just _wrong_ on Linux:
> A reference to openmodelica path still present on a Linux platform compilation.

, and if corrected would find the headers as intended?

**Comment by arun3688** [comment] 2024-11-14 09:02
> > @BasilioPV I guess we need to copy the FMI headers directly into sources to avoid this, i will try to fix this
> 
> @arun3688 Isn't it rather the problem that a left-over Windows path is just _wrong_ on Linux:
> 
> > A reference to openmodelica path still present on a Linux platform compilation.
> 
> , and if corrected would find the headers as intended?

that is true, what i also meant here is, users might not have openmodelica installed and it should be still possible for them to compile the source code build the fmu's and for that we need to copy the fmi headers to the sources folder to avoid that
