### ISSUE TITLE
Unrecognized redeclared partial classes in Buildings

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8092] opened 2021-11-04 11:12 UTC
The issue is described in detail in [Buildings ticket #2714](https://github.com/lbl-srg/modelica-buildings/issues/2714).

This MWE should apparently be valid
```
model MinimumExample
  partial model PartialComponent
    replaceable package Medium=Modelica.Media.Interfaces.PartialMedium;
    replaceable model SubComponentModel = PartialSubComponent (
      redeclare final package Medium=Medium);
    SubComponentModel subCom;
  end PartialComponent;

  partial model PartialSubComponent
    replaceable package Medium=Modelica.Media.Interfaces.PartialMedium;
    parameter Medium.ThermodynamicState sta_default=
      Medium.setState_pTX(T=Medium.T_default, p=Medium.p_default, X=Medium.X_default);
  end PartialSubComponent;

  model SubComponent
    extends PartialSubComponent;
  end SubComponent;

  model Component
    extends PartialComponent(redeclare model SubComponentModel = SubComponent);
  end Component;

  package Medium = Buildings.Media.Water;
  Component com(redeclare package Medium=Medium);
end MinimumExample;
```
but currently isn't.
```
[2] 11:58:59 Translation Notification
[MinimumExample: 10:17-10:71]: From here:

[3] 11:58:59 Translation Error
[MinimumExample: 24:3-24:49]: component com contains the definition of a partial class Medium.
Please redeclare it to any package compatible with Modelica.Media.Interfaces.PartialMedium.
```

**Comment by casella** [comment] 2021-11-09 22:49
@perost, technically speaking this issue is not part of the LBL agreement, which focused on Buildings 7.0.x to avoid fighting a moving target. That said, we'll have to solve this problem anyway sooner or later to provide support to later versions of Buildings, so the earlier this gets done, the better.

Is this an easy fix?

**Comment by perost** [comment] 2021-11-09 23:10
> Is this an easy fix?

I don't know yet, but I was planning on taking a look at it tomorrow.

**Comment by perost** [comment] 2021-11-10 16:21
The fix turned out to be fairly easy, we didn't apply the original modifier when redeclaring a class. However, while it fixes your example it does not fix the Buildings models, where we instead get the issue that we try to apply a modifier twice on a component (which fails because it's marked final). I don't know if that's related to my fix or just a different issue, but I will continue to investigate.

**Comment by janpeter19** [comment] 2021-11-23 14:46
I am interested to follow the progress here since I have some similar problem, I think.

**Comment by casella** [comment] 2021-11-23 16:47
@janpeter19, in fact this is not strictly related with Buildings 7.0.x (for which we are aiming at 100% success rate by the end of the year), since the problem shows up in later versions of that library. But we'll get that fixed anytime soon.

**Comment by janpeter19** [comment] 2021-11-24 13:42
@casella, yes I understand the problem is far more general. Per Ostlund saw that my error message is very similar to yours 

"component bioreactor contains the definition of  a partial class Gasphase. Please redeclare it to any package compatible with BPL.Interfaces.GasPhaseBase."

How interesting is this similarity? Does it help troubleshooting? My code also works fine with JModelica and even OCT from Modelon.

**Comment by janpeter19** [comment] 2021-11-26 16:58
Does it mean not correct code from me and Casella et al or does it mean identified compiler error?

**Comment by perost** [comment] 2021-11-26 16:59
> Does it mean not correct code from me and Casella et al or does it mean identified compiler error?

The model in the example should be valid, but currently does not work due to some compiler issues.

**Comment by janpeter19** [comment] 2021-11-29 09:05
Tested my code on earlier releases of OpenModelica and got the results below that I hope is of of some help:
1) Run my code in OpenModelica 1.18.0 stable - and got the same error text
2) When I test in OpenModelica 1.17.0 stable I do not get that error, but another red complaint about "implicit iteration range" that you later allowed in 1.18.0 (and we hade some correspondence around back in March).

**Comment by janpeter19** [comment] 2021-11-30 16:47
I tested part of my code more on 1.17.0 and found a misstake of mine related to re-declaration.
"Gasphase is partial, name lookup is not allowed in partial classes".

This is a rule that I dd not know of and seems Modelon software ignore too.
After correction of library code I got a simpler Application code (no gasphase) working in 1.17, 1.18 and even todays 1.19. 

But with a more demanding Application code that use Gasphase then I get some other type of errors
that some variable ar out of scope. 

Some small progress, and I suspect that a corrected compiler may play a role for me too.

**Comment by casella** [comment] 2021-11-30 17:32
> But with a more demanding Application code that use Gasphase then I get some other type of errors that some variable ar out of scope.

It would be good for us to be able to reproduce the issue, otherwise it might be hard to fix it.

**Comment by janpeter19** [comment] 2021-11-30 17:47
Just now, see my comments as input to our common problem with error text like this:

[MinimumExample: 24:3-24:49]: component com contains the definition of a partial class Medium.
Please redeclare it to any package compatible with Modelica.Media.Interfaces.PartialMedium.

In my library-application code I first thought we may have identical problems and related to "Porting constrained by modifiers..."

Now at least part of my problems was solved by correcting code with error text from OM 1.17.0
"Gasphase is partial, name lookup is not allowed in partial classes".

Maybe something similar is relevant for Casellas problem too?

If not, then I think you just focus on "Porting constrained by... " issues.

Right now I think I cannot share code with you. Perhaps later I can construct a small code example that illustrate the problem if the problem is still there.

**Closed** 2021-11-30 18:41 UTC
Labels: COMP/New Instantiation

**Comment by perost** [comment] 2021-11-30 18:43
The redeclare issue should now be fixed. The ChillerBorefield model in Buildings still does not work, but that's due to some unrelated issues that I will investigate later.

**Comment by casella** [comment] 2021-11-30 22:47
Thanks @perost!

**Comment by janpeter19** [comment] 2021-12-01 07:24
Tested my code this morning with nightly build dev-435-g14546fe  And my problems remain as described above, a bit as expected, and we handle that separately in one way or the other. I will come back in the coming weeks.
