### ISSUE TITLE
omc ignores experiment annotation

### ISSUE THREAD

**Issue by robryk** [OpenModelica/OpenModelica#8122] opened 2021-11-12 00:48 UTC
### Description
`experiment` annotation seems to be ignored by `omc`. Regardless of its contents, the `stopTime` in the `foo_init.xml` file is set to 1, and the simulation terminates by default after 1 second.

### Steps to reproduce

Create `A.mo` with the following contents:

```mo
model A
  Real x;
equation
  x = 0;
  annotation(experiment(stopTime=10));
end A;
```

Run: `omc -s A.mo && make -f A.makefile && ./A`

Observe that:
 - `A_init.xml` specifies `stopTime` of 1,
 - `OMPlot --plotAll --filename=A_res.mat` shows values for times from 0 to 1.

### Expected behavior
I would instead expect `stopTime` to be equal to 10 and the result file to contain values for time up to 10.

### Version and OS

```
$ omc --version
OMCompiler ..0-dev.-1+
```

I think that OpenModelica build setup in NixOS fails to provide version that it builds from. In any case, my installation of OpenModelica was built from https://github.com/OpenModelica/OpenModelica/tree/v1.18.0

I am running this on NixOS (a distribution of Linux).

**Comment by mahge** [comment] 2021-11-12 10:36
Hi @robryk. thank you for the report. 

We are aware of this issue and have plans to fix it. There is a bit more to it though. You can see #7860 (and #7861) for more information. 

If you want a quick workaround to avoid specifying the stop times on the command line, you can use a mos script. Something like

`A.mos`
```mo
loadFile("A.mo");
getErrorString();

simulate(A, stopTime=10);
getErrorString();
```
Then compile and simulate it in one go as
```sh
omc A.mos
```
------------------------------------------------

However, keep in mind that the options you specify in the mos file will **disable all the options you have set in the model annotations**, i.e., they can not filtered and combined, everything is ignored from the annotation. See #7861 for more info.

**Comment by mahge** [comment] 2021-11-12 10:39
Duplicate of #7860.

**Closed by mahge** 2021-11-12 10:39 UTC
Labels: duplicate

**Comment by sjoelund** [comment] 2021-11-12 10:44
> I think that OpenModelica build setup in NixOS fails to provide version that it builds from. In any case, my installation of OpenModelica was built from https://github.com/OpenModelica/OpenModelica/tree/v1.18.0

You need to either use have git installed to get the version info from the tree, or a source tarball with the additional file REVISION: https://build.openmodelica.org/apt/pool/contrib/openmodelica_1.18.0.orig.tar.xz
