### ISSUE TITLE
 Modelica-Buildings Library (master-fmi-fmpy): Division by zero 0.5

### ISSUE THREAD

**Issue by deepak19015** [OpenModelica/OpenModelica#11802] opened 2024-01-12 06:18 UTC
### Description

The simulation of fmu generated through omedit are failed while simulating in jupyter-notebook using fmpy library  and throws error that is  Division by zero 0.5 .
The following below listed models have same issues: 

```
Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.FiniteLineSource_Integrand_Equivalent 
Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.CylindricalHeatSource_Integrand
Buildings.Utilities.Math.Examples.BesselY1
Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.FiniteLineSource_Integrand
Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.FiniteLineSource_Integrand_Length
Buildings.Utilities.Math.Functions.Examples.BesselY1
Buildings.Utilities.Math.Examples.BesselY0
Buildings.Utilities.Math.Examples.ExponentialIntegralE1
Buildings.BoundaryConditions.WeatherData.Validation.DecemberToJanuary
Buildings.Controls.OBC.CDL.Reals.Validation.MovingAverage_nonZeroStart
Buildings.Utilities.Math.Functions.Examples.BesselY0
Buildings.Utilities.Math.Functions.Examples.ExponentialIntegralE1
```
On simulating the model in jupyter-notebook using fmpy library leads to following errors/warnings:

```
1. Division by zero 0.5 / (/*Real*/(nBor2) * len2 * u ^ 2.0) in function context
2. FMICallException
3. fmi2ExitInitializationMode failed with status 3 (error).
```

### Steps to Reproduce

Load the Modelica-Buildings master fmi fmpy library (Source: https://libraries.openmodelica.org/branches/master-fmi-fmpy/Buildings_latest/Buildings_latest.html)
Right click on the model and export fmu. import the fmu in python platform and the run python code.
Simulate the model "Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.FiniteLineSource_Integrand_Equivalent"

### Expected Behavior

The simulation should run without any error and plot the graph according to variables present in model.

### Screenshots
![Screenshot from 2024-01-12 11-35-16](https://github.com/OpenModelica/OpenModelica/assets/139556265/c1aa3ec2-73f9-4f10-ad6a-66e72e5bb469)

### Version and OS

-    OpenModelica Version: OpenModelica 1.23.0~dev-151-g8fef40a
-    OS: Ubuntu 22.04 focal
-    FMPy 0.3.19 
-    Python version: Python 3.10.12

       Versions of used Modelica libraries:
        Modelica 4.0.0
        Buildings master (11.0.0)

**Comment by casella** [comment] 2024-01-16 10:20
The problem with these models is that they all have an equation like `u = time` and have `StartTime > 0`, so `u` is never supposed to be called with a zero value. Unfortunately, a bug in FMPy causes the initial equations to be solved with `time = 0`, which triggers function calls with `u = 0`, causing all kind of exceptions.

Once CATIA-Systems/FMPy#638 is resolved and a new version of FMPy is available, this issue should be resolved automatically.

**Comment by casella** [comment] 2024-01-22 19:37
It seems that if the FMU is generated by Dymola, this problem does not occur, so this is probably due to an OMC FMI export issue, see #11855.

**Comment by arun3688** [comment] 2024-02-20 16:47
@casella I think this problem is not related with solving initial equation with `startTime > 0 `, I tested the model posted by you https://github.com/CATIA-Systems/FMPy/issues/638#issue-2083545525 and exported the fmu and simulated with OMSimulator and i can see that the initial equations are solved at `time 0.2` specified in `defaultExperiment`

![image](https://github.com/OpenModelica/OpenModelica/assets/6870949/d049a55f-0cc2-46c9-9687-8e9c69bd90e6)

When i tried to test the following fmu `Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.FiniteLineSource_Integrand_Equivalent.fmu`, I get division by zero error 

```
# OMSimulator FiniteLineSource_Integrand_Equivalent.fmu
info:    model doesn't contain any continuous state
LOG_ASSERT        | debug   | Division by zero 0.5 / (/*Real*/(nBor2) * len2 * u ^ 2.0) in function context
error:   [fmi2logger] C:/OPENMODELICAGIT/buildingstest/model-drngi7up/temp/0001_FiniteLineSource_Integrand_Equivalent (logFmi2Call): fmi2EnterInitializationMode: terminated by an assertion.
error:   [initialize] fmi2_import_exit_initialization_mode failed for FMU "model.root.FiniteLineSource_Integrand_Equivalent"
error:   [initialize] Initialization of system "model.root" failed
error:   [simulate] Model "model" is in wrong model state
info:    0 warnings
info:    4 errors
```

**Comment by casella** [comment] 2024-02-20 18:48
> @casella I think this problem is not related with solving initial equation with `startTime > 0 `, I tested the model posted by you [CATIA-Systems/FMPy#638 (comment)](https://github.com/CATIA-Systems/FMPy/issues/638#issue-2083545525) and exported the fmu and simulated with OMSimulator and i can see that the initial equations are solved at `time 0.2` specified in `defaultExperiment`

As I understand, they aren't. If they were, you would get `x0 = 0.2`, instead you get `x0 = 0`, as the plot you posted clearly shows 😃

**Comment by arun3688** [comment] 2024-02-23 15:24
@casella the issue is fixed now and i tested the fmu in OMSimulator, we get the expected results, see below

![image](https://github.com/OpenModelica/OpenModelica/assets/6870949/fc63e136-c066-46c1-8427-f19f3a988cf3)

And also i tested this fmu, `Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.FiniteLineSource_Integrand_Equivalent.fmu` after this change in `OMSimulator` and it works now and we do not get the Division by zero error see below

```
# OMSimulator FiniteLineSource_Integrand_Equivalent.fmu
info:    model doesn't contain any continuous state
info:    Result file: model_res.mat (bufferSize=10)
```

Hopefully the other Building fmus with this problem should be fixed.

**Comment by casella** [comment] 2024-02-23 18:46
Excellent! Let's check the https://libraries.openmodelica.org/branches/master-fmi-fmpy/ test results tomorrow, so we can see the actual impact, then we can close this.

**Comment by casella** [comment] 2024-02-27 13:42
OK, I checked the new https://libraries.openmodelica.org/branches/master-fmi-fmpy/Buildings_latest/Buildings_latest.html report and all those models are now running correctly.

@deepak19015, please update your records accordingly.

**Closed by casella** 2024-02-27 13:42 UTC
Labels: COMP/FMI

**Comment by casella** [comment] 2024-02-28 19:22
This is the corresponding regression report: https://libraries.openmodelica.org/branches/history/master-fmi-fmpy/2024-02-19%2001:50:41..2024-02-26%2013:19:30.html

**Comment by deepak19015** [comment] 2024-03-04 07:22
yes, all the model mentioned in this ticket are running fine.
