### ISSUE TITLE
Nominal value is not used to detect zero crossings

### ISSUE THREAD

**Issue by CSchoel** [OpenModelica/OpenModelica#6970] opened 2020-11-19 16:33 UTC
### Description

In my journey to learn about nominal values and clean up my model code, I found another case where the OMC shows unexpected behavior with variables that have a small order of magnitude: It seems that the nominal value is not taken into consideration when detecting zero crossings.

### Steps to reproduce

Example model:

```modelica
model ZeroCrossing
  Real r(nominal=1e-12) = sin(time) * 1e-12;
  Boolean crossing(start=false, fixed=true) = r > 0; // does not work
  //Boolean crossing(start=false, fixed=true) = r / 1e-12 > 0; // does work
end ZeroCrossing;
```

Example script:
```modelica
setCommandLineOptions("-d=newInst,nfAPI");
loadModel(ZeroCrossing); getErrorString();
simulate(ZeroCrossing, tolerance=1e-6, startTime=0, stopTime=20, numberOfIntervals=2000); getErrorString();
plot({r, crossing})
```

### Expected behavior

Since `r` has a nominal value of `1e-12`, I would expect that zero crossings are detected at scales down to `1e-12 * tolerance = 1e-18`. However, the plot for `crossing` shows a flat line that stays at zero for the whole simulation.

This behavior can be fixed by dividing r by the nominal value before checking for the zero crossing (as shown in the commented line).

### Version and OS
 - OpenModelica Version: `OMCompiler v1.17.0-dev.159+gc2ca162139`
 - OS: Manjaro Linux, 64 bit

**Comment by casella** [comment] 2023-02-27 10:04
@AnHeuermann, @phannebohm I missed this ticket when it was posted 2.5 yrs ago. I think it is important to get this right. Also, I'm not sure what is the tolerance that we are currently using in the runtime, since I see no flag to possibly modify it. 

Can you please comment on that?

Thanks

**Comment by casella** [comment] 2023-02-27 19:14
Could we multiply `tolZC` by the nominal attribute of `r`?

**Comment by casella** [comment] 2023-02-27 21:14
Adding @AndreaBartolini to the loop.

**Comment by phannebohm** [comment] 2023-02-28 19:44
> Could we multiply `tolZC` by the nominal attribute of `r`?

We should! But what about relations with more complicated expressions? Consider:

```modelica
model ZeroCrossingExpression
  Real r(nominal=1e-12) = sin(time) * 1e-12; 
  Real s(nominal=1e8) = cos(time) * 1e8;
  Boolean crossing(start=false, fixed=true) = r*s > 0; 
end ZeroCrossingExpression;
```

We need nominal propagation onto expressions to see that `r*s` must have scaling `1e-4`.

Maybe we can have a `$tmp` variable that stores `r.nominal * s.nominal` and multiplies that into `tolZC`.

**Comment by casella** [comment] 2023-02-28 22:03
Yeah, I thought about that, but it becomes quickly very complicated. In principle, we could use the same logic we use for scaling residuals in kinsol: you take the norm of the element-wise product of the nominal attributes of all the variables involved times the derivative of the expression with respect to them. But it seems to me a bit of an overkill. 

If you want you can implement that. However, I would suggest to start with the simple solution for expressions made by a simple variable, _and also do the same for min and max_.

**Comment by phannebohm** [comment] 2023-07-12 15:46
As it is now, the zero-crossings are already a little too complicated because we do `a > b` where often `b = 0.0` but we can't know in the runtime so the code looked like this:
https://github.com/OpenModelica/OpenModelica/blob/ca93d5a2520f05bb13312f2f6d5ad82062a15ca9/OMCompiler/SimulationRuntime/c/simulation/solver/model_help.c#L1430-L1435

Ideally I would like to simplify it to only consider `x > 0` e.g. `a-b > 0` so we only have one expression in the runtime. In general we would then need some way to get a nominal value for sums and differences, which at first glance seems nontrivial to me. That's another story, see #4515. For the (probably not so) special case of model `ZeroCrossing` the expression would simplify to a simple variable, which would make things easier.

What we came up with is #10960. Note that we can't use default nominal value 1.0 for the rhs `0` because that would "saturate" the tolerance again, so we use the dubious-seeming value of 0.0. Arbitrary expressions get a value of 1.0 and thus should behave like before. I will update `getExpNominal` to work with more general expressions like e.g. `2*r` in another PR when #10960 is merged successfully.

**Comment by bilderbuchi** [comment] 2023-07-13 08:01
> What we came up with is #10960. Note that we can't use default nominal value 1.0 for the rhs `0` because that would "saturate" the tolerance again, so we use the dubious-seeming value of 0.0. Arbitrary expressions get a value of 1.0 and thus should behave like before.

I'm not familiar with the details here, but can't you scale the `a`, `b` values with the nominals before tolerancing to deal with this case without workarounds? I mean
```
double eps = tolZC * (fmax(fabs(a/a_nominal), fabs(b/b_nominal)) + tolZC;
```
I'm not sure if nominal values of `0` are admissible (they don't make sense, intuitively) and thus could lead to div-by-zero problems here.

**Comment by phannebohm** [comment] 2023-07-13 09:27
> I'm not familiar with the details here, but can't you scale the `a`, `b` values with the nominals before tolerancing to deal with this case without workarounds? I mean
> 
> ```
> double eps = tolZC * (fmax(fabs(a/a_nominal), fabs(b/b_nominal)) + tolZC;
> ```

This wouldn't work. Consider the case when `a` is approximately equal to `a_nominal = 1e-12`. In that case you would scale the tolerance by approximately 1 but you want to scale it by 1e-12.

If it makes sense to you, you can also see from a dimensional analysis point of view that both a and a_nominal need to be in the numerator of eps. Since we test `a-b > eps` they have to have the same dimensions and `tolZC` is dimensionless.

**Comment by phannebohm** [comment] 2023-07-13 09:43
@mpradovelasco provided some nice theoretical underpinning in #10948:

>Considering `a = An as` and `b = Bn bs`, where `An` and `Bn` are the nominal values of `a` and `b`. If they have been properly selected, then the scaled values `as` and `bs` are around 1. Then, assuming `An > Bn`:
>
> ```
> a - b = An (as - Bn/An bs)
> ```
>
> That is, the scaled variable `(as - Bn/An bs)` is also around 1. This seems the target value to compute the crossover.
>
> In the case that `Bn > An`, then:
>
> ```
> a - b = Bn (An/Bn as - bs)
> ```
>
> That is, the scaled variable to `(An/Bn as - bs)` seems the target value to compute the crossover.

I think this is a good reason to implement it as I did in #10960.

However it still does not address the case when `An = Bn` in which case we have two numbers with the same order of magnitude canceling to give a number with potentially much smaller order of magnitude. I suspect there is not much we can do about that though.

**Comment by phannebohm** [comment] 2023-07-13 18:09
With #10963 merged, also basic expressions should work now. :tada:

I made PR #10964 to support builtin function calls but then realized that $cse variables are generated for all function calls so we would need to give $cse variables nominal values from the expressions they come from. Unfortunately my stuff is in SimCode so I don't have direct access to that, I think. I'll have to look into that...

**Comment by phannebohm** [comment] 2023-07-14 07:45
BTW, the [latest regressions](https://libraries.openmodelica.org/branches/history/master/2023-07-13%2012:38:39..2023-07-13%2022:28:31.html) and corresponding fix #10969 reminded me that we only support literals for now, so a nominal value defined by a parameter is not used at the moment. This should be easy to fix though.

**Comment by casella** [comment] 2023-07-19 14:15
> BTW, the [latest regressions](https://libraries.openmodelica.org/branches/history/master/2023-07-13%2012:38:39..2023-07-13%2022:28:31.html) and corresponding fix #10969 reminded me that we only support literals for now, so a nominal value defined by a parameter is not used at the moment. This should be easy to fix though.

Uh-oh. This should be done absolutely. The PowerGrids library define all nominal values as parameters, for example.

@phannebohm would you mind opening a specific ticket for this task, so we don't forget about it?

**Comment by casella** [comment] 2023-07-19 14:34
OK. But, in general, please try to keep tickets as atomic as possible, otherwise managing thousands of them becomes impossible 😅

**Comment by casella** [comment] 2023-07-19 14:39
> However it still does not address the case when `An = Bn` in which case we have two numbers with the same order of magnitude canceling to give a number with potentially much smaller order of magnitude. I suspect there is not much we can do about that though.

Exactly. Even though the magnitude of the difference will be small, _the numerical error_ will have the same order of magnitude as A_n and B_n, and that's what we should worry about when setting tolerances.

**Comment by phannebohm** [comment] 2023-07-19 14:48
> OK. But, in general, please try to keep tickets as atomic as possible, otherwise managing thousands of them becomes impossible :sweat_smile:

Good, I'll close this one as soon as #10983 is merged. Propagating nominal values across function calls will have to be done in the NB first then, see #4515.

> Exactly. Even though the magnitude of the difference will be small, _the numerical error_ will have the same order of magnitude as A_n and B_n, and that's what we should worry about when setting tolerances.

OK makes sense.

**Closed** 2023-07-21 11:47 UTC
Labels: COMP/OMC/Runtime

**Comment by casella** [comment] 2023-07-22 09:33
Will be interesting to see the impact on the library testsuite.
