### ISSUE TITLE
displayUnits as axis labels

### ISSUE THREAD

**Issue by nift-d** [OpenModelica/OpenModelica#8478] opened 2022-01-27 15:48 UTC
### Description

I can define a displayUnit for parameters and they are shown in the plot tab in the variables browser (at least sometimes) as expected. It would be nice if those defined units would show up as axis labels too (or an option to select them). Now the labels are set to the default unit
another problem is the play button in the variables browser: it does not do anything. I expected the values for the parameters to change as the slider moves along the progress bar, but they stay at the last calculated value all the time.

### Version and OS

 - OpenModelica Version: OMCompiler v1.18.0
 - MSL 4.0.0
 - OS: OS: Manjaro KDE

**Comment by nift-d** [comment] 2022-01-27 23:01
I have the feeling I need to specify the issue:
### Description
I have this hydraulic pump characteristic of a known pump I want to model. Resulting in a graph with flow on the horizontal and differential pressure on the vertical axis.
<details><summary>pump characteristic of manufacturer</summary>
    <pre> 
<img src = "https://user-images.githubusercontent.com/88383796/151448087-c33487ec-3a92-4878-8c41-313851fca77b.png" />
    </pre>
   </details>

### Steps to reproduce
I have chosen the TestWaterPumpDefault Example from ModelicaTest.Fluid.TestComponents.Machines to demonstrate this briefly:

```modelica
model PumpTest
  extends ModelicaTest.Fluid.TestComponents.Machines.TestWaterPumpDefault(pump(
  // pump definition
    redeclare function flowCharacteristic = Modelica.Fluid.Machines.BaseClasses.PumpCharacteristics.
    polynomialFlow(
        V_flow_nominal = {0.188, 0.277, 0.361, 0.5, 0.611}, head_nominal = {35, 32, 30, 24, 17}), 
    N_nominal = 1486, 
    V_flow(displayUnit = "m3/h"),
    dp_pump(displayUnit = "m")), 
  // Sink definition
    downstreamPressure(
      duration = 100, height = 3.5e5, offset = 1.7e5, startTime = 0), Valve.dp_nominal = 10000, Source.p = 0.5e5);
 annotation(experiment(StartTime = 0, StopTime = 100, Tolerance = 1e-6));
end PumpTest;
```

### Expected behavior
I have chosen a polynominal flowCharacteristic with supporting values according to a known pump characteristic together with a rising back pressure from the source matching the curve.
I expected a curve like shown above. Since I most likely I made a mistake in modeling this curve I at least expected the axis labels to match my definitions. But as shown in the screenshot the original and generated graphs do not match at all: the differential pressure is shown in m, but the conversion is wrong and the flow is shown in m3/s, despite the fact it is shown in m3/h in the variable browser. 
And I expected the values of the variables in the variable browser to change while the slider is moving along the progress bar.

### Screenshots
<details><summary>simulation result</summary>
    <pre> 
        <img src = "https://user-images.githubusercontent.com/88383796/151456350-a808efc3-a9e5-4189-b898-ea1feace05c1.png" />
    </pre> 
</details>

### Additional text
the issue guide line tells me to:
> Run with `$ omc minimalExample.mos` on your favorite unix-like shell or use CMD `>"C:\Program Files\OpenModelica1.17.0-dev-64bit\bin\omc.exe" minimalExample.mos`
I dont know how to do that, just pasted what I typed in OMEdit. I am on my own with learning modelica with no good support forum around.

**Comment by casella** [comment] 2022-01-28 12:23
@nift-d, thanks for your feedback; there is something wrong with the management of display units that we need to fix, see next comment.

Regarding the guidelines, the requirement is that you provide **either** a list of actions or a Modelica script file to reproduce the issue. The script has the advantage of being 100% foolprof, because we get exactly the same output as you do, without issues of interpretation. But it's not necessary to provide it, what you sent is just fine. BTW, if the issue is with the GUI, there is no way to reproduce it with a script.

If you ever want to use a script, you need to create a script file `minimalExample.mos` containing the API calls to load it, possibly configure the compiler flags, and simulate it. The full list of the API functions is available [here](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html). Then, you need to run omc from the command line, so you cd to the directory where the .mos file is located, open a command line shell (on linux you can use bash or similar, in Windows you right-click on the Start button at the bottom left of the screen, select Run, run the `cmd` command, and then cd to the right directory). Then you type in the relevant command line at the prompt, on Linux omc is in the path, so there's no need to provide it, while on Windows you need to provide the full path to the omc executable.

You can also find/ask for info on https://www.openmodelica.org/forum and on StackOverflow.

Hope this helps 😃

**Comment by nift-d** [comment] 2022-01-28 13:04
@casella thx for your answer! is my approach to modeling the pump characteristics okay so far? I can not asses if it is due to my modeling or modelica that  the results are that far from the original curve.

**Comment by casella** [comment] 2022-01-28 17:52
@adeas31 please run model S in this MWE package
```modelica
package TestDisplayUnit
  model M
    parameter Modelica.Units.SI.VolumeFlowRate q0;
    Modelica.Units.SI.VolumeFlowRate q(displayUnit = "m3/h");
    Modelica.Units.SI.Length h;
  equation
    q = q0*(1+sin(10*time));
    h = 1-q^2;
  end M;

  model S
  M m(q0 = 1)  annotation(
      Placement(visible = true, transformation(origin = {8, 2}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  end S;
end TestDisplayUnit;
```
If you make a parametric plot of m.h vs. m.q, you get:
![immagine](https://user-images.githubusercontent.com/4233148/151596145-025aa296-5dd8-48f3-bedc-33b8f7c09dda.png)
where the unit on the x-axis is reported to be m3/h (as mandated by the displayUnit attribute), but is actually plotted in m3/s. I guess this is a bug of parametric plots not doing the unit conversions correctly.

Can you manage to fix that for the 1.19.0 release?

**Comment by casella** [comment] 2022-01-28 17:53
> @casella thx for your answer! is my approach to modeling the pump characteristics okay so far?

Yes. Please check the results in SI units. We still have some issues with unit handling in plots, I guess.

**Comment by casella** [comment] 2022-01-28 18:21
See also #8487 and #8488, which I found out while analyzing this test case.

**Comment by bilderbuchi** [comment] 2022-04-01 13:03
I'm seeing this using the current nightly (FYI, meaning it hasn't been accidentally fixed in the meantime).

**Closed** 2022-11-25 12:29 UTC
Labels: bug, COMP/GUI/OMEdit
