### ISSUE TITLE
A bug in fmi2Reset?

### ISSUE THREAD

**Issue by tinrabuzin** [OpenModelica/OpenModelica#6703] opened 2020-08-11 12:30 UTC
Hi, 

I was refered to here from [fmpy](https://github.com/CATIA-Systems/FMPy/issues/162).

I was trying to do a parameter sweep with an FMUs generated from OpenModelica (2.0 both me and cs) but whenever I reset the FMU I get the following error:
```
Traceback (most recent call last): 
File ".../generate_fmu.py", line 24, in <module> res = model.simulate(experiment_settings) File "...\models.py", line 74, in simulate validate=False, input=self.input, output=self.output, start_values=self.start_values, **experiment_settings) 
File "....py", line 573, in simulate_fmu result = simulateCS(model_description, fmu, start_time, stop_time, relative_tolerance, start_values, apply_default_start_values, input, output, output_interval, timeout, step_finished)
File "...\fmpy\simulation.py", line 972, in simulateCS fmu.exitInitializationMode() 
File "...\fmpy\fmi2.py", line 286, in exitInitializationMode return self.fmi2ExitInitializationMode(self.component)
File "...\fmpy\fmi2.py", line 206, in w res = f(*args) OSError: exception: access violation writing 0x0000000000000000
```

This is e.g. one FMU that generates this error: [FMU](https://github.com/OpenModelica/OpenModelica/files/5056919/DynEq.ReferenceModel.1.zip)

And this problem can be recreated using this code:

```import fmpy

fmu_path = '' # SET THE PATH HERE
model_description = fmpy.read_model_description(fmu_path))
unzipdir = fmpy.extract(fmu_path)
fmu=fmpy.instantiate_fmu(unzipdir, model_description, 'ModelExchange')

for i in range(2):
    fmu.reset()
    res1 = fmpy.simulation.simulate_fmu(unzipdir, fmu_instance=fmu, model_description=model_description,
                                    validate=False, output=['source.P'])
```

The developer of fmpy says that's due to an error in fmi2reset function. Is there maybe a workaround for this?

**Comment by AnHeuermann** [comment] 2020-11-17 11:40
Hey and thanks for your bug report.
I could reproduce your problem with Pendulum from MSL together with OMSimulator. We are testing the fmi2Reset function, but only with a full simulation before the reset is called. So this case slipped through our tests.

The core of the problem: We want to free a linear system and fail while doing so.

----

When running runTest.mos
```
loadModel(Modelica); getErrorString();

buildModelFMU(Modelica.Mechanics.MultiBody.Examples.Elementary.Pendulum); getErrorString();

system("mv Modelica.Mechanics.MultiBody.Examples.Elementary.Pendulum.fmu fmus/ && rm Modelica_Mechanics_MultiBody_Examples_Elementary_Pendulum*"); getErrorString();

writeFile("runTest.lua","
oms_setTempDirectory(\"./temp/\")
oms_newModel(\"model\")
oms_addSystem(\"model.root\", oms_system_sc)
-- instantiate FMUs
oms_addSubModel(\"model.root.system1\", \"fmus/Modelica.Mechanics.MultiBody.Examples.Elementary.Pendulum.fmu\")
oms_instantiate(\"model\")
-- initialize FMU
oms_initialize(\"model\")
-- reset FMU
oms_reset(\"model\");
"); getErrorString();

system("OMSimulator runTest.lua"); getErrorString();
```
with `$omc runTest.mos` I get a segmentation fault.

Error log
```
$ omc runTest.mos 
true
""
"/home/andreas/workspace/Testitesttest/ticket-6703/Modelica.Mechanics.MultiBody.Examples.Elementary.Pendulum.fmu"
""
0
""
true
""
info:    Set temp directory to    "/home/andreas/workspace/Testitesttest/ticket-6703"
info:    Set working directory to "/home/andreas/workspace/Testitesttest/ticket-6703"
info:    Set temp directory to    "/home/andreas/workspace/Testitesttest/ticket-6703/temp"
info:    New model "model" with corresponding temp directory "/home/andreas/workspace/Testitesttest/ticket-6703/temp/model-208vgyqe"
info:    maximum step size for 'model.root': 0.100000
info:    Result file: model_res.mat (bufferSize=10)
info:    Variable model.root.system1.body.cylinder.shapeType will not be stored in the result file, because the signal type is not supported
info:    Variable model.root.system1.body.sphere.shapeType will not be stored in the result file, because the signal type is not supported
info:    Variable model.root.system1.rev.cylinder.shapeType will not be stored in the result file, because the signal type is not supported
info:    Variable model.root.system1.world.gravityArrowHead.shapeType will not be stored in the result file, because the signal type is not supported
info:    Variable model.root.system1.world.gravityArrowLine.shapeType will not be stored in the result file, because the signal type is not supported
info:    Parameter model.root.system1.world.label1 will not be stored in the result file, because the signal type is not supported
info:    Parameter model.root.system1.world.label2 will not be stored in the result file, because the signal type is not supported
info:    Variable model.root.system1.world.x_arrowHead.shapeType will not be stored in the result file, because the signal type is not supported
info:    Variable model.root.system1.world.x_arrowLine.shapeType will not be stored in the result file, because the signal type is not supported
info:    Variable model.root.system1.world.x_label.cylinders[1].shapeType will not be stored in the result file, because the signal type is not supported
info:    Variable model.root.system1.world.x_label.cylinders[2].shapeType will not be stored in the result file, because the signal type is not supported
info:    Variable model.root.system1.world.y_arrowHead.shapeType will not be stored in the result file, because the signal type is not supported
info:    Variable model.root.system1.world.y_arrowLine.shapeType will not be stored in the result file, because the signal type is not supported
info:    Variable model.root.system1.world.y_label.cylinders[1].shapeType will not be stored in the result file, because the signal type is not supported
info:    Variable model.root.system1.world.y_label.cylinders[2].shapeType will not be stored in the result file, because the signal type is not supported
info:    Variable model.root.system1.world.z_arrowHead.shapeType will not be stored in the result file, because the signal type is not supported
info:    Variable model.root.system1.world.z_arrowLine.shapeType will not be stored in the result file, because the signal type is not supported
info:    Variable model.root.system1.world.z_label.cylinders[1].shapeType will not be stored in the result file, because the signal type is not supported
info:    Variable model.root.system1.world.z_label.cylinders[2].shapeType will not be stored in the result file, because the signal type is not supported
info:    Variable model.root.system1.world.z_label.cylinders[3].shapeType will not be stored in the result file, because the signal type is not supported
info:    Final Statistics for 'model.root':
         NumSteps = 0 NumRhsEvals  = 0 NumLinSolvSetups = 0
         NumNonlinSolvIters = 0 NumNonlinSolvConvFails = 0 NumErrTestFails = 0
error:   [fmi2logger] system1 (logStatusError): fmi2Terminate: Illegal call sequence. fmi2Terminate is not allowed in Initialization Mode state.
error:   [terminate] Termination of system "system1" failed
error:   [terminate] Termination of system "model.root" failed
Segmentation fault
139
""
```

----

Having a look into this with gdb we find the problem to be at
https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c#L384
```C
int freeLinearSystems(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  int i,j;
  LINEAR_SYSTEM_DATA* linsys = data->simulationInfo->linearSystemData;

  infoStreamPrint(LOG_LS_V, 1, "free linear system solvers");
  for(i=0; i<data->modelData->nLinearSystems; ++i)
  {
    /* free system and solver data */
    for (j=0; j<omc_get_max_threads(); ++j)
    {
      free(linsys[i].parDynamicData[j].b);
    }
```

**Comment by AnHeuermann** [comment] 2020-11-17 22:33
@tinrabuzin Please check with the next nightly build if this solves your problem.

**Comment by tinrabuzin** [comment] 2020-11-30 11:46
@AnHeuermann I have tested it now with a nightly build (OpenModelica Compiler OpenModelica 1.17.0~dev-197-g6cf0e30) and something similar happens. The first run of the FMU is ok but on the second attempt fmpy returns a segmentation fault on the call to `fmi2ExitInitializationMode`.

**Comment by AnHeuermann** [comment] 2020-11-30 13:08
Then I'll check again. Maybe our `fmi2ExitInitializationMode` function has an additional bug I didn't test with OMSimulator.

**Comment by AnHeuermann** [comment] 2020-12-07 16:28
Now I actually tested with fmpy as well. I hope now I got all leftover bugs in fmi2Reset.

**Comment by AnHeuermann** [comment] 2020-12-07 18:58
@tinrabuzin Can you please check again with the next nightly build (available tomorrow)  if your problem is fixed with the latest commit?

**Comment by tinrabuzin** [comment] 2020-12-08 13:19
@AnHeuermann It seems to be working now! Thanks a lot for fixing it.

**Comment by tinrabuzin** [comment] 2020-12-08 13:56
@AnHeuermann Sorry to disappoint you but there is a new problem appearing. I guess this does not really correspond to the title of this issue but here it goes anyways. When using CVODE with a Co-Simulation, again in a loop, I get an exception on the second run. 

Specifically it says `Exception: fmi2DoStep failed with status 4.` and I get the printed output `[CVODE ERROR]  CVodeSetStopTime
  The value tstop = 0.01 is behind current t = 10 in the direction of integration.` I guess CVODE does not get restarted?

**Comment by AnHeuermann** [comment] 2020-12-08 14:32
> I guess CVODE does not get restarted?

Yeah could be. CVODE is kinda new and not tested very well, so it's very good you are finding these bugs.

Bugs with CVODE are on my todo-list any way, so I'll look into this and see what's the problem.

**Comment by tinrabuzin** [comment] 2020-12-08 14:34
@AnHeuermann Btw, are there plans to include the support for more solvers for co-simulation?

**Comment by AnHeuermann** [comment] 2020-12-08 14:40
An implicit Euler method is somewhere on my list so we have an implicit solver independent of 3rdParty libraries. But I wont get to implement it in the near future.
Otherwise, no.

Including the same solver we already have in the C runtime is (more or less) straightforward, but is there really a need to do so?
Is there a specific solver you need? And for what reasons?

**Comment by AnHeuermann** [comment] 2020-12-08 14:46
Related ticket https://trac.openmodelica.org/OpenModelica/ticket/5867

**Comment by tinrabuzin** [comment] 2020-12-08 14:46
I am typically using rungekutta for my power system models. If I use the default for FMUs (Euler) the simulation becomes unstable or I think it's close to being unstable. On the other hand, if I switch to CVODE it takes a lot longer to simulate compared to rungekutta which makes simulating FMUs for what I do unfeasible. 

Right now I am bypassing FMUs by directly running executables generated by OpenModelica and specifying rungekutta in the arguments.

**Closed** 2020-12-09 11:33 UTC

**Comment by AnHeuermann** [comment] 2020-12-10 13:28
@tinrabuzin Do you mind testing it again? The CVODE problem should be fixed now.

**Comment by tinrabuzin** [comment] 2021-02-12 17:27
@AnHeuermann It's long overdue, but I tested it now and it works. Thanks a lot!

**Comment by tinrabuzin** [comment] 2021-02-14 08:52
I suspect this is more related to my model than OpenModelica, but just in case, during one of the simulation loop I get the following error:
```
[CVODE ERROR]  CVode
  tout too close to t0 to start integration.

fmi2DoStep: ##CVODE## -27 error occurred at time = 3.37.```

**Comment by AnHeuermann** [comment] 2021-02-15 10:25
You can create a new ticket for this one. I'm not sure what the problem is in this case.
