### ISSUE TITLE
Something got wrong with records in ClaRa

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10345] opened 2023-03-08 11:11 UTC
A commit between 2 and 3 March broke most of ClaRa models, see [regression report](https://libraries.openmodelica.org/branches/history/master/2023-02-26%2005:19:20..2023-03-01%2017:50:55.html).

@mahge the models segfault inside fluid media calculation functions, so I guess something got wrong with your commit dbfaced642. Please check ASAP.

**Comment by casella** [comment] 2023-03-08 11:15
Please also check [PowerGrids.Electrical.Test.TestTerminalVoltageTransducerIEEE](https://libraries.openmodelica.org/branches/master/PowerGrids/files/PowerGrids_PowerGrids.Electrical.Test.TestTerminalVoltageTransducerIEEE.err). It used to work previously (see [v1.20 report](https://libraries.openmodelica.org/branches/v1.20/PowerGrids/PowerGrids.html)) and now it fails because of code related to Complex records.

**Comment by casella** [comment] 2023-03-13 14:09
@HSchatzTLK, please check with @AnHeuermann and @mahge, maybe there is still something fishy in the TILMedia C external functions.

**Comment by casella** [comment] 2023-03-13 14:11
Maybe related to #9249.

**Comment by AnHeuermann** [comment] 2023-03-13 14:50
> Maybe related to https://github.com/OpenModelica/OpenModelica/issues/9249.

Very likely. Basically the constructor of all external TILMedia objects is broken for OpenModelica, because a special case for OpenModelica (or a general case) is missing for `void* TILMedia_createExternalObject`.

We have to wait for TLK to update the TILMedia library, update our library tests to use the fixed version of TILMedia (hopefully named v1.8.1) and see if that solves most of the segmentation faults.

**Comment by casella** [comment] 2023-03-13 15:02
OK, so there's no point waiting for this to be fixed in order to release 1.21.0.

Thanks!

**Comment by phannebohm** [comment] 2023-05-09 10:28
I guess this is also fixed with [TILMediaClaRa v1.8.1](https://github.com/TLK-Thermo/TILMediaClaRa/releases/tag/1.8.1), see [regression report](https://libraries.openmodelica.org/branches/history/master/2023-05-07%2022:21:56..2023-05-08%2022:52:05.html).

**Closed by phannebohm** 2023-05-09 10:28 UTC
Labels: COMP/OMC/Codegen, regression

**Comment by casella** [comment] 2023-05-09 11:24
> I guess this is also fixed with [TILMediaClaRa v1.8.1](https://github.com/TLK-Thermo/TILMediaClaRa/releases/tag/1.8.1), see [regression report](https://libraries.openmodelica.org/branches/history/master/2023-05-07%2022:21:56..2023-05-08%2022:52:05.html).

The regression report still refers to 1.8.0, see my [comment in #9249](https://github.com/OpenModelica/OpenModelica/issues/9249#issuecomment-1539983935), but I guess it should also be fine in 1.8.1.
