### ISSUE TITLE
omc -s --newbackend Modelname.mo uses the old backend.

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10142] opened 2023-02-02 14:40 UTC
@perost [pointed out](https://github.com/OpenModelica/OpenModelica/issues/10126#issuecomment-1413833997) that running `omc -s --newBackend Modelname.mo` still used the old backend to compile the code. I have no MWE to prove that, but it should be easy to fix it anyway.

**Comment by mahge** [comment] 2023-02-16 10:20
This is a duplicate of #7860. It is just translating a model directly with `omc -s` ignoring model annotations. I will see what I can do.

**Comment by perost** [comment] 2023-02-16 10:23
> This is a duplicate of #7860. It is just translating a model directly with `omc -s` ignoring model annotations. I will see what I can do.

This has nothing to do with annotations, the issue is that `omc -s --newBackend Modelname.mo` will still use the old backend since the code in `Main` doesn't care about the `--newBackend` flag. The code probably needs to be redesigned quite a lot since it currently uses the old DAE structure everywhere.

**Comment by mahge** [comment] 2023-02-16 10:27
I see. From the code samples provided in #10126 and the description of this ticket I assumed you were relying on the annotations. We can keep this open then.

**Comment by perost** [comment] 2023-02-16 10:30
> I see. From the code samples provided in #10126 and the description of this ticket I assumed you were relying on the annotations. We can keep this open then.

That's understandable, the description was missing the `--newBackend` flag but I've added it now.

**Closed** 2023-03-25 10:58 UTC
Labels: duplicate
