### ISSUE TITLE
Error while simulating models with 2D arrays in OpenModelica over OPC-UA server 

### ISSUE THREAD

**Issue by SudhakarKuma** [OpenModelica/OpenModelica#7467] opened 2021-05-16 06:53 UTC
### Description

I have an OpenModelica model, which has a few two-dimensional arrays. For my project, I am simulating the model from `OMShell-terminal`. First, I simulate the model with a certain `stopTime` and no simulation flags,  In this case, the simulation runs properly, and I can get the data (`.mat` file) at the end of the simulation. Second, I simulate the same model with a certain `stopTime` and two simulation flags (`-rt=1.0 -embeddedServer=opc-ua`). In this case, after simulating the model over the OPC-UA server, I execute a Python OPC-UA client too. During the simulation, it works fine, and I can observe the read/write operations. However, when the simulation approaches the specified `stopTime`, `OMShell-terminal` throws an error as shown below:

![Screenshot from 2021-05-16 11-40-14](https://user-images.githubusercontent.com/12606778/118387333-9986b500-b63b-11eb-92e0-ca7aee4fd32d.png)

I have worked with models which have one-dimensional arrays over an OPC-UA server and a Python OPC-UA client. Those models work fine. However, I am having issues with simulating models with two-dimensional arrays over an OPC-UA server. 

### Steps to Reproduce
The Modelica model and the Python OPC-UA client can be found below: 
[Simulation-Files.zip](https://github.com/OpenModelica/OpenModelica/files/6488793/Simulation-Files.zip)

Consider that the Modelica model has been saved as `trays.mo`, and it is available in the current working directory. Assuming that I am using Linux, I will launch a Terminal. First, we will simulate the Modelica model by following the steps given below:

- Launch `OMShell-terminal`. 
- Execute: `loadModel(Modelica)`
- Execute: `loadFile("trays.mo")`
- Execute: `simulate(trays, startTime = 0, stopTime = 10, simflags = "-rt=1.0 -embeddedServer=opc-ua")`

Consider that the Python OPC-UA client has been saved as `test_client.py`.  To execute the client, we will execute the command `python3 test_client.py`  

### Expected Behavior

Ideally, the simulation should stop at the specified  `stopTime` in the `OMShell-terminal`. Accordingly, It should show the name of the result file and a message like ` The simulation finished successfully.`  

### Version and OS
I am using the following tools:

- OpenModelica 1.17.0
- Linux Ubuntu 20.04.2 LTS (64-bit)
- Modelica 3.2.3 

### Additional Context
I have found a similar issue on https://github.com/open62541/open62541/issues/3552.

**Comment by SudhakarKuma** [comment] 2021-05-17 07:56
@sjoelund @arun3688 The attachment (`.zip` file) contains the Modelica model and the Python OPC-UA client. I have saved the Modelica Model by using the `Save Total` feature in `OMEdit`. Thus, this model can only be simulated by `OMShell-terminal`.

**Comment by sjoelund** [comment] 2021-05-24 13:15
So I can confirm this crashes, and I tried to upgrade open62541 since it seems to be an error in the library and not our code. However, the interface changed substantially and even fixing all compilation warnings does not fix everything. I'm not sure when I would have time to look into this, so I put the work in progress at https://github.com/sjoelund/OpenModelica/tree/open62541-upgrade

**Comment by SudhakarKuma** [comment] 2021-05-24 23:47
@sjoelund Thank you for your response. For your kind information, I have tried simulating these files using `nightly` and `release` builds of OpenModelica. However, the server still crashes. So, we may infer that the library itself needs to be fixed in the OPC-UA server of OpenModelica. Also, I am assuming that my Python OPC-UA client is doing its job properly.

**Comment by rahulp13** [comment] 2021-07-12 08:32
@sjoelund We believe the crash is associated with boolean variables generated in the target C code. We have been working on resolving it and came up with a fix that worked for the aforesaid attached model by @SudhakarKuma and few other models that we made. We will keep you posted and soon create a PR for the same.

**Closed** 2021-07-29 05:29 UTC
Labels: COMP/OPC
