### ISSUE TITLE
Libraries aren't shown in the left pane

### ISSUE THREAD

**Issue by yurivict** [OpenModelica/OpenModelica#9920] opened 2022-12-11 08:25 UTC
When OMEdit starts on FreeBSD it doesn't show some items in the left pane, and there are errors/warnings printed:
![image](https://user-images.githubusercontent.com/271906/206893332-467ac9a1-8b1e-43d1-b7d7-82577ac23b05.png)

**Comment by perost** [comment] 2022-12-11 11:24
Do you have any libraries installed that you think should show up there? We only distribute the base libraries with the installers, if you've compiled OM from source you need to install them yourself (File->Manage Libraries->Install Library).

**Comment by perost** [comment] 2022-12-11 19:33
> Now I am wondering if it is normal that on FreeBSD only one item is shown after first install.

Yes, it's not a issue with FreeBSD specifically, you just didn't have any libraries installed that would show up. That's normal when building OM yourself from source. The `OpenModelica` one is just an internal library in the compiler, so it's always available.

Feel free to open a new issue if you have suggestions on how OM could handle this better. I will close this one though since the issue as described isn't actually an issue but working as intended.

**Closed by perost** 2022-12-11 19:33 UTC

**Comment by casella** [comment] 2022-12-12 22:21
@yurivict please also check https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/packagemanager.html
